### DISCUSSION TITLE
Ask about Templet and false positive

### DISCUSSION THREAD

**Discussion by uskolor** [projectdiscovery/nuclei-templates#10529] [General]
hi Team 

I would like ask about Templates for Nuclei .I do not understand why this template during probe some website a lot time show my false positive xss .How to reduce false positive .What is wrong .?

```yaml
http:
  - method: GET
    path:
      - '{{BaseURL}}/?q=<script>alert(1);</script>'
      
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<script>alert(/{{randstr}}/);</script>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```
