### DISCUSSION TITLE
[Feature] If a matchers match words,print this words.

### DISCUSSION THREAD

**Discussion by No-Github** [projectdiscovery/nuclei-templates#1504] [General]
**Is your feature request related to a problem? Please describe.**

I'm making a template for SEO detection
There are multiple results in the return value that will hit
I hope I can see the matched words directly

**Describe the solution you'd like**

For Examples
```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "快三"
          - "走势"
          - "开户"
          - "玩法"
          - "老虎机"
          - "澳门银行"
          - "万博亚洲官网"
          - "狗万app"
          - "新万博官网"
          - "ylg9999"
          - "九州娱乐"
          - "澳门威尼斯人"
          - "娱乐场直营"
          - "威尼斯人"
          - "澳门太阳城"
        part: body
        condition: or
		print: true
```
