### DISCUSSION TITLE
[Bug] maestro-unauth-rce

### DISCUSSION THREAD

**Discussion by nrathaus** [projectdiscovery/nuclei-templates#2303] [General]
The template seems to use:
```yaml
    extractors:
      - type: regex
        regex:
          - 'LISTSERV Maestro\s+9\.0-[123456780]'
          - 'LISTSERV Maestro\s+[5678]'
          - 'Administration Hub 9\.0-[123456780]'
          - 'Administration Hub [5678]'
        condition: or
```

But no matchers, isn't this a mistake?
