### DISCUSSION TITLE
token-spray template if there is 2 required API key / token

### DISCUSSION THREAD

**Discussion by daffainfo** [projectdiscovery/nuclei-templates#3092] [Q&A] [answered]
Hi! I found a website that requires a project-id and a secret token to make an API request, for example

```
curl --request POST \
	--url https://test.stytch.com/v1/users \
	-u 'PROJECT ID:SECRET' \
	-H 'Content-Type: application/json' \
	-d '{
		"email": "test@stytch.com"
	}'
```

How to create the token-spray template if there is a case like this?
Is this what the template looks like?
```
- raw:
      - |
        POST /v1/users HTTP/1.1
        Authorization: Basic base64{{token}}
        Host: test.stytch.com
        Content-Type: application/json
        Content-Length: 28
        
        {"email": "test@stytch.com"}
```
