### DISCUSSION TITLE
Detect self-signed SSL certificate

### DISCUSSION THREAD

**Discussion by righettod** [projectdiscovery/nuclei-templates#3678] [Q&A] [answered]
Hi,

I'm trying to write a template to detect self-signed SSL certificate in a HTTP/S context. I used samples present in the [ssl folder](https://github.com/projectdiscovery/nuclei-templates/tree/master/ssl) to understand the syntax and attributes available.

I cannot achieve to access the **Issuer** and **Subject** certificate attribute in a **Matchers** condition:

```yaml
id: selsigned-ssl

info:
  name: Self-Signed SSL Certificate
  author: righettod
  severity: low
  tags: ssl

ssl:
  - address: "{{Host}}:{{Port}}"
    matchers:
      - type: dsl
        dsl:
          - "common_name == issuer_common_name"
```

![image](https://user-images.githubusercontent.com/1573775/152764742-1612c845-5a80-4cf2-b0c8-4c19456d6bb2.png)

I does not found any more information in the [matchers documentation](https://nuclei.projectdiscovery.io/templating-guide/operators/matchers/).

I have found [in source](https://github.com/projectdiscovery/nuclei/blob/master/v2/pkg/protocols/ssl/ssl.go#L238) that these attributes does not seems to be exposed.

Did I miss something?

Thank you very much in advance for your help 😃
