### DISCUSSION TITLE
How to use cookie-reuse in Attack mode

### DISCUSSION THREAD

**Discussion by rhbb** [projectdiscovery/nuclei-templates#3755] [General]
How to use cookie-reuse in Attack mode

**Comment by ehsandeep** [comment]
@rhbb it should be same, any example to share where it was it not working?

**Reply by rhbb** [reply]
this is nuclei-templates
```yaml
    raw:
      - |
        POST /login.do HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 163
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6

        login_username={{username}}&login_password=123456

      - |
        POST /hello.do HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 51
        Accept: application/json, text/javascript, */*; q=0.01
        X-Requested-With: XMLHttpRequest
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
        Cook111ie: JSESSIONID=4EFF6ABE38F1B2544F35BD22F9A7E2DB; loginPageURL=""; avatarImageUrl=601843454090428479
        Connection: close

        test1=111&test2=1111
    cookie-reuse: true `
```
this is debug-req

```console
POST /login.do HTTP/1.1
Host: 192.168.1.111:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
Connection: close
Content-Length: 41
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: max-age=0
Content-Type: application/x-www-form-urlencoded
Upgrade-Insecure-Requests: 1

login_username=test&login_password=123456
[INF] [weak-password] Dumped HTTP request for http://192.168.1.111:9000/

POST /login.do HTTP/1.1
Host: 192.168.1.111:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
Connection: close
Content-Length: 43
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: max-age=0
Content-Type: application/x-www-form-urlencoded
Upgrade-Insecure-Requests: 1

login_username=123456&login_password=123456
[INF] [weak-password] Dumped HTTP request for http://192.168.1.111:9000/

POST /hello.do HTTP/1.1
Host: 192.168.1.111:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
Content-Length: 20
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: close
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cook111ie: JSESSIONID=4EFF6ABE38F1B2544F35BD22F9A7E2DB; loginPageURL=""; avatarImageUrl=601843454090428479
X-Requested-With: XMLHttpRequest

test1=111&test2=1111
[INF] [weak-password] Dumped HTTP request for http://192.168.1.111:9000/

POST /hello.do HTTP/1.1
Host: 192.168.1.111:9000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)
Content-Length: 20
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: close
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cook111ie: JSESSIONID=4EFF6ABE38F1B2544F35BD22F9A7E2DB; loginPageURL=""; avatarImageUrl=601843454090428479
X-Requested-With: XMLHttpRequest

test1=111&test2=1111
```

I used test and 123456 for Attack. If the cookie-reuse parameter is added, this process is problematic.
