### DISCUSSION TITLE
dsl matcher with request condition not working as expected

### DISCUSSION THREAD

**Discussion by mrnfrancesco** [projectdiscovery/nuclei-templates#4451] [Q&A] [answered]
Hello,
I'm developing a template like the following:

```yml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/some-stuff-here"
      - "{{BaseURL}}/other-stuff-here"

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 404"
          - "status_code_2 == 200 && contains(body_2, 'whatever')"
        condition: and
```

When I run the template using `-ms` to see the matched status I always get "failed" even if the response should match, because it seems nuclei tries to match all two the conditions on every response; obviously `status_code_2` cannot exists on the first response.

Am I missing something or misunderstood dsl matcher usage or this is a bug in nuclei?
