### DISCUSSION TITLE
how to do variable nesting

### DISCUSSION THREAD

**Discussion by Mr-xn** [projectdiscovery/nuclei-templates#5145] [Q&A] [answered]
hi,guys 
how to do variable nesting ? like this templates :
the below way of hex_decode variable nesting exp variable was wrong.
```
requests:
  - raw:
      - |
        POST {{path}} HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        content-type: application/x-www-form-urlencoded

        {{hex_decode({{exp}})}}

      - |
        GET /xxxxxx HTTP/1.1
        Host: {{Hostname}}

    payloads:
      path:
        - /aaaa
        - /cccc

      exp:
        - aaa
        - sss
        - xxx

```

how to nesting exp in hex_decode function ?
