### DISCUSSION TITLE
URLs with parameters and appends the payload to the end of the parameter.

### DISCUSSION THREAD

**Discussion by JoshMorrison99** [projectdiscovery/nuclei-templates#6307] [Q&A] [answered]
I want to feed nuclei URLs like so:
```
https://example.com/e/er?retURL1=
https://example.com/e/er?d=
```

I want to create a template that will append to the value like so:
```
https://example.com/e/er?retURL1=HELLO
https://example.com/e/er?d=HELLO
```

When I create the template like so:
```
requests:
    - raw:
        - |
          GET HELLO HTTP/1.1
          Host: {{Hostname}}
```

I get a response like so:
```
GET /e/erHELLO?retURL1= HTTP/1.1
```

I want the HELLO to be at the end like so:
```
GET /e/er?retURL1=HELLO HTTP/1.1
```
