### DISCUSSION TITLE
Send a Blank Host

### DISCUSSION THREAD

**Discussion by random-robbie** [projectdiscovery/nuclei-templates#6366] [Q&A] [answered]
Hey,

Is it possible to send a request with a blank host i.e like

```
GET /
Host:
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
Connection: close
```

**Comment by random-robbie** [comment, marked as answer]
Found the answer but i think it breaks and does not send the request.
```
requests:
  - raw:
      - |
        GET /
        Host:   
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en
        User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
        Connection: close
    
    unsafe: true
    matchers:
      - type: word
        part: body
        words:
          - "http"
          
```
