### DISCUSSION TITLE
Print custom word if a "matchers" match a certain word

### DISCUSSION THREAD

**Discussion by pascal-sun** [projectdiscovery/nuclei-templates#6460] [Q&A] [answered]
Hi! :wave:

It is possible to do "conditional matchers", which returns a different result depending on the match?
For example here, I have different hashes that can appear on a page, and that can determine the version of the Citrix ADC: https://gist.github.com/fox-srt/c7eb3cbc6b4bf9bb5a874fa208277e86
Can I make a `matchers` on the hash, and if there is a match, I print the associated version?

I saw the `extrators` feature, but that's not what I want because I don't want to extract the hash, but the associated version (which does not appear on the page).

**Comment by olearycrew** [comment]
@princechaddha any thoughts on if this is possible or if I should open a Nuclei issue for this?

**Reply by pascal-sun** [reply, marked as answer]
Finally, I think I found a solution for my issue:

```yaml
    matchers:
      - type: word
        name: version 1.0.0
        words:
          - "hash0001"
      - type: word
        name: version 1.0.1
        words:
          - "hash0002"
      ...
      - type: word
        name: version X.X.X
        words:
          - "hashXXXX"
```

This will match on `hashXXXX` for example, and print `version X.X.X` for example, which resolves my issue :smiley:
