### DISCUSSION TITLE
Question: Can I write non-ascii characters in HTTP request body or request header?

### DISCUSSION THREAD

**Discussion by miaochiahao** [projectdiscovery/nuclei-templates#698] [Q&A] [answered]
deserialization vulnerabilities may require this kind of features. I wonder if there's something like 
```yaml
payload:
    - base64_decode("based64_encoded_payload")
```

**Comment by ehsandeep** [comment, marked as answer]
@miaochiahao Yes, you can, here is an example using in template-based payload support, you can also use [file-based payloads](https://nuclei.projectdiscovery.io/templating-guide/#intruder-payloads) as well, and later apply [helper functions](https://nuclei.projectdiscovery.io/templating-guide/#helper-functions) at the time of using defined payloads in the request block as shared in the below example.

```yaml
requests:

  - payloads:
      data:
        - this_is_payload

    raw:
      - |
        GET /manager/html HTTP/1.1
        Host: {{Hostname}}
        Token: {{base64('§data§')}}   
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
        Accept-Language: en-US,en;q=0.9
        Connection: close
```
