### DISCUSSION TITLE
extract the filename

### DISCUSSION THREAD

**Discussion by 0xc4sper0** [projectdiscovery/nuclei-templates#7292] [Q&A]
Hello guys ..

I'm working on a nuclei template, but there's a problem I'm facing, the tool can't extract the filename via -itags fuzz command

Well the idea for this template is a little different

I want the template to search across a combination of letters and numbers

Example we have a file named
site-ftp-log__ee9c0df-20075822.txt

If we look at the name, we will need the template to perform a brute force attack through payload

```yaml
path:
      - '{{BaseURL}}/site-ftp-log__{{nameslug1}}-{{nameslug2}}.txt'
    attack: clusterbomb
    payloads:
        nameslug1:
         - "a"
         - "b"
         - "c"
         - "d"
         - "e"
         - "f"
         - "0"
         - "1"
         - "2"
         - "3"
         - "4"
         - "5"
         - "6"
         - "7"
         - "8"
         - "9"
        numeslug2:
         - "0"
         - "1"
         - "2"
         - "3"
         - "4"
         - "5"
         - "6"
         - "7"
         - "8"
         - "9"
```

Unfortunately, all my attempts failed to make this template work.

my question:
Is there a property that can be used to make the nuclei sort and match characters to catch the correct filename?
