### DISCUSSION TITLE
sending 2 requests with "if"

### DISCUSSION THREAD

**Discussion by rawezh80** [projectdiscovery/nuclei-templates#7703] [Q&A] [answered]
hi team I hope you are doing well 
I need some help to build my own template 
I want to send request to find some word for example token or api-key like this 

id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: word
        words:
          - "api-key"
on response found api-key now I want test it this api-key vuln or not 

and second request to  https://googlekey.blindf.com/ to check api-key 

Or I want to do some other things for me, for example, I want to send a request to find some programs, for example, twitter
If you find it in the response , send a request to the Twitter link bring me back what is response

**Comment by princechaddha** [comment, marked as answer]
Hi @Rawezho1o, For your specific scenario, you can write a template like this:

```
http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        @Host: https://googlekey.blindf.com
        GET /?token={{token}} HTTP/1.1
        Host: googlekey.blindf.com

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "test"

    extractors:
      - type: regex
        name: token
        internal: true
        group: 1
        regex:
          - '<token>(.*)</token>'
```

The second request will be sent only once the key has been extracted.
