### DISCUSSION TITLE
Extractor usage：How to get the result and return

### DISCUSSION THREAD

**Discussion by k3rwin** [projectdiscovery/nuclei-templates#7744] [Q&A] [answered]
Can the fields in the response packet be extracted and returned to the terminal scan result?
For example, if I want to get the execution result of the whoami command, how can I extract the result from the response packet and return it to the terminal scan result?

thanks！

**Comment by ehsandeep** [comment, marked as answer]
@k3rwin, you can use extractors to print any or additional info in the CLI output, for example - https://github.com/projectdiscovery/nuclei-templates/blob/24475321fd4e0c2eb2b7dbda418ef90c2c3448b6/http/exposed-panels/ewm-manager-panel.yaml#L34

**Reply by k3rwin** [reply]
Thanks, it works now

**Reply by k3rwin** [reply]
Another question, I just want to print out the regular matching group 1, is there a relevant syntax for this, such as r"xxx(.*)xxx"[1] in python

**Reply by k3rwin** [reply]
ok,i get it !
group: 1
thanks!

**Reply by ehsandeep** [reply]
See https://github.com/projectdiscovery/nuclei-templates/blob/24475321fd4e0c2eb2b7dbda418ef90c2c3448b6/http/cves/2023/CVE-2023-1177.yaml#L61

**Reply by k3rwin** [reply]
another question of extractors,how to use or to match multiple regular expressions, if the first one is matched, the second one will not be matched.
For example, linux use \n and windows use \r\n,I only want to match once,Is there any parameter setting?  like `condition: or` in matchers
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*)\n</string>'
```

**Reply by k3rwin** [reply]
Using this configuration can also achieve the effect, but I would like to ask how to use the built-in parameters to achieve the same effect
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*\w)\n</string>'
```
