### DISCUSSION TITLE
Multiple request template

### DISCUSSION THREAD

**Discussion by k3rwin** [projectdiscovery/nuclei-templates#7745] [Q&A] [answered]
if multiple requests are sent, I only want to match the response package of one of the requests, how to implement it in the template

**Comment by ehsandeep** [comment, marked as answer]
@k3rwin see https://nuclei.projectdiscovery.io/templating-guide/protocols/http/#request-condition, you can specify counter to define specific response to match.

**Reply by k3rwin** [reply]
I'm using this syntax in a template and I only want to match the second response packet. But in debug mode, after seeing the first packet sent, it shows `[WRN] [xx] No parameter 'body_2' found.`

**Reply by ehsandeep** [reply]
If you see this warning, that means there is no 2nd response received from server, you can share an example template for further assistance.

**Reply by k3rwin** [reply]
template：
```
requests:
  - raw:
      - |
        POST /x1 HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9

        {pay1}

      - |
        POST /x2 HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: cookiets=1681785470496; JSESSIONID=33989F450B1EA57D4D3ED07A343770FF.server
        If-None-Match: W/"1571-1589211696000"
        Connection: close
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 96

        pay2=xxx

    matchers:
      - type: dsl
        dsl:
          - "contains(body_2,'<?xml version=')"

    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*?)\r\n</string>'
```
operation result：
```
POST /x1 HTTP/1.1
Host: x
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Connection: close
Content-Length: 251
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Accept-Encoding: gzip

{pay1}

**[WRN] [template] No parameter 'body_2' found.**
[DBG] [template] Dumped HTTP response url1

HTTP/1.1 200
Connection: close
Content-Length: 0
Date: Sun, 23 Jul 2023 08:39:04 GMT
Server: server

[INF] [template] Dumped HTTP request for url2

POST /x2 HTTP/1.1
Host: x
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Content-Length: 96
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: max-age=0
Connection: close
Content-Type: application/x-www-form-urlencoded
Cookie: cookiets=1681785470496; JSESSIONID=33989F450B1EA57D4D3ED07A343770FF.server
If-None-Match: W/"1571-1589211696000"
Upgrade-Insecure-Requests: 1

pay2=xxx
[DBG] [template] Dumped HTTP response url2

HTTP/1.1 200
Connection: close
Content-Length: 86
Content-Type: text/html;charset=ISO-8859-1
Date: Sun, 23 Jul 2023 08:39:06 GMT
Entry1: 1
Server: server
Set-Cookie: JSESSIONID=7DDF93EC1F74D4A4EC91A190CDEE8F19.server; Path=/; HttpOnly

<?xml version='1.0' encoding='UTF-8'?><string>res
</string>
[template:dsl-1] [http] [critical] url2 [res]
```

**Reply by ehsandeep** [reply]
```
[template:dsl-1] [http] [critical] url2 [res]
```

it looks like you got the match, you can ignore the warning, alternatively, you can also use word matcher like: 

```yaml
    matchers:
      - type: word
        part: body_2
        words:
          - "<?xml version="
```

**Reply by k3rwin** [reply]
Thank you, I learned a lot, but there is a little wrong grammar：
```
    matchers:
      - type: word
        part: body_2
        words:
          - "<?xml version="
```
