### DISCUSSION TITLE
question of extractors

### DISCUSSION THREAD

**Discussion by k3rwin** [projectdiscovery/nuclei-templates#7767] [General]
how to use or to match multiple regular expressions, if the first one is matched, the second one will not be matched.
For example, linux use \n and windows use \r\n,I only want to match once,Is there any parameter setting?  like `condition: or` in matchers
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*)\n</string>'
```

_Originally posted by @k3rwin in https://github.com/projectdiscovery/nuclei-templates/discussions/7744#discussioncomment-6520244_

**Comment by ehsandeep** [comment]
@k3rwin, if the purpose is to extract any (first) match, you can use the above format.

If you want to ensure other extractors to check regardless of the first extract, you can write in separate blocks, for example:

```yaml
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\n</string>'
```

**Comment by k3rwin** [comment]
> 

What I mean is that it ends when the first regex is matched, because the second regex can also be matched, so the content will be printed twice, and I only want to print the content of the first match

**Comment by k3rwin** [comment]
> @k3rwin, if the purpose is to extract any (first) match, you can use the above format.
> 
> If you want to ensure other extractors to check regardless of the first extract, you can write in separate blocks, for example:
> 
> ```yaml
>     extractors:
>       - type: regex
>         group: 1
>         part: body
>         regex:
>           - '<string>(.*)\r\n</string>'
>           
>       - type: regex
>         group: 1
>         part: body
>         regex:
>           - '<string>(.*)\n</string>'
> ```
When I use this, it will extract twice and return two results, one without \r and one with \r
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*)\n</string>'
```

**Comment by Tito0015** [comment]
The issue happens because Nuclei evaluates every pattern listed in the regex: array and appends all valid matches to the extraction output. On Windows systems, both of your patterns match simultaneously:
```

<string>(.*)\r\n</string> matches the line ending.

<string>(.*)\n</string> also matches because .* greedily captures the trailing \r into group 1.
```

Since Nuclei does not have a "stop-at-first-match" flag across multiple list items, the cleanest fix is to combine both OS line endings into a single regex pattern using an optional \r?.

Solution: Single Unified Regex
Replace the two array items with a single regex using non-greedy matching .*? and \r?\n:

YAML
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*?)\r?\n</string>'
```
Why this works:
Single Pass: Nuclei only runs one extraction pass because there is only one pattern in the list.

Non-Greedy Match (.*?): Prevents .* from swallowing trailing carriage returns into your captured output group.

Cross-Platform: \r?\n seamlessly handles both Windows (\r\n) and Linux (\n) responses.

Note: If you frequently deal with cross-platform HTTP line endings (\r\n vs \n), raw socket precision, and complex multi-step state extraction in Nuclei, we recently published a technical benchmark titled "CPG Compilation vs. LLM AI Generation: Empirical Analysis of CVE-2025-62593 Rule Accuracy" on Medium that dives deep into handling these exact socket-level nuances.
