### DISCUSSION TITLE
Code engine template issue

### DISCUSSION THREAD

**Discussion by Lavan08** [projectdiscovery/nuclei-templates#7815] [General]
```
line 11: field code not found in type templates.Alias
[FTL] Could not validate templates: errors occured during template validation
```

while using the below yaml file I got this issue 

```yaml
id: py-code-snippet

info:
  name: py-code-snippet
  author: pdteam
  severity: info
  tags: code
  description: |
    py-code-snippet

code:
  - engine:
      - py
      - python3
    source: |
      import sys
      print("hello from " + sys.stdin.read())

    matchers:
      - type: word
        words:
          - "hello from input"
```

**Comment by ehsandeep** [comment]
@Lavan08, it's code templates is an unreleased feature that is available in `v3-beta` branch.

You can either build from the source or install it with `go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@v3-beta`

**Comment by MasoudAbdaal** [comment]
@ehsandeep 
I would like to bring to your attention that the issue persists. Additionally, I have noticed that the [documentation](https://docs.projectdiscovery.io/templates/protocols/code#running-code-templates) does not provide a detailed description of this feature, mentioning only the necessity to run the template with the `-code` switch. Could you please clarify whether this feature is currently unreleased?
Thank you for your assistance.

**Comment by ehsandeep** [comment]
@MasoudAbdaal this one is released long back and you can see existing code template example here - https://github.com/projectdiscovery/nuclei-templates/tree/main/code/cves

**Reply by MasoudAbdaal** [reply]
I still have problem to run code templates. Also signed python hello world example template. Is there any additional configuration or specific setup to run it?

**Reply by ehsandeep** [reply]
```console
$ echo test | nuclei -t test.yaml -code -debug

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.10

		projectdiscovery.io

[url] got empty hostname for test skipping ip selection
[INF] Current nuclei version: v3.3.10 (latest)
[INF] Current nuclei-templates version: v10.1.5 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 281
[INF] Templates loaded for current scan: 1
[INF] Executing 1 signed templates from pd
[INF] Targets loaded for current scan: 1
[DBG] [py-code-snippet] Dumped Executed Source Code for input/stdin: 'test'
---------------
Source Code:
---------------
import sys
print("hello from " + sys.stdin.read())


---------------
Command Executed:
---------------
/usr/bin/python3 /var/folders/ml/m31ysb5x73l1s3kjlyn5g4180000gn/T/nuclei-tmp-3987847129/1892545428

---------------
Command Output:
---------------
hello from test

[WRN] Command Output here is stdout+sterr, in response variables they are seperate (use -v -svd flags for more details)
[DBG] [py-code-snippet] Dumped Code Execution for test

hello from test

[INF] No results found. Better luck next time!
```

same template works without any error.

**Reply by MasoudAbdaal** [reply]
It does not working for me!

```powershell
nuclei.exe -t .\templates\py-snippet.yaml -code  -duc

                     __     _       
   ____  __  _______/ /__  (_)      
  / __ \/ / / / ___/ / _ \/ /       
 / / / / /_/ / /__/ /  __/ /        
/_/ /_/\__,_/\___/_/\___/_/   v3.3.7

                projectdiscovery.io

[WRN] Found 32 template[s] loaded with deprecated paths, update before v3 for continued support.
[WRN] Found 1 unsigned or tampered code template (carefully examine before using it & use -sign flag to sign them)
[WRN] Skipping 1 unsigned template[s]
[INF] Current nuclei version: v3.3.7 (outdated)
[INF] Current nuclei-templates version: v10.1.5 (outdated)
[WRN] Scan results upload to cloud is disabled.
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

Im using compiled version of nuclei for Windows

**Reply by ehsandeep** [reply]
```
[WRN] Found 1 unsigned or tampered code template (carefully examine before using it & use -sign flag to sign them)
[WRN] Skipping 1 unsigned template[s]
```

See the warning, you need to sign the template before you can use it, it's getting skipped as it's unsiged.

https://docs.projectdiscovery.io/templates/reference/template-signing

**Reply by MasoudAbdaal** [reply]
Thank you! It worked for the sample template which exist in https://github.com/projectdiscovery/nuclei/blob/main/integration_tests/protocols/code/py-snippet.yaml
but when I modified it and sign it again, I got the same error

```yaml
id: py-code-snippet

info:
  name: py-code-snippet
  author: Masoud
  severity: info
  tags: code
  description: |
    py-code-snippet

code:
  - engine:
      - py
      - python3
      - python
    source: |
      import sys
      print("hello from Masoud ")
    
    matchers:
      - type: word
        words:
          - "Masoud"
# digest: 4a0a00473045022100b5f2d1701e7e56c2bc7797f3205b81f8a02688fa56d5a0cd34f5c36b0e431674022027084cd397dc2a500e1cc4440d8dd7ab6ce5d38742109852ced7a45ca7cf3d7c:f5b8be78a188003848e6cc9396eef6af
```
