### DISCUSSION TITLE
changing Content-Length and add header without command

### DISCUSSION THREAD

**Discussion by rawezh80** [projectdiscovery/nuclei-templates#7913] [Q&A] [answered]
Dear Nuclei community
this is my own template 

```yaml
id: kurdOff

info:
  name: chaneg parent
  author: kurdtem
  severity: high



http:
  - raw:
    - |+
      POST / HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.3
      Content-Type: application/x-www-form-urlencoded
      Content-Length: 4
      Transfer-Encoding: chunked


      kurd1
      kurd2
      kurd3
      kurd4

      kurd-1
      kurd-2
```

 run this code line : `nuclei -t kurd.yaml -u https://sorare.com  -debug-req`

you will see this

```
POST / HTTP/1.1
Host: sorare.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.3
Connection: close
Content-Length: 46
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip


kurd1
kurd2
kurd3
kurd4

kurd-1
kurd-2
```
[INF] No results found. Better luck next time!

as you this header is added

```
Connection: close
Accept-Encoding: gzip
```
and `Content-Length:` is updated I know my content lenght request is more than 4  however
I don't want any headers added and I don't want Content Lens to updated

please review 
kind regards
