### DISCUSSION TITLE
How to do math operations in templates

### DISCUSSION THREAD

**Discussion by clancyb00m** [projectdiscovery/nuclei-templates#7922] [Q&A] [answered]
I need to subtract 1 from the hexadecimal value generated by the hex_encode function and then use the hex_decode function
```
abcdef  -> abcdee
hex_encode("abcdef") -> 616263646566
616263646566-1=616263646565
hex_decode("616263646565") -> abcdee
```
so how can i implement it
```
{{hex_decode({{hex_encode("abcdef")}}-1)}}
error:
unresolved variables found: hex_decode(616263646566-1)
```

**Comment by princechaddha** [comment, marked as answer]
Hi @clancyb00m, The response time for this discussion was much longer than usual. You can perform math operations as shown in the following example:

```yaml
id: math-operations

info:
  name: Math operations
  author: princechaddha
  severity: info
variables:
  string: "aaaaa"
  hex: "{{hex_encode(string)}}"
  substract: "{{to_number(hex)-1}}"

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: status
        status:
          - 200

    extractors:
      - type: dsl
        dsl:
          - string
          - hex
          - substract
```

```
[math-operations:status-1] [http] [info] https://google.com [aaaaa,6161616161,6161616160]
```
