### DISCUSSION TITLE
How to extract root domain and subdomain in response body or header

### DISCUSSION THREAD

**Discussion by 3terN4l** [projectdiscovery/nuclei-templates#7951] [Q&A] [answered]
if my input parameter is `-u http://www.google.com`, i want to extract subdomain from google.com's response, how to set extractors block?

  ```
extractors:
    - type: regex
      name: subdomain
      part: body, all_headers
      regex:
        - "[^ .]+.{{this should be google.com as var}}"
```
