### DISCUSSION TITLE
Test nuclei http headers

### DISCUSSION THREAD

**Discussion by 0xc4sper0** [projectdiscovery/nuclei-templates#8027] [Q&A] [answered]
hello community

I was wondering could it be that the nuclei templates are testing the http Cookie headers from a SQL injection vulnerability

Example:
https://portswigger.net/web-security/sql-injection/blind/lab-time-delays

I tried it and it didn't work..
I tried external templates through github and it didn't work to detect injection

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    headers:
      User-Agent: "' x'||pg_sleep(20)--'"
      Content-Length: "' x'||pg_sleep(15)--'"
      Cookie: "'x'||pg_sleep(10)--'"

    matchers:
      - type: dsl
        dsl:
          - 'duration>=10'
          -  'duration>=15'
          -  'duration>=20'
```
