### DISCUSSION TITLE
Templates cluster not working in sometimes

### DISCUSSION THREAD

**Discussion by SuperXiaoxiong** [projectdiscovery/nuclei-templates#8119] [Q&A]
When there are two templates

template1 

```
http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/index.php"
```

template2 
```
http:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/index.jsp"
```

As expect:
when template cluster worked
It will do 3 request:
1. "{{BaseURL}}"
2. "{{BaseURL}}/index.php"
3. "{{BaseURL}}/index.jsp"

But as result:
It do 4 request:
1. "{{BaseURL}}"
2. "{{BaseURL}}"
3. "{{BaseURL}}/index.php"
4. "{{BaseURL}}/index.jsp"

there is a dup request in the same path 

So how to resolve the problem , It is work by designed ?
Or is there some better pratice for this moment
