### DISCUSSION TITLE
Base64 Decode and match

### DISCUSSION THREAD

**Discussion by random-robbie** [projectdiscovery/nuclei-templates#8781] [Q&A] [answered]
I am struggling to get the AI to generate a working template for this.

I want to be able to use an extractor to take a base64 string and then decode it and then match for words inside that decoded string.

Any one able to assist?

**Comment by princechaddha** [comment, marked as answer]
Hi @random-robbie, The response time to this issue was much longer than usual. You can do so using a extractor and dsl matcher

```yaml
http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: dsl
        dsl:
          - base64_decode(string) == "test"

    extractors:
      - type: regex
        part: body
        name: string
        group: 1
        internal: true
        regex:
          - <text>([a-zA-Z=]+)<\/text>
```
