### DISCUSSION TITLE
How can we use 2 or more dns requests in a single template

### DISCUSSION THREAD

**Discussion by iamxhunt3r** [projectdiscovery/nuclei-templates#9108] [General]
For example i need to check softfail spf without dmarc

SO i need two dns request 

```yaml
- name: "{{FQDN}}"
     type: TXT
     
- name: "_dmarc.{{FQDN}}"
   type: TXT
```
   
  With their each matcher and dependant on each other.
  
  like a if condition
  
  Please comment
