### ISSUE TITLE
[FTL] Could not run nuclei: no templates provided for scan

### ISSUE THREAD

**Issue by yogendra-singh-rathore** [projectdiscovery/nuclei-templates#10025]
### Issue description:
[FTL] Could not run nuclei: no templates provided for scan

![Screenshot 2024-06-13 115804](https://github.com/projectdiscovery/nuclei-templates/assets/24251342/156f2011-f7d2-4e48-b760-46d6e9522bbe)

even i sign my template
[
![Screenshot 2024-06-13 164413](https://github.com/projectdiscovery/nuclei-templates/assets/24251342/74b6c287-34fe-41d4-ad62-142fb55f5b51)
](url)

Here is my code:
id: xss-detection
info:
  name: Cross-Site Scripting Detection
  author: yourname
  severity: medium
requests:
  - method: GET
    path:
      - "{{BaseURL}}/#/search?q=<iframe src=<script>alert(1)</script>"
matchers:
    - type: word
      words:
        - "<script>alert(1)</script>"
      part: body
# digest: 490a0046304402200683a9ad39f2c3aa846ed829af8b10db381cbd84723a6d8dadaf6044679cce45022075cff6f3729b11393f5ee743b1f3fada1a7620c5385323853a7ca62851154904:90b8c143e584318207909ca5fa1c5999

**Comment by Mzack9999** [comment]
I think your template is not formatted properly, this works for me:
```yaml
id: xss-detection
info:
  name: Cross-Site Scripting Detection
  author: yourname
  severity: medium
  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/#/search?q=<iframe src=<script>alert(1)</script>"
    matchers:
      - type: word
        words:
          - "<script>alert(1)</script>"
        part: body
```
