### ISSUE TITLE
 JSON Web Key (JWK) File Finder.

### ISSUE THREAD

**Issue by Mohsen-Yaghoubi** [projectdiscovery/nuclei-templates#10207]
### Template Information:

Searches for JSON Web Key (JWK) file.
https://portswigger.net/web-security/jwt/algorithm-confusion

### Nuclei Template:

```yaml
id: jwk-json-leak 

info:
  name: JSON Web Key File leakage
  author: Mohsen Yaghoubi
  severity: medium
  description: Searches for JSON Web Key (JWK) file.
  tags: exposure,token,generic
  
http:
  - method: GET
    path:
      - "{{BaseURL}}/.well-known/jwks.json"
      - "{{BaseURL}}/.well-known/jwks"
      - "{{BaseURL}}/jwks.json"
      - "{{BaseURL}}/jwks"
    matchers:
      - type: word
        name: id
        words:
          - '"kid":'
```

### Result: 
[jwk-json-leak:id] [http] [medium] https:/Url/.well-known/jwks.json
