### ISSUE TITLE
Many False Positives due to CVE-2023-35161 template

### ISSUE THREAD

**Issue by tarunkant** [projectdiscovery/nuclei-templates#10261]
### Nuclei Version:

[INF] Nuclei Engine Version: v3.2.9

### Template file:

http/cves/2023/CVE-2023-35161.yaml

### Description:
It was noticed that this template caused many false positives as the matchers are weak. If the host just returns the URI value in response, the template will detect as the finding which in actual case is a false positive. It is recommended to please make the matchers more strictly based on the CVE information to reduce false positives.

Current Matcher:
```
matchers:
      - type: word
        part: body
        words:
          - 'javascript:alert(document.domain)'
          - 'DeleteApplication'
        condition: and

      - type: word
        part: header
        words:
          - 'text/html'

      - type: status
        status:
          - 200
          - 401
   ```
