### ISSUE TITLE
[nuclei-template] substack.com user user detection (osint)

### ISSUE THREAD

**Issue by cheesymoon** [projectdiscovery/nuclei-templates#10350]
### Template Information:

Very basic user enumeration on substack.com

### Nuclei Template:

```yaml
id: substack

info:
  name: substack.com User Name Information - Detect
  author: cheesymoon
  severity: info
  description: substack.com user name information check was conducted.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,substack

self-contained: true

http:
  - method: GET
    path:
      - "https://substack.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        negative: true
        words:
          - "No people found for"

      - type: word
        part: body
        words:
          - "@{{user}}"

```

![image](https://github.com/user-attachments/assets/3c5c63bd-d56c-49d5-9d00-9486ff124a6f)
