### ISSUE TITLE
nacos-version.yaml

### ISSUE THREAD

**Issue by k3mlol** [projectdiscovery/nuclei-templates#10517]
### Nuclei Version:
v3.2.8

### Template file:
http/technologies/nacos-version.yaml

### Command to reproduce:
nuclei -t http/technologies/nacos-version.yaml -u https://live-backstage.tiktok.com -duc

### updated template

``` yaml
id: nacos-version

info:
  name: Nacos - Detect
  author: Arm!tage
  severity: info
  description: |
    Nacos was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: title:"Nacos"
  tags: tech,detect,nacos

http:
- method: GET
  path:
  - '{{BaseURL}}/v1/console/server/state?accessToken=&username='
  - '{{BaseURL}}/nacos/v1/console/server/state?accessToken=&username='

  matchers-condition: and
  matchers:
  - type: regex
    regex:
    - '"version":"(\d+\.\d+\.\d+)"'

  - type: status
    status:
    - 200

  - type: word
    words:
    - "application/json"
    part: header

  extractors:
  - type: regex
    part: body
    regex:
    - '"version":"(\d+\.\d+\.\d+)"'
```
