### ISSUE TITLE
update http/exposed-panels/xiaomi-wireless-router-login.yaml

### ISSUE THREAD

**Issue by k3mlol** [projectdiscovery/nuclei-templates#10520]
### Template Information:
http/exposed-panels/xiaomi-wireless-router-login.yaml, I add     - <title>Mi Router</title>

### Nuclei Template:

```yaml
id: xiaomi-wireless-router-login

info:
  name: Xiaomi Wireless Router Admin Panel - Detect
  author: lu4nx
  severity: info
  description: |
    Xiaomi Wireless router admin panel was detected.
  reference:
  - https://www.mi.com/shop/search?keyword=%E8%B7%AF%E7%94%B1%E5%99%A8
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
    shodan-query: http.title:"小米路由器"
    zoomeye-query: title:'小米路由器'
  tags: panel,xiaomi

http:
- method: GET
  path:
  - '{{BaseURL}}/cgi-bin/luci/web'

  matchers-condition: and
  matchers:
  - type: word
    part: body
    words:
    - <title>小米路由器</title>
    - <title>Redmi路由器</title>
    - <title>Mi Router</title>
    condition: or

  - type: status
    status:
    - 200

```
