### ISSUE TITLE
Github Pages Subdomain Takeover No Longer Detected

### ISSUE THREAD

**Issue by syntacticNaCl** [projectdiscovery/nuclei-templates#10552]
### Nuclei Version:

3.3.0

### Template file:

`/http/takeovers/github-takeover.yaml`

### Command to reproduce:
`nuclei -u <domain-to-test> -id github-takeover`

It appears that the "word" matchers are no longer valid since the 404 page has been changed by Github. Previously it was looking for:
```
      - type: word
        words:
          - "There isn't a GitHub Pages site here."
          - "For root URLs (like http://example.com/) you must provide an index.html file"
        condition: or
```
but that no longer matches. We should update the matchers so that it can begin detecting takeovers again.

<img width="948" alt="Screenshot 2024-08-15 at 5 47 37 PM" src="https://github.com/user-attachments/assets/1de5d8ca-aa31-4635-b645-0181d4da3f1f">
