### ISSUE TITLE
[Bug] Template sets 'regex' while 'regex' is not in use

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#1064]
In CVE-2020-35476.yaml

It seems that the 'regex' is being defined while no regex is provided

In addition 'regex' parameter is being used, while in other yamls 'words' is use - which one is the correct one?

```
  - type: regex
        regex:
          - plotted
          - timing
          - cachehit
        part: body
        condtion: and
```
