### ISSUE TITLE
[nuclei-template] Anonymous FTP Template

### ISSUE THREAD

**Issue by celsec** [projectdiscovery/nuclei-templates#1065]
**Template Details**

```yaml

id: exposed-ftp

info:
  name: FTP Anonymous Login
  author: Celesian ( @C3l3si4n )
  severity: Medium
  reference: https://tools.ietf.org/html/rfc2577
  tags: network,ftp

network:
  - inputs:
      - data: "USER anonymous\r\nPASS nuclei\r\n"

    host:
      - "{{Hostname}}"
      - "{{Hostname}}:21"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "230"
      - type: word
        negative: true
        words:
          - "530"
```
