### ISSUE TITLE
[nuclei-template] Default Login Check via API on Port 81 nginx-proxy-manager

### ISSUE THREAD

**Issue by barttran2k** [projectdiscovery/nuclei-templates#10721]
### Template Information:

Check login for Default Login nginx-proxy-manager on Port 81

### Nuclei Template:

```yaml
id: check-default-login-nginx-proxy-manager-port-81

info:
  name: Default Login Check via API on Port 81 nginx-proxy-manager
  author: barttran2000
  severity: high
  tags: login, default, auth, api

requests:
  - method: POST
    path:
      - "http://{{Hostname}}:81/api/tokens"
    body: |
      {
        "identity": "admin@example.com",
        "secret": "changeme"
      }
    headers:
      Content-Type: application/json

    matchers:
      - type: word
        words:
          - "token"        
          - "expires"
        condition: or
      - type: status
        status:
          - 200

```
