### ISSUE TITLE
how to set header as dynamic parameter

### ISSUE THREAD

**Issue by k3mlol** [projectdiscovery/nuclei-templates#10730]
Hi, I want to set the header as dynamic parameter, how to write this template?

``` yaml
id: scan-header-cus

info:
  name: detect custom header 
  author: k3mlol
  severity: low
  description: detect custom header
  metadata:
    verified: true
  tags: headers

flow: |
  http(1);
  for (let c_header of iterate(template["custom_headers"])) {
    set("c_header", c_header);
    http(2);
  }
http:
  - method: OPTIONS
    path:
      - '{{BaseURL}}'

    headers:
      Origin: '{{BaseURL}}'

    extractors:
      - type: kval
        name: custom_headers
        kval:
          - allow_headers
        internal: true
        group: 1
      
  - method: GET
    path:
      - "{{BaseURL}}"
    
    headers:
      {{c_header}}: ssss
    
    matchers-condition: and
    matchers:
    - type: status
      status:
      - 200
```
