### ISSUE TITLE
CVE-2017-15944 RCE on Palo Alto GlobalProtect

### ISSUE THREAD

**Issue by emadshanab** [projectdiscovery/nuclei-templates#1091]
```yaml
id: CVE-2017-15944

info:
 name: PreAuth RCE on Palo Alto GlobalProtect
 author: emadshanab
 severity: high
 reference: http://blog.orange.tw/2019/07/attacking-ssl-vpn-part-1-preauth-rce-on-palo-alto.html
 tags: cve,cve2017,rce,vpn

requests:
 - method: GET
   path:
    - "{{BaseURL}}/global-protect/portal/css/login.css"
   matchers-condition: and
   matchers:
    - type: word
      words:
       - "Last-Modified: Sun, 10 Sep 2017 16:48:23 GMT"
      part: body

    - type: status
      status:
       - 200
```
