### ISSUE TITLE
file-upload-endpoint

### ISSUE THREAD

**Issue by mchklt** [projectdiscovery/nuclei-templates#10994]
Detects endpoints with forms that contain file upload functionality by identifying form tags with relevant attributes such as method, input, and button elements. This can potentially expose the application to risks like remote code execution, XSS attacks, or abuse of the server for hosting malicious files.

**Comment by mchklt** [comment]
```yaml
id: file-upload-endpoint
info:
  name: File Upload Endpoint Detection
  author: YourName
  severity: info
  description: Detects endpoints with forms containing file upload fields by checking for form tags with method, input, and button elements.

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "<form[^>]*method=[\"']?(post|POST)[\"']?[^>]*>"
          - "<input[^>]*type=[\"']?file[\"']?[^>]*>"
          - "<button[^>]*type=[\"']?submit[\"']?[^>]*>"
        condition: or
      - type: regex
        part: body
        regex:
          - "type=[\"'](file)[\"']"
          - "<button[^>]*type=[\"']?submit[\"']?[^>]*>"
        condition: or
```

**Comment by mchklt** [comment]
```yaml
id: file-upload-endpoint
info:
  name: File Upload Endpoint Detection
  author: mchklt
  severity: info
  description: Detects endpoints with forms containing file upload fields by checking for form tags with method, input, and button elements.

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "<form[^>]*method=[\"']?(post|POST)[\"']?[^>]*>"
          - "<input[^>]*type=[\"']?file[\"']?[^>]*>"
          - "<button[^>]*type=[\"']?submit[\"']?[^>]*>"
        condition: or
      - type: regex
        part: body
        regex:
          - "type=[\"'](file)[\"']"
          - "<button[^>]*type=[\"']?submit[\"']?[^>]*>"
        condition: or
```
