### ISSUE TITLE
[nuclei-template] default login ZyXEL

### ISSUE THREAD

**Issue by wtzuq** [projectdiscovery/nuclei-templates#1125]
Here is a simple template for the default administration password on ZyXEL devices. I tested it only on two different ZyXEL devices, the authentication flow and the resulting page may differ on other models, so it needs more tests.

```yaml
id: zyxel-default-password

info:
  name: ZyXEL Default Password
  author: wtzu
  severity: high
  tags: zyxel

requests:
  - raw:
      - |
        POST /goform/formPassword HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Connection: close

        username=admin&Loginpassword=1234&Login=login

      - |
        GET /index.asp HTTP/1.1
        Connection: close

    matchers:
      - type: word
        words:
          - "setCurStatus"
```

**Comment by toufik-airane** [comment]
Dear @wtzuq,

If you use raw requests don't forget to set the `reuse-cookie` to `true` to make the session mechanism work.

In my opinion, to properly test a default credentials weakness, you should do it in a **one base request** style such as the next example:
```
requests:
  - method: POST
    path:
      - "{{BaseURL}}/goform/formPassword"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: |
      username=admin&Loginpassword=1234&Login=login
```

To move forward, please provide a valid matcher or an authentication workflow to work on the matcher.
Ping me if you need any help during the testing stage.

I will let the issue open for 30 days before taking further action.
