### ISSUE TITLE
matchers:       - type: regex         part: body         regex:           - "(?<![\"'])<hacktivist1337>hacktivist1337<\/hacktivist1337>(?![\"'])"         condition: and ```

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/nuclei-templates#11375]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Why am I getting escape errors even though I escape this regex?

```
    matchers:
      - type: regex
        part: body
        regex:
          - "(?<![\"'])<hacktivist1337>hacktivist1337<\/hacktivist1337>(?![\"'])"
        condition: and
```

![Image](https://github.com/user-attachments/assets/198fed26-5556-46fe-a06c-1a757c529438)

### Expected Behavior

There is no error in the site "https://jsonformatter.org/yaml-validator".There doesn't seem to be anything related to yaml layout.

### Steps To Reproduce

Add this method to any template. then test this

```

    matchers:
      - type: regex
        part: body
        regex:
          - "(?<![\"'])<hacktivist1337>hacktivist1337<\/hacktivist1337>(?![\"'])"
        condition: and
```

### Relevant log output

```shell

```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```
