### ISSUE TITLE
CVE-2024-6387.yaml

### ISSUE THREAD

**Issue by h3xploit0x1** [projectdiscovery/nuclei-templates#11426]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2024-6387

info:
  name: Detect RegreSSHion Vulnerability
  author: H3Xploit0X1
  severity: Critical
  description: An unauthenticated remote code execution in OpenSSH's server (sshd) that grants full root access.
  classification:
    cve-id: CVE-2024-6387
  metadata:
    max-request: 3
    vendor: OpenSSH
    product: OpenSSH
    fofa: app="OpenSSH"
    shodan: product:"OpenSSH"
  tags: cve,cve2024,ssh

tcp:
  - host:
      - '{{Hostname}}'
    port: 22
    matchers:
      - type: regex
        part: body
        regex:
          - 'OpenSSH_(8\.(5|6|7|8|9)p?[12]?|9\.(0|1|2|3|4|5|6|7)p?[12]?|[0-3]\.[0-9]p?[12]?|4\.(0|1|2|3)p?[12]?)'
    extractors:
      - type: regex
        part: body
        regex:
          - 'SSH-[0-9]+\.[0-9]+-.*'

```

### Relevant dumped responses

```shell

```
