### ISSUE TITLE
[TEMPLATE CONTRIBUTION] ...

### ISSUE THREAD

**Issue by bashird56** [projectdiscovery/nuclei-templates#11459]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: template-id

info:
  name: Install concrete5
  author: durrani
  severity: high
  description: concrete5 default installation page can lead to complete take over 
  reference:
    - https://
  tags: tags

http:
  - raw:
      - |+
        GET /index.php/install HTTP/1.1
        Host: {{Hostname}}
        Accept-Language: en-US,en;q=0.9
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.6778.140 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive
```

### Relevant dumped responses

```shell

```

### Anything else?

hi 
i found an issue in concrete5 were a default install page is not disabled and it can lead to complete take over 
the template is made with burp extension so you can make any changes as you please 
also could you add one one end point : /updates/concrete5-8.5.1/index.php/install
i m also adding screen short as a proof 

![Image](https://github.com/user-attachments/assets/d90d1058-98e0-434d-b64c-ac1b9c12bc6e)
