### ISSUE TITLE
[TEMPLATE CONTRIBUTION] Tyk API Gateway detection

### ISSUE THREAD

**Issue by davidfegyver** [projectdiscovery/nuclei-templates#11452]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: tyk-gateway-detect

info:
  name: Tyk API Gateway Detection
  author: davidfegyver
  severity: info
  reference: https://github.com/TykTechnologies/tyk
  description: |
    Detects if the application uses Tyk API Gateway

http:
  - method: GET
    path:
      - "{{BaseURL}}/hello"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Tyk GW"
      - type: word
        part: header
        words:
          - application/json
    extractors:
      - type: regex
        name: version
        part: body
        regex:
          - "\"version\":\"([^\"]*)\""
        group: 1
```

### Relevant dumped responses

```shell
HTTP/1.1 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Length: 155
Content-Type: application/json
Date: Sun, 05 Jan 2025 14:09:08 GMT
Via: 1.1 google

{
    "description": "Tyk GW",
    "details": {
        "redis": {
            "componentType": "datastore",
            "status": "pass",
            "time": "2025-01-05T14:09:01Z"
        }
    },
    "status": "pass",
    "version": "5.3.1"
}
```

### Anything else?

https://github.com/tykTechnologies/tyk?tab=readme-ov-file#step-3---deploy-tyk-gateway-and-redis
