### ISSUE TITLE
False Positive because of poor validation in: CVE-2020-0618

### ISSUE THREAD

**Issue by 53n4d** [projectdiscovery/nuclei-templates#11498]
### Template IDs or paths

https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2020/CVE-2020-0618.yaml

```yaml
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "view report"

      - type: status
        status:
          - 200
```

This validation is pretty naive. In a world of SPA where almost any response status is 200, trying to validate issue with simple string "view report" will produce a lot of FP. I faced it on my own, and that's why i checked this POC.

What is the problem here? The intention might have been to quickly identify instances as a precursor to further manual testing or exploitation.

No Exploitation Validation:

This vulnerability involves deserialization, which requires a crafted serialized payload sent via POST. A simple GET request cannot trigger or validate this behavior.

False Positives:

Many non-vulnerable SSRS instances will still respond with "view report" or a 200 status code for ReportViewer.aspx, leading to false positives.

The presence of the endpoint alone does not indicate the server is vulnerable to CVE-2020-0618.

No Payload Injection:

Without sending a payload to test deserialization, the template cannot confirm the existence of the vulnerability.

I suggest you to remove current POC, and to set a task to replace it with new one, to prevent FP
```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

### Steps To Reproduce

test raise an issue because of status code 200 and match: "view report" in this part:

meta property="og:description" content="--Redacted part-- web application is a secure, cloud based website that allows users to view reports and visualizations of their --Redacted part--"

as you can see there's a string: view reports -> and issue is raised based on it, even this page actually returns:

![Image](https://github.com/user-attachments/assets/bc9f3b52-5af1-4b43-996b-e1a673b0aa91)

### Relevant dumped responses

```shell

```

### Anything else?

Proposed solution: 

```yaml
id: CVE-2020-0618

info:
  name: Microsoft SQL Server Reporting Services - Remote Code Execution
  author: your-name
  severity: high
  description: Vulnerability in SQL Server Reporting Services (SSRS) due to improper handling of serialized objects, leading to RCE.
  impact: Allows arbitrary code execution on the server.
  remediation: Apply the latest security patches from Microsoft.
  references:
    - https://www.mdsec.co.uk/2020/02/cve-2020-0618-rce-in-sql-server-reporting-services-ssrs/
    - https://github.com/euphrat1ca/CVE-2020-0618
  classification:
    cve-id: CVE-2020-0618
    cwe-id: CWE-502
  tags: cve,rce,ssrs

http:
  - method: POST
    path:
      - "{{BaseURL}}/ReportServer/Pages/ReportViewer.aspx"

    headers:
      Content-Type: application/x-www-form-urlencoded

    body: |
      <serialized-payload>

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "specific-response-or-indicator-of-execution"

      - type: status
        status:
          - 200
```
