### ISSUE TITLE
[nuclei-template] bookstack-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1157]
**Template Details**

This template detects installations of [BookStackApp/BookStack](https://github.com/BookStackApp/BookStack).  

```yaml
id: bookstack-detect

info:
  name: BookStack detect
  author: cyllective
  severity: info
  description: Detects BookStack
  tags: technology,bookstack
  references:
    - https://github.com/BookStackApp/BookStack

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login"
      - "{{BaseURL}}/books"
      - "{{BaseURL}}/shelves"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<title>Shelves | BookStack</title>'
          - '<title>Books | BookStack</title>'
          - '<title>BookStack</title>'
          - '<span class="logo-text">BookStack</span>'

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?:app\.js|(?:print\-)?styles\.css)\?version=([\w\.\-]+)["'']>'
```
