### ISSUE TITLE
[nuclei-template] moinmoin-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1159]
**Template Details**

Detects installations of [moinwiki/moin-1.9](https://github.com/moinwiki/moin-1.9) AKA. MoinMoin.  

The regex pattern tries to filter for the [short version string](https://github.com/moinwiki/moin-1.9/blob/1.9.11/MoinMoin/version.py#L19), which discloses the exact version of MoinMoin.

```yaml
id: moinmoin-detect

info:
  name: MoinMoin wiki detect
  author: cyllective
  severity: info
  description: Detects MoinMoin Wiki
  tags: technology,moin,moinmoin,wiki
  references:
    - https://github.com/moinwiki/moin-1.9
    - https://github.com/moinwiki/moin-1.9/blob/1.9.11/MoinMoin/version.py#L19

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/robots.txt"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<a href="http://moinmo.in/" title="This site uses the MoinMoin Wiki software.">MoinMoin Powered</a>'
          - '<a href="http://moinmo.in/Python" title="MoinMoin is written in Python.">Python Powered</a>'
          - '#        url_prefix_action to "action", cf. HelpOnConfiguration'

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '\/moin_static(\w+)\/'
```
