### ISSUE TITLE
[nuclei-template] bolt-cms-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1160]
**Template Details**

This template detects installations of [bolt/bolt](https://github.com/bolt/bolt) CMS.

```yaml
id: bolt-cms-detect

info:
  name: bolt CMS detect
  author: cyllective
  severity: info
  description: Detects bolt CMS
  tags: technology,bolt,cms
  references:
    - https://github.com/bolt/bolt

requests:
  - method: GET
    path:
      - "{{BaseURL}}/bolt/login"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<form action="/bolt/login"'
          - '<img class="logo" alt="Bolt CMS logo"'
          - '<img src="/app/view/img/bolt-logo.png"'
          - '<link rel="shortcut icon" href="/app/view/img/favicon-bolt.ico">'
          - '<link rel="stylesheet" href="/app/view/css/bolt-old-ie.css"'
          - '<link rel="stylesheet" href="/app/view/css/bolt.css"'
          - '<script src="/app/view/js/bolt.js"></script>'
          - '<script src="/app/view/js/bolt.min.js"'
          - '<script src="/assets/bolt.js"></script>'
          - 'Bolt requires JavaScript to function properly and continuing without it might corrupt or erase data.'
          - 'Bolt » Login'
          - 'Cookies are required to log on to Bolt. Please allow cookies.'
```
