### ISSUE TITLE
[nuclei-template] strapi-cms-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1161]
**Template Details**

This template detects installations of [strapi/strapi](https://github.com/strapi/strapi)

```yaml
id: strapi-cms-detect

info:
  name: strapi CMS detect
  author: cyllective
  severity: info
  description: Detects strapi CMS
  tags: technology,strapi,cms
  references:
    - https://github.com/strapi/strapi

requests:
  - method: GET
    path:
      - "{{BaseURL}}/admin/auth/login"
      - "{{BaseURL}}/admin/auth/forgot-password"
      - "{{BaseURL}}/documentation/"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<title>Strapi Admin</title>'
          - '<title>Strapi'
          - '"x-strapi-config":'
```
