### ISSUE TITLE
[nuclei-template] shopware-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1162]
**Template Details**

This template detects installations of [shopware/shopware](https://github.com/shopware/shopware) and [shopware/platform](https://github.com/shopware/platform). Shopware v5 and Shopware v6 respectively.

```yaml
id: shopware-detect

info:
  name: Shopware CMS detect
  author: cyllective
  severity: info
  description: Detects Shopware CMS
  tags: technology,shopware,cms
  references:
    - https://github.com/shopware/shopware
    - https://github.com/shopware/platform

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/admin"
      - "{{BaseURL}}/backend"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - 'class="icon icon-shopware icon-xs"'
          - '<i class="icon--shopware"></i>'
          - 'Realisiert mit Shopware'
          - 'Realised with Shopware'
          - 'Shopware Administration (c) shopware AG'
          - '<title>Shopware 5 - Backend (c) shopware AG</title>'
```
