### ISSUE TITLE
Suggestion to Extend Spring Boot Heap Dump Template for BBO Endpoints

### ISSUE THREAD

**Issue by laurashalmaev** [projectdiscovery/nuclei-templates#11653]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: springboot-heapdump

info:
  name: Spring Boot Actuator - Heap Dump Detection (Extended for BBO Endpoints)
  author: that_juan_, dwisiswant0, wdahlenb, laurashalmaev
  severity: critical
  description: |
    A Spring Boot Actuator heap dump was detected. A heap dump is a snapshot of JVM memory, which could expose environment variables and HTTP requests.
    This template has been extended to include additional BBO-related endpoints.
  reference:
    - https://github.com/pyn3rd/Spring-Boot-Vulnerability
  metadata:
    max-request: 13
  tags: springboot, exposure, misconfig

variables:
  str: "{{rand_base(6)}}"

http:
  - raw:
      - |
        GET /{{str}} HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-admin/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-admin/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-rest/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-rest/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-search/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-search/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-token/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-token/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-vin/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-vin/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}

    max-size: 2097152 # 2MB - Max Size to read from server response

    matchers-condition: or
    matchers:
      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_2), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_3), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_4), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_5), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_6), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_7), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_8), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_9), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_10), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_11), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_12), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_13), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "contains(hex_encode(body_2), '4a4156412050524f46494c45') || contains(hex_encode(body_2), '4850524f46')"
          - "contains(hex_encode(body_3), '4a4156412050524f46494c45') || contains(hex_encode(body_3), '4850524f46')"
        condition: or
```

### Relevant dumped responses

```shell

```

### Anything else?

The current `springboot-heapdump.yaml` template (https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/springboot/springboot-heapdump.yaml) only checks the default actuator heapdump endpoints. However, additional heap dump exposures in found in BBO-related endpoints such as:

- `/bbo-admin/heapdump`
- `/bbo-rest/heapdump`
- `/bbo-search/heapdump`
- `/bbo-token/heapdump`
- `/bbo-vin/heapdump`

Suggest adding these paths to improve coverage.

https://threats.wiz.io/all-incidents/volkswagen-massive-data-leak-through-spring-boot-actuator-misconfiguration 

```
id: springboot-heapdump

info:
  name: Spring Boot Actuator - Heap Dump Detection (Extended for BBO Endpoints)
  author: that_juan_, dwisiswant0, wdahlenb, laurashalmaev
  severity: critical
  description: |
    A Spring Boot Actuator heap dump was detected. A heap dump is a snapshot of JVM memory, which could expose environment variables and HTTP requests.
    This template has been extended to include additional BBO-related endpoints.
  reference:
    - https://github.com/pyn3rd/Spring-Boot-Vulnerability
  metadata:
    max-request: 13
  tags: springboot, exposure, misconfig

variables:
  str: "{{rand_base(6)}}"

http:
  - raw:
      - |
        GET /{{str}} HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-admin/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-admin/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-rest/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-rest/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-search/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-search/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-token/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-token/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-vin/heapdump HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /bbo-vin/actuator/heapdump HTTP/1.1
        Host: {{Hostname}}

    max-size: 2097152 # 2MB - Max Size to read from server response

    matchers-condition: or
    matchers:
      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_2), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_3), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_4), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_5), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_6), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_7), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_8), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_9), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_10), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_11), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_12), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "!contains(hex_encode(body_1), '1f8b080000000000')"
          - "contains(hex_encode(body_13), '1f8b080000000000')"
        condition: and

      - type: dsl
        dsl:
          - "contains(hex_encode(body_2), '4a4156412050524f46494c45') || contains(hex_encode(body_2), '4850524f46')"
          - "contains(hex_encode(body_3), '4a4156412050524f46494c45') || contains(hex_encode(body_3), '4850524f46')"
        condition: or

```
