### ISSUE TITLE
[nuclei-template] opencast-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1173]
**Template Details**

Detects installations of [opencast/opencast](https://github.com/opencast/opencast).

```yaml
id: opencast-detect

info:
  name: Opencast detect
  author: cyllective
  severity: info
  description: Detects Opencast
  tags: technology,opencast
  references:
    - https://github.com/opencast/opencast

requests:
  - method: GET
    path:
      - "{{BaseURL}}/admin-ng/login.html"
      - "{{BaseURL}}/info/me.json"
      - "{{BaseURL}}/engage/ui/index.html"
      - "{{BaseURL}}/oaipmh/default?verb=ListMetadataFormats"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<title>Opencast</title>'
          - '"org.opencastproject.admin.help.restdocs.url":'
          - '"org.opencastproject.'
          - '<meta name="description" content="Opencast Media Module">'
          - '<schema>http://www.opencastproject.org/oai/matterhorn'
          - '<metadataNamespace>http://www.opencastproject.org/oai/matterhorn'
```
