### ISSUE TITLE
CVE-2025-2129

### ISSUE THREAD

**Issue by zn9988** [projectdiscovery/nuclei-templates#11775]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2025-2129

info:
  name: Mage AI - Insecure Default Authentication Setup Leading to Zero-Click RCE
  author: zn9988 (https://github.com/zn9988) | H0j3n (https://github.com/h0j3n)
  severity: Medium
  description: Check for unauthenticated access to Mage AI - Insecure Default Authentication Setup Leading to Zero-Click RCE
  classification:
   cvss-metrics: CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N
   cvss-score: 6.3
   cve-id: CVE-2025-2129
  reference:
   - https://nvd.nist.gov/vuln/detail/CVE-2025-2129
   - https://github.com/zn9988/publications/tree/main/2.Mage-AI%20-%20Insecure%20Default%20Authentication%20Setup%20Leading%20to%20Zero-Click%20RCE
  tags: auth,bypass,cve,rce,http

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/kernels"

    headers:
      Content-Type: application/json
      Connection: close

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"kernels":'
        part: body
```

### Relevant dumped responses

```shell
nuclei -u http://localhost:6789 -t CVE-2025-2129.yaml
                   __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.10

		projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[INF] Current nuclei version: v3.3.10 (latest)
[INF] Current nuclei-templates version: v10.1.5 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 281
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[CVE-2025-2129] [http] [medium] http://localhost:6789/api/kernels
```

### Anything else?

Template / PR Information
Added [CVE-2025-2129](https://www.cve.org/CVERecord?id=CVE-2025-2129)
References: [Proof Of Concept](https://github.com/zn9988/publications/tree/main/2.Mage-AI%20-%20Insecure%20Default%20Authentication%20Setup%20Leading%20to%20Zero-Click%20RCE)
The template was tested against Mage-AI v0.9.75
