### ISSUE TITLE
[TEMPLATE CONTRIBUTION] ...CVE-2025-20229.yaml (Splunk RCE via File Upload)

### ISSUE THREAD

**Issue by 0xKayala** [projectdiscovery/nuclei-templates#11833]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2025-20229

info:
  name: Splunk Enterprise RCE via File Upload - CVE-2025-20229
  author: 0xKayala
  severity: high
  description: |
    Detects Splunk Enterprise versions vulnerable to CVE-2025-20229, a Remote Code Execution vulnerability exploitable by a low-privileged user via malicious file uploads to the apptemp directory.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2025-20229
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H
    cvss-score: 8.0
    cve-id: CVE-2025-20229
  tags: splunk, rce, cve-2025

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/en-US/splunkd/__raw/services/server/info"

    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Nuclei"

    matchers:
      - type: dsl
        dsl:
          - "contains(tolower(body), 'splunk') && status_code == 200"
        name: splunk-detection
        condition: and

      - type: regex
        part: body
        regex:
          # Vulnerable Splunk Enterprise versions: Below 9.3.3, 9.2.5, 9.1.8
          - 'version[" ]*:[" ]*(9\.[0-2]\.[0-4]|[0-8]\..*|9\.3\.[0-2]|9\.2\.[0-4]|9\.1\.[0-7])'
        name: vulnerable-version
        condition: or

      - type: status
        status:
          - 200
        condition: and

    extractors:
      - type: regex
        name: version
        part: body
        regex:
          - 'version[" ]*:[" ]*([0-9]+\.[0-9]+\.[0-9]+)'

    matchers-condition: and

  - method: POST
    path:
      - "{{BaseURL}}/en-US/splunkd/__raw/servicesNS/nobody/system/storage/collections/data/apptemp"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Nuclei"
      Content-Type: "application/json"
    body: |
      {"test": "nuclei-check"}

    matchers:
      - type: status
        status:
          - 403
          - 401
        negative: true
        condition: or
      - type: word
        words:
          - "apptemp"
        part: body
        condition: and
    description: "Checking for unrestricted access to apptemp directory (CVE-2025-20229)"
```

### Relevant dumped responses

```shell

```
