### ISSUE TITLE
[TEMPLATE CONTRIBUTION] Erlang/OTP SSH RCE Vulnerability - CVE-2025-32433

### ISSUE THREAD

**Issue by denizcevik** [projectdiscovery/nuclei-templates#11955]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: CVE-2025-32433

info:
  name: Erlang/OTP SSH RCE Vulnerability - CVE-2025-32433
  description: CVE-2025-32433 check template based on POC https://github.com/ProDefense/CVE-2025-32433
  author: BIZZYLABS.IO
  severity: critical

tcp:
- host:
    - "{{Hostname}}"
  port: 22,2222
  read-size: 1024

  inputs:
    - data: "SSH-2.0-OpenSSH_8.9\r\n"
      read: 1024
    - data: "50"
      type: hex
      read: 1024

  matchers:
    - type: word
      words:
        - "Erlang"
        - "OTP"
      part: response_1

    - type: word
      words:
        - "Protocol mismatch"
        - "Disconnect"
      part: response_2
      negative: true

  extractors:
    - type: regex
      name: banner
      part: response_1
      group: 0
      regex:
        - "SSH-2.0-.*"
```

### Relevant dumped responses

```shell

```
