### ISSUE TITLE
nti-enviromuux-default-login

### ISSUE THREAD

**Issue by digitalsurgn** [projectdiscovery/nuclei-templates#12028]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: nti-enviromuux-default-login

info:
  name: Network Technologies Inc ENVIROMUX Default Login
  author: M.Sarmad Shafiq
  severity: high
  description: Attempts default credentials (username=root, password=nti) on NTI ENVIROMUX system.
    Only reports when login is successful Models ENVIROMUX-2D,ENVIROMUX-5D,ENVIROMUX-MINI-LXO .
  reference:
    - http://www.networktechinc.com/download/d-environment-monitor-16.html
    - http://www.networktechinc.com/pdf/man154.pdf
  tags: default-login,networktechinc,enviro,http,scada

requests:
  - method: POST
    path:
      - "{{BaseURL}}/goform/login"
    headers:
      Content-Type: application/x-www-form-urlencoded
      X-Requested-With: XMLHttpRequest
      Accept-Language: en-US,en;q=0.9
      Accept: application/json, text/javascript, */*; q=0.01
      Origin: "{{BaseURL}}"
      Referer: "{{BaseURL}}/login.asp"
      Accept-Encoding: gzip, deflate, br
      Connection: keep-alive
    body: "username=root&password=nti"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"success":"true"'
          - '"cookie":"sessionId='
        condition: and
      - type: status
        status:
          - 200
```

### Relevant dumped responses

```shell
[DBG] [nti-enviromuux-default-login] Dumped HTTP response http://10.1.1.1/goform/login

HTTP/1.0 200 OK
Connection: close
Cache-Control: no-cache
Content-Type: text/html; charset="UTF-8"
Pragma: no-cache
Server: GoAhead-Webs

{ "success":"true", "cookie":"sessionId=cm9vdDpudGk6MTQ=" }
[nti-enviromuux-default-login:word-1] [http] [high] http://10.1.1.1/goform/login
[nti-enviromuux-default-login:status-2] [http] [high] http://10.1.1.1/goform/login
```

### Anything else?

About the product: 
The ENVIROMUX® Enterprise Environment Monitoring System monitors critical environmental conditions, such as temperature, humidity, liquid water presence, power, intrusion, and smoke. When a sensor goes out of range of a configurable threshold, the system will notify you via email, LEDs, alarm beacon, siren, web page, network management (SNMP), voice phone calls (via Automatic Voice Dialer System), and SMS messages (via external USB 3G modem)
 Links:
    - http://www.networktechinc.com/download/d-environment-monitor-16.html
    - http://www.networktechinc.com/pdf/man154.pdf
