### ISSUE TITLE
[nuclei-template] access-log-file

### ISSUE THREAD

**Issue by hackerrishad** [projectdiscovery/nuclei-templates#1203]
**Template Details**

```yaml
id: access-log-file

info:
  name: Publicly accessible access-log file
  author: sheikhrishad
  severity: low
  tags: log

requests:
  - method: GET
    path:
      - "{{BaseURL}}/access.log"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "GET /"

      - type: word
        words:
          - "text/plain"
        part: header

      - type: status
        status:
          - 200
```

**Comment by geeknik** [comment]
A minor suggestion would be to add another matcher: 

```
      - type: word
        words:
          - "text/plain"
        part: header
```
