### ISSUE TITLE
[TEMPLATE CONTRIBUTION] ...Git Configuration File Exposure

### ISSUE THREAD

**Issue by R-Sudharshan** [projectdiscovery/nuclei-templates#12058]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: exposed-git-config

info:
  name: Exposed Git Config File
  author: Sudharshan R
  severity: high
  description: Detects exposed .git/config file that may lead to source code disclosure
  tags: git,source-disclosure,misconfig

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers:
      - type: word
        words:
          - "[core]"
          - "repositoryformatversion"
        condition: and

    extractors:
      - type: regex
        regex:
          - 'url = (.+)'
```

### Relevant dumped responses

```shell

```

### Anything else?

The template has been tested against  target where .git/config was publicly accessible. It reliably detects the presence of Git configuration files.The url extractor helps identify exposed remote repositories, such as GitHub or GitLab URLs.

This template helps detect serious misconfigurations that could lead to full source code leakage. It works with both HTTP and HTTPS

Reference:
https://docs.gitlab.com/security/
