### ISSUE TITLE
[TEMPLATE CONTRIBUTION] SAP Netweaver Composition Environment Tools Detect

### ISSUE THREAD

**Issue by ap3r** [projectdiscovery/nuclei-templates#12072]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: sap-netweaver-cet-disclosure

info:
  name: SAP NetWeaver Composition Environment Tools Information Disclosure
  author: ap3r
  severity: info
  description: Detects the presence of the SAP NetWeaver Process Integration / Composition Environment Tools page
  reference:
    - https://www.sap.com/
    - https://help.sap.com/doc/saphelp_scm700_ehp02/7.0.2/en-US/f6/2a7cb018bc4b239ea5b7af675a18ef/content.htm?no_cache=true
  tags: sap, disclosure, default-page

http:
  - method: GET
    path:
      - "{{BaseURL}}/rep/start/index.jsp" # Construct full URL here

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "NPP: Composition Environment Tools"
          - "Composition Environment Tools"
        condition: and

      - type: word
        part: header
        words:
          - "text/html"
        condition: and
```

### Relevant dumped responses

```shell
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[DBG] [sap-netweaver-pit-disclosure] Dumped HTTP response https://xx.xx.xx.xx:443/rep/start/index.jsp

HTTP/1.1 200 OK
Connection: close
Content-Type: text/html;charset=ISO-8859-1
Date: Tue, 13 May 2025 12:26:33 GMT
Set-Cookie: BIGipServerpool_temp_b2b_b2c_50001=xxx; path=/; Httponly; Secure

<html>
<head>
<TITLE>	NPP: Composition Environment Tools</TITLE>
<META http-equiv="expires" content="0">
<META http-equiv="cache-control" content="no-cache">
<META name="description" content="Startpage for the Composition Environment Tools">
<META name="keywords" content="Composition Environment Tools">
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="streamline.css" type="text/css">
<link rel="stylesheet" href="xi.css" type="text/css">
<link rel="shortcut icon" href="./layout/Netweaver.ico" type="image/ico">

<-- snip -->
```

### Anything else?

https://help.sap.com/doc/saphelp_scm700_ehp02/7.0.2/en-US/f6/2a7cb018bc4b239ea5b7af675a18ef/content.htm?no_cache=true
