### ISSUE TITLE
[TEMPLATE CONTRIBUTION] bitbucket-oauth-exposure

### ISSUE THREAD

**Issue by thezakman** [projectdiscovery/nuclei-templates#12265]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: bitbucket-oauth-exposure

info:
  name: Bitbucket OAuth Credentials Exposure
  author: TheZakMan
  severity: high
  description: Detects exposed auth.json files containing Bitbucket OAuth credentials
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  tags: exposure,bitbucket,oauth,credentials,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/auth.json"
      - "{{BaseURL}}/.auth.json"
      - "{{BaseURL}}/config/auth.json"
      - "{{BaseURL}}/configs/auth.json"
      - "{{BaseURL}}/configuration/auth.json"
      - "{{BaseURL}}/api/auth.json"
      - "{{BaseURL}}/app/auth.json"
      - "{{BaseURL}}/assets/auth.json"
      - "{{BaseURL}}/data/auth.json"
      - "{{BaseURL}}/files/auth.json"
      - "{{BaseURL}}/public/auth.json"
      - "{{BaseURL}}/static/auth.json"
      - "{{BaseURL}}/uploads/auth.json"
      - "{{BaseURL}}/backup/auth.json"
      - "{{BaseURL}}/backups/auth.json"
      - "{{BaseURL}}/tmp/auth.json"
      - "{{BaseURL}}/temp/auth.json"
      - "{{BaseURL}}/cache/auth.json"
      - "{{BaseURL}}/logs/auth.json"
      - "{{BaseURL}}/admin/auth.json"
      - "{{BaseURL}}/administrator/auth.json"
      - "{{BaseURL}}/src/auth.json"
      - "{{BaseURL}}/source/auth.json"
      - "{{BaseURL}}/www/auth.json"
      - "{{BaseURL}}/web/auth.json"
      - "{{BaseURL}}/site/auth.json"
      - "{{BaseURL}}/sites/auth.json"
      - "{{BaseURL}}/private/auth.json"
      - "{{BaseURL}}/secure/auth.json"
      - "{{BaseURL}}/secret/auth.json"
      - "{{BaseURL}}/secrets/auth.json"
      - "{{BaseURL}}/env/auth.json"
      - "{{BaseURL}}/environment/auth.json"
      - "{{BaseURL}}/test/auth.json"
      - "{{BaseURL}}/tests/auth.json"
      - "{{BaseURL}}/dev/auth.json"
      - "{{BaseURL}}/development/auth.json"
      - "{{BaseURL}}/staging/auth.json"
      - "{{BaseURL}}/prod/auth.json"
      - "{{BaseURL}}/production/auth.json"
      - "{{BaseURL}}/includes/auth.json"
      - "{{BaseURL}}/include/auth.json"
      - "{{BaseURL}}/lib/auth.json"
      - "{{BaseURL}}/libs/auth.json"
      - "{{BaseURL}}/library/auth.json"
      - "{{BaseURL}}/vendor/auth.json"
      - "{{BaseURL}}/vendors/auth.json"
      - "{{BaseURL}}/node_modules/auth.json"
      - "{{BaseURL}}/storage/auth.json"
      - "{{BaseURL}}/database/auth.json"
      - "{{BaseURL}}/db/auth.json"
      - "{{BaseURL}}/auth/auth.json"
      - "{{BaseURL}}/authentication/auth.json"
      - "{{BaseURL}}/oauth/auth.json"
      - "{{BaseURL}}/keys/auth.json"
      - "{{BaseURL}}/credentials/auth.json"
      - "{{BaseURL}}/creds/auth.json"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "bitbucket-oauth"
          - "bitbucket"
        condition: or
        case-insensitive: true

      - type: word
        words:
          - "consumer-secret"
          - "consumer-key"
          - "consumer_secret"
          - "consumer_key"
        condition: or
        case-insensitive: true

    extractors:
      - type: regex
        name: bitbucket_credentials
        regex:
          - '"consumer-key":\s*"([^"]+)"'
          - '"consumer-secret":\s*"([^"]+)"'
          - '"consumer_key":\s*"([^"]+)"'
          - '"consumer_secret":\s*"([^"]+)"'
        group: 1

      - type: regex
        name: bitbucket_oauth_block
        regex:
          - '"bitbucket-oauth":\s*\{[^}]+\}'
          - '"bitbucket":\s*\{[^}]+\}'
```

### Relevant dumped responses

```shell
Example:
[bitbucket-oauth-exposure:bitbucket_credentials] [http] [high] https://example.com/auth.json ["173mxQsLTelfnE3g3b","amf8rAZDybxq7TZMKAcxkhma1UJVpz3D"]
[bitbucket-oauth-exposure:bitbucket_oauth_block] [http] [high] https://example.com/auth.json  [""bitbucket-oauth": {\n        "bitbucket.org": {\n            "consumer-key": "173mxQsLTelfnE3g3b",\n            "consumer-secret": "amf8rAZDybxq7TZMKAcxkhma1UJVpz3D"\n        }"]

```
