### ISSUE TITLE
[nuclei-template]  CVE-2021-28073

### ISSUE THREAD

**Issue by z3bd** [projectdiscovery/nuclei-templates#1264]
**CVE-2021-28073 - ntopng Authentication Bypass versions < 4.3**

```yaml
id: CVE-2021-28073

info:
  name: ntopng Authentication Bypass (CVE-2021-28073)
  author: z3bd
  severity: critical
  description: Ntopng is a passive network monitoring tool focused on flows and statistics that can be obtained from the traffic captured by the server. There is a authentication bypass vulnerability in ntopng <= 4.2
  tags: ntopng,cve,rce,ssrf
  reference: |
      - http://noahblog.360.cn/ntopng-multiple-vulnerabilities/

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 302
        part: header

      - type: word
        words:
          - "Location: /lua/login.lua?referer="
        part: header
        condition: and

```
