### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by LuskaBol** [projectdiscovery/nuclei-templates#1265]
**Template Details**

```yaml
id: CVE-2020-13379

info:
  name: Denial of Service in Grafana
  author: LuskaBol
  severity: medium
  tags: cve,cve2020,grafana
  description: CVE-2020-13379
  reference: https://www.exploit-db.com/exploits/48638

requests:
  - method: GET
    path:
      - '{{BaseURL}}/avatar/ThisShouldNotExist'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "grafana_sess"
        part: header
        
      - type: status
        status:
          - 200
```

After some time of research I realized that the ssrf has been resolved and practically does not appear yet, but it is still possible to do the DoS
