### ISSUE TITLE
[nuclei-template] plone cms detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1267]
**Template Details**

This template detects installations of [plone/Products.CMFPlone](https://github.com/plone/Products.CMFPlone) (Plone CMS).

```yaml
id: plone-cms-detect

info:
  name: plone cms detect
  author: cyllective
  severity: info
  description: Detects Plone CMS
  tags: technology,plone,cms
  references:
    - https://github.com/plone/Products.CMFPlone

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/sitemap"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<meta name="generator" content="Plone - '
          - '<div xmlns:css="http://namespaces.plone.org/diazo/css"'
          - '/++plone++static/plone-compiled.css'
          - '/++plone++static/tinymce-styles.css'
          - '>Powered by Plone &amp; Python</a>'

      - type: regex
        part: body
        internal: true
        condition: or
        regex:
          - '\<link\s+?rel="stylesheet"\s+?(?:type="text/css"\s+?)?href="(?:https?:)?//.+?/\+\+plone\+\+production/'
          - '\<link\s+?rel="stylesheet"\s+?(?:type="text/css"\s+?)?href="(?:https?:)?//.+?/\+\+theme\+\+plone.+?'
          - 'href=".+?/\+\+plone\+\+.+?"'
```
