### ISSUE TITLE
[nuclei-template] mautic-crm-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1268]
**Template Details**

This template detects installations of [mautic/mautic](https://github.com/mautic/mautic).

```yaml
id: mautic-crm-detect

info:
  name: mautic crm detect
  author: cyllective
  severity: info
  description: Detects Mautic CRM
  tags: technology,mautic,crm
  references:
    - https://github.com/mautic/mautic

requests:
  - method: GET
    path:
      - "{{BaseURL}}/s/login"

    matcherscondition: or
    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<title>Mautic</title>'
          - '<div class="mautic-logo '

      - type: regex
        part: body
        internal: true
        condition: or
        regex:
          - 'var\s+?mautic(?:BasePath|BaseUrl|AjaxUrl|AjaxCsrf|AssetPrefix|Content|Env|Lang)\s+?='
          - 'Copyright \d{4} Mautic\. All Rights Reserved\.'
```
