### ISSUE TITLE
[nuclei-template] takeover

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#1280]
https://github.com/Elsfa7-110/testbug/blob/main/takeover.yaml

```yaml
id: careercast-takeover

info:
  name: Careercast Takeover Detection
  author: ELSFA7110
  severity: high
  tags: takeover

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "The provided host name is not valid for this server"
 ```
