### ISSUE TITLE
Open Api Root Django Misconfiguration

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1297]
** Open Api Root Django Misconfiguration**

```yaml

--- 
id: django-OpenApi-Root-Misconfiguration
info: 
  author: hackergautam
  name: "Django Open Api Root Misconfiguration"
  severity: low
  tags: panel
requests: 
  - 
    matchers: 
      - 
        condition: and
        part: body
        type: word
        words: 
          - "Django tried these URL patterns, in this order"
    method: GET
    path: 
      - "{{BaseURL}}/NON_EXISTING_PATH/"

```

<img width="1426" alt="Screenshot 2021-04-17 at 3 55 53 PM" src="https://user-images.githubusercontent.com/18241082/115109780-677b2800-9f95-11eb-8145-e0ac4f5ce77a.png">
