### ISSUE TITLE
[nuclei-template] grav-cms-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1315]
**Template Details**

Detects installations of [getgrav/grav](https://github.com/getgrav/grav).

```yaml
id: grav-cms-detect

info:
  name: grav cms detect
  author: cyllective
  severity: info
  description: Detects Grav CMS
  tags: technology,grav,cms
  references:
    - https://github.com/getgrav/grav

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/admin"

    matchers-condition: or
    matchers:
      - type: word
        part: header
        words:
          - 'Set-Cookie: grav-site-'

      - type: word
        part: body
        condition: or
        words:
          - '<meta name="generator" content="GravCMS" />'
          - '<title>Grav Admin Login | '
```
