### ISSUE TITLE
open-stack-dashboard-login

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1367]
**open-stack-dashboard-login portals**

```yaml

--- 
id: open-stack-dashboard-login
info: 
  author: hackergautam
  name: "OpenStack Dashboard"
  reference: ~
  severity: info
  tags: "panel, openstack"
requests: 
  - 
    matchers: 
      - 
        type: word
        words: 
          - "<title>Login - OpenStack Dashboard</title>"
      - 
        status: 
          - 200
        type: status
    matchers-condition: and
    method: GET
    path: 
      - "{{BaseURL}}/horizon/auth/login/?next=/horizon/"
    redirects: true

```

<img width="1515" alt="Screenshot 2021-04-25 at 2 45 08 PM" src="https://user-images.githubusercontent.com/18241082/115987956-070f6a80-a5d5-11eb-9478-abddf90754a0.png">
