### ISSUE TITLE
[nuclei-template] Detect Java RMI Protocol

### ISSUE THREAD

**Issue by f1tz** [projectdiscovery/nuclei-templates#1385]
**Template Details**

```yaml
id: java-rmi-detect

info:
  name: Detect Java RMI Protocol
  author: F1tz
  severity: info
  tags: network,rmi

network:
  - inputs:
    - data: "{{hex_decode('4a524d4900024b')}}"
    read-size: 1024
    host:
      - "{{Hostname}}"
    matchers:
      - type: regex
        part: raw
        regex:
          - "^N\\x00\\x0e(\\d{1,3}\\.){3}\\d{1,3}\\x00\\x00"
```
