### ISSUE TITLE
[nuclei-template] Detect Weblogic T3 Protocol

### ISSUE THREAD

**Issue by f1tz** [projectdiscovery/nuclei-templates#1386]
**Detect Weblogic T3 Protocol**

```yaml

id: weblogic-t3-detect

info:
  name: Detect Weblogic T3 Protocol
  author: F1tz
  severity: info
  description: Check T3 protocol status.
  tags: network,weblogic

network:
  - inputs:
    - data: "t3 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"
    read-size: 1024
    host:
      - "{{Hostname}}"
    matchers:
      - type: word
        words:
          - "HELO"
```
