### ISSUE TITLE
[nuclei-template] Detect Weblogic IIOP Protocol

### ISSUE THREAD

**Issue by f1tz** [projectdiscovery/nuclei-templates#1387]
**Detect Weblogic IIOP Protocol**

```yaml

id: weblogic-iiop-detect

info:
  name: Detect Weblogic IIOP Protocol
  author: F1tz
  severity: info
  description: Check IIOP protocol status.
  tags: network,weblogic

network:
  - inputs:
    - data: "{{hex_decode('47494f50010200030000001700000002000000000000000b4e616d6553657276696365')}}"
    read-size: 1024
    host:
      - "{{Hostname}}"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "GIOP"
      - type: word
        words:
          - "weblogic"
```
