### ISSUE TITLE
[nuclei-template] freshservice-takeover

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1396]
```yaml
id: freshservice-takeover
info:
  name: freshservice takeover detection
  author: philippedelteil
  description: This template is based on the freshdesk take over, they are similar but not the same. 
  severity: high
  tags: takeover
  reference: https://twitter.com/ja1sharma/status/1377239265348743175

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - There is no helpdesk here!
          - Maybe this is still fresh!
          - freshservice.com
        condition: and
```
