### ISSUE TITLE
[nuclei-template]  nginx version detect

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1397]
```yaml
id: nginx-version-detect
info:
  name: nginx version detect
  author: philippedelteil
  description: Some nginx servers have the version on the response header. Useful when you need to find specific CVEs on your targets.
  severity: info
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: and
    matchers:

      - type: regex
        part: header
        regex:
          - "nginx+"

      - type: status
        status:
          - 200

    extractors:
      - type: kval
        part: header
        kval:
          - Server
```
