### ISSUE TITLE
[nuclei-template] kubernetes-version

### ISSUE THREAD

**Issue by raesene** [projectdiscovery/nuclei-templates#1403]
**Template Details**

This template should match Kubernetes API servers. The `/version` endpoint is very commonly exposed unauthenticated on Kubernetes API servers, so it's quite a good test.

```yaml
id: kubernetes-version

info:
  name: Kubernetes Version Exposure
  author: raesene
  description: Searches for exposed Kubernetes API servers which return version information unauthenticated 
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/version"
    matchers:
      - type: word
        words:
          - "gitVersion"
          - "goVersion"
          - "platform"
        condition: and
```

Sample response from a curl request to that endpoint shown below. I'd *expect* the words above to match fairly well and not be too false positive prone, but it could be improved with more info. if that'd help.

```json
curl -k https://192.168.41.212:6443/version
{
  "major": "1",
  "minor": "20",
  "gitVersion": "v1.20.5",
  "gitCommit": "6b1d87acf3c8253c123756b9e61dac642678305f",
  "gitTreeState": "clean",
  "buildDate": "2021-03-18T01:02:01Z",
  "goVersion": "go1.15.8",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
