### ISSUE TITLE
Custom template using a file-based approach with path argumant

### ISSUE THREAD

**Issue by 0xSayDoo** [projectdiscovery/nuclei-templates#14300]
### description:

I would like to create a new custom template using a file-based approach. While reviewing the documentation, I noticed a section called "Path" but couldn't find an example of how it should be included in the template. I tried various methods, but the template validation consistently returned errors related to the key "path" mentioned in the documentation. I decided to examine the source code to gain a better understanding, but unfortunately, I didn't find anything related to the "path" there either.

### Question:
Additionally, I'm wondering if it's possible to read the file name using a file-based template. For instance, if I discover a DLL file, can I retrieve DLL files whose filenames contain the word "system," such as "system_old.dll" while ignoring any other files?

### References:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/120846592/14e5d0cb-9cd3-479d-891b-f1bf590cf708)

[file-based-templates](https://github.com/projectdiscovery/nuclei/blob/main/SYNTAX-REFERENCE.md#filerequest)

**Comment by dwisiswant0** [comment]
Note that the "path" in the file protocol doc is not a configuration field, it's a part definition (a runtime variable).

The file protocol does not have a path configuration field in the template YAML. Instead, you specify the files/directories to scan via the CLI when running nuclei (e.g., `-target /path/to/scan`).

The correct structure for a file template is:

```yaml
id: my-file-template

info:
  name: My File Scanner
  author: your-name
  severity: info
  tags: file

file:
  - extensions:
      - .dll # Filter by extension
      # OR use "all" to match all files

    # Optional fields:
    # denylist:
    #   - .exe
    # max-size: "5Mb"
    # archive: true
    # no-recursive: true

    matchers:
      - type: word
        words:
          - "some content"
    
    extractors:
      - type: regex
        regex:
          - "pattern"
```

Or you can use the path or matched runtime variables in matchers. Here's how to find DLL files containing "system" in the filename:

```yaml
id: dll-system-finder

info:
  name: Find DLLs with "system" in filename
  author: your-name
  severity: info
  tags: file,dll

file:
  - extensions:
      - .dll

    matchers:
      - type: regex
        part: path # match against the file path
        regex:
          - "(?i)system.*\\.dll$" # case-insensitive, matches system_old.dll, System32.dll, etc.
```

Or using a word matcher:

```yaml
file:
  - extensions:
      - .dll

    matchers:
      - type: dsl
        dsl:
          - 'contains(to_lower(path), "system")' # DSL expression to check filename
```

The [SYNTAX-REFERENCE.md](/SYNTAX-REFERENCE.md) documentation's "path" entry is describing what variables are available at runtime for matching, not what you put in the YAML configuration.

Hope that helps!
