### ISSUE TITLE
[nuclei-template] microsoft-exchange-control-panel

### ISSUE THREAD

**Issue by r3dg33k** [projectdiscovery/nuclei-templates#1439]
**Template Details**

```yaml                                                                                      
id: microsoft-exchange-control-panel

info:
  name: Microsoft Exchange Control Panel
  author: r3dg33k
  severity: low
  reference: N/A
  description: |
       Check for Exchange Server Microsoft Exchange Server Control Panel
requests:
  - method: GET
    path:
      - "{{BaseURL}}/owa/auth/logon.aspx?replaceCurrent=1&url={{BaseURL}}/ecp"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
```
