### ISSUE TITLE
[nuclei-template] Cloudflare Image Resizing SSRF

### ISSUE THREAD

**Issue by vavkamil** [projectdiscovery/nuclei-templates#1449]
**Template Details**

When the Cloudflare Image Resizing functionality is enabled and set to resize images from any origin, this "miss-configuration" could be used in exploit chains, for example, to exfiltrate authentication tokens in SSO, bypassing generic origin based`allow list` functions.

```yaml
id: cloudflare-image-ssrf
info:
  name: Cloudflare Image Resizing SSRF
  author: vavkamil
  severity: info
  description: Cloudflare Image Resizing defaults to restricting resizing to the same domain. This prevents third parties from resizing any image at any origin. However, you can enable this option if you check _Resize images from any origin_.
  reference: https://support.cloudflare.com/hc/en-us/articles/360028146432-Understanding-Cloudflare-Image-Resizing#12345684
  tags: cloudflare

requests:
  - raw:
      - |
        GET /cdn-cgi/image/width/https://{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
        Connection: close
        Accept: */*
        Accept-Language: en
        Accept-Encoding: gzip

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "http"
```
