### ISSUE TITLE
[nuclei-template] wazuh-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1466]
**Template Details**

This template detects installations of [wazuh/wazuh](https://github.com/wazuh/wazuh).

```yaml
id: wazuh-detect

info:
  name: wazuh detect
  author: cyllective
  severity: info
  description: Detects wazuh
  tags: technology,wazuh
  references:
    - https://github.com/wazuh/wazuh

requests:
  - method: GET
    path:
      - "{{BaseURL}}/app/login"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '&quot;id&quot;:&quot;wazuh&quot;'
          - '&quot;title&quot;:&quot;Wazuh&quot;'
          - '&quot;icon&quot;:&quot;plugins/wazuh/img/icon_blue.png&quot;'
          - '&quot;url&quot;:&quot;/app/wazuh&quot;'
```
