### ISSUE TITLE
Joomla related database files and source code

### ISSUE THREAD

**Issue by iampritam97** [projectdiscovery/nuclei-templates#1479]
**Template Details**
This template detects Joomla related database files and source code related to websites running Joomla and it also exposes the directory listing of websites

```yaml
id: joomla-files

info:
  name: Joomla database files and source code
  author: iampritam
  severity: low
  reference: https://www.exploit-db.com/ghdb/6377
  description: Searches for the pattern /libraries/joomla/database/ on passed URLs.
  tags: file,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/libraries/joomla/database/"

    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Index of /"

      - type: status
        status:
          - 200
```
