### ISSUE TITLE
[nuclei-template] octobercms-detect

### ISSUE THREAD

**Issue by cydave** [projectdiscovery/nuclei-templates#1487]
**Template Details**

Detects installations of [octobercms/october](https://github.com/octobercms/october).

```yaml
id: octobercms-detect

info:
  name: OctoberCMS detect
  author: cyllective
  severity: info
  description: Detects OctoberCMS
  tags: tech,octobercms
  references:
    - https://github.com/octobercms/october

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/backend/backend/auth/signin"
      - "{{BaseURL}}/modules/system/assets/js/framework.combined-min.js"

    matchers:
      - type: word
        part: body
        condition: or
        words:
          - '<meta name="generator" content="OctoberCMS">'
          - 'OctoberCMS'
          - 'October CMS'
```
