### ISSUE TITLE
[nuclei-template] LandrayOA-detect

### ISSUE THREAD

**Issue by bu1xuan2** [projectdiscovery/nuclei-templates#1495]
```yaml
id: landrayoa-detect

info:
  name: LandrayOA detect
  author: YanYun
  severity: info
  tags: tech,landrayoa

requests:
  - method: GET
    path:
      - '{{BaseURL}}/login.jsp'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
           - 'lui_login_input_username'
           - 'lui_login_input_password'
        condition: and
      - type: word
        words:
           - 'isopen='
        part: header

```
