### ISSUE TITLE
[nuclei-template] FanRuanOA2012-detect

### ISSUE THREAD

**Issue by bu1xuan2** [projectdiscovery/nuclei-templates#1509]
```yaml

id: FanRuanOA2012-detect

info:
  name: FanRuanOA2012-detect
  author: YanYun
  severity: info
  tags: oa,java

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    redirects: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'down.download?FM_SYS_ID'

```
