### ISSUE TITLE
[Bug] CVE-2016-10033.yaml

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#1525]
I believe there is a mistake in the 'regex' extractor:
```
 unsafe: true
    extractors:
      - type: regex
        name: username
        internal: true
        group: 1
        part: body
        regex:
          - 'Author:(?:[A-Za-z0-9 -\_="]+)?<span(?:[A-Za-z0-9 -\_="]+)?>([A-Za-z0-9]+)<\/span>'
          - 'ocation: https:\/\/[a-z0-9.]+\/author\/([a-z]+)\/'
```

The first `regex` makes sense, as it would be in the `body`, however, the `Location` I believe would be in the `header` and not in the `body`.
