### ISSUE TITLE
CVE-2017-9248

### ISSUE THREAD

**Issue by ZhenwarX** [projectdiscovery/nuclei-templates#1527]
```yaml
id: CVE-2017-9248

info:
  name: Telerik UI for ASP.NET AJAX 2012.3.1308 < 2017.1.118 - Encryption Keys Disclosure
  author: zhenwarx
  description: Telerik file uploader to RCE on windows servers
  severity: critical
  tags: rce
  reference: |
    - https://www.exploit-db.com/exploits/43873
    - https://github.com/ZhenwarX/Telerik-CVE-2017-9248-PoC

requests:
  - method: GET
    path:
      - '{{BaseURL}}/DesktopModules/Admin/RadEditorProvider/telerik.web.ui.dialoghandler.aspx'
      - '{{BaseURL}}/providers/htmleditorproviders/telerik/telerik.web.ui.dialoghandler.aspx'
      - '{{BaseURL}}/desktopmodules/telerikwebui/radeditorprovider/telerik.web.ui.dialoghandler.aspx'
      - '{{BaseURL}}/desktopmodules/dnnwerk.radeditorprovider/dialoghandler.aspx'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Loading the dialog..."
        part: body

      - type: status
        status:
          - 200
```
