### ISSUE TITLE
[nuclei-template] Insecure XP Webcam

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1534]
**Template Details**
This template deals with the detection of exposed XP Webcams in servers by attempting to query /mobile.html with the words webcamXP in the response.
```yaml
id: xp-webcam

info:
  name: XP Webcam Viewer Page
  author: aashiq
  severity: medium
  description: Searches for exposed webcams by querying the /mobile.html endpoint and existance of webcamXP in the body
  tags: webcam

requests:
  - method: GET
    path:
      - "{{BaseURL}}/mobile.html"
    matchers:
      - type: word
        words:
          - "webcamXP"
        part: body
```
