### ISSUE TITLE
[nuclei-template]  securenvoy-admin-panel

### ISSUE THREAD

**Issue by 0xrod** [projectdiscovery/nuclei-templates#1535]
**Template Details**

admin panel from securenvoy ( securenvoy [dot] com/)
 
```yaml
id: securenvoy-admin-panel

info:
  name: Securenvoy painel detector
  author: 0xrod
  severity: info
  tags: panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/secadmin/"
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'secadmin'
        part: body
      - type: status
        status:
          - 200
```
