### ISSUE TITLE
[nuclei-template] natshell debug.php RCE

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#1548]
**Template Details**
https://github.com/Elsfa7-110/testbug/blob/main/exposed-debug-php.yaml

```yaml
id: rce-debug-php

info:
  name: natshell debug.php RCE
  author: ELSFA7110
  severity: critical
  reference: https://twitter.com/sec715/status/1397924997457317897
  tags: rce,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Command"
        part: body

      - type: status
        status:
          - 200

```
