### ISSUE TITLE
[nuclei-template] Wordpress DB Repair Page Exposed

### ISSUE THREAD

**Issue by aldo-moreno-leon** [projectdiscovery/nuclei-templates#1554]
**Template Details**
The database repair page is a wordpress function to check and optimize the website database. If this feature is enabled in the wp-config.php file, it may be accessible by unauthorized users. 

```yaml

id: wordpress-db-repair-exposed

info:
  name: Wordpress DB Repair Exposed
  author: _C0wb0y_
  severity: medium
  description: Discover repair page in Wordpress sites
  tags: wordpress,config

requests:
  - method: GET
    path: 
      - "{{BaseURL}}/wp-admin/maint/repair.php"

    file:
      - extensions:
          - php

    matchers:
      - type: word
        words:
          - "repair.php?repair=1"
```
