### ISSUE TITLE
[nuclei-template] Exposed VSCode Folders

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1557]
**Template Details**
Organizations sometimes forget to remove hidden code folders such as the .vscode folders from their servers/ web applications. 

This template deals with the detection of exposed VSCode Folders on servers by attempting to query /.vscode with the words "index of: in the response body.

```yaml
id: exposed-vs-code-folders

info:
  name: Exposed VSCode Folders
  author: aashiq
  severity: medium
  description: Searches for exposed Visual Studio Code Directories by querying the /.vscode endpoint and existence of "index of" in the body
  tags: vscode

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.vscode"
    matchers:
      - type: word
        words:
          - "index of"
        part: body
```
