### ISSUE TITLE
[nuclei-template] Servicedesk Login Panel

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1558]
**Template Details**
This template attempts to detect ServiceDesk login portals via attempting to query the customer login endpoint with standard headers.

```yaml
id: servicedesk-login-panel

info:
  name: Servicedesk Login Panel Detector
  author: aashiq
  severity: info
  description: Searches for ServiceDesk login panels by trying to query the "servicedesk/customer/user/login" endpoint
  tags: servicedesk

requests:
  - method: GET
    path:
      - "{{BaseURL}}/servicedesk/customer/user/login"
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
    matchers:
      - type: status
        status:
          - 200
```
