### ISSUE TITLE
[nuclei-template] EMS Login Detection

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1559]
**Template Details**

```yaml

id: EMS-login-Detection

info:
  name: EMS Login page detection
  author: __Fazal
  severity: info
  tags: panel

requests:
  - method: GET
    path:
      - '{{BaseURL}}/EMSWebClient/Login.aspx'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
```
