### ISSUE TITLE
Clave-login-panel

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1573]
**Template Details**

```yaml

id: Clave-login-panel

info:
  name: Clave login page detection
  author: __Fazal
  severity: info
  tags: panel, Clave

requests:
  - method: GET
    path:
      - '{{BaseURL}}/admin.php'
      - '{{BaseURL}}/admin_login.php'
      - '{{BaseURL}}/admin/admin_login.php'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Clave"
```
