### ISSUE TITLE
Lancom-1970va-business-vpn-router-panel

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1574]
**Template Details**

```yaml

id: Lancom-1970va-business-vpn-router-panel

info:
  name: Lancom-1970a-business-vpn-router-login-panel-detection
  author: __Fazal
  severity: info
  tags: panel, vpn, lancom

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
      
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "LANCOM 1790VA-4G"
          - "Name"
          - "Password"
```
