### ISSUE TITLE
Zenario-login-panel

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1578]
**Template Details**

```yaml

id: Zenario-login-panel

info:
  name: Zenario login page detection
  author: __Fazal
  severity: info
  tags: panel, zenario

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
      - '{{BaseURL}}/zenario/zenario/admin/welcome.php'
      - '{{BaseURL}}/zero/zenario/admin/welcome.php'
      - '{{BaseURL}}/zenario/admin/welcome.php'
           
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Welcome to Zenario"
```
