### ISSUE TITLE
Citrix metaframework presentation server login page detection

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1579]
**Template Details**

```yaml

id: Citrix-Metaframework-Login-login-panel

info:
  name: Citrix metaframework presentation server login page detection
  author: __Fazal
  severity: info
  tags: panel

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Citrix/MetaFrame/default/default.aspx'
                 
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Login Form"
```
