### ISSUE TITLE
[nuclei-template] Epson WF Series Printer Detection

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1609]
**Template Details**
This template is aimed at detecting EPSON WF series printers accessible via the server by querying the PRINTINFO endpoint
```yaml
id: epson-wf-series-detection

info:
  name: Epson WF Series Detection
  author: aashiq
  severity: info
  description: Searches for Epson WF series printers on the domain
  tags: printer

requests:
  - method: GET
    path:
      - "{{BaseURL}}/PRESENTATION/HTML/TOP/PRTINFO.HTML"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "EPSON"
```
