### ISSUE TITLE
[nuclei-template] LuCi Login Detector

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1610]
**Template Details**
This template is aimed at detecting LuCi login pages by querying the cgi-bin/luci endpoint
```yaml
id: luci-login-detection

info:
  name: LuCi Login Detector
  author: aashiq
  severity: info
  description: Searches for LuCi Login pages by attempting to query the cgi-bin endpoint
  tags: login

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/luci"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "Authorization Required"
```
