### ISSUE TITLE
[nuclei-template] Mailchimp 4 Wordpress Log Exposure Detection

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1611]
**Template Details**
This template is aimed at searching for Mailchimp log exposure by attempting to query the debug log endpoint on wp-content
```yaml
id: mailchimp-4-wordpress-log-exposure

info:
  name: Mailchimp 4 Debug Log Detector
  author: aashiq
  severity: medium
  description: Searches for Mailchimp log exposure by attempting to query the debug log endpoint on wp-content
  tags: logs

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/uploads/mc4wp-debug.log"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "Mailchimp"
```
