### ISSUE TITLE
[nuclei-template] Private Key Exposure Via Helper Detector

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1612]
**Template Details**
This template is aimed at searching for private key exposure by attempting to query the helper endpoint on node_modules
```yaml
id: private-key-exposure-via-helper

info:
  name: Private key exposure via helper detector
  author: aashiq
  severity: high
  description: Searches for private key exposure by attempting to query the helper endpoint on node_modules
  tags: key_exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/node_modules/mqtt/test/helpers"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "private-key.pem"
```
