### ISSUE TITLE
[nuclei-template] WordPress Popup Exposure Detector

### ISSUE THREAD

**Issue by AashiqRamachandran** [projectdiscovery/nuclei-templates#1613]
**Template Details**
This template is aimed at searching for sensitive directories present in the wordpress-popup plugin.
```yaml
id: wordpress-popup-exposure

info:
  name: WordPress Popup Exposure Detector
  author: aashiq
  severity: medium
  description: Searches for sensitive directories present in the wordpress-popup plugin.
  tags: directory, wordpress

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/wordpress-popup/views/admin"
    matchers:
      - type: status
        status:
          - 200
```
