### ISSUE TITLE
[nuclei-template] CNVD-2021-30167

### ISSUE THREAD

**Issue by 1337plus** [projectdiscovery/nuclei-templates#1619]
**Template Details**

```yaml

id: CNVD-2021-30167

info:
  name: YONYOU NC RCE(CNVD-2021-30167)
  author: xm17
  severity: critical
  reference: https://www.cnvd.org.cn/webinfo/show/6491
  tags: YONYOU,rce

requests:
  - method: GET
    path:
      - "{{BaseURL}}/servlet/~ic/bsh.servlet.BshServlet"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'BeanShell'
          - 'print("hello!")'
        part: body
        condition: and

      - type: status
        status:
          - 200

```
