### ISSUE TITLE
[false-positive] wordpress-db-repair

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1635]
I  don't know if the solution is adding a rule for the 403 http code or grepping the error text. 

**Nuclei version**

```
2.3.7
```

**Nuclei template version**

```
8.8.3
```

**Template ID**

 wordpress-db-repair 

**Commands to Reproduce**

```
nuclei -debug -t nuclei-templates/vulnerabilities/wordpress/wordpress-db-repair.yaml -u https://wp.blog.ui.com

```

**Comment by geeknik** [comment]
I'm curious why nuclei is ignoring the second matcher in the template:
```
matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>WordPress"

      - type: word
        words:
          - "define('WP_ALLOW_REPAIR', true);"
```
