### ISSUE TITLE
Exposed SVN Directory too lax resulting in false-positives.

### ISSUE THREAD

**Issue by EdOverflow** [projectdiscovery/nuclei-templates#166]
The conditions in the Exposed SVN Directory template (see below) are too lax resulting in many false-positives. Maybe we should consider adding additional conditions to reduce the number of false-positives.

```
matchers:
    - type: word
    words:
        - "dir"
    - type: status
    status:
        - 200
```
