### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1707]
**Template Details**

```yaml

id: Odoo-Database

info:
  name: Odoo-Database-Manager
  author: __Fazal,R3dg33k
  severity: High
  tags: panel, odoo, manager

requests:
  - method: GET
    path:
      - '{{BaseURL}}/web/database/manager'
                 
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'Create Database'
```
