### ISSUE TITLE
DSL syntax for headers/values that are not present

### ISSUE THREAD

**Issue by emilva** [projectdiscovery/nuclei-templates#172]
Hi all,

I am trying to write a check that checks if the following:
1) `Access-Control-Allow-Origin` is `*`
2) `Cache-Control` does NOT contain `no-store`.

In the second case the header `Cache-Control` might be set or not, and it might contain other values than `no-store`. 

My matcher:
``` 
    matchers:
      - type: dsl
        name: "[ACAO * and no cache-control header]"
        dsl:
          - "contains(access_control_allow_origin, '*') && !contains(tolower(all_headers), 'no-store')"
``` 

Does `!` work as `NOT` in the dsl syntax? How would you write it?

Test cases:

Correct headers - should not trigger a finding
```
Access-Control-Allow-Origin: *
Cache-Control: no-store
``` 

Missing `Cache-Control`, should trigger a finding
```
Access-Control-Allow-Origin: *
```
 
`Cache-Control` set but not containing `no-store`, should trigger a finding
```
Access-Control-Allow-Origin: *
Cache-Control: private
```

Missing ACAO, should not trigger a finding
```
Cache-Control: private, no-cache, no-store, must-revalidate
``` 

With my current DSL, I get positive matches on all my test cases except the last one. Any Idea why?

Cheers,

emil

**Comment by dwisiswant0** [comment]
Try this _(using RegEx)_:

```yaml
    matchers:
      - type: regex
        name: '[ACAO * and no cache-control header]'
        regex:
          - '(?mi)^((?:access-control-allow-origin\s*?:)(?:.*\*))'
          - '(?mi)^((?:cache-control\s*?:)(?!.*no-store))'
        condition: and
        part: header
```

**Comment by emilva** [comment]
@dwisiswant0 thanks for the answer! I was hoping to avoid regex, since I find them very hard to read and write myself :)

When I am testing your regex I am getting this error message:
``` could not compile regex: (?mi)^((?:cache-control\s*?:)(?!.*no-store))```
Can you spot the error? The only diff I see from the other expression is the `!` before `no-store`

**Comment by Mzack9999** [comment]
Hi @emilva - The syntax that you used is absolutely correct. There was an issue at runtime that caused the `all_headers` to be empty under certain conditions. This should be fixed in https://github.com/projectdiscovery/nuclei/pull/132

**Comment by bauthard** [comment]
I can confirm it works now @emilva 

```bash
>  chaos -d redacted.com -bbq -http-url | nuclei -t cors-test.yaml -silent

[basic-cors-test:[ACAO * and no cache-control header]] [http] https://assets.redacted.com
```

with your matcher:-  

```
    matchers:
      - type: dsl
        name: "[ACAO * and no cache-control header]"
        dsl:
          - "contains(access_control_allow_origin, '*') && !contains(tolower(all_headers), 'no-store')"
```
