### ISSUE TITLE
[nuclei-template] mail-EXPN-support-detect

### ISSUE THREAD

**Issue by r3dg33k** [projectdiscovery/nuclei-templates#1737]
**Template Details**

```yaml

id: mail-EXPN-support-detect

info:
  name: Mail Server EXPN Detect
  author: r3dg33k
  severity: info
  tags: mail,EXPN,network

network:
  - inputs:
      - data: "65686c6f20636865636b746c730a"
        type: hex
        read-size: 2048

    host:
      - "{{Hostname}}"
      - "{{Hostname}}:25"

    matchers:
      - type: word
        name: EXPN Supported (User Enumeration)
        words:
          - "250-EXPN"
```
