### ISSUE TITLE
[nuclei-template] mail-STARTTLS-support-detect

### ISSUE THREAD

**Issue by r3dg33k** [projectdiscovery/nuclei-templates#1738]
**Template Details**

```yaml

id: mail-STARTTLS-support-detect

info:
  name: Mail Server STARTTLS Detect
  author: r3dg33k
  severity: info
  tags: mail,STARTTLS,network

network:
  - inputs:
      - data: "65686c6f20636865636b746c730a"
        type: hex
        read-size: 2048

    host:
      - "{{Hostname}}"
      - "{{Hostname}}:25"

    matchers:
      - type: word
        name: STARTTLS supported
        words:
          - "250-STARTTLS"
```
