### ISSUE TITLE
[nuclei-template] calendarix-Login-Detect

### ISSUE THREAD

**Issue by r3dg33k** [projectdiscovery/nuclei-templates#1746]
**Template Details**

```yaml

id: calendarix-Login-Detect

info:
  name: Calendarix login detect
  author: r3dg33k
  severity: Info
  tags: panel, calendarix

requests:
  - method: GET
    path:
      - '{{BaseURL}}/calendarix/admin/cal_login.php'
      - '{{BaseURL}}/calendar/admin/cal_login.php'
                 
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'Calendarix Admin Login'
```
