### ISSUE TITLE
[Bug] showdoc-file-upload-rce.yaml

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#1749]
Hi,

The following extractor is used:
```
extractors:
      - type: regex
        name: path
        group: 1
        internal: true
        part: body
        regex:
          - '/Uploads\\(.*?)"\,"success"'
```

What is the purpose of the `\,` it looks like a mistake or something else was intended to be placed there?
