### ISSUE TITLE
[nuclei-template] Livezilla-Login-Detect

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1754]
**Template Details**

```yaml

id: Livezilla-Login-Detect

info:
  name: Livezilla login detect
  author: __Fazal
  severity: Info
  tags: panel, livezilla

requests:
  - method: GET
    path:
      - '{{BaseURL}}/mobile/index.php'
                 
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'LiveZilla'
```
