### ISSUE TITLE
[nuclei-template] Sitecore Login Panel

### ISSUE THREAD

**Issue by bAuh0lz** [projectdiscovery/nuclei-templates#1761]
**Template Details**

```yaml

id: sitecore-login-panel

info:
  name: Sitecore Login Panel
  author: b4uh0lz
  severity: info
  tags: panel

requests:
  - method: GET
    redirects: true
    path:
      - "{{BaseURL}}/sitecore/admin"
      - "{{BaseURL}}/sitecore/admin/login.aspx"
      - "{{BaseURL}}/sitecore/login"
      - "{{BaseURL}}/sitecore/login.aspx"
      - "{{BaseURL}}/sitecore/login/default.aspx"
    matchers:
      - type: word
        words:
          - "Sitecore Login"
          - "LoginTextBox"
          - "PasswordTextBox"
        condition: or
        part: body
```
