### ISSUE TITLE
[nuclei-template] Sprintful-Domain-Takeover

### ISSUE THREAD

**Issue by mhdsamx** [projectdiscovery/nuclei-templates#1768]
**Template Details**

```yaml
id: sprintful-takeover

info:
  name: Sprintful Takeover
  author: Mhdsamx
  severity: info
  tags: domain, takeover

requests:
  - method: GET
    path:
      - '{{BaseURL}}'
                   
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'The user account associated with this calendar has been deactivated. Please contact the owner of this calendar directly in order to book a meeting.'
        condition: and

      - type: word
        words:
          - "Sprintful"
```
