### ISSUE TITLE
[nuclei-template] Flywheel Subdomain Takeover

### ISSUE THREAD

**Issue by smaranchand** [projectdiscovery/nuclei-templates#1770]
**Template Details**
Flywheel PaaS is vulnerable to subdomain takeover. Since there aren't any supporting writeups/POC's available on the internet I did a writeup as well as made a nuclei template.
https://smaranchand.com.np/2021/06/flywheel-subdomain-takeover

```yaml

id: Flywheel-Takeover

info:
  name: Flywheel Subdomain Takeover
  author: smaranchand
  severity: high
  tags: takeover
  reference: https://smaranchand.com.np/2021/06/flywheel-subdomain-takeover

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: word
        words:
          - "We're sorry, you've landed on a page that is hosted by Flywheel"
          - "<h1>Oops! That's not the site<br>you're looking&nbsp;for.</h1>"
        condition: and
```
