### ISSUE TITLE
addeventlistener-message

### ISSUE THREAD

**Issue by yavolo** [projectdiscovery/nuclei-templates#1781]
**Check for message eventlisteners to manually audit input handling**

```yaml
id: addeventlistener-message

info:
  name: AddEventlistener('message') in body
  author: yavolo
  severity: info
  tags: xss
  reference: https://portswigger.net/web-security/dom-based/controlling-the-web-message-source

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
    matchers:
      - type: regex
        regex:
          - addEventListener\("message
          - addEventListener\('message
          - addeventlistener\("message
          - addeventlistener\('message
        part: body
```
