### ISSUE TITLE
[nuclei-template] Zmanda Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1792]
**Template Details**
Template for default credentials located on Zmanda application.
Push to: /default-logins/zmanda 

```yaml
id: zmanda-default-credentials

info:
  name: Zmanda Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of admin:admin on Zmanda application.
  tags: zmanda,default-login

requests:
  - method: POST
    path:
      - '{{BaseURL}}/ZMC_Admin_Login'
    headers:
      Content-Type: application/x-www-form-urlencoded
      Cookie: zmc_cookies_enabled=true

    body: login=AEE&last_page=&username=admin&password=admin&submit=Login&JS_SWITCH=JS_ON

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ZMC - Backup Set Management"

      - type: status
        status:
          - 200
```
