### ISSUE TITLE
[nuclei-template] VisionHub Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1793]
**Template Details**
Template for default credentials located on VisionHub application.
Push to: /default-logins/visionhub 
```yaml
id: visionhub-default-credentials

info:
  name: VisionHub Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of admin:admin on VisionHub application.
  tags: visionhub,default-login

requests:
  - method: POST
    path:
      - '{{BaseURL}}/VisionHubWebApi/api/Login'
    headers:
      Authorization: Basic YWRtaW46YWRtaW4=

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Set-Cookie: admin"
        part: header
      - type: status
        status:
          - 200
```
