### ISSUE TITLE
Workflow Logic

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei-templates#180]
Is it possible to accept values other than `bool` under `logic` conditions? Since there has been a `tech-detect` template that fingerprinting the framework.

### Use cases

```yaml
variables:
  tech-detect: technologies/tech-detect.yaml
  php-fusion-cve: cve/cve-1-1.yaml

logic:
  |
    if tech-detect == "php-fusion" {
        php-fusion-cve
    }
```

Regards.
