### ISSUE TITLE
[nuclei-template] CodeMeter WebAdmin Panel

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1815]
**Template Details**

```yaml
id: codemeter-webadmin-panel

info:
  name: CodeMeter WebAdmin Panel
  author: Techryptic (@Tech)
  severity: high
  description: Panel on CodeMeter WebAdmin application.
  tags: codemeter,webadmin,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "WebAdmin | Dashboard"

      - type: word
        words:
          - "Set-Cookie: CmWebAdminSession"
        part: header

      - type: status
        status:
          - 200

```
