### ISSUE TITLE
[nuclei-template] Dell EMC ECOM Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1816]
**Template Details**

```yaml
id: dell-emc-ecom-default-credentials

info:
  name: Dell EMC ECOM Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of admin:#1Password on Dell EMC ECOM application.
  reference: https://www.dell.com/support/kbdoc/en-za/000171270/vipr-controller-operation-denied-by-clariion-array-you-are-not-privileged-to-perform-the-requested-operation
  tags: dell,emc,ecom,default-login

requests:
  - method: GET
    path:
      - '{{BaseURL}}/'
    headers:
      Authorization: Basic YWRtaW46IzFQYXNzd29yZA==

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Set-Cookie: ECOMSecurity"
        part: header

      - type: word
        words:
          - "Welcome to ECOM"

      - type: status
        status:
          - 200
```
