### ISSUE TITLE
[nuclei-template] HortonWorks SmartSense Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1817]
**Template Details**

```yaml
id: hortonworks-smartsense-default-credentials

info:
  name: HortonWorks SmartSense Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of admin:admin on HortonWorks SmartSense application.
  reference: https://docs.cloudera.com/HDPDocuments/SS1/SmartSense-1.2.2/bk_smartsense_admin/content/manual_server_login.html
  tags: hortonworks,smartsense,default-login

requests:
  - method: GET
    path:
      - '{{BaseURL}}/apt/v1/context'
    headers:
      Authorization: Basic YWRtaW46YWRtaW4=

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Set-Cookie: SUPPORTSESSIONID"
        part: header

      - type: word
        words:
          - "smartsenseId"

      - type: status
        status:
          - 200
```
