### ISSUE TITLE
[nuclei-template] Palo Alto Networks PAN-OS Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1818]
**Template Details**

```yaml
id: palo-alto-pan-os-default-credentials

info:
  name: Palo Alto Networks PAN-OS Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of admin:admin on Palo Alto Networks PAN-OS application.
  reference: https://docs.paloaltonetworks.com/pan-os/8-1/pan-os-admin/getting-started/integrate-the-firewall-into-your-management-network/perform-initial-configuration.html#:~:text=By%20default%2C%20the%20firewall%20has,with%20other%20firewall%20configuration%20tasks.
  tags: paloalto,panos,default-login

requests:
  - method: POST
    path:
      - '{{BaseURL}}/php/login.php'

    body: user=admin&passwd=admin&challengePwd=&ok=Login

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Set-Cookie: PHPSESSID"
        part: header

      - type: word
        words:
          - "Warning: Your device is still configured with the default admin"

      - type: status
        status:
          - 200

```
