### ISSUE TITLE
[nuclei-template] IDEMIA BIOMetrics Default Credentials

### ISSUE THREAD

**Issue by Techryptic** [projectdiscovery/nuclei-templates#1819]
**Template Details**

```yaml
id: idemia-biometrics-default-credentials

info:
  name: IDEMIA BIOMetrics Default Credentials
  author: Techryptic (@Tech)
  severity: high
  description: Default Credentials of password=12345 on IDEMIA BIOMetrics application.
  reference: https://www.google.com/search?q=idemia+password%3D+"12345"
  tags: idemia,biometrics,default-login

requests:
  - method: POST
    path:
      - '{{BaseURL}}/cgi-bin/login.cgi'

    body: password=12345

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "session_id="
          - "resource"
        condition: and

      - type: word
        words:
          - "Invalid Password"
        part: body
        negative: true

      - type: status
        status:
          - 200

```
