### ISSUE TITLE
[nuclei-template] Drupal install page

### ISSUE THREAD

**Issue by linfatall** [projectdiscovery/nuclei-templates#1832]
**Template Details**

```yaml

id: Drupal-install-page

info:
  name: Drupal install page
  author: __Fazal
  severity: High
  tags: panel, Drupal, CMS

requests:
  - method: GET
    path:
      - 'http://{{BaseURL}}/core/install.php'
      - 'https://{{BaseURL}}/core/install.php'
                 
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'Choose profile'
          - 'Verify requirements'
          - 'Set up database'
          - 'Install site'
          - 'Configure site'

```
