### ISSUE TITLE
[nuclei-template] rsync-detect

### ISSUE THREAD

**Issue by vsh00t** [projectdiscovery/nuclei-templates#1833]
**Template Details**

```yaml
id: rsync-detect

info:
  name: Rsync Detection
  author: vsh00t
  severity: low
  tags: network,rsync
  description: Detect rsync.
  reference: |
     - https://www.rapid7.com/blog/post/2018/12/21/rsunk-your-battleship-an-ocean-of-data-exposed-through-rsync/

network:
  - host:
      - "{{Hostname}}"
      - "{{Hostname}}:873"
    matchers:
      - type: word
        words:
          - "RSYNCD"
```
