### ISSUE TITLE
[nuclei-template] Wordpress User Enumeration

### ISSUE THREAD

**Issue by r3dg33k** [projectdiscovery/nuclei-templates#1840]
**Template Details**
reference to test: rtl-theme.com

```yaml

id: wordpress-user-enum

info:
  name: Wordpress User Enumeration
  author: r3dg33k
  severity: info
  tags: wordpress

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?author=1"
      - "{{BaseURL}}/?author=2"
      - "{{BaseURL}}/?author=3"
      - "{{BaseURL}}/?author=4"
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '(?i)Location: http(s|):\/\/[\w\.\-]+\/author\/\w+'
        part: header
      - type: status
        status:
          - 301
    extractors:
      - type: regex
        part: header
        regex:
          - 'author\/\w+'

```
