### ISSUE TITLE
dotenv file environment disclosure 

### ISSUE THREAD

**Issue by emadshanab** [projectdiscovery/nuclei-templates#1877]
```yaml
id: dotenv-file-environment-disclosure

info:
  name: Dotenv file environment disclosure
  author: emadshanab
  severity: high
    description: dotenv file environment disclosure leading to exposing symfony APP_SECRET and MAILER_DSN password.
     reference: https://www.acunetix.com/vulnerabilities/web/dotenv-env-file/
  tags: exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/.env"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "APP_SECRET"

      - type: status
        status:
          - 200

      - type: word
        words:
          - "APP_SECRET"
          - "MAILER_DSN"
          -"symfony"
          -"DATABASE_URL"
        condition: or
        part: header
```
