### ISSUE TITLE
[nuclei-template] Exposed .gitignore

### ISSUE THREAD

**Issue by thezakman** [projectdiscovery/nuclei-templates#1898]
**Exposed .gitignore - sensitive resource**

```yaml
id: exposed-gitignore

info:
  name: Exposed .gitignore
  author: TheZakMan
  severity: info
  description: Expose sensitive resources 
  tags: config,git,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.gitignore"
      - "{{BaseURL}}/assets/.gitignore"
      - "{{BaseURL}}/includes/.gitignore"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: dsl
        dsl:
          - '!contains(body_2, "<html")'
          - '!contains(body_2, "<HTML")'
        condition: and
```
