### ISSUE TITLE
[nuclei-template] Extract Disallow URLs from robots.txt

### ISSUE THREAD

**Issue by thezakman** [projectdiscovery/nuclei-templates#1903]
**Extract Disallow URLs From robots.txt**

```yaml

id: robots-disallow

info:
  name: Extract Disallow URLs
  author: TheZakMan
  severity: info
  description: Expose sensitive resources 
  tags: config,git,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/robots.txt"
      
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Disallow:"

      - type: word
        words:
          - text/plain
        part: header

      - type: dsl
        dsl:
          - "len(body)>=10 && status_code==200"

    extractors:
      - type: regex
        regex:
          - 'Disallow:.*'
```
