### ISSUE TITLE
[nuclei-template]  CVE-2019-12616

### ISSUE THREAD

**Issue by Mohammedsaneem** [projectdiscovery/nuclei-templates#1904]
**Template Details**
This is based on CSRF due to CVE-2019-12616 
An issue was discovered in phpMyAdmin before 4.9.0. A vulnerability was found that allows an attacker to trigger a CSRF attack against a phpMyAdmin user. The attacker can trick the user, for instance through a broken <img> tag pointing at the victim's phpMyAdmin database, and the attacker can potentially deliver a payload (such as a specific INSERT or DELETE statement) to the victim.

```yaml

id: CVE-2019-12616

info:
  name: Phpmyadmin CSRF
  author: Mohammed Saneem
  severity: medium
  References: https://www.exploit-db.com/exploits/46982,https://nvd.nist.gov/vuln/detail/CVE-2019-12616

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/"

    matchers:
      - type: word
        words:
          - "4.6.6deb4+deb9u2"

      - type: status
        status:
          - 200

```
