### ISSUE TITLE
keycloak-openid-config

### ISSUE THREAD

**Issue by rodnt** [projectdiscovery/nuclei-templates#1989]
**Template Details**
Oauth2 and Openid configs from keycloak assuming that master realm is open.

```yaml

id: keycloak-openid-config

info:
  name: Keycloak openid-config 
  author: rodnt 
  severity: info 
  reference: https://issues.jboss.org/browse/KEYCLOAK-571 
  tags: keycloak, keycloak config

requests:
  - raw:
      - |
        GET /auth/realms/master/.well-known/openid-configuration HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Content-Type: application/x-www-form-urlencoded

        

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'issuer'
          - 'authorization_endpoint'
          - 'token_endpoint'
          - 'userinfo_endpoint'
          - 'end_session_endpoint'
          - 'jwks_uri'
          - 'grant_types_supported'
```
