### ISSUE TITLE
how fix this 

### ISSUE THREAD

**Issue by Kalimon12** [projectdiscovery/nuclei-templates#2126]
```yaml
id: open-redirect

info:
  name: Open URL redirect detection
  author: kali
  severity: high
  description: fuzzing open-redirect
  tags: redirect

requests:
  - payloads:
      payload: helpers/payloads/payloads.txt

    attack: sniper

  - method: GET

    path:
      - '{{BaseURL}}§payload§'
      - '{{BaseURL}}/?next=§payload§'
      - '{{BaseURL}}/?url=§payload§'
      - '{{BaseURL}}/?target=§payload§'
      - '{{BaseURL}}/?rurl=§payload§'
      - '{{BaseURL}}/?dest=§payload§'
      - '{{BaseURL}}/?destination=§payload§'
      - '{{BaseURL}}/?redir=§payload§'
      - '{{BaseURL}}/?redirect_uri=§payload§'
      - '{{BaseURL}}/?redirect_url=§payload§'
      - '{{BaseURL}}/?redirect=§payload§'
      - '{{BaseURL}}/redirect/§payload§'
      - '{{BaseURL}}/cgi-bin/redirect.cgi?§payload§'
      - '{{BaseURL}}/out/§payload§'
      - '{{BaseURL}}/out?§payload§'
      - '{{BaseURL}}/?view=§payload§'
      - '{{BaseURL}}/login?to=§payload§'
      - '{{BaseURL}}/?image_url=§payload§'
      - '{{BaseURL}}/?go=§payload§'
      - '{{BaseURL}}/?return=§payload§'
      - '{{BaseURL}}/?returnTo=§payload§'
      - '{{BaseURL}}/?return_to=§payload§'
      - '{{BaseURL}}/?checkout_url=§payload§'
      - '{{BaseURL}}/?continue=§payload§'
      - '{{BaseURL}}/?return_path=§payload§'

    matchers-condition: or
    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$'
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)bing\.com.*$'
        part: header

      - type: status
        status:
          - 302
          - 301
```
