### ISSUE TITLE
[nuclei-template] exacqVision default password

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#2139]
**Template Details**
exacqVision default password
https://raw.githubusercontent.com/Elsfa7-110/graphql-elsfa7-nuclei-template/main/exacqVision.yaml

reference : https://cdn.exacq.com/auto/manspec/files_2/exacqvision_user_manuals/web_service/exacqVision_Web_Service_Configuration_User_Manual_(version%208.8).pdf

```yaml

id: exacqVision-default-password

info:
  name: exacqVision Default Password
  author: ELSFA7110
  severity: high
  tags: exacqVision,default-login

requests:
  - raw:
      - |
        POST /service.web HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Connection: close

        action=login&u=admin&p=admin256

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
        condition: and

```
