### ISSUE TITLE
[nuclei-template] CKEditor 3 - SSRF

### ISSUE THREAD

**Issue by bernardofsr** [projectdiscovery/nuclei-templates#2147]
**Template Details**

```yaml
id: CKEditor 3 - SSRF

info:
  name: CKEditor 3 - Server-Side Request Forgery (SSRF)
  author: Bernardo Rodrigues @bernardofsr
  severity: medium
  description: |
    - This vulnerability allows an attacker to induce the server-side application to make HTTP requests to an arbitrary domain of the attacker’s choosing. It's similar to the exploitation of XMLRPC on Wordpress, that allows ping another websites.
  reference: |
    - https://www.exploit-db.com/exploits/50021
  tags: ssrf, ckeditor

requests:
  - method: GET
    path:
      - '{{BaseURL}}/editor/filemanager/connectors/uploadtest.html'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "Upload a new file:"
          - "Custom Uploader URL:"
        part: body
        condition: and
```
