### ISSUE TITLE
[nuclei-template] cerebro page Unauth

### ISSUE THREAD

**Issue by bigzeroo** [projectdiscovery/nuclei-templates#2254]
```yaml
id: cerebro-page 

info:
  name: cerebro Unauth
  author: huowuzhao
  severity: high
  reference: https://github.com/lmenezes/cerebro
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cerebro/"
    matchers:
      - type: word
        words:
          - "cerebro"
        condition: and
        part: body
```
