### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by incogbyte** [projectdiscovery/nuclei-templates#2395]
**Template Details**

NTLM info disclosure: https://medium.com/swlh/internal-information-disclosure-using-hidden-ntlm-authentication-18de17675666

```yaml

id: ntlm-info-disclosure

info:
  name: ntlm info disclosure
  author: incogbyte
  severity: low
  description: During a penetration test this can be used to identify internal naming conventions, determine end-of-life operating systems, and discover internal DNS names. To describe one potential use-case for this data, the domain suffix, found in the decoded response, is often required for password spraying attacks against Outlook web applications. Targeting OWA is a common technique used by hackers to identify valid domain credentials, and made possible through this exposure
  reference:
    - https://medium.com/swlh/internal-information-disclosure-using-hidden-ntlm-authentication-18de17675666
  tags: generic

requests:
  - method: GET
    headers:
      User-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36"
      Authorization: "NTLM TlRMTVNTUAABAAAAB4IIAAAAAAAAAAAAAAAAAAAAAAA="
    path:
      - "{{BaseURL}}/adfs/"
      - "{{BaseURL}}/"
      - "{{BaseURL}}/certenroll/"
      - "{{BaseURL}}/certprov/"
      - "{{BaseURL}}/certsrv/"
      - "{{BaseURL}}/exchange/"
      - "{{BaseURL}}/exchweb/"
      - "{{BaseURL}}/groupexpansion/"
      - "{{BaseURL}}/hybridconfig/"
      - "{{BaseURL}}/oab/"
      - "{{BaseURL}}/ocsp/"
      - "{{BaseURL}}/owa/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "WWW-Authenticate"
          - "WWw-Authenticate"
        part: header

      - type: status
        status:
          - 401
```
