### ISSUE TITLE
I'm not able to use payloads without raw request

### ISSUE THREAD

**Issue by Vishnuraghav89** [projectdiscovery/nuclei-templates#2468]
Hi Sandeep and team,

Is there any way to use payloads without http raw request?

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{path}}/"
    matchers:
      - type: word
        words:
          - "anything"
     payloads:
         path: helpers/payloads/command-injection.txt
```

**Comment by ehsandeep** [comment]
@Vishnuraghav89 payloads need to be defined under request block and not outside of it, so the valid example for the above will be:-

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/{{path}}"
      
     payloads:
         path: helpers/payloads/command-injection.txt

    matchers:
      - type: word
        words:
          - "anything"
```
