### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by b0rn2r00t** [projectdiscovery/nuclei-templates#2524]
**Template Details**
Unauthenticated Access to Mongo Express Admin Panel
```yaml
id: mongo-express-admin-panel

info:
  name: Unauthenticated Mongo Express Panel
  author: b0rn2r00t [Shubham Ingle]
  severity: Critical
  reference: https://www.shodan.io/search?query=%22mongo-express%22
  tags: panel

requests:
  - method: GET
    path:
      - '{{BaseURL}}/db/admin/system.users'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Mongo Express</a>'
      - type: status
        status:
          - 200
```
