### ISSUE TITLE
[nuclei-template] Craft CMS Detection

### ISSUE THREAD

**Issue by skeltavik** [projectdiscovery/nuclei-templates#2544]
**Template Details**
Template to detect if Craft CMS is used. 

Following checks are performed:
- "X-Powered-By"-header
- Craft CMS Session ID
- Craft CMS CSRF Token

```yaml

id: craft-cms-detect

info:
  name: Craft CMS Detect
  author: skeltavik
  severity: info
  description: Detects Craft CMS
  tags: tech,craft,cms
  reference: https://craftcms.com

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: or
    matchers:
      - type: word
        part: header
        words:
          - 'X-Powered-By: Craft'

      - type: regex
        part: header
        # Regex checks Session ID and/or CSRF Token (CraftSessionId & CRAFT_CSRF_TOKEN)
        regex:
          - 'Set-Cookie: (Craft|CRAFT)'
```
