### ISSUE TITLE
[nuclei-template] Nextcloud Detection

### ISSUE THREAD

**Issue by skeltavik** [projectdiscovery/nuclei-templates#2569]
**Template Details**

```yaml

id: nextcloud-detect

info:
  name: Nextcloud Detect
  author: skeltavik
  severity: info
  description: Detects Nextcloud
  tags: tech,nextcloud,storage
  reference: https://nextcloud.com/

requests:
  - method: GET
    path:
      - '{{BaseURL}}/nextcloud/index.php/login'
      - '{{BaseURL}}/login'
      - '{{BaseURL}}'

    redirects: true
    max-redirects: 2
    
    matchers:
      - type: word
        part: body
        words:
          - 'var nc_lastLogin'
```
