### ISSUE TITLE
[nuclei-template] Nextcloud Exposed Installation

### ISSUE THREAD

**Issue by skeltavik** [projectdiscovery/nuclei-templates#2570]
**Template Details**

```yaml

id: nextcloud-install

info:
  name: Nextcloud Exposed Installation
  author: skeltavik
  severity: high
  tags: tech,nextcloud,storage
  reference: https://docs.nextcloud.com/server/latest/admin_manual/installation/installation_wizard.html

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    redirects: true
    max-redirects: 2
    
    matchers:
      - type: word
        part: body
        words:
          - '<fieldset id="adminaccount"><legend>Create an <strong>admin account</strong></legend>'
          - '<legend><a id="showAdvanced" tabindex="0" href="#">Storage &amp; database'
        condition: and

      - type: status
        status:
          - 200
```
