### ISSUE TITLE
[nuclei-template] OpenVPN Host Header Injection

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#2588]
**Template Details**
Injection in HOST value OpenVPN
```yaml
id: openvpn-hhi

info:
  name: OpenVPN Host Header Injection
  author: twitter.com/Dheerajmadhukar
  severity: info
  tags: openvpn,hhi

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{randstr}}.tld

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "https://{{randstr}}.tld/__session_start__/"
          - "openvpn_sess"
        part: header
        condition: and

      - type: status
        status:
          - 302
```
