### ISSUE TITLE
[Bug] CVE-2021-20092.yaml 

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#2638]
The following information is shown inside the template:
```
- raw:
      - |
        GET /images/..%2finfo.html HTTP/1.1
        Host: {{Hostname}}
        Referer: {{{{BaseURL}}}}/info.html
```

Is the `{{{{BaseURL}}}}` a mistake ?
