### ISSUE TITLE
[nuclei-template] Sitecore Version Disclosure

### ISSUE THREAD

**Issue by bernardofsr** [projectdiscovery/nuclei-templates#2661]
**Description**
This template aims to verify if the version in use of Sitecore is available on the host. 

**Template**

```yaml

id: sitecore-version-disclosure

info:
  name: Sitecore Version Disclosure
  author: bernardofsr
  severity: info
  tags: panel,sitecore,disclosure
  references: https://www.cvedetails.com/vulnerability-list/vendor_id-9609/Sitecore.html

requests:
  - method: GET
    path:
      - "{{BaseURL}}/sitecore/shell/sitecore.version.xml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<version>"
        part: body
```
