### ISSUE TITLE
create new template

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/nuclei-templates#270]
i managed to create new template which grap regex api, BUT
this template has multi regex and when i run against url it just mention the yaml id name not which regex he catches !
is it possible to till me which regex it catches when matches one of multiple provided in the same template.
example of my temp
```
id: mytemp

info:
  name: mytemp
  author: test
  severity: medium

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    extractors:
      - type: regex
        part: body
        regex:
          - "blabla1"
		  - "blabla2"
		  - "blabla3"
		  - "blabla4"
		  - "blabla5"
		  - "blabla6"
		  - "blabla7"
```
the simple question is could nuclei till me which bla it catches

**Comment by bauthard** [comment]
Hey @Sy3Omda, 

Have a look at [multiple-matchers ](https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md#multiple-matchers)

```
matchers:
  - type: word
    name: php
    words:
      - "X-Powered-By: PHP"
      - "PHPSESSID"
    part: header
  - type: word
    name: node
    words:
      - "Server: NodeJS"
      - "X-Powered-By: nodejs"
    condition: or
    part: header
  - type: word
    name: python
    words:
      - "Python/2."
      - "Python/3."
```

And here is an example of this [detect-all-takeovers ](https://github.com/projectdiscovery/nuclei-templates/blob/master/subdomain-takeover/detect-all-takeovers.yaml), once you got a match, it will print matcher name as well, so you know which matcher got matched.
