### ISSUE TITLE
AlphaWeb-XE-default-credential

### ISSUE THREAD

**Issue by bu1xuan2** [projectdiscovery/nuclei-templates#2739]
**Template Details**

```yaml
id: AlphaWeb-XE-default-credential

info:
  name: AlphaWeb XE Default credentials
  author: Lark Lab
  severity: medium
  tags: default-login

requests:
  - raw:
      - |
        GET /php/node_info.php HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic YWRtaW46YWxwaGFhZG1pbg==
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Referer: {{Hostname}}/php/index.php
        Accept-Encoding: gzip, deflate
        Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
        Cookie: PHPSESSID=bc11e93b2bde8a19659519ba263d220a
        Connection: close

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Information"
          - "Configuration"
        condition: and
      - type: status
        status:
          - 200

```
