### ISSUE TITLE
[feature] Add username/password/credential to output file with default-logins templates

### ISSUE THREAD

**Issue by l0nedigit** [projectdiscovery/nuclei-templates#2781]
When using default-logins templates, it would be convenient to have the successful username(s) & password(s) used against the application included in the output file specified (stdout and json format).  Understand the -irr flag can be used, but is also cumbersome at times to sort through.

**Comment by ehsandeep** [comment]
@l0nedigit This can be accomplished by upgrading all current login templates to incorporate payloads, as the nuclei engine does include matched payload values in the output.

For example, [dell-idrac-default-login](https://github.com/projectdiscovery/nuclei-templates/blob/54c9f0823356bc9817801f5e46cad86e7c9fb956/default-logins/dell/dell-idrac-default-login.yaml) can be updated as follows:

```yaml
id: dell-idrac-default-login
info:
  name: Dell iDRAC6/7/8 Default login
  author: kophjager007
  severity: high
  tags: dell,idrac,default-login

requests:
  - method: POST
    path:
      - "{{BaseURL}}/data/login"

    body: "user={{username}}&password={{password}}"

    headers:
      Content-Type: "application/x-www-form-urlencode"
      Referer: "{{BaseURL}}/login.html"

    attack: pitchfork
    payloads:
      username:
        - root

      password:
        - calvin
        
    cookie-reuse: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '<authResult>0</authResult>'
```
