### ISSUE TITLE
[nuclei-template]  AWS Config In Larvel Debug Method Enabled

### ISSUE THREAD

**Issue by xcapri** [projectdiscovery/nuclei-templates#2804]
**Template Details**
I want to add this template, is it valid in writing syntax?

```yaml

id: aws-in-laraveldebug

info:
  name: AWS Config In Larvel Debug Method Enabled
  author: xcapri
  severity: medium
  reference: https://github.com/workchainio/bug-bounty/issues/304
  tags: debug,laravel,configuration

requests:
  - method: POST
    path:
      - "{{BaseURL}}"

    body: "nuc=lei"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - AKIA

      - type: status
        status:
          - 405
```
