### ISSUE TITLE
detect-all-takeovers:unbounce needs an additional check

### ISSUE THREAD

**Issue by un-fmunozs** [projectdiscovery/nuclei-templates#281]
A lot of subdomains from Google return this generic "The requested URL was not found on this server."

The sample page I found https://info.hacker.one/ the response is exactly that. I think changing it to regex to match exactly the expected output is better.

https://www.mohamedharon.com/2019/02/2-subdomains-takeover-via-unbounce-in.html 

```
[INF] [detect-all-takeovers] Loaded template Subdomain Takeover Detection (@melbadry9 & pxmme1337) [high]
[detect-all-takeovers:unbounce] [http] https://elements.google.com/
[detect-all-takeovers:unbounce] [http] https://info.hacker.one/
[INF] No results found. Happy hacking!
```
After this change:
```
      - type: regex
        name: unbounce
        regex:
          - "^The requested URL was not found on this server.$"
```
It no longer triggers on Google but works on info.hacker.one
```
[INF] [detect-all-takeovers] Loaded template Subdomain Takeover Detection (@melbadry9 & pxmme1337) [high]
[detect-all-takeovers:unbounce] [http] https://info.hacker.one/
[INF] No results found. Happy hacking!
```

**Comment by bauthard** [comment]
Hey @un-fmunozs, 

I'm trying this locally, using below regex, 

```
      - type: word
        name: unbounce
        regex:
          - "^The requested URL was not found on this server.$"
```

It was missing `https://info.hacker.one` this as well.
