### ISSUE TITLE
[nuclei-template] Lansweeper login page detection

### ISSUE THREAD

**Issue by securitytest3r** [projectdiscovery/nuclei-templates#2868]
**Detects login page for Lansweeper HTTP/S service**

```yaml

id: lansweeper-login

info:
  name: Lansweeper Login
  author: divya_mudgal
  severity: info
  tags: lansweeper,tech,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login.aspx"

    matchers:
      - type: regex
        regex:
          - <title>[\s\S]*?Lansweeper - Login[\s\S]*?<\/title>
        condition: or
        
      - type: dsl
        name: lansweeper
        dsl:
          - "len(body)==15086 && status_code==200 && (\"0A60C945E674EC7B953429B515519567\" == md5(body))"
```
