### ISSUE TITLE
dwsync-xml.yaml

### ISSUE THREAD

**Issue by kaizensecurity** [projectdiscovery/nuclei-templates#2989]
### Template Information:

```yaml
id: dwsync-info

info:
  name: Dwsync.xml Exposure
  author: KaizenSecurity
  severity: info
  description: The dwsync.xml file is a file generated by Dreamweaver. Where the file contains information related to what files are in the website directory.
  tags: dwsync.xml,exposure,xampp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_notes/dwsync.xml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - '<dwsync>'

```
