### ISSUE TITLE
Index error in Template Creation

### ISSUE THREAD

**Issue by amiralkizaru** [projectdiscovery/nuclei-templates#302]
## Description

Hello Team
Thank you for making the template creation process easier for us so we can do more pull requests

I wanted to create a template for password regex and here is my attempt

```yaml
id: Password Regex

info:
  name: Password Checker
  author: Sicksec
  severity: Low

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'r"password\s*[`=:\"]+\s*[^\s]+|" \''
          - 'r"password is\s*[`=:\"]*\s*[^\s]+|" \''

    extractors:
      - type: regex
        part: body
        regex:
          - 'r"password is\s*[`=:\"]*\s*[^\s]+|" \''
          - 'r"password\s*[`=:\"]+\s*[^\s]+|" \''
```
I get an error in [http://www.yamllint.com/](http://www.yamllint.com/)that says 

`(<unknown>): did not find expected '-' indicator while parsing a block collection at line 18 column 11`

Regards
