### ISSUE TITLE
Cookie-Extractor.yaml

### ISSUE THREAD

**Issue by NagliNagli** [projectdiscovery/nuclei-templates#3054]
```yaml
id: cookie-detect
info:
  name: Cookies-extractor
  author: Nagli
  description: Extract cookies
  severity: info
  tags: cookies

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: kval
        part: header
        kval:
          - Set_Cookie
```
