### ISSUE TITLE
[false-negative] freshdesk-takeover

### ISSUE THREAD

**Issue by aspx** [projectdiscovery/nuclei-templates#3106]
### Nuclei Version:

2.5.3

### Template file:

takeovers/freshdesk-takeover.yaml

### Command to reproduce:

The template is not capturing domain takeover for valid domains.

Executing the following command we do not have an positive answer: 

```
nuclei -u http://freshdesk.aspx.dev -t /root/nuclei-templates/takeovers/freshdesk-takeover.yaml
```

Root Cause : The template is expecting `Maybe this is still fresh!` but the site is returning `May be this is still fresh!`. 

Sample request 
```
curl http://freshdesk.aspx.dev
```
Sample output
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="robots" content="noindex"/>
		<meta name="robots" content="noarchive"/>
		<link rel="stylesheet" href="/assets/page/404.css" type="text/css" media="screen, projection" />
		<title>There is no helpdesk here!</title>
	</head>
	<body>
		<div id="wrap" class="container">
			<div class="wrapper">
				<div class="wrapper-shadow">
					<div class="no-helpdesk">
						<img src="/assets/misc/freshdesklogo.png" alt="Freshdesk Support Desk" width="204px" height="50px" />
						<h2>  We couldn&#x27;t find  <span id="domainname"></span></h2>
						<p> May be this is still fresh!  </p> 
						<p> You can claim it now at <a href="http://www.freshdesk.com/signup">http://www.freshdesk.com/signup</a></p>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
//<![CDATA[

			document.getElementById("domainname").innerHTML = (document.domain);

//]]>
</script>	</body>
</html>

```

During my tests I found another issue, sometimes the answer can be in another language, Portuguese, French, ... 

My suggestion is to change the template to the following: 

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "404.css"
          - "signup"
        condition: and

      - type: dsl
        dsl:
          - contains(host,"freshpo.com")
        negative: true
```

Any thoughts ?
