### ISSUE TITLE
Golang expvar Information Disclosure

### ISSUE THREAD

**Issue by luqmanhy** [projectdiscovery/nuclei-templates#3126]
### Template Information:

Package expvar provides a standardized interface to public variables, such as operation counters in servers. It exposes these variables via HTTP at /debug/vars in JSON format. 
References : https://www.acunetix.com/vulnerabilities/web/unrestricted-access-to-golang-expvar-page/

### Nuclei Template:

```yaml
id: debug-vars

info:
  name: debug vars file
  author: luqman
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug/vars"
    matchers:
      - type: word
        words:
          - "memstats"
```
