### ISSUE TITLE
False negatives in Prometheus templates

### ISSUE THREAD

**Issue by alph4byt3** [projectdiscovery/nuclei-templates#3204]
### Template file:

All related Prometheus templates, namely:

https://github.com/projectdiscovery/nuclei-templates/blob/master/exposed-panels/prometheus-exposed-panel.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/prometheus-targets-endpoint.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/prometheus-flags-endpoint.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/prometheus-config-endpoint.yaml

### Description

If we take a look at https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/, you will notice that a Shodan search query is given to find exposed Prometheus panels `http.favicon.hash:-1399433489`

After I did some searching around, I found that there are a lot of panels being hosted on port 9090 as well.

Due to each template not having a request for port 9090, it can miss panels that are being hosted on that port, for example:

I modified the following template to include the check for port 9090 as well...

```yaml
id: prometheus-config-endpoint

info:
  name: Prometheus config API endpoint
  author: geeknik
  severity: info
  description: The config endpoint returns the loaded Prometheus configuration file. This file also contains addresses of targets and alerting/discovery services alongside the credentials required to access them. Usually, Prometheus replaces the passwords in the credentials config configuration field with the placeholder <secret> (although this still leaks the username).
  reference: https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  tags: prometheus,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/status/config"
      - "{{BaseURL}}:9090/api/v1/status/config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - 'job_name:'
          - '{"status":"success","data":'
          - 'targets:'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'
```

I took some endpoints exposed on Shodan and tested them and it returned back results while it didn't before I modified the template

![Screenshot 2021-11-25 152315](https://user-images.githubusercontent.com/67894940/143449286-fec027f3-3d17-4f7f-b11b-e9c128c68858.png)

Here's another example with the panel template:

![Screenshot 2021-11-25 153620](https://user-images.githubusercontent.com/67894940/143451274-ed78b103-1982-466c-ab2c-4b6af31afb2b.png)

I also noticed that some URLs can include the prometheus word so it might be a good idea to add that path as well as seen below

![Screenshot 2021-11-25 152632](https://user-images.githubusercontent.com/67894940/143449849-0e7862b4-7df3-4bee-aa1d-b2e4b712daad.png)

Something else I'd like to mention as well, wouldn't it be better to mark these templates as a different severity. The reason for this is that if we look at the article https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/ carefully, it explains in detail what kind of sensitive information can be leaked in misconfigured instances including cloud service metadata.

I was actually creating my own Prometheus templates to share and when I saw that they already existed, I went to check on them and saw they aren't doing checks on port 9090 which is what brought me here.

I hope this helps
