### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by bjhulst** [projectdiscovery/nuclei-templates#323]
On this page you talk about "matcher:" but I think the software only scans for "matchers:" in the yaml files.
https://nuclei.projectdiscovery.io/templating-guide/#types 
```
To match status codes for responses, you can use the following syntax.
matcher:
  # Match the status codes
  - type: status
    # Some status codes we want to match
    status:
      - 200
      - 302
```
