### ISSUE TITLE
[nuclei-template] neos-cms-detect

### ISSUE THREAD

**Issue by k11h-de** [projectdiscovery/nuclei-templates#3243]
### Template Information:

detection of Neos CMS based on header and comment in body

### Nuclei Template:

```yaml
id: neos-cms-detect

info:
  name: Neos CMS detection
  author: k11h-de
  description: some Neos websites remove the X-Flow-Powered Header, but they usually all have a comment line at the top of the body
  severity: info
  reference: https://github.com/neos/
  tags: tech,neos-cms

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: regex
        part: header
        regex:
          - "X-Flow-Powered: Flow/.*Neos/.*"

      - type: regex
        part: body
        regex:
          - "This website is powered by Neos. the Open Source Content Application Platform licensed under the GNU/GPL"

    extractors:
      - type: kval
        part: header
        kval:
          - X_Flow_Powered

```

Example Reponse looks like
```
HTTP/2 200 
server: nginx
date: Wed, 01 Dec 2021 21:41:54 GMT
content-type: text/html; charset=UTF-8
content-length: 95641
vary: Accept-Encoding
x-flow-powered: Flow/6.3 Neos/5.3

<!DOCTYPE html><html lang="de">
<!--
This website is powered by Neos, the Open Source Content Application Platform licensed under the GNU/GPL.
Neos is based on Flow, a powerful PHP application framework licensed under the MIT license.

More information and contribution opportunities at https://www.neos.io
-->
<head><script......
```
