### ISSUE TITLE
[nuclei-template] neos-cms-panel

### ISSUE THREAD

**Issue by k11h-de** [projectdiscovery/nuclei-templates#3244]
### Template Information:

detection of Neos CMS backend login panel based on warranty disclaimer in footer

### Nuclei Template:

```yaml
id: neos-cms-panel

info:
  name: Neos CMS Login Panel
  author: k11h-de
  severity: info
  description: detection of default route to admin login panel based on warranty disclainer in footer
  reference: https://github.com/neos/neos/blob/master/Configuration/Routes.yaml
  tags: panel,neos-cms

requests:
  - method: GET
    path:
      - '{{BaseURL}}/neos/login'

    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Neos comes with ABSOLUTELY NO WARRANTY'

      - type: status
        status:
          - 200

    extractors:
      - type: kval
        part: header
        kval:
          - X_Flow_Powered
```

A list of Neos-based website for testing is located [here](https://www.neos.io/who-uses-neos/show-cases.html)
