### ISSUE TITLE
Dmarc-Detect

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei-templates#3257]
### Template Information:

The template returns the result of DMARC
https://support.google.com/a/answer/2466580?hl=en

### Nuclei Template:

```yaml
id: dmarc-detect

info:
  name: test
  author: brenocss
  severity: info
  tags: dns,dmarc

stop-at-first-match: true
dns:
  - name: _dmarc.{{FQDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tTXT\t(.+)"
  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"

    extractors:
      - type: regex
        group: 1
        regex:
          - "IN\tTXT\t(.+)"


```
