### ISSUE TITLE
Missing-Dmarc

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei-templates#3258]
### Template Information:

Template alerts when DMARC is missing

### Nuclei Template:

```yaml
id: spoofable-mail-missingdmarc

info:
  name: spoofable-mail-missingdmarc
  author: brenocss
  severity: medium
  tags: dns,dmarc

dns:
  - name: _dmarc.{{FQDN}}
    id: fqdn
    type: TXT
    class: inet
    recursion: true
    retries: 3

  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
      
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        part: fqdn_answer
        negative: true

      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
        part: answer
        negative: true
```
