### ISSUE TITLE
DMARC-Spoofable-Pnone

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei-templates#3259]
### Template Information:

Template alerts when DMARC is incorrectly configured.  p=none
This can also be set for "sp=quarantine"
"sp=none"
"p=quarantine"

### Nuclei Template:

```yaml
id: dmarc-spoofable-Pnone

info:
  name: test
  author: brenocss
  severity: medium
  tags: dns,dmarc

stop-at-first-match: true
dns:
  - name: _dmarc.{{FQDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
      - type: regex
        regex:
          - "(\\sp=none)"
  - name: _dmarc.{{RDN}}
    type: TXT
    class: inet
    recursion: true
    retries: 3
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "v=dmarc1"
          - "v=DMARC1"
      - type: regex
        regex:
          - "(\\sp=none)"
```
