### ISSUE TITLE
[nuclei-template] apache-cocoon-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3271]
### Template Information:

cocoon detect

https://cocoon.apache.org/

### Nuclei Template:

```yaml
id: apache-cocoon-detect
info:
  name: Apache-Cocoon-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="APACHE-Cocoon"
  tags: apache,cocoon

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        part: header
        words:
          - "X-Cocoon-Version"
```
![image](https://user-images.githubusercontent.com/18167071/144784372-0976a29d-31c7-4e7a-9002-da557dd1e525.png)
