### ISSUE TITLE
[nuclei-template] apache-dubbo-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3272]
### Template Information:

dubbo detect
- https://dubbo.apache.org/en/

### Nuclei Template:

```yaml
id: apache-dubbo-detect
info:
  name: Apache-dubbo-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="APACHE-dubbo"
  tags: apache,dubbo

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        part: header
        words:
          - "Basic realm=\"dubbo\""
```

![image](https://user-images.githubusercontent.com/18167071/144785238-dd9daeea-a4dd-434f-8d1a-5ad3675c25c0.png)
