### ISSUE TITLE
[nuclei-template] B2BBuilder-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3282]
### Template Information:

B2BBuilder detect
- http://www.b2b-builder.com/

### Nuclei Template:

```yaml
id: B2BBuilder-detect

info:
  name: B2BBuilder-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="B2BBuilder"
  tags: B2BBuilder,tech

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'content="B2Bbuilder"'
          - 'translateButtonId = "B2Bbuilder"'
        condition: or

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/144977367-cb3306fa-e594-4dc2-95ef-c46bb96203b3.png)
