### ISSUE TITLE
[nuclei-template] Ymhome-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3283]
### Template Information:

Ymhome detect
- http://www.yimihome.com/

### Nuclei Template:

```yaml
id: Ymhome-detect

info:
  name: Ymhome-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="一米OA"
  tags: Ymhome,oa,tech

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "yimioa.apk"
          - "isSavePwd"
        condition: and

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/144987870-cc84f1dd-3ca1-49ff-aaf8-e45d47df6bb8.png)
