### ISSUE TITLE
thruk-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3314]
### Template Information:

thruk detect
- https://www.thruk.org/

### Nuclei Template:

```yaml
id: thruk-detect

info:
  name: thruk detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: title=="Thruk Monitoring Webinterface"
  tags: thruk,tech

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2
    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - 'Thruk Monitoring Webinterface'

      - type: word
        part: header
        words:
          - "/thruk/cgi-bin/login.cgi?thruk/"

```

![image](https://user-images.githubusercontent.com/18167071/145504092-3667f04a-6fdd-4959-a7c5-e4ba09dc4cb9.png)
