### ISSUE TITLE
cves\2017\CVE-2017-10974.yaml

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#3338]
The issue isn't strictly a false positive/false negative, its just a badly written check
```
      - type: dsl
        dsl:
          - '!contains(tolower(body), "<html")'
          - '!contains(tolower(body), "<HTML")'
        condition: or
```

Since we are doing `tolower`, the second one will never hit, a fix:
```
      - type: dsl
        dsl:
          - '!contains(tolower(body), "<html")'
```
