### ISSUE TITLE
CaseManager-panel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3347]
### Template Information:

CaseManager detect

### Nuclei Template:

```yaml
id: CaseManager-panel

info:
  name: CaseManager-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: title="CaseManager"
  tags: CaseManager,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login"
    redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "CaseManager"
          - "bootstrap.min.css"
        condition: and
      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/146153567-cd2bfd2c-6a9d-492e-9e01-bf350f1c489e.png)
