### ISSUE TITLE
e-message panel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3363]
### Template Information:

e-message detect
- https://emobile.weaver.com.cn/emessage/?_timestamp=1639724977738

### Nuclei Template:

```yaml
id: e-message-panel

info:
  name: e-message panel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: title="emessage"
  tags: panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login.jsp"

    redirects: true
    max-redirects: 2
    matchers-condition: or
    matchers:
      - type: word
        words:
          - "<title>emessage"
          - "username"
          - "password"
        part: body
        condition: and
```

![image](https://user-images.githubusercontent.com/18167071/146504153-5f4d15a5-0b03-4609-8722-0c699a804c54.png)
