### ISSUE TITLE
[nuclei-template] Service Now Help The Help Desk

### ISSUE THREAD

**Issue by jordanpotti** [projectdiscovery/nuclei-templates#3366]
### Template Information:

ServiceNow has a feature, that when configured, allows ServiceNow customers to collect information from their employees or customers endpoints. This is in the form of a WMI script, that collects system information, and ships it off to ServiceNow.

This sounds great, except for how ServiceNow decided to authenticate those requests to submit system information. Curiously, the credentials for the request were stored in a public JavaScript file on all ServiceNow instances utilizing the HelpTheHelpDesk feature.

The JavaScript file can be accessed at https://<customername>.servicenow.com/HelpTheHelpDesk.jsdbx. The credentials are at the top of the script for anyone’s viewing pleasure. How this hadn’t been found before is interesting.

Fortunately, the password was encrypted… Unfortunately, the password was actually base64 encoded, and not encrypted as the JS file tried to convince us by prepending the base64 encoded password with encrypt:.

https://jordanpotti.com/2021/02/21/ServiceNow-HelpTheHelpDeskAndTheHackers/

If you run it against a subdomain enumeration of service-now.com you get a number of results. 

### Nuclei Template:

```yaml
id: help-the-help-desk-service-now

info:
  name: help-the-help-desk
  author: ok_bye_now
  severity: high
  description: Detection of exposed credentials in help the help desk JS file.
  reference:
    - https://jordanpotti.com/2021/02/21/ServiceNow-HelpTheHelpDeskAndTheHackers/
  tags: servicenow

requests:
  - method: GET
    path:
      - "{{BaseURL}}/HelpTheHelpDesk.jsdbx"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'var httpUsername'
        part: body

      - type: status
        status:
          - 200
```
