### ISSUE TITLE
Craft CMS admin panel

### ISSUE THREAD

**Issue by supr4s** [projectdiscovery/nuclei-templates#3379]
### Template Information:

Find admin panels for [Craft CMS](https://craftcms.com/)

### Nuclei Template:

```yaml
id: craftcms-admin-panel

info:
  name: Craft CMS admin panel
  author: Supras
  severity: info
  reference: https://www.shodan.io/search?query=X-Powered-By%3A+Craft+CMS
  tags: panel,craftcms

requests:
  - method: GET
    path:
      - '{{BaseURL}}/admin/login'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Craft CMS"

      - type: status
        status:
          - 200

```

![craft_cms_template](https://user-images.githubusercontent.com/34515269/146684283-9865cd8f-0981-492a-950c-1ce2142f5c47.png)
