### ISSUE TITLE
iXCache pannel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3408]
### Template Information:

iXCache pannel
- https://www.panabit.com/cn/product/iXCache/

### Nuclei Template:

```yaml
id: iXCache-pannel

info:
  name: iXCache pannel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="iXCache"
  tags: iXCache,pannel

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>iXCache</title>'
        part: body
        condition: and
```

![image](https://user-images.githubusercontent.com/18167071/147306940-7290eb9c-334d-462d-b8b9-890b675ae651.png)
