### ISSUE TITLE
panabit pannel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3409]
### Template Information:

panabit pannel
- https://www.panabit.com/

### Nuclei Template:

```yaml
id: panabit-pannel

info:
  name: panabit pannel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="Panabit-智能网关"
  tags: panabit,pannel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/login/login.htm"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Panabit</title>'
        part: body
        condition: and

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/147307223-d4e69b45-9278-43fe-80eb-f3467477f5f3.png)
