### ISSUE TITLE
KodExplorer-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3410]
### Template Information:

KodExplorer detect
- https://github.com/kalcaddle/KodExplorer

### Nuclei Template:

```yaml
id: KodExplorer-detect

info:
  name: KodExplorer-detect
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="Powered-by-KodExplorer"
  tags: KodExplorer,detect

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2
    matchers-condition: or
    matchers:
      - type: regex
        regex:
          - '(?i)<title>.* - Powered by KodExplorer</title>'
```

![image](https://user-images.githubusercontent.com/18167071/147307889-08c44fbf-940c-4ba9-bacd-bb95313a360f.png)
