### ISSUE TITLE
Acrolinx Dashboard Pannel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3427]
### Template Information:

Acrolinx Dashboard Pannel

### Nuclei Template:

```yaml
id: Acrolinx-Dashboard-Pannel

info:
  name: Acrolinx Dashboard Pannel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: title=="Acrolinx Dashboard"
  tags: acrolinx,pannel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/dashboard.html"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Acrolinx Dashboard</title>'
          - 'Acrolinx</title>'
        part: body
        condition: or

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/147401119-b13e7f16-e30b-4c71-96f7-70400cc89903.png)
