### ISSUE TITLE
Adminset-Pannel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3428]
### Template Information:

Adminset Pannel

vendor: https://github.com/guhongze/adminset/

### Nuclei Template:

```yaml
id: Adminset-Pannel

info:
  name: Adminset Pannel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="AdminSet"
    vendor: https://github.com/guhongze/adminset/
  tags: Adminset,pannel

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>AdminSet Login</title>"
        part: body
        condition: and

      - type: word
        words:
          - "text/html"
        part: header

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/18167071/147401215-78114cd1-3c01-4b0a-ab32-f27e36236bcd.png)
