### ISSUE TITLE
test-cgi-script-leaking-environment-variables.yaml

### ISSUE THREAD

**Issue by emadshanab** [projectdiscovery/nuclei-templates#3495]
```yaml
id: test-cgi-script-leaking-environment-variables
info: 
  author: emadshanab
  name: "Test CGI script leaking environment variables"
  reference: "https://www.acunetix.com/vulnerabilities/web/test-cgi-script-leaking-environment-variables/"
  severity: medium
  tags: "exposure,generic"
requests: 
  - 
    matchers: 
      - 
        status: 
          - 200
        type: status
      - 
        part: body
        type: word
        words: 
          - MYSQL_HOME
          - OPENSSL_CONF
          - REMOTE_ADDR
          - SERVER_ADMIN
    matchers-condition: and
    method: GET
    path: 
      - "{{BaseURL}}/cgi-bin/printenv.pl"

```
