### ISSUE TITLE
gocron-panel

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3510]
### Template Information:

gocron panel
- https://github.com/ouqiang/gocron

### Nuclei Template:

```yaml
id: gocron-panel

info:
  name: gocron panel
  author: ffffffff0x
  severity: info
  metadata:
    fofa-query: app="gocron-定时任务系统"
  tags: gocron,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2

    matchers:
      - type: word
        part: body
        words:
          - '<title>gocron - 定时任务系统</title>'
```

![image](https://user-images.githubusercontent.com/18167071/148724511-f4c935b4-3d67-4908-9657-872f8c6e3052.png)

![image](https://user-images.githubusercontent.com/18167071/148724556-0e4c601a-2d7f-4973-a106-3d1b7fcd553a.png)
