### ISSUE TITLE
apc-file-leak

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3561]
### Nuclei Template:

```yaml
id: apc-file-leak

info:
  name: apc-file-leak
  severity: info
  author: ffffffff0x
  metadata:
    google-dork: inurl:"apc.php"
  reference: |
    - https://www.acunetix.com/vulnerabilities/web/apc-php-page-found/
  tags: apc,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}/apc.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>APC"
          - 'h1.apc'
          - 'class="apc">'
          - 'http://pecl.php.net/package/APC'
        condition: and

      - type: status
        status:
          - 200
```
![image](https://user-images.githubusercontent.com/18167071/150082728-4d789ff8-41da-4c98-9d70-662207ec8bcb.png)

![image](https://user-images.githubusercontent.com/18167071/150082764-bf10111f-4448-48e0-bf41-04e261eabacd.png)
