### ISSUE TITLE
openbmcs-detect

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3609]
### Template Information:

openbmcs-detect

quake-query is https://quake.360.cn/quake/#/index

### Nuclei Template:

```yaml
id: openbmcs-detect

info:
  name: openbmcs-detect
  author: ffffffff0x
  severity: info
  metadata:
    quake-query: openbmcs
  tags: openbmcs,detect

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 2

    matchers:
      - type: word
        part: body
        words:
          - '<!--<title>BMS - Login</title>-->'
          - 'Copyright all rights reserved by Open BMCS'
          - 'OpenBMCS does not support Internet Explorer'
        condition: or

```

![image](https://user-images.githubusercontent.com/18167071/151163430-51256449-b1c3-47e6-9fd0-4e2be241cadb.png)
