### ISSUE TITLE
Multiple backup file detection

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3610]
### Template Information:

Detect backup files based on domain name
```
{{FQDN}}	# www.projectdiscovery.io
{{RDN}}		# projectdiscovery.io
{{DN}}		# projectdiscovery
{{TLD}}		# io
{{SD}}		# www
```

### Nuclei Template:

```yaml
id: backup-files-TLD

info:
  name: Compressed Web File
  author: ffffffff0x
  description: |
    testphp.vulnweb.com
      {{TLD}}
      com
  severity: medium
  tags: exposure,backups

requests:
  - method: GET
    path:
      - "{{RootURL}}/{{TLD}}.{{suffix}}"

    payloads:
      suffix:
        - 'zip'
        - 'rar'
        - 'gz'
        - 'tar.gz'
        - '7z'
        - 'bz2'
        - 'tar.z'
        - 'db'
    attack: pitchfork

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "377ABCAF271C"  # 7z
          - "314159265359"  # bz2
          - "53514c69746520666f726d6174203300"  # SQLite format 3.
          - "1f8b"  # gz tar.gz
          - "526172211A0700"  # rar RAR archive version 1.50
          - "526172211A070100"  # rar RAR archive version 5.0
          - "FD377A585A0000"  # xz tar.xz
          - "1F9D"  # z tar.z
          - "1FA0"  # z tar.z
          - "4C5A4950"  # lz
          - "504B0304"  # zip
        condition: or
        part: body

      - type: status
        status:
          - 200
```

```yaml
id: backup-files-SD

info:
  name: Compressed Web File
  author: ffffffff0x
  description: |
    testphp.vulnweb.com
      {{replace_regex("{{Host}}", '(\\..*)', "")}}
      {{SD}}
      testphp
  severity: medium
  tags: exposure,backups

requests:
  - raw:
      - |
        GET /{{SD}}.{{suffix}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
      suffix:
        - 'zip'
        - 'rar'
        - 'gz'
        - 'tar.gz'
        - '7z'
        - 'bz2'
        - 'tar.z'
        - 'db'
    attack: pitchfork

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "377ABCAF271C"  # 7z
          - "314159265359"  # bz2
          - "53514c69746520666f726d6174203300"  # SQLite format 3.
          - "1f8b"  # gz tar.gz
          - "526172211A0700"  # rar RAR archive version 1.50
          - "526172211A070100"  # rar RAR archive version 5.0
          - "FD377A585A0000"  # xz tar.xz
          - "1F9D"  # z tar.z
          - "1FA0"  # z tar.z
          - "4C5A4950"  # lz
          - "504B0304"  # zip
        condition: or
        part: body

      - type: status
        status:
          - 200
```

```yaml
id: backup-files-RDN

info:
  name: Compressed Web File
  author: ffffffff0x
  description: |
    testphp.vulnweb.com
      {{RDN}}
      vulnweb.com
  severity: medium
  tags: exposure,backups

requests:
  - raw:
      - |
        GET /{{RDN}}.{{suffix}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
      suffix:
        - 'zip'
        - 'rar'
        - 'gz'
        - 'tar.gz'
        - '7z'
        - 'bz2'
        - 'tar.z'
        - 'db'
    attack: pitchfork

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "377ABCAF271C"  # 7z
          - "314159265359"  # bz2
          - "53514c69746520666f726d6174203300"  # SQLite format 3.
          - "1f8b"  # gz tar.gz
          - "526172211A0700"  # rar RAR archive version 1.50
          - "526172211A070100"  # rar RAR archive version 5.0
          - "FD377A585A0000"  # xz tar.xz
          - "1F9D"  # z tar.z
          - "1FA0"  # z tar.z
          - "4C5A4950"  # lz
          - "504B0304"  # zip
        condition: or
        part: body

      - type: status
        status:
          - 200
```

```yaml
id: backup-files-FQDN

info:
  name: Compressed Web File
  author: ffffffff0x
  description: |
    testphp.vulnweb.com
      {{FQDN}}
      testphp.vulnweb.com
  severity: medium
  tags: exposure,backups

requests:
  - method: GET
    path:
      - "{{RootURL}}/{{FQDN}}.{{suffix}}"

    payloads:
      suffix:
        - 'zip'
        - 'rar'
        - 'gz'
        - 'tar.gz'
        - '7z'
        - 'bz2'
        - 'tar.z'
        - 'db'
    attack: pitchfork

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "377ABCAF271C"  # 7z
          - "314159265359"  # bz2
          - "53514c69746520666f726d6174203300"  # SQLite format 3.
          - "1f8b"  # gz tar.gz
          - "526172211A0700"  # rar RAR archive version 1.50
          - "526172211A070100"  # rar RAR archive version 5.0
          - "FD377A585A0000"  # xz tar.xz
          - "1F9D"  # z tar.z
          - "1FA0"  # z tar.z
          - "4C5A4950"  # lz
          - "504B0304"  # zip
        condition: or
        part: body

      - type: status
        status:
          - 200
```

```yaml
id: backup-files-DN

info:
  name: Compressed Web File
  author: ffffffff0x
  description: |
    testphp.vulnweb.com
      {{DN}}
      vulnweb
  severity: medium
  tags: exposure,backups

requests:
  - method: GET
    path:
      - "{{RootURL}}/{{DN}}.{{suffix}}"

    payloads:
      suffix:
        - 'zip'
        - 'rar'
        - 'gz'
        - 'tar.gz'
        - '7z'
        - 'bz2'
        - 'tar.z'
        - 'db'
    attack: pitchfork

    max-size: 500
    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "377ABCAF271C"  # 7z
          - "314159265359"  # bz2
          - "53514c69746520666f726d6174203300"  # SQLite format 3.
          - "1f8b"  # gz tar.gz
          - "526172211A0700"  # rar RAR archive version 1.50
          - "526172211A070100"  # rar RAR archive version 5.0
          - "FD377A585A0000"  # xz tar.xz
          - "1F9D"  # z tar.z
          - "1FA0"  # z tar.z
          - "4C5A4950"  # lz
          - "504B0304"  # zip
        condition: or
        part: body

      - type: status
        status:
          - 200
```
