### ISSUE TITLE
jsf-detection.yaml + detect primefaces + detect richfaces

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/nuclei-templates#3617]
### Template Information:

Detect jsf and primefaces, richfaces
### Nuclei Template:

```yaml
id: jsf-detection

info:
  name: JavaServer Faces Detection
  author: brenocss, Moritz Nentwig
  severity: info
  description: Searches for JavaServer Faces content on a URL.
  tags: jsf,tech

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    redirects: true
    max-redirects: 6

    matchers-condition: or
    matchers:
    - type: dsl
      name: javafaces
      dsl:
        - "contains(tolower(body), 'javax.faces.resource')"
        - "contains(tolower(body), 'javax.faces.ViewState')"
      condition: or

    - type: dsl
      name: primefaces
      dsl:
        - "contains(tolower(body), 'primefaces')"

    - type: dsl
      name: richfaces
      dsl:
        - "contains(tolower(body), 'richfaces')"
```
