### ISSUE TITLE
AntSword_bypass_disable_functions_shell

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3628]
### Template Information:

Ant Sword「绕过 disable_functions」plugin generated shell

https://github.com/AntSwordProject/AntSword-Labs/tree/master/bypass_disable_functions/9

### Nuclei Template:

```yaml
id: AntSword_bypass_disable_functions_shell

info:
  name: AntSword_bypass_disable_functions_shell
  author: ffffffff0x
  severity: critical
  description: |
    蚁剑「绕过 disable_functions」插件生成的 shell
  reference: https://github.com/AntSwordProject/AntSword-Labs/tree/master/bypass_disable_functions/9
  tags: backdoor

requests:
  - method: POST
    path:
      - "{{BaseURL}}/.antproxy.php"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: 'ant=phpinfo();'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "PHP Extension"
          - "PHP Version"
          - "Zend"
          - "探针"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '>PHP Version <\/td><td class="v">([0-9.]+)'

```
