### ISSUE TITLE
[false-positive] CVE-2017-5638

### ISSUE THREAD

**Issue by ohlinge** [projectdiscovery/nuclei-templates#364]
**CVE-2017-5638**

```
cves/CVE-2017-5638.yaml
```
Such as:
![image](https://user-images.githubusercontent.com/15817052/91650976-4d014680-eab9-11ea-84d1-1a2a84f145de.png)

This template matchers possible error:
```
    matchers:
      - type: word
        words:
          - "Bounty Plz"
        part: header
```
This HTTP Request and Response content-type have "Bounty Plz", but this is false positive.

I suggest :
```
    matchers:
      - type: word
        words:
          - "X-Hacker: Bounty Plz"
        part: header
```
