### ISSUE TITLE
token-spray api-cloudflare

### ISSUE THREAD

**Issue by No-Github** [projectdiscovery/nuclei-templates#3690]
### Template Information:

cloudflare API Test

### Nuclei Template:

```yaml
id: api-cloudflare

info:
  name: cloudflare API Test
  author: ffffffff0x
  severity: info
  reference:
    - https://dash.cloudflare.com/profile/api-tokens
  tags: token-spray,cloudflare

self-contained: true
requests:
  - raw:
      - |
        GET https://api.cloudflare.com/client/v4/user/tokens/verify HTTP/1.1
        Host: api.cloudflare.com
        Authorization: Bearer {{token}}
        Content-Type:application/json

    matchers:
      - type: word
        part: body
        words:
          - 'This API Token is valid and active'
        condition: and

```
