### ISSUE TITLE
Find Pypicloud instance and login pane

### ISSUE THREAD

**Issue by supr4s** [projectdiscovery/nuclei-templates#3739]
### Template Information:

Find [Pypicloud](https://pypicloud.readthedocs.io/) instance and login panel.

### Nuclei Template:

```yaml
id: pypicloud-panel-detect

info:
  name: Pypicloud panel detector
  author: Supras
  severity: info
  reference: https://pypicloud.readthedocs.io/en/latest/
  tags: panel,pypicloud
  metadata:
    google-query: 'intext:pypicloud'


requests:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Pypicloud</title>'
          - '<html ng-app="pypicloud">'
        part: body
      - type: status
        status:
          - 200

```

![pypicloud-nuclei](https://user-images.githubusercontent.com/34515269/154846352-1fcb3631-fc43-4e0c-8e0f-128a1b8fd531.png)
