### ISSUE TITLE
Token-Spray api-launchdarkly

### ISSUE THREAD

**Issue by Luqiih** [projectdiscovery/nuclei-templates#3764]
### Template Information:
This template is used to validate LaunchDarkly API tokens

References:
https://apidocs.launchdarkly.com/

### Nuclei Template:

```yaml
id: api-launchdarkly

info:
  name: LaunchDarkly REST API
  author: Luqmaan Hadia
  severity: info
  reference:
    - https://apidocs.launchdarkly.com/
  tags: token-spray,launchdarkly

self-contained: true
requests:
  - raw:
      - |
        GET https://app.launchdarkly.com/api/v2/members HTTP/1.1
        Host: app.launchdarkly.com
        Authorization: {{token}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "totalCount"
```
Output from test:

```bash
┌──(luqmaan㉿luqii-laptop)-[~/nuclei-templates]
└─$ nuclei -t token-spray/ -var token=api-4dfc17e5-2acc-4075-83bf-REDACTED

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.6.0

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.6.0 (outdated)
[INF] Using Nuclei Templates 8.8.5 (latest)
[INF] Templates added in last update: 3117
[INF] Templates loaded for scan: 147
[2022-02-23 20:46:36] [api-launchdarkly] [http] [info] https://app.launchdarkly.com/api/v2/members [token=api-4dfc17e5-2acc-4075-REDACTED]
```
Example response when using cURL:

```
HTTP/2 200 
content-type: application/json
access-control-allow-headers: Accept,Content-Type,Content-Length,Accept-Encoding,Authorization,X-Requested-With,X-LD-Private,X-LD-AccountId,X-LD-EnvId,X-LD-PrjId,X-LaunchDarkly-Event-Schema,X-LaunchDarkly-User-Agent,X-LaunchDarkly-Wrapper,LD-API-Version
access-control-allow-methods: OPTIONS, HEAD, GET, POST
access-control-allow-origin: *
access-control-max-age: 300
ld-api-version: 20191212
strict-transport-security: max-age=31536000
x-ratelimit-reset: 1645642320000
x-ratelimit-route-limit: 500
x-ratelimit-route-remaining: 499
accept-ranges: bytes
date: Wed, 23 Feb 2022 18:51:57 GMT
via: 1.1 varnish
x-served-by: cache-cpt13824-CPT
x-cache: MISS
x-cache-hits: 0
x-timer: S1645642316.319009,VS0,VE689
vary: Accept-Encoding, Origin
age: 0
```
