### ISSUE TITLE
Netflix Conductor UI detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3769]
### Template Information:
Netflix Conductor UI detection  
- The UI title has changed in later versions.  
- X-Powered-By: Express header is always returned between tested versions. 

Tested against: 
- v2.27.0
- v3.6.0 (latest)

### Nuclei Template:
```yaml
id: netflix-conductor-ui

info:
  name: Netflix Conductor UI Detection
  author: c-sh0
  description: Netflix conductor ui Detection
  severity: info
  metadata:
    shodan-query: http.title:"Conductor UI", http.title:"Workflow UI"
  tags: webserver,netflix,conductor,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'X-Powered-By: Express'

      - type: word
        part: body
        words:
          - '<title>Conductor UI</title>'
          - '<title>Workflow UI</title>'
```
![ui-detection](https://user-images.githubusercontent.com/25989137/155631087-59b70c5c-094a-4af5-827f-ca9119738ff3.png)
