### ISSUE TITLE
Netflix Conductor Version Detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3770]
### Template Information:
Netflix Conductor Version Detection
- /api/sys (json: .sys.version) was removed  >= v3.1.0

This word matcher was added to insure we are seeing a conductor API
- CONDUCTOR_  upper case returned from /api/sys endpoint
- CONDUCTOR_  upper and lower case is returned from api/admin/config endpoint

The data returned from these endpoints also includes internal ip:port, service information, etc..

Tested against:
- v2.27.0
- v3.6.0 (latest)

### Nuclei Template:
```yaml
id: netflix-conductor-version

info:
  name: Netflix Conductor Version Detection
  author: c-sh0
  reference:
    - https://github.com/Netflix/conductor/blob/v1.6.0-rc1/ui/src/server.js#L17
    - https://github.com/Netflix/conductor/blob/v3.1.0/rest/src/main/java/com/netflix/conductor/rest/controllers/AdminResource.java#L42
    - /api/sys was removed  >= v3.1.0
  severity: info
  description: Obtain netflix conductor version information
  tags: tech,netflix,conductor,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/sys"
      - "{{BaseURL}}/api/admin/config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'application/json'

      - type: word
        part: body
        case-insensitive: true
        words:
          - 'CONDUCTOR_'

    extractors:
      - type: json
        json:
          - '.sys.version'

      - type: json
        json:
          - '.version'
```
![version](https://user-images.githubusercontent.com/25989137/155631874-1a054f29-6e2b-4ed0-b976-c412de318d8f.png)
