### ISSUE TITLE
RackN Digital Rebar provision UI detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3779]
### Template Information:
RackN Digital Rebar provision UI detection
- The ui endpoint always redirect to the single page app located at portal.rackn.io. (just to render it locally, All UI actions/requests go back to the host's API) 

Tested with multiple versions
https://registry.hub.docker.com/v1/repositories/digitalrebar/provision/tags
```
docker run -it --rm --net host index.docker.io/digitalrebar/provision:$TAG /bin/bash
```

### Nuclei Template:
```yaml
id: digitalrebar-provision-ui

info:
  name: RackN Digital Rebar provision UI detection
  author: c-sh0
  description: RackN Digital Rebar provision UI detection
  reference:
    - https://docs.rackn.io/
    - https://docs.rackn.io/en/latest/doc/server.html#ports
  severity: info
  tags: rackn,digitalrebar,webserver,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ui"

    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '<title>Digital Rebar</title>'
```
![dr-ui](https://user-images.githubusercontent.com/25989137/155815498-44ec9f84-a541-4e6c-bf0c-1115367a5f2a.png)
