### ISSUE TITLE
RackN Digital Rebar provision default login detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3780]
### Template Information:
RackN Digital Rebar provision default login detection
- X-Drp-*: header is always returned 

Tested with multiple versions
https://registry.hub.docker.com/v1/repositories/digitalrebar/provision/tags
```
docker run -it --rm --net host index.docker.io/digitalrebar/provision:$TAG /bin/bash
```
### Nuclei Template:
```yaml
id: digitalrebar-provision-default-login

info:
  name: RackN Digital Rebar provision default login
  author: c-sh0
  reference:
     - https://docs.rackn.io/en/latest/doc/faq-troubleshooting.html?#what-are-the-default-passwords
  severity: high
  tags: rackn,digitalrebar,default-login

requests:
  - raw:
      - |
        GET /api/v3/users HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic {{base64(username + ':' + password)}}

    payloads:
      username:
        - rocketskates
      password:
        - r0cketsk8ts
    attack: pitchfork

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'X-Drp-'

      - type: word
        part: body
        words:
          - 'Name'
          - 'Secret'
        condition: and
```
![dr-login](https://user-images.githubusercontent.com/25989137/155815803-3beb4f19-bdea-488c-84f8-1b9ff8ac32ad.png)
