### ISSUE TITLE
InfluxDB Version Detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3789]
### Template Information:
InfluxDB Version Detection via /ping endpoint 
- Extracts version from X-Influxdb-Version: header. 

Note: This header is retuned from any request made to the api. I'm not sure if this is the best way for version detection. However, the /ping endpoint always returns a 204 response and currently doesn't require authentication. Figured this might a good way to avoid a false positive? 

### Nuclei Template:
```yaml
id: influxdb-version

info:
  name: InfluxDB Version Detection
  author: c-sh0
  reference:
     - https://docs.influxdata.com/influxdb/v1.8/tools/api/#ping-http-endpoint
     - https://github.com/influxdata/influxdb/blob/master/http/platform_handler.go#L62
     - /ping endpoint always returns 204 status
     - verbose option was removed in later versions see commit f2898d199243ce45b9d7db65da165920d1b83fbb
  severity: info
  description: Obtain InfluxDB Version Information
  tags: tech,influxdb,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ping"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 204

      - type: word
        part: header
        words:
          - 'X-Influxdb-'

    extractors:
      - type: regex
        part: header
        group: 1
        regex:
          - "X-Influxdb-Version:.*([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
```
![influx-version](https://user-images.githubusercontent.com/25989137/155862480-fd98f252-95b7-4823-aa53-6ba77e9d4a25.png)
