### ISSUE TITLE
Jenkins - Version Detection

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3827]
### Template Information:
Jenkins Version Detection
- Uses the /whoAmI/ endpoint (trailing slash required, no auth required) 
- Pulls version from X-Jenkins header

### Nuclei Template:
```yaml
id: jenkins-version

info:
  name: Jenkins Version Detection
  author: c-sh0
  reference:
     - https://www.jenkins.io/doc/book/using/remote-access-api/#RemoteaccessAPI-DetectingJenkinsversion
     - https://github.com/jenkinsci/jenkins/pull/470
     - https://www.jenkins.io/doc/book/security/access-control/permissions/#access-granted-without-overallread
  severity: info
  description: Obtain Jenkins Version
  tags: tech,jenkins,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/whoAmI/"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'X-Jenkins:'

    extractors:
      - type: regex
        part: header
        group: 1
        regex:
          - "X-Jenkins:.*([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
```
![jenkins-version](https://user-images.githubusercontent.com/25989137/156613842-e9d3c690-4b0e-4a57-8c4d-4c4f517c1842.png)
