### ISSUE TITLE
Jenkins - CVE-2019-10405

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3828]
### Template Information:
CVE-2019-10405: 
Jenkins 2.196 and earlier, LTS 2.176.3 and earlier printed the value of the Cookie HTTP request header on the /whoAmI/ URL
- Cookie/JSESSIONID detection (no authentication required) 
- Trailing slash is needed (whoAmI/)

### Nuclei Template:
```yaml
id: CVE-2019-10405
info:
  name: Jenkins 2.196 and earlier, LTS 2.176.3 and earlier printed the value of the Cookie on the /whoAmI/ URL
  severity: medium
  author: c-sh0
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2019-10405
    - https://jenkins.io/security/advisory/2019-09-25/#SECURITY-1505
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 4.30
    cve-id: CVE-2019-10405
    cwe-id: CWE-200
  tags: cve,cve2019,jenkins,xss

requests:
  - raw:
      - |
        GET {{BaseURL}}/whoAmI/ HTTP/1.1
        Host: {{Hostname}}

      - |
        GET {{BaseURL}}/whoAmI/ HTTP/1.1
        Host: {{Hostname}}

    cookie-reuse: true
    matchers-condition: and
    matchers:
     - type: status
       status:
         - 200

     - type: word
       part: header
       words:
         - 'text/html'
         - 'X-Jenkins:'
       condition: and

     - type: word
       part: body
       words:
         - 'Cookie'
         - 'JSESSIONID'
       condition: and
```
**Detection**
![jenkins-cookie-exposed](https://user-images.githubusercontent.com/25989137/156617643-c2f75360-c9ac-42ec-ac91-9814767082e2.png)
![jenekins-cve](https://user-images.githubusercontent.com/25989137/156617694-631f5247-a1bd-4104-8c5a-4bfd14a98ca6.png)
----
**Fixed Version/Sample**

![jekins-fixed](https://user-images.githubusercontent.com/25989137/156617770-dcc57444-3785-411b-83e1-dd10095e7ef7.png)
