### ISSUE TITLE
Jenkins - CVE-2020-2103

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3829]
### Template Information:
CVE-2020-2103: 
Jenkins 2.218 and earlier, LTS 2.204.1 and earlier exposed session identifiers on a user's detail object in the whoAmI diagnostic page
- SessionId variable detection (no authentication required)
- Trailing slash required (whoAmI/)

### Nuclei Template:
```yaml
id: CVE-2020-2103
info:
  name: Jenkins 2.218 and earlier, LTS 2.204.1 and earlier exposed session identifiers on a user's detail object in the whoAmI diagnostic page.
  severity: medium
  author: c-sh0
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2020-2103
    - https://www.jenkins.io/security/advisory/2020-01-29/#SECURITY-1695
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 5.40
    cve-id: CVE-2020-2103
    cwe-id: CWE-200
  tags: cve,cve2020,jenkins,xss

requests:
  - raw:
      - |
        GET {{BaseURL}}/whoAmI/ HTTP/1.1
        Host: {{Hostname}}

      - |
        GET {{BaseURL}}/whoAmI/ HTTP/1.1
        Host: {{Hostname}}

    cookie-reuse: true
    matchers-condition: and
    matchers:
     - type: status
       status:
         - 200

     - type: word
       part: header
       words:
         - 'text/html'
         - 'X-Jenkins:'
       condition: and

     - type: word
       part: body
       words:
         - 'Cookie'
         - 'SessionId:'
       condition: and
```
**Detection** Note: SessionID is just null for Anon Users 
![damnit](https://user-images.githubusercontent.com/25989137/156623428-d8aa722d-0a86-4f8d-b8c9-f1d85da6335e.png)

![cve-2020](https://user-images.githubusercontent.com/25989137/156619876-3f3f47cf-1b1e-427b-b34f-0837ec7b2a86.png)

**Fixed Version Sample**
![jekins-fixed](https://user-images.githubusercontent.com/25989137/156619831-613a7ee6-f64e-405e-9da7-d239200763dc.png)
![fff](https://user-images.githubusercontent.com/25989137/156620216-78dbd1f0-37e0-4cd5-abdc-6fd848422210.png)
