### ISSUE TITLE
Swagger Version - 2.x  and under

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3830]
### Template Information:
Swagger UI 2.x and under, Extracts 2 values
- swagger-ui version 
- swagger-client version 

### Nuclei Template:
```yaml
id: swagger-version

info:
  name: Swagger 2.x Version Detection
  author: c-sh0
  reference:
     - Swagger UI 2.x and under
     - https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/version-detection.md
  severity: info
  description: Obtain Swagger Version
  tags: tech,swagger,api

requests:
  - method: GET
    path:
      - "{{BaseURL}}/swagger-ui/swagger-ui.js"
      - "{{BaseURL}}/swagger/swagger-ui.js"
      - "{{BaseURL}}/swagger-ui.js"
      - "{{BaseURL}}/swagger/ui/swagger-ui.js"

    matchers-condition: and
    matchers:
     - type: status
       status:
         - 200

    extractors:
     - type: regex
       part: body
       group: 1
       regex:
         - " @version (v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3})"
```
![swagger-version](https://user-images.githubusercontent.com/25989137/156627033-08cdfc6b-afaa-4d6b-b983-be6b252373be.png)
