### ISSUE TITLE
ElasticSearch Information Disclosure - Template Enhancement 

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3950]
### Template Information:

Elasticsearch version can be grabbed from `host:port/` 
- Add extractor to grab version (`/?pretty` arg)

### Nuclei Template:
misconfiguration/elasticsearch.yaml
```
requests:
  - method: GET
    path:
      - '{{BaseURL}}/?pretty'
      - '{{BaseURL}}/_cat/indices?v'
      - '{{BaseURL}}/_all/_search'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - '"You Know, for Search"'
          - '"took":'
          - 'status'
        condition: or

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '"number"\s:\s"([0-9.]+)"'
```
![version-info](https://user-images.githubusercontent.com/25989137/159330761-5881d8c3-4aa4-4c5a-a0fa-53f220cf1aad.png)
![elasticsearech-version](https://user-images.githubusercontent.com/25989137/159330146-84425e3e-db57-44e7-8237-b70ee0efb1d0.png)
