### ISSUE TITLE
liquibase spring boot Actuator

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#3969]
### Template Information:

https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#liquibase

### Nuclei Template:

```yaml
id: liquibase-spring-boot

info:
  name: Detect liquibase spring boot Actuator
  author: ELSFA7110
  severity: low
  description: the liquibase endpoint provides information about database changes
  tags: springboot,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/liquibase"
      - "{{BaseURL}}/actuator/liquibase"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "liquibase"
        condition: or
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
        condition: or
        part: header
```
