### ISSUE TITLE
scheduledtasks spring boot Actuator

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#3971]
### Template Information:

https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#scheduled-tasks

### Nuclei Template:

```yaml
id: scheduledtasks-spring-boot

info:
  name: Detect scheduledtasks spring boot Actuator
  author: ELSFA7110
  severity: low
  description: this endpoint to retrieve the scheduled tasks
  tags: springboot,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/actuator/scheduledtasks"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "cron"
          - "fixedDelay"
        condition: or
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
        condition: or
        part: header
```
