### ISSUE TITLE
flyway spring boot Actuator

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#3972]
### Template Information:

https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#flyway

### Nuclei Template:

```yaml
id: flyway-spring-boot

info:
  name: Detect flyway spring boot Actuator
  author: ELSFA7110
  severity: low
  description: this endpoint to retrieve the migrations
  tags: springboot,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/actuator/flyway"
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "flyway"
          - "flywayBeans"
        condition: or
      - type: status
        status:
          - 200
      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
        condition: or
        part: header
```
