### ISSUE TITLE
CVE-2022-0870

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#3982]
### Template Information:

Authenticated Server-Side Request Forgery (SSRF) in Gogs

https://huntr.dev/bounties/327797d7-ae41-498f-9bff-cc0bf98cf531/

If the port is open you will see : fatal: repository 'http://127.1.33.7:80/' not found
If the port is closed : fatal: unable to access 'http://127.1.33.7:3306/': Failed to connect to 127.1.33.7 port 3306: Connection refused

If not vulnerable, you will see : URL invalide

### Nuclei Template:

```yaml
id: CVE-2022-0870

info:
  name: Gogs - SSRF
  author: Akincibor
  severity: medium
  description: Server-Side Request Forgery (SSRF) in Gogs prior to 0.12.5.
  reference: https://huntr.dev/bounties/327797d7-ae41-498f-9bff-cc0bf98cf531/
  tags: cve,ssrf
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.30
    cve-id: CVE-2022-0870
    cwe-id: CWE-918

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        name: version
        internal: true
        group: 1
        regex:
          - '<div class="ui left">\n\s+© \d{4} Gogs Version: ([\d.]+) Page:'

      - type: regex
        group: 1
        regex:
          - '<div class="ui left">\n\s+© \d{4} Gogs Version: ([\d.]+) Page:'

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        part: body
        regex:
          - '<div class="ui left">\n\s+© \d{4} Gogs Version: ([\d.]+) Page:'

      - type: dsl
        dsl:
          - to_string(version) < "0.12.5"
```

[2022-03-25 18:33:06] [CVE-2022-0870] [http] [medium] https://REDACTED [0.11.91.0811]
