### ISSUE TITLE
CVE-2021-24746 - Reflected XSS though Sassy Social Share Wordpress plugin

### ISSUE THREAD

**Issue by supr4s** [projectdiscovery/nuclei-templates#4029]
### Template Information:

CVE-2021-24746 - Reflected XSS though Sassy Social Share Wordpress plugin

https://wpscan.com/vulnerability/99f4fb32-e312-4059-adaf-f4cbaa92d4fa

### Nuclei Template:

```yaml
id: CVE-2021-24746

info:
  name: WordPress Sassy Social Share Plugin - Reflected XSS
  author: Supras
  severity: medium
  description: WP plugin Sassy Social Share < 3.3.40 - Reflected Cross-Site Scripting
  reference: https://wpscan.com/vulnerability/99f4fb32-e312-4059-adaf-f4cbaa92d4fa
  tags: cve,cve2021,wordpress,wp-plugin,xss
  metadata:
    google-query: 'inurl:"/wp-content/plugins/sassy-social-share"'

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/sassy-social-share/readme.txt"

    extractors:
      - type: regex
        name: version
        internal: true
        group: 1
        regex:
          - "(?m)Stable tag: ([0-9.]+)"

      - type: regex
        group: 1
        regex:
          - "(?m)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "Sassy Social Share"
          - '== Changelog =='
        condition: and

      - type: dsl
        dsl:
          - to_string(version) < "3.3.40"


```

![CVE-POC](https://user-images.githubusercontent.com/34515269/161332617-8c3d4c71-8bed-4d4e-902a-48b3fa88d512.png)
