### ISSUE TITLE
[nuclei-template] Microsoft Azure - Domain Tenant ID

### ISSUE THREAD

**Issue by V0idC0de** [projectdiscovery/nuclei-templates#4119]
### Template Information:

Microsoft Azure offers discovery endpoints to provide information about domains using Azure as Identity Provider.
This can be used to extract the Azure Tenant ID this domain is in.
For example, this URL shows the Tenant ID of `office.com` as part of multiple URLs contained in the response.
https://login.microsoftonline.com/office.com/v2.0/.well-known/openid-configuration

### Nuclei Template:

```yaml
id: azure-domain-tenant-id

# Uses Azure configuration data to detect the Azure tenant ID of a domain
info:
  name: Microsoft Azure - Domain Tenant ID
  author: V0idC0de
  severity: info
  description: Checks if the domain is part of an Azure tenant and finds the ID using Azure's OpenID discovery page.
  tags: azure,microsoft,tenant,cloud,domain

self-contained: true
requests:
  - method: GET
    path:
      - "https://login.microsoftonline.com/{{domain}}/v2.0/.well-known/openid-configuration"

    matchers:
      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "\"https:\\/\\/login\\.microsoftonline\\.com\\/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"
```

**Output on success:**

```shell
root@kali:~# nuclei -t ./tenant.yaml -var domain=office.com -silent
[2022-04-12 13:54:24] [azure-domain-tenant-id] [http] [info] https://login.microsoftonline.com/office.com/v2.0/.well-known/openid-configuration [f8cdef31-a31e-4b4a-93e4-5f571e91255a]
```

**Example response from URL mention at the top (office.com):**

The matching should be pretty safe, if the endpoint returns a response, as I've never seen two different values for `login.microsoftonline.com/...` in a single response, thus the (frist) one that is found (usually the "token_endpoint" field) yields the correct ID.

```json
{
  "token_endpoint": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/token",
  "token_endpoint_auth_methods_supported":
    ["client_secret_post", "private_key_jwt", "client_secret_basic"],
  "jwks_uri": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/discovery/v2.0/keys",
  "response_modes_supported": ["query", "fragment", "form_post"],
  "subject_types_supported": ["pairwise"],
  "id_token_signing_alg_values_supported": ["RS256"],
  "response_types_supported":
    ["code", "id_token", "code id_token", "id_token token"],
  "scopes_supported": ["openid", "profile", "email", "offline_access"],
  "issuer": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/v2.0",
  "request_uri_parameter_supported": false,
  "userinfo_endpoint": "https://graph.microsoft.com/oidc/userinfo",
  "authorization_endpoint": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/authorize",
  "device_authorization_endpoint": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/devicecode",
  "http_logout_supported": true,
  "frontchannel_logout_supported": true,
  "end_session_endpoint": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/oauth2/v2.0/logout",
  "claims_supported":
    [
      "sub",
      "iss",
      "cloud_instance_name",
      "cloud_instance_host_name",
      "cloud_graph_host_name",
      "msgraph_host",
      "aud",
      "exp",
      "iat",
      "auth_time",
      "acr",
      "nonce",
      "preferred_username",
      "name",
      "tid",
      "ver",
      "at_hash",
      "c_hash",
      "email",
    ],
  "kerberos_endpoint": "https://login.microsoftonline.com/f8cdef31-a31e-4b4a-93e4-5f571e91255a/kerberos",
  "tenant_region_scope": "WW",
  "cloud_instance_name": "microsoftonline.com",
  "cloud_graph_host_name": "graph.windows.net",
  "msgraph_host": "graph.microsoft.com",
  "rbac_url": "https://pas.windows.net",
}
```

## Use Case

Companies might use multiple Azure Tenants or none at all. By checking the tenant ID of a domain (i.e. the domain their employees use for e-mail), we can infer whether they use Azure/O365 for that domain. If they do, it's very likely that their main domain is known at Azure, thus having this endpoint.

From a defensive perspective, checking all known domains of a company allows to find undocumented systems, i.e. developers setting up systems in an unknown subscription to "just test some thing", which poses quite a risk, if production data is involved or systems go from "just testing a couple things" to "this runs production now".

## Removing `self-contained: true`

As pointed out in [this Discord message](https://discord.com/channels/695645237418131507/700096242226692236/963387175792169031), this template might become usable with the target domain actually being entered with the target flag, instead of being passed as "domain=target.com", as soon as [Pull#1805](https://github.com/projectdiscovery/nuclei/pull/1805) is implemented.
