### ISSUE TITLE
False positive wp-woocommerce-email-verification.yaml

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4159]
### Nuclei Version:

Latest

### Template file:

wp-woocommerce-email-verification.yaml

### Anything else:

This is due to the matcher :

```yaml
      - type: dsl
        dsl:
          - 'status_code != 401'
          - 'status_code != 403'
        condition: or
```

If status code is 401 or 403 this matcher will be always true because condition is or so : 

if 401 : 'status_code != 401' = false and 'status_code != 403' = true ==> Valid
if 403 : 'status_code != 401' = true and 'status_code != 403' = false ==> Valid
