### ISSUE TITLE
[nuclei-template]  WordPress Avada (ThemeFusion) SSRF

### ISSUE THREAD

**Issue by MantisSTS** [projectdiscovery/nuclei-templates#4189]
### Template Information:

This is a template for the WordPress Avada (Theme-Fusion) theme SSRF found by @calumjelrick at Rootshell Security.

- https://www.rootshellsecurity.net/rootshell-discovered-a-critical-vulnerability-in-top-wordpress-theme/ 

### Nuclei Template:

```yaml
id: wordpress-avada-theme-ssrf

info:
  name: Wordpress Avada Theme (Fusion) SSRF
  author: MantisSTS,calumjelrick
  severity: High
  tags: wordpress,ssrf,fusion,themefusion,avada
  description: An SSRF vulnerability found by Calum Elrick (Rootshell Security) in the Theme-Fusion WordPress plugins

requests:
  - method: POST
  path:
    - "{{BaseURL}}/wp-admin/admin-ajax.php"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
    Accept-Language: "en-US,en;q=0.5"
    Accept-Encoding: "gzip, deflate"
    Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
    X-Requested-With: "XMLHttpRequest"
    Sec-Fetch-Dest: "empty"
    Sec-Fetch-Mode: "cors"
    Sec-Fetch-Site: "same-origin"
    Te: "trailers"
    Origin: "{{BaseURL}}"
    Referer: "{{RootURL}}/contact-us/"
    body: "action=fusion_form_update_view&form_id=1231451451"
  
  matchers:
    - type: word
  words:
    - "fusion-form-nonce-1231451451"
```

This is an indicator of vulnerability rather than specifically exploiting the issue. However, you could make a workflow to grab the token nonce and then create a second request to the server exploiting the SSRF.
