### ISSUE TITLE
CVE-2021-25111

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4259]
```yaml
id: CVE-2021-25111

info:
  name: English WordPress Admin < 1.5.2 - Unauthenticated Open Redirect
  author: akincibor
  severity: low
  description: The plugin does not validate the admin_custom_language_return_url before redirecting users o it, leading to an open redirect issue.
  reference:
    - https://wpscan.com/vulnerability/af548fab-96c2-4129-b609-e24aad0b1fc4
  tags: wp-plugin,redirect,wordpress,wp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/admin-ajax.php?action=heartbeat&admin_custom_language_toggle=1&admin_custom_language_return_url=https://example.com"

    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$'
        part: header
```
