### ISSUE TITLE
CVE-2022-0165

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4284]
```yaml
id: CVE-2022-0165

info:
  name: Page Builder KingComposer <= 2.9.6 - Open Redirect
  author: akincibor
  severity: low
  description: The plugin does not validate the id parameter before redirecting the user to it via the kc_get_thumbn AJAX action available to both unauthenticated and authenticated users.
  reference:
    - https://wpscan.com/vulnerability/906d0c31-370e-46b4-af1f-e52fbddd00cb
  tags: wp-plugin,redirect,wordpress,wp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wp-admin/admin-ajax.php?action=kc_get_thumbn&id=https://example.com"

    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$'
        part: header
```
