### ISSUE TITLE
Oracle E-Business Login Panel That Allowed To Access For All Employees Information's 

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#4401]
### Nuclei Template:

```yaml
id: oracle

info:
  name: oracle_logic
  author: 3th1c_yuk1
  description: Oracle E-Business Login Panel That Allowed To Access For All Employees Information's & In Some cases Passwords At More Than 1000 Companies
  severity: high
  reference: https://orwaatyat.medium.com/my-new-discovery-in-oracle-e-business-login-panel-that-allowed-to-access-for-all-employees-ed0ec4cad7ac

requests:
  - method: GET
    path:
      - "{{BaseURL}}/OA_HTML/ibeCAcpSSOReg.jsp"

    matchers-condition: and
    matchers:

      - type: status
        status:
          - 200

      - type: word
        words:
          - "Register as individual"
```
