### ISSUE TITLE
Xyxel-Firewall Panel

### ISSUE THREAD

**Issue by 0x240x23elu** [projectdiscovery/nuclei-templates#4423]
```yaml
id: xyxel-firewall

info:
  name: Xyxel-Firewall Exposure
  author: 0x240x23elu
  severity: info
  tags: panel,xyxel,firewall

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - "USG FLEX"
          - "mode_ana"	
        part: body
        condition: and
```
