### ISSUE TITLE
[nuclei-template] Selenium Grid

### ISSUE THREAD

**Issue by w0Tx** [projectdiscovery/nuclei-templates#4455]
### Template Information:

This template has been made to detect Selenium Grid directly exposed without any authentication. The first exploit that can be made is an LFI. But if you are lucky enough and Chromium is configured on the remote Grid, you'll be able to do some RCE.

It is possible by using the command argument "--utility-cmd-prefix=" which will be executed before the start of chromium binary.

This template aims at finding "/wd/hub" which is the endpoint needed to submit data, and also look for the keyword "WebDriverRequest".

### Nuclei Template:

```yaml
id: selenium-exposure

info:
  name: Selenium Node exposure
  author: w0Tx
  severity: high
  description: If a Selenium Node is exposed without any form of authentication, RCE could be possible if chromium is configured. By default the port is 4444, still, most of the internet facing are done through reverse proxies.
  reference: 
    - https://nutcrackerssecurity.github.io/selenium.html
    - https://labs.detectify.com/2017/10/06/guest-blog-dont-leave-your-grid-wide-open/
  tags: selenium,misconfiguration,rce,chromium

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wd/hub"
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - 'WebDriverRequest'
```
