### ISSUE TITLE
Jupyter-notebook dashboard access

### ISSUE THREAD

**Issue by hakimkt** [projectdiscovery/nuclei-templates#4467]
# Create Jupyter-notebook dashboard access

```yaml
id: jupyter-notebook

info:
  name: Jupyter Notebook
  author: hakimkt
  severity: info
  tags: jupyter-notebook

requests:
  - method: GET
    path:
      - "{{BaseURL}}/jupyter/login"
      - "{{BaseURL}}/jupyter/tree"
      - "{{BaseURL}}/jupyter/lab"
      - "{{BaseURL}}/jupyter/hub/lti/launch"
      
    matchers:
      - type: word
        words:
          - '/jupyter/static/base/images/logo.png'
          - '/jupyter/hub/logo'
        condition: or
```
