### ISSUE TITLE
CVE-2019-12922

### ISSUE THREAD

**Issue by v4yne1** [projectdiscovery/nuclei-templates#4521]
### Template Information:

This one is similar to already existing template [CVE-2019-12616](https://github.com/projectdiscovery/nuclei-templates/blob/5bbb03725f01792ff98a601191889434b8449af3/cves/2019/CVE-2019-12616.yaml)

**phpMyAdmin <= 4.9.0.1** is vulnerable to **CSRF** attack via **CVE-2019-12922**

Regex is bad, someone fix it pls 😂 

References:

https://nsfocusglobal.com/phpmyadmin-cross-site-request-forgery-vulnerability-cve-2019-12922-threat-alert/
https://www.exploit-db.com/exploits/47385
https://nvd.nist.gov/vuln/detail/CVE-2019-12922

### Nuclei Template:

```yaml
id: CVE-2019-12922

info:
  name: phpMyAdmin CSRF
  author: v4yne1
  severity: medium
  description: A vulnerability was found that allows an attacker to trigger a CSRF attack against a phpMyAdmin user. The attacker can easily create a fake hyperlink containing the request that wants to execute on behalf the user, doing a CSRF attack due the use of wrong HTTP method. Example (http://victim.com/phpmyadmin/setup/index.php?page=servers&mode=remove&id=1) to delete main server.
  reference:
    - https://nsfocusglobal.com/phpmyadmin-cross-site-request-forgery-vulnerability-cve-2019-12922-threat-alert/
    - https://www.exploit-db.com/exploits/47385
    - https://hackerone.com/reports/1113212
    - https://nvd.nist.gov/vuln/detail/CVE-2019-12922
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N
    cvss-score: 6.5
    cve-id: CVE-2019-12922
    cwe-id: CWE-352
  tags: cve,cve2019,phpmyadmin,csrf

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "phpmyadmin.net"
          - "phpMyAdmin"
        condition: or

      - type: regex
        regex:
          - 'v=[1-4]\.[0-9]\.'  # Fixed in 4.9.1

      - type: status
        status:
          - 200
          - 401  # password protected
```
