### ISSUE TITLE
Add more payloads to open-redirect.yaml

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4552]
```yaml
    payloads:
      redirect:
        - ?next=http://example.com
        - ?url=http://example.com
        - ?target=http://example.com
        - ?rurl=http://example.com
        - ?dest=http://example.com
        - ?destination=http://example.com
        - ?redir=http://example.com
        - ?redirect_uri=http://example.com
        - ?redirect_url=http://example.com
        - ?redirect=http://example.com
        - redirect/example.com
        - cgi-bin/redirect.cgi?example.com
        - out?example.com
        - ?view=http://example.com
        - login?to=http://example.com
        - ?image_url=http://example.com
        - ?go=http://example.com
        - ?return=http://example.com
        - ?returnTo=http://example.com
        - ?return_to=http://example.com
        - ?checkout_url=http://example.com
        - ?continue=http://example.com
        - ?return_path=http://example.com
```
