### ISSUE TITLE
ManageEngine ADSelfService Plus XSS CVE-2022-24681

### ISSUE THREAD

**Issue by Open-Sec** [projectdiscovery/nuclei-templates#4576]
```yaml
id: CVE-2022-24681

info:
  name: ManageEngine ADSelfService XSS
  author: Open-Sec
  severity: medium
  reference: CVE-2022-24681 https://raxis.com/blog/cve-2022-24681
  description : There is a XSS (stored, post authentication) vulnerability in ManageEngine ADSelfService in build versions less than 6121.
  tags: manageengine,xss,cve2022

requests:
  - raw:
    - |
      POST /servlet/GetProductVersion HTTP/1.1
      Host: {{Hostname}}

    extractors:
      - type: json
        part: body
        internal: true
        name: buildnumber
        json:
          - '.BUILD_NUMBER'

    matchers:
      - type: dsl
        part: body
        dsl:
          - compare_versions(buildnumber, '< 6121')
```
