### ISSUE TITLE
Enhancement of interactsh templates

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei-templates#4745]
### Please describe your feature request:
There are multiple templates containing `{{interactsh-url}}` and only one matcher that confirms the dns/http callback from the server, but many honeypots just send the request to the interact server, leading to false-positive results.

If possible, we can add additional matchers, such as a word or status code from the vulnerable request's response. Additionally, we can add the following matcher to confirm the user agent or any string in the request received by the interact server.

```
      - type: word
        part: interactsh_request
        words:
          - "ShibbolethIdp"
```

### Describe the use case of this feature:

- Template enhancement
- Prevents false positives results
