### ISSUE TITLE
CVE-2022-2274

### ISSUE THREAD

**Issue by Facucuervo87** [projectdiscovery/nuclei-templates#4775]
### Template Information:

CVE-2022-2274

### Nuclei Template:

```yaml
id: OpenSSL-Heap_Memory_Corruption_CVE-2022-2274

info:
  name: Openssl Heap Memory Corruption (CVE-2022-2274)
  author: h4kux
  severity: critical
  description: The OpenSSL 3.0.4 release introduced a serious bug in the RSA implementation for X86_64 CPUs supporting the AVX512IFMA instructions. This issue makes the RSA implementation with 2048 bit private keys incorrect on such machines and memory corruption will happen during the computation. As a consequence of the memory corruption an attacker may be able to trigger a remote code execution on the machine performing the computation. SSL/TLS servers or other servers using 2048 bit RSA private keys running on machines supporting AVX512IFMA instructions of the X86_64 architecture are affected by this issue. 
  tags: tech, cve
  reference:
    - https://github.com/openssl/openssl/issues/18625
    - https://www.openssl.org/news/secadv/20220705.txt
    - https://nvd.nist.gov/vuln/detail/CVE-2022-2274
  classification:
    cve-id: CVE-2022-2274
    cwe-id: CWE-787
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:

      - type: regex
        part: header
        regex:
          - "OpenSSL/3.0.4"

      - type: status
        status:
          - 200

    extractors:
      - type: kval
        part: header
        kval:
          - Server

```
