### ISSUE TITLE
Unauth SmartPing Dashboard

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei-templates#4803]
### Nuclei Template:

```yaml
id: smartping-dashboard

info:
  name: Unauth SmartPing Dashboard
  author: DhiyaneshDk
  severity: low
  metadata:
    verified: true
    shodan-query: title:"SmartPing Dashboard"
  tags: misconfig,unauth

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config.html"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '<title>SmartPing Dashboard</title>'
        part: body
      - type: word
        words:
          - 'text/html'
        part: header
```
