### ISSUE TITLE
Create rustici-content-controller.yaml

### ISSUE THREAD

**Issue by DhiyaneshGeek** [projectdiscovery/nuclei-templates#4811]
### Nuclei Template:

```yaml
id: rustici-content-controller

info:
  name: Rustici Content Controller
  author: DhiyaneshDk
  severity: info
  metadata:
    verified: true
    shodan-query: title:"Rustici Content Controller"
  tags: panel,rustici

requests:
  - method: GET
    path:
      - "{{BaseURL}}/#!/auth/signIn"

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - '<title>Rustici Content Controller</title>'

      - type: status
        status:
          - 200
```
