### ISSUE TITLE
roxy fileman detection

### ISSUE THREAD

**Issue by liquidsec** [projectdiscovery/nuclei-templates#4910]
### Template Information:

Older versions of roxy fileman have several serious security vulnerabilities:
https://www.cvedetails.com/vulnerability-list/vendor_id-18324/product_id-46688/Roxyfileman-Roxy-Fileman.html

This template should reliably detect multiple versions of the utility (asp.net/php) 

Even if a non-vulnerable version is detected, it's presence has value for situational awareness (knowledge that the application contains a file upload utility)

### Nuclei Template:

```yaml

id: roxyfileman-detect

info:
  name: Roxy Fileman Detect
  author: liquidsec
  severity: info
  description: Older versions of roxy fileman have several serious security vulnerabilities 
  reference:
    - https://packetstormsecurity.com/files/155666/Roxy-Fileman-1.4.5-For-.NET-Directory-Traversal.html
    - https://www.exploit-db.com/exploits/46085
    - https://nvd.nist.gov/vuln/detail/CVE-2018-20525
    - https://nvd.nist.gov/vuln/detail/CVE-2018-20526
  tags: tech,fileupload

requests:

  - method: GET
    path:
      - "{{BaseURL}}/fileman/index.html"

    redirects: true
    max-redirects: 2
    matchers:
      - type: word
        words:
          - "RoxyFileman.com"


  - method: GET
    path:
      - "{{BaseURL}}/fileman/php/fileslist.php"

    redirects: true
    max-redirects: 2
    matchers:
      - type: word
        words:
          - "[{\"p\""

  - method: GET
    path:
      - "{{BaseURL}}/fileman/asp_net/main.ashx"


    redirects: true
    max-redirects: 2
    matchers:
      - type: word
        words:
          - "[{\"p\""

```

Example data:

* fileman/index.html

```
<html>
<body>
<!--StartFragment-->

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <!--
  | RoxyFileman - web based file manager. Ready to use with CKEditor, TinyMCE.
  | Can be easily integrated with any other WYSIWYG editor or CMS.
  |  
  | Copyright (C) 2013, RoxyFileman.com - Lyubomir Arsov. All rights reserved.
  | For licensing, see LICENSE.txt or http://RoxyFileman.com/license
  |  
  | This program is free software: you can redistribute it and/or modify
  | it under the terms of the GNU General Public License as published by
  | the Free Software Foundation, either version 3 of the License.
  |  
  | This program is distributed in the hope that it will be useful,
  | but WITHOUT ANY WARRANTY; without even the implied warranty of
  | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  | GNU General Public License for more details.
  |  
  | You should have received a copy of the GNU General Public License
  | along with this program.  If not, see <http://www.gnu.org/licenses/>.
  |  
  | Contact: Lyubomir Arsov, liubo (at) web-lobby.com
  | -->
  | <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  | <title>Roxy file manager</title>
  | <link href="css/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" type="text/css" />
  | <link href="css/main.min.css" rel="stylesheet" type="text/css" />
  | <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  | <script type="text/javascript" src="js/jquery-ui-1.10.4.custom.min.js"></script>
  | <script type="text/javascript" src="js/custom.js"></script>
  | <script type="text/javascript" src="js/main.min.js"></script>
  | <script type="text/javascript" src="js/jquery-dateFormat.min.js"></script>
  | </head>

<!--EndFragment-->
</body>
</html>


<!DOCTYPE html>
<html>
<head>
<!--
  RoxyFileman - web based file manager. Ready to use with CKEditor, TinyMCE. 
  Can be easily integrated with any other WYSIWYG editor or CMS.

  Copyright (C) 2013, RoxyFileman.com - Lyubomir Arsov. All rights reserved.
  For licensing, see LICENSE.txt or http://RoxyFileman.com/license

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Contact: Lyubomir Arsov, liubo (at) web-lobby.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Roxy file manager</title>
<link href="[css/jquery-ui-1.10.4.custom.min.css](http://192.168.58.130/fileman/css/jquery-ui-1.10.4.custom.min.css)" rel="stylesheet" type="text/css" />
<link href="[css/main.min.css](http://192.168.58.130/fileman/css/main.min.css)" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="[//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js](http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js)"></script>
<script type="text/javascript" src="[js/jquery-ui-1.10.4.custom.min.js](http://192.168.58.130/fileman/js/jquery-ui-1.10.4.custom.min.js)"></script>
<script type="text/javascript" src="[js/custom.js](http://192.168.58.130/fileman/js/custom.js)"></script>
<script type="text/javascript" src="[js/main.min.js](http://192.168.58.130/fileman/js/main.min.js)"></script>
<script type="text/javascript" src="[js/jquery-dateFormat.min.js](http://192.168.58.130/fileman/js/jquery-dateFormat.min.js)"></script>
</head>

```
* main.ashx / fileslist.php

```
 [{"p":"/Uploads","f":"0","d":"24"},{"p":"/Uploads/test.txt","f":"0","d":"3"}]
```

**Comment by ehsandeep** [comment]
@liquidsec, thank you for sharing this,  this template can be simplified with something like shared below, let me know if this works for you?

```yaml
id: roxyfileman-detect

info:
  name: Roxy Fileman Detect
  author: liquidsec
  severity: info
  description:
    Older versions of roxy fileman have several serious security vulnerabilities.
  reference:
    - https://packetstormsecurity.com/files/155666/Roxy-Fileman-1.4.5-For-.NET-Directory-Traversal.html
    - https://www.exploit-db.com/exploits/46085
    - https://nvd.nist.gov/vuln/detail/CVE-2018-20525
    - https://nvd.nist.gov/vuln/detail/CVE-2018-20526
  tags: tech,fileupload,roxy,fileman

requests:
  - method: GET
    path:
      - "{{BaseURL}}/fileman/index.html"
      - "{{BaseURL}}/fileman/php/fileslist.php"
      - "{{BaseURL}}/fileman/asp_net/main.ashx"

    redirects: true
    max-redirects: 2
    matchers:
      - type: word
        words:
          - 'RoxyFileman.com'
          - '"p":"'
        condition: or
```
