### ISSUE TITLE
[nuclei-template] ClearCom CCM Detect

### ISSUE THREAD

**Issue by fail-open** [projectdiscovery/nuclei-templates#5252]
### Template Information:

Basic tech detect for a clearcom ccm login page
https://www.clearcom.com/DownloadCenter/manuals/FreeSpeakII_Online_Manual/UserGuide/Content/Base/CCM/CCM.htm

### Nuclei Template:

```yaml
id: ccm-detect

info:
  name: ClearCom Core Configuration Manager (CCM)Detect
  author: failOpen
  severity: info
  tags: tech,clearcom,ccm

requests:
- raw:
  - |+
    GET / HTTP/1.1
    Host: {{Hostname}}



  matchers-condition: and
  matchers:
  - type: word
    part: body
    words:
    - CCM - Authentication Failure
  - type: status
    status:
    - 401

```

[ccm-detect] [http] [info] https://snip

HTTP/1.1 401 Unauthorized
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
WWW-Authenticate: Digest realm="CCM", nonce="snip", qop="auth",opaque=""
Cache-Control: private, no-cache, no-store, must-revalidate
Expires: -1
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Content-Length: 1769
ETag: snip
Date: Tue, 30 Aug 2022 12:05:21 GMT
Connection: close

<html>
    <head>
        <title>CCM - Authentication Failure</title>
        <style type="text/css">
            body {
                margin: 0px;
                padding: 0px;
                color: #ccc;
                background: #333;
            }

            p {
                padding-left: 40px;
                margin-bottom: 10px;
            }

            p.logo {
                width: 100%;
                background: #ccc;
                padding-top: 10px;
                padding-bottom: 10px;
            }

            button {
                text-align: center;
                margin: 0 auto;
                width:250px;
                color: black;
                background-color: white;
            }
        </style>
        <script>

        </script>
    </head>

    <body>
        <p class="logo"><img src="/images/logo-full.png"/></p>
        <br>
        <h1>Authentication failure</h1>
        <p>You must supply the CCM username and password before being allowed access.</p>
        
            <p>If you have not set a password on this unit before, the default password will be available on the back of the unit in the mDNS name: CC-E-IPA-<b><font color="red">PASSWORD</font></b>.</p>
            <p>For example, if your mDNS name is CC-E-IPA-<b><font color="red">12345678</font></b>, your CCM password will be <b><font color="red">12345678</font></b>.</p>
            <p>If you still cannot access the unit or have forgotten the password, you can reset the password back to default by pressing and holding the reset button 30 seconds or changing the password from EHX.</p>
        

        <br>
        <button onclick="window.location.reload(true)">
            Click to try again
        </button>
    </body>
</html>
