### ISSUE TITLE
broken link hikacking

### ISSUE THREAD

**Issue by Sabeesh89** [projectdiscovery/nuclei-templates#5286]
```yaml
id: BrokenLinkHijacking
info:
  name: Broken Link Hijacking Template
  author: sabeesh (Indira)
  severity: low

requests:
    - method: GET
      path:
        - "https://facebook.com/{{Host}}"
        - "https://instagram.com/{{Host}}"
        - "https://twitter.com/{{Host}}"
 matchers:
      - type: regex
        regex:
          - "This Page is not available"
          - "This account doesnt exist"
          - "page doesn't exist"
          - "page may have been removed"
```

**Comment by davidfegyver** [comment]
Hey! As far as I know, Facebook and Instagram uses react.js - client side rendering, in this way this template could never trigger. 

Second issue is that this would create a lot of noise and false positives, as a broken link hijacking is only a broken link hijacking when the website has a link pointing to the url you can hijack :D This template does not check if the hijackable link is present on the host.

**Comment by davidfegyver** [comment]
A template for this vulnerability type might also generate high traffic on 3rd party sites, which a hunter might not want :/ 

Others please share your thoughts, get some pros and contras about such a template :D

**Comment by akincibor** [comment]
I agree with @davidfegyver 

I have my own template but facebook and instagram didn't work since last month, you can't access instagram unauth anymore. For twitter, I'm using their API :

```yaml
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    headers:
      Authorization: Bearer {{REDACTED}}

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "https://api.twitter.com/2/problems/invalid-request"
          - "Could not find user with username:"
        condition: or
      - type: status
        status:
          - 400
```
