### ISSUE TITLE
Automatic syntax checker

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei-templates#56]
We need to automate the syntax checking for newly added YAML files in the pull request.

**Comment by EdOverflow** [comment]
You can integrate [Travis CI](https://travis-ci.org/) and run [yamllint](https://github.com/adrienverge/yamllint) for each pull request. You can then include a custom linting configuration as described in https://yamllint.readthedocs.io/en/stable/configuration.html.

```yaml
language: python
python: "3.8"

install:
    - pip install --user yamllint
scripts:
    - yamllint .
```
