### ISSUE TITLE
[nuclei-template] Wordpress User Enumeration

### ISSUE THREAD

**Issue by densi97** [projectdiscovery/nuclei-templates#5603]
### Template Information:

Wordpress user enumeration using `/wp-json/wp/v2/users/` endpoint.

### Nuclei Template:

```yaml
id: wordpress-wpjson-user-enum

info:
  name: Wordpress wp-json User Enumeration
  author: densi97
  severity: info
  tags: wordpress,enum

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-json/wp/v2/users/'
    redirects: true

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "slug"

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
            - '"slug":"(.*?)",'
```
