### ISSUE TITLE
loqate-api-key Template

### ISSUE THREAD

**Issue by realexp3rt** [projectdiscovery/nuclei-templates#5666]
### Template Information:
This is a template to detect Loqate api keys

### Nuclei Template:

```yaml
id: loqate-api-key

info:
  name: Loqate API Key
  author: realexp3rt
  severity: low
  tags: exposure,token,loqate

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - "[A-Z]{2}[0-9]{2}-[A-Z]{2}[0-9]{2}-[A-Z]{2}[0-9]{2}-[A-Z]{2}[0-9]{2}"
```

![loqate](https://user-images.githubusercontent.com/50926987/195645909-4b944ad1-3ee4-410c-858d-f9edbd59d05d.jpg)
