### ISSUE TITLE
Oracle ATG Commerce Detect

### ISSUE THREAD

**Issue by fail-open** [projectdiscovery/nuclei-templates#5669]
### Template Information:
Shodan Samples https://www.shodan.io/search?query=Oracle+ATG

### Nuclei Template:

```yaml
id: oracle-atg-commerce

info:
  name: Detect Oracle ATG Commerce Platform
  author: Dale Clarke
  severity: info
  tags: tech,oracle,ATG

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: or
    matchers:
      - type: word
        part: header
        words:
          - x-atg-version
          - X-Atg-Version
          - atg_session_id
          - ATG_SESSION_ID

```

[2022-10-13 19:40:26] [oracle-atg-commerce] [http] [info] https://www.redacted.com

HTTP/1.1 200 OK
Date: Thu, 13 Oct 2022 04:16:31 GMT
Server: Apache/2.2.15 (Oracle)
Cache-Control: no-cache
Pragma: no-cache
Expires: Tue, 04 Dec 1993 21:29:02 GMT
X-ATG-Version: version=QVRHUGxhdGZvcm0vMTEuMg==
Set-Cookie: JSESSIONID=redact-SkonZVZd564HIhUg!-805347703; path=/; HttpOnly
Vary: User-Agent,Accept-Encoding
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
