### ISSUE TITLE
context deadline exceeded error

### ISSUE THREAD

**Issue by testjeevi** [projectdiscovery/nuclei-templates#6050]
I have installed Nuclei latest version 2.7.9
 While running valid customized template, facing this error in Nuclei execution

[WRN] [template-id] Could not execute request for https://hostname:443 context deadline exceeded

**Comment by DhiyaneshGeek** [comment]
@testjeevi try to use -timeout flag and see if it works ,

If the response body is huge this error occurs, feel free to reach us out in discord 👍

**Comment by testjeevi** [comment]
Hi.. Tried with -timeout flag. PFA same issue exists in both nuclei execution and in Burp Nuclei extender 
![image](https://user-images.githubusercontent.com/115452811/201647380-5999df14-f86e-4dac-9e7a-27d8a5acf799.png)

Please assist me on this

**Comment by DhiyaneshGeek** [comment]
i can see the template works for me 

`nuclei -u https://demo.testfire.net -t test.yaml -vv`

![image](https://user-images.githubusercontent.com/24750220/201648396-6d053470-ae74-444a-8df8-56e485d4e42b.png)

**Comment by testjeevi** [comment]
![image](https://user-images.githubusercontent.com/115452811/201651849-ab507d9a-b368-4ce3-b9ef-173fc5ca862b.png)
Could you please suggest to troubleshoot "this context deadline exceeded " error which I am facing in both nuclei cmd and in burp extensions

**Comment by ehsandeep** [comment]
@testjeevi please share the textual version of the template you created using nuclei burp plugin.

**Comment by testjeevi** [comment]
Attached the textual version for the reference.

FYI- Issue exists not for this particular template only. As a beginner, same issue persists for any new custom template creation. Kindly advice.

id: template-id

info:
  name: Template Name
  author: sample
  severity: info
  description: description
  reference:
    - https://
  tags: tags

requests:
  - raw:
      - |+
        GET /login.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
        Referer: https://demo.testfire.net/login.jsp
        
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - Apache-Coyote/1.1
      - type: status
        status:
          - 200

**Comment by DhiyaneshGeek** [comment]
@testjeevi i tried replication at my end, found the template is working fine 

```yaml
id: template-id

info:
  name: Template Name
  author: sample
  severity: info
  description: description
  reference:
    - https://
  tags: tags

requests:
  - raw:
      - |+
        GET /login.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
        Referer: {{BaseURL}}/login.jsp
        
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - Apache-Coyote/1.1
      - type: status
        status:
          - 200
```
![image](https://user-images.githubusercontent.com/24750220/201885226-58f0704b-f5a5-4ef0-b7b5-4f166441a26f.png)
