### ISSUE TITLE
manageengine-servicedesk-plus-user-enumeration

### ISSUE THREAD

**Issue by lopesg** [projectdiscovery/nuclei-templates#6074]
### Template Information

Version 9.0 and below of ManageEngine ServiceDesk allow an unauthenticated attacker to request the “AJaxDomainServlet” script to enumerate arbitrary usernames and domains. If the user does not exist, the servers replies with the `null` value. If the user exists, the servers returns the domain name where the user belongs. This issue was fixed on version 9.0 Build 9031.

For this template, I choosed to test a non existant user. If the server returns `null`, a vulnerable version is used.
The template only tests the unauthenticated issue.

### Nuclei Template

```yaml
id: manageengine-servicedesk-plus-user-enumeration

info:
  name: ManageEngine ServiceDesk Plus User Enumeration Vulnerability
  author: Guillaume Lopes
  severity: info
  description: ManageEngine ServiceDesk Plus is vulnerable to unauthenticated user enumeration. The application returns the domain name if the user specified on the search parameter exists.
  reference:
    - https://www.tenable.com/plugins/nessus/86444
    - https://www.rewterz.com/vulnerabilities/manageengine-servicedesk-plus-user-enumeration-vulnerability
    - https://www.exploit-db.com/exploits/35891
  classification:
    cvss-metrics: CVSS:2/AV:N/AC:L/Au:N/C:P/I:N/A:N
    cvss-score: 5
  tags: manageengine,enumeration,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/domainServlet/AJaxDomainServlet?action=searchLocalAuthDomain&search=nonexistant"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'null'

      - type: status
        status:
          - 200
```
