### ISSUE TITLE
xss_serialize_javascript

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6321]
### Template Information:

Untrusted user input reaching `serialize-javascript` with `unsafe` attribute can cause Cross Site Scripting (XSS).

### Nuclei Template:

```yaml
id: xss_serialize_javascript

info:
  name: xss_serialize_javascript
  description: Untrusted user input reaching `serialize-javascript` with `unsafe` attribute can cause Cross Site Scripting (XSS).
  reference: cwe-80
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        name: match
        regex:
                - "\\$S = require\\('serialize-javascript'\\)"
                - "\\$S\\(..., {unsafe: true}\\)"

        condition: or

      - type: regex
        negative: true
        name: inverse
        regex:
                - "escape\\(...\\)"
                - "encodeURI\\(...\\)"
```
