### ISSUE TITLE
express_xss

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6322]
### Template Information:

Untrusted User Input in Response will result in Reflected Cross Site Scripting Vulnerability.

### Nuclei Template:

```yaml
id: express_xss

info:
  name: express_xss
  description: Untrusted User Input in Response will result in Reflected Cross Site Scripting Vulnerability.
  reference: cwe-79
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: INFO

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "function \\($REQ, $RES, ...\\) {...}"
                - "function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}"
                - "\\$X = function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}"
                - "var \\$X = function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}\\;"
                - "\\$APP\\.\\$METHOD\\(..., function \\$FUNC\\(\\$REQ, \\$RES, ...\\)"
                - "\\$RES\\.write\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$RES\\.write\\(..., <... \\$REQ\\.\\$QUERY\\.\\$FOO ...>, ...\\)"
                - "\\$RES\\.send\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$RES\\.send\\(..., <... \\$REQ\\.\\$QUERY\\.\\$FOO ...>, ...\\)"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "\\$RES\\.write\\(..., <... $LOCALVAR ...>, ...\\)"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY\\.\\$FOO ...>\\;"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "var {\\$LOCALVAR} = <... \\$REQ\\.\\$QUERY\\.\\$FOO ...>\\;"
                - "\\$RES\\.write\\(..., <... \\$LOCALVAR ...>, ...\\)"
                - "var {\\$LOCALVAR} = <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>\\;"
                - "\\$RES\\.send\\(..., <... \\$LOCALVAR ...>, ...\\)"
                - "var {\\$LOCALVAR} = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "\\$LOCALVAR = {\\$KEY: <... \\$REQ\\.\\$QUERY ...>}\\;"
                - "\\$LOCALVAR =  {\\$KEY: <... \\$REQ\\.\\$QUERY\\.\\$FOO ...>}\\;"
                - "\\$LOCALVAR = {\\$KEY: <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>}\\;"
                - "\\$LOCALVAR =  {\\$KEY: <... \\$REQ\\.\\$QUERY ...>}\\;"
                - "\\$LOCALVAR\\.push\\(<... \\$REQ\\.\\$QUERY ...>\\)"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "\\$ARR\\.push\\(<... \\$LOCALVAR ...>\\)"
                - "\\$RES\\.write\\(..., <... \\$ARR ...>, ...\\)"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "\\$RES\\.send\\(..., <... \\$ARR ...>, ...\\)"
                - "\\$RES\\.write\\(..., <... \\$OUT ...>, ...\\)"
                - "\\$LOCALVAR = <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>\\;"
                - "\\$OUT = <... \\$LOCALVAR ...>\\;"
```
