### ISSUE TITLE
xss_disable_mustache_escape

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6323]
### Template Information:

Markup escaping disabled. This can be used with some template engines to escape disabling of HTML entities, which can lead to XSS attacks.

### Nuclei Template:

```yaml
id: xss_disable_mustache_escape

info:
  name: xss_disable_mustache_escape
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  description: Markup escaping disabled. This can be used with some template engines to escape disabling of HTML entities, which can lead to XSS attacks.
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "\\$OBJ\\.escapeMarkup = false"
```
