### ISSUE TITLE
admzip_path_overwrite

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6324]
### Template Information:

Insecure ZIP archive extraction using adm-zip can result in arbitrary path over write and can result in code injection.

### Nuclei Template:

```yaml
id: admzip_path_overwrite

info:
  name: admzip_path_overwrite
  description: Insecure ZIP archive extraction using adm-zip can result in arbitrary path over write and can result in code injection.
  reference: cwe-22
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "\\$X = require\\('adm-zip'\\)"
                - "\\$ZIPENTZ\\.forEach\\(function \\$FUNC\\(\\$ENTRY, ...\\) {"
                - "\\$FS\\.createWriteStream\\(...\\) }, ...\\)"
                - "\\$FS\\.writeFile\\(...\\)"
                - "\\$FS\\.writeFileSync\\(...\\) }, ...\\)"
```
