### ISSUE TITLE
express_lfr

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6325]
### Template Information:

Untrusted user input in express render() function can result in arbitrary file read if hbs templating is used.

### Nuclei Template:

```yaml
id: express_lfr

info:
  name: express_lfr
  description: Untrusted user input in express render() function can result in arbitrary file read if hbs templating is used.
  reference: cwe-23
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "$INP = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "$RES\\.render\\(\\$VIEW, <... \\$INP ...>\\)"
                - "$RES.render\\($VIEW, <... $REQ.$QUERY.$FOO ...>\\)"
                - "$RES\\.render\\(\\$VIEW, <... \\$REQ\\.\\$BODY ...>\\)"
```
