### ISSUE TITLE
generic_path_traversal

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6326]
### Template Information:

Untrusted user input in readFile()/readFileSync() can endup in Directory Traversal Attacks.

### Nuclei Template:

```yaml
id: generic_path_traversal

info:
  name: generic_path_traversal
  description: Untrusted user input in readFile()/readFileSync() can endup in Directory Traversal Attacks.
  reference: cwe-23
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "function \\(\\$REQ, \\$RES, ...\\) {...}"
                - "function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}"
                - "\\$X = function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}"
                - "var \\$X = function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...};"
                - "\\$APP.\\$METHOD\\(..., function \\$FUNC\\(\\$REQ, \\$RES, ...\\) {...}\\)"
                - "\\$X\\.createReadStream\\(..., <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>, ...\\)"
                - "\\$X\\.createReadStream\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$X\\.readFile\\(..., <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>, ...\\)"
                - "\\$X\\.readFile\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$X\\.readFileSync\\(..., <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>, ...\\)"
                - "\\$X\\.readFileSync\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$X\\.readFileAsync\\(..., <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>, ...\\)"
                - "\\$X\\.readFileAsync\\(..., <... \\$REQ\\.\\$QUERY ...>, ...\\)"
                - "\\$INP = <... \\$REQ\\.\\$QUERY\\.\\$VAR ...>\\;"
                - "\\$X\\.createReadStream\\(..., <... \\$INP ...>, ...\\)"
                - "\\$INP = <... \\$REQ\\.\\$QUERY ...>\\;"
                - "\\$X\\.readFile\\(..., <... \\$INP ...>, ...\\)"
                - "\\$X\\.readFileSync\\(..., <... \\$INP ...>, ...\\)"
                - "\\$Y = \\$REQ\\.\\$QUERY\\.\\$VAR\\;"
                - "\\$INP = <... \\$Y ...>\\;"
                - "\\$Y = \\$REQ\\.\\$QUERY\\;"
                - "\\$X\\.readFileAsync\\(..., <... \\$INP ...>, ...\\)"
```
