### ISSUE TITLE
tar_path_overwrite

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6327]
### Template Information:

Insecure TAR archive extraction can result in arbitrary path over write and can result in code injection.

### Nuclei Template:

```yaml
id: tar_path_overwrite

info:
  name: tar_path_overwrite
  description: Insecure TAR archive extraction can result in arbitrary path over write and can result in code injection.
  reference: cwe-22
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "\\$X = require\\('tar-stream'\\)"
                - "\\$EXTRACT\\.on\\('entry', function \\$FUNC\\(...\\) {"
                - "\\$FS\\.createWriteStream\\(\\$FIL, ...\\)"
                - "\\$FS\\.writeFile\\(\\$FIL, ...\\)"
                - "\\$FS\\.writeFileSync\\(\\$FIL, ...\\)"
```
