### ISSUE TITLE
zip_path_overwrite

### ISSUE THREAD

**Issue by Dheerajmadhukar** [projectdiscovery/nuclei-templates#6328]
### Template Information:

Insecure ZIP archive extraction can result in arbitrary path over write and can result in code injection.

### Nuclei Template:

```yaml
id: zip_path_overwrite

info:
  name: zip_path_overwrite
  description: Insecure ZIP archive extraction can result in arbitrary path over write and can result in code injection.
  reference: cwe-22
  author: me_dheeraj (https://twitter.com/Dheerajmadhukar)
  severity: info

file:
  - extensions:
      - all
    extractors:
      - type: regex
        regex:
                - "\\$X = require\\('unzip'\\)"
                - "\\$X = require\\('unzipper'\\)"
                - "\\$Y\\.pipe\\(\\$UNZIP\\.Parse\\(...\\)\\)\\.on\\('entry', function $FUNC\\(...\\) {"
                - "\\$X = \\$FILENAME\\.indexOf\\(...\\)"
                - "\\$FUNC\\.pipe\\(\\$FS\\.createWriteStream\\(\\$FIL, ...\\)\\)"
                - "\\$FUNC\\.pipe\\(\\$FS\\.writeFile\\(\\$FIL, ...\\)\\)"
                - "\\$FUNC\\.pipe\\(\\$FS\\.writeFileSync\\(\\$FIL, ...\\)\\)"
                - "\\$UNZIP\\.Parse\\(...\\)\\.on\\('entry', function \\$FUNC\\(\\$ENTRY\\) {"
                - "\\$FS\\.createWriteStream\\(\\$FIL, ...\\)"
                - "\\$FS\\.writeFile\\(\\$FIL, ...\\)"
                - "\\$FS\\.writeFileSync\\(\\$FIL, ...\\)"
```
