### ISSUE TITLE
CVE-2022-29153 - HashiCorp Consul and Consul Enterprise SSRF

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#6476]
### Template Information:
CVE-2022-29153 - HashiCorp Consul and Consul Enterprise SSRF. HTTP + Interval health check configuration now provides a disable_redirects option to prohibit this behavior.
https://discuss.hashicorp.com/t/hcsec-2022-10-consul-s-http-health-check-may-allow-server-side-request-forgery/38393

This template attempts to create a benign http heath check with the  `disable_redirects`  option set. Considered vulnerable if this option is rejected. Ref: https://github.com/hashicorp/consul/pull/12685

### Validation
1. Download a binary release version from: https://releases.hashicorp.com/consul/
2. Run consul agent: 
`./consul agent -dev -node machine -bind=<your-ip> -client=<your-ip> -ui`

Vulnerable version's missing the `disable_redirects`  option will return
- Status: 400
- Body: Request decode failed: json: unknown field "disable_redirects"

Tested Against:
- v1.4.3, v1.8.3, v1.9.15, and Fixed v1.9.17

### Nuclei Template:
```yaml
id: CVE-2022-29153
info:
  name: HashiCorp Consul and Consul Enterprise up to 1.9.16, 1.10.9, and 1.11.4 may allow server side request forgery when the Consul client agent follows redirects returned by HTTP health check endpoints. Consul follows HTTP redirects by default. HTTP + Interval health check configuration now provides a disable_redirects option to prohibit this behavior.
  severity: high
  author: c-sh0
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2022-29153
    - https://discuss.hashicorp.com/t/hcsec-2022-10-consul-s-http-health-check-may-allow-server-side-request-forgery/38393
    - https://github.com/hashicorp/consul/pull/12685
    - https://developer.hashicorp.com/consul/docs/discovery/checks
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N
    cvss-score: 7.5
    cve-id: CVE-2022-29153
    cwe-id: CWE-918
  tags: cve,cve2022,consul,ssrf

requests:
  - raw:
      - |
        PUT {{BaseURL}}/v1/agent/check/register HTTP/1.1
        Host: {{Hostname}}

        Content-Type: application/json
        {
         "id": "{{randstr}}",
         "name": "{{randstr}}",
         "method": "GET",
         "http": "/dev/null",
         "interval": "10s",
         "timeout": "1s",
         "disable_redirects": true
        }

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 400

      - type: word
        part: body
        words:
          - 'unknown field "disable_redirects"'
```
![CVE-2022-29153](https://user-images.githubusercontent.com/25989137/210900060-21bef084-446d-41d8-995c-3e63872fdf31.png)
