### ISSUE TITLE
golang-goroutine-debug

### ISSUE THREAD

**Issue by MrEmpy** [projectdiscovery/nuclei-templates#6622]
### Nuclei Template:

An application that exposes Golang Debug, allows users to look into stack traces, application time, memory usage, command line parameters, and allows triggering GC pauses, which allows a denial of service via of repeatedly triggering a garbage collection.

```yaml
id: golang-goroutine-debug

info:
  name: Golang Debug Detector
  author: MrEmpy (https://mrempy.github.io/about)
  description: An application that exposes Golang Debug, allows users to look into stack traces, application time, memory usage, command line parameters, and allows triggering GC pauses, which allows a denial of service via of repeatedly triggering a garbage collection.
  severity: medium
  shodan-query: html:"/debug/pprof/"
  tags: golang, debug, detector, sensive
  reference: https://hackerone.com/reports/1247910

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug/pprof/"
    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - ">full goroutine stack dump</a>"
        condition: and

      - type: status
        status:
          - 200
```
