### ISSUE TITLE
[nuclei-template] Lucee  Dectection of lucee CFML application server/engine/web/admin page

### ISSUE THREAD

**Issue by unp4ck** [projectdiscovery/nuclei-templates#6635]
### Template Information:

Hello 🧙🏻‍♂️

This template can be used to identify the framework/CMS Lucee, and using these references [ https://github.com/httpvoid/writeups/blob/main/Apple-RCE.md] [https://github.com/projectdiscovery/nuclei-templates//issues/2823] we can identify xss, or even a RCE.

### Nuclei Template:

```yaml
id: admin-server-web-lucee

info:
  name: Dectection of lucee CFML application server/engine/web/admin
  author: unp4ck
  reference: https://github.com/httpvoid/writeups/blob/main/Apple-RCE.md,https://github.com/projectdiscovery/nuclei-templates/issues/2823
  severity: info
  metadata:
    shodan-query: http.title:"Lucee"
  tags: tech,lucee

requests:
  - method: GET
    path:
      - '{{BaseURL}}/lucee/admin/web.cfm'
    matchers:
      - type: word
        words:
          - "lucee-admin-search-input"
          - "lucee-docs-search-input"
          - "server-lucee-small.png.cfm"
        part: body
```

<img width="904" alt="Screenshot 2023-01-29 at 13 43 10" src="https://user-images.githubusercontent.com/101719434/215343544-b2ea86ff-f216-4506-acd4-b1b5c5be6d5f.png">
