### ISSUE TITLE
Improve regular expressions in ruijie-eg-rce.yaml

### ISSUE THREAD

**Issue by Flower-fertilizer** [projectdiscovery/nuclei-templates#6686]
This poc will not extract the admin user password correctly when multiple accounts exist.

### Please describe your feature request:
Improve regular expressions for extractors.
e.g.{"data":"WORD\r\r\n\r\r\n00. admin admin\r\r\n01. test 123456","status":1}

### Describe the use case of this feature:
```yaml
extractors:
  - type: regex
    name: admin
    group: 1
    internal: true
    regex:
      - 'admin ([a-zA-Z0-9#@]+)([",|\\r])'
```
