### ISSUE TITLE
Error creating raw http request for proxy detection

### ISSUE THREAD

**Issue by denizcevik** [projectdiscovery/nuclei-templates#6725]
i have created following template for detecting proxy misconfiguration. But request is being created like below by nuclei. 

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.6 (latest)

GET  HTTP/1.1
Host: Hostname
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Netscape/8.0.4

[DBG] [poss_proxy_detection] Dumped HTTP response http://hostname/https:/2LY9tLJNQTSZ4MsQEn4gcV0rUcx.com

Although unsafe and raw request options are added the template, I cannot create request like below. Also i have checked openproxy* templates in /misconfiguration/proxy/. Same problem seems to apply to them.

GET http://www HTTP/1.1
Host: Hostname

Which options should i use to create the request as i specified above.

Thanks

--------------------------------

id: poss_proxy_detection

info:
  name: Possible Proxy
  author: bizzy
  severity: low

requests:
  - raw:
      - |+
        GET https://{{randstr}}.com HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Netscape/8.0.4

    unsafe: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 302
      - type: word
        words:
          - "{{randstr}}.com"
        part: header
        condition: and

**Comment by DhiyaneshGeek** [comment]
Hi @denizcevik 

Can you check the below template, it's working well on the latest version of `nuclei v2.9.0`

```yaml
id: poss-proxy

info:
  name: Possible Proxy
  author: DhiyaneshDK
  severity: info

requests:
  - raw:
      - |+
        GET https://{{randstr}}.com HTTP/1.1
        Host: {{Hostname}}

    unsafe: true
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "{{randstr}}.com"

      - type: status
        status:
          - 302
```

```bash
nuclei -t test.yaml -u http://testphp.vulnweb.com -vv -debug-req
```

Response

```
[INF] [poss-proxy] Dumped HTTP request for http://testphp.vulnweb.com/http:/2NM6PZMhGr7lT4cf7DSkXlBEVSe.com

GET https://2NM6PZMhGr7lT4cf7DSkXlBEVSe.com HTTP/1.1
Host: testphp.vulnweb.com
```
