### ISSUE TITLE
Feature request: display a single regex extractor catch per line 

### ISSUE THREAD

**Issue by Sim4n6** [projectdiscovery/nuclei-templates#6825]
### Please describe your feature request:

I've made a nuclei template that relies heavily on `regex extractor`. It extracts a regex value from JS files. 
The problem is that it finds more than a single hit which is not nicely formatted output as in sub-finder use.  

### Describe the use case of this feature:
Retrieve a JS file, and the following extractor for instance:

```
    extractors:
      - type: regex
        name: endpoint
        regex:
          - "(?i)('|\")([a-z0-9-_/=:&?\\.]+)('|\")"
```

would display something similar to:

```
[template-extractor] [http] [info] URL.js ["word1", "word2", "word3" .... ]
```

Is there a way to display them like in subfinder, a single result per line?
