### ISSUE TITLE
A lot of False positives for to svn-wc-db.yaml

### ISSUE THREAD

**Issue by tarunkant** [projectdiscovery/nuclei-templates#6841]
### Nuclei Version:

2.8.9

### Template file:

exposures/svn-wc-db.yaml, [Link](https://github.com/projectdiscovery/nuclei-templates/blob/main/exposures/files/svn-wc-db.yaml)

### Command to reproduce:

The matching conditions are very vague as this only checks with a status code of 200, there are a lot of application that results in 200 but no DB leaks, we should add some fingerprint check to have a correct match of DB leak which will reduce False positive.

**Affected Code:**

```
requests:
  - method: HEAD
    path:
      - "{{BaseURL}}/.svn/wc.db"
      - "{{BaseURL}}/wc.db"

    stop-at-first-match: true
    max-size: 10000
    matchers:
      - type: status
        status:
          - 200
```
