### ISSUE TITLE
CPE metadata in CVE templates

### ISSUE THREAD

**Issue by sduc** [projectdiscovery/nuclei-templates#6888]
I would be interested to add CPE metadata on all CVE templates to indicate which product and versions are affected by the CVE. This could be useful to since we could have the impacted versions directly available in the scan results without having to check the NVD. I'm happy to make a PR to update all existing templates if you agree with this FR.

### Please describe your feature request:

The idea would be to add CPE 2.3 metadata on all CVE templates. For example for CVE `CVE-2019-0193`, we could add the following metadata under classification:
```yaml
cpe-id: "cpe:2.3:a:apache:solr:*:*:*:*:*:*:*:*"
cpe-version-end-excluding: 8.2.0
```

We can get the metadata from the NIST. For example for CVE-2019-0193: https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2019-0193

### Describe the use case of this feature:

This would be useful to create reports where we can easily point out affected versions and recommend the minimum version to upgrade to. It makes it also easier when doing many scans on lots of hosts within a network to group by CVEs per CPE.

**Comment by ehsandeep** [comment]
Thanks for the feature request, this is undoubtedly useful. Do you plan to automate this? as of now CVE templates classification is generated using https://github.com/projectdiscovery/nuclei/tree/main/v2/cmd/cve-annotate that can be extended to include these two new pieces of information under the template classification section. What do you think?

```yaml
info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 7.2
    cve-id: CVE-2019-0193
    cwe-id: CWE-94
    cpe-id: cpe:2.3:a:apache:solr:*:*:*:*:*:*:*:*
    cpe-version-end-excluding: 8.2.0
```
