### ISSUE TITLE
Exchange Autodiscover Information Disclosure/ Basic Auth

### ISSUE THREAD

**Issue by td4b** [projectdiscovery/nuclei-templates#6977]
### Template Information:

I have a vulnerability that includes information disclosure and brute forcing with Autodiscover enabled on exchange domains with ADFS integration. Thinking this could potentially be rolled up into two separate templates but for now I am trying to figure out how we can do this by overwriting the variable for URL.

In this case the URL is static and the basic auth credentials will determine the target Federated Domain. e.g. 
some.user@domain.com

Idea on this:
So the target URL is static (Office365 Exchange) and has static entry point into the auto-discover domain. e.g. The target URL is always: https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml

However, the target domain is the ADFS or "Federated" domain which will be the DOMAIN_HERE parameter in the Basic Auth request below.

For now as an example the template looks like the following, where {{DOMAIN_HERE}} is manually set in the template below, and then run the template using the static URL.

```bash
nuclei -debug -t template.yaml -u https://autodiscover-s.outlook.com
```

### Nuclei Template:

```yaml
id: autodiscover-login
info:
  name: Auto Discover Information Disclosure
  author: td4b
  severity: medium
  tags: exchange,misconfig
requests:
  - raw:
      - |
        GET /autodiscover/autodiscover.xml
        Host: autodiscover-s.outlook.com
        Authorization: Basic {{base64(username + ':' + password)}}

    attack: pitchfork
    payloads:
      username:
        - jon.doe@{{DOMAIN_HERE}}
      password:
        - dsabkuasbdaobfdugkh
    matchers-condition: and
    matchers:
      - type: word
        part: all_headers
        words:
          - "X-Autodiscovery-Error: LiveIdBasicAuth:InvalidCreds"
          - "<LogonFailed-BadPassword>"
        condition: and
      - type: word
        part: body
        words:
          - "<Response>"
          - "<Message>Invalid Request</Message>"
        condition: and

      - type: status
        status:
          - 401

```

Side Note:
Will probably also want to add Information disclosure on "Account Existence" since this can be determined based on the Autodiscover Header error in the reply.

URL will show up in the header as something like this (can add regex). 
```bash
<STSUrl:https://myokta.domain/app/office365/adjslhflsahfdshjaf/sso/wsfed/active>
```

If the account shows above as a match its vulnerable to Basic Auth attacks / Brute force and account lockouts. 401 is always expected but the auto-discover headers change depending on if the Domain or Account is vulnerable.

Cheers,
