### ISSUE TITLE
[nuclei-template] rubygems.org user detection (osint)

### ISSUE THREAD

**Issue by cheesymoon** [projectdiscovery/nuclei-templates#7034]
### Template Information:

Very basic user detection template for the rubygems.org website, as an addition to the osint templates.

### Nuclei Template:

```yaml
id: rubygems

info:
  name: RubyGems User Name Information - Detect
  author: cheesymoon
  description: RubyGems.org user name information check was conducted.
  severity: info
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: osint,osint-social,rubygems

self-contained: true
requests:
  - method: GET
    path:
      - "https://rubygems.org/profiles/{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "Total gems"

```

### Results example:
![image](https://user-images.githubusercontent.com/56579976/230358681-18c6f6ae-88df-48ff-99c3-66eb9de0bd67.png)
