### ISSUE TITLE
[nuclei-template] imgbb.com user detection (osint)

### ISSUE THREAD

**Issue by cheesymoon** [projectdiscovery/nuclei-templates#7054]
### Template Information:

Detect usernames at the image hosting service imgbb.com

### Nuclei Template:

```yaml
id: imgbb

info:
  name: imgbb.com User Name Information - Detect
  author: cheesymoon
  description: imgbb.com user name information check was conducted.
  severity: info
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: osint,osint-image

self-contained: true
requests:
  - method: GET
    path:
      - "https://{{user}}.imgbb.com"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "Most recent"
          - "Followers"
        condition: and
```

![image](https://user-images.githubusercontent.com/56579976/231729442-eb3d50ba-e0e8-42e7-adc4-15d5d53e0cff.png)
