### ISSUE TITLE
[nuclei-template] hashnode.com user detection (osint)

### ISSUE THREAD

**Issue by cheesymoon** [projectdiscovery/nuclei-templates#7066]
### Template Information:

User detection on the medium-like social platform

### Nuclei Template:

```yaml
id: hashnode

info:
  name: hashnode.com User Name Information - Detect
  author: cheesymoon
  severity: info
  description: hashnode.com user name information check was conducted.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: osint,osint-social,hashnode

self-contained: true
http:
  - method: GET
    path:
      - "https://hashnode.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Member Since"
          - "Follow"
        condition: and

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/56579976/232086819-91d52209-d347-4ddf-85b0-6663011b96cb.png)
