### ISSUE TITLE
semicolon in GET requests

### ISSUE THREAD

**Issue by denizcevik** [projectdiscovery/nuclei-templates#7083]
If there are multiple semicolons (;) inside a GET request, they are deleted. for example if the path defined like below

```yaml
  - method: GET
    path:
      - '{{BaseURL}}/ctc/servlet/ConfigServlet?param=com.sap.ctc.util.FileSystemConfig;EXECUTE_CMD;CMDLINE=tasklist'
```
nuclei generates the request as below.

http://server/ctc/servlet/ConfigServlet?param=com.sap.ctc.util.FileSystemConfigEXECUTE_CMDCMDLINE=tasklist

but if there is only one semicolon, the request is generated without any problems.
