### ISSUE TITLE
[nuclei-template] Umami Default Login

### ISSUE THREAD

**Issue by barthy-koeln** [projectdiscovery/nuclei-templates#7163]
### Template Information:

This template is an adaptation of the existing [zabbix-default-login.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/default-logins/zabbix/zabbix-default-login.yaml) for the [Umami website analytics project](https://umami.is/).

The default setup comes with a default admin user, [as documented](https://umami.is/docs/login):

> Your Umami installation will create a default administrator account with the username `admin` and the password `umami`.
>
> The first thing you will want to do is log in and change your password.

### Nuclei Template:

```yaml
id: umami-default-login

info:
    name: Umami Default Login
    author: barthy.koeln
    severity: high
    description: Umami default admin credentials were discovered.
    reference:
        - https://umami.is/docs/login
    classification:
        cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L
        cvss-score: 8.3
        cwe-id: CWE-522
    tags: umami,default-login

http:
    - raw:
          - |
              POST /api/auth/login HTTP/1.1
              Host: {{Hostname}}
              Content-Type: application/json; charset=utf-8
              
              {"username":"{{username}}","password":"{{password}}"}

      payloads:
          username:
              - admin
          password:
              - umami
      attack: pitchfork

      matchers-condition: and
      matchers:
          - type: word
            part: body
            words:
                - "token"
                - "user"

          - type: status
            status:
                - 200

```

### Template Results

With default PW:

```text
[…]
[INF] Found 1 URL from httpx
[umami-default-login] [http] [high] https://redacted.com/api/auth/login [username="admin",password="umami"]
```

With secure PW:

```text
[…]
[INF] Found 1 URL from httpx
[INF] No results found. Better luck next time!
```

### Example Response

Content:

```json
{
  "token": "string",
  "user": { 
    "id": "uuid v4",
    "username": "admin",
    "createdAt": "ISO 8601" 
  }
}
```

Headers (partial):

Only one header contains anything related to Umami.

The value  `api.umami.is`  is [hard-coded in the current version](https://github.com/umami-software/umami/blob/586529a5ca2913f43a9b14a45ea65f99164abd61/next.config.js).

Should I add it to the expected response?

```json
{
  "name": "content-security-policy",
  "value": "default-src 'self'; img-src *; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' api.umami.is; frame-ancestors 'self';"
},
```
