### ISSUE TITLE
Add `max-request` as metadata information

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#7167]
### Please describe your feature request:
Add `max-request` attribute in the metadata section for each template.

```yaml
id: basic-example

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  metadata:
    max-request: 2

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/test"

    matchers:
      - type: word
        words:
          - "This is test matcher text"
```

- `max-request` counter represents the maximum number of requests that will be sent out for running a specific template.
- This will help to understand the overall resource that will be consumed in terms of time or request beforehand.
- This information will also allow users to execute / filter templates based on the number of requests it will make.
- These counters will be updated/added for all the nuclei templates added to the template project using [GH workflow](https://github.com/projectdiscovery/nuclei-templates/blob/main/.github/workflows/cve-annotate.yml).

## Anything else
- https://github.com/projectdiscovery/nuclei/pull/3607
- https://github.com/projectdiscovery/nuclei/issues/3575
