### ISSUE TITLE
New Template: Jedox Detect

### ISSUE THREAD

**Issue by cmahrl** [projectdiscovery/nuclei-templates#7180]
### Template Information:

This template is for detecting Jedox on-premise instances (https://www.jedox.com). Jedox is an Enterprise Performance Management software which is used for planning, analytics and reporting  in finance and other areas such as sales, human resources and procurement.

Detecting instances could be relevant for the following CVEs:
https://docs.syslifters.com/en/advisories/#jedox-2023

### Nuclei Template:

```yaml
 id: jedox-detect
 info:
   name: Jedox Detect
   author: Team Syslifters / Christoph MAHRL, Aron MOLNAR, Patrick PIRKER, Michael WEDL
   severity: info
   description: Jedox is an Enterprise Performance Management software which is used for planning, analytics and reporting  in finance and other areas such as sales, human resources and procurement.
   reference:
     - https://www.jedox.com
   metadata:
     verified: true
     google-query: allintext:"Jedox AG. All rights reserved." allintitle:Jedox Web Login
   tags: tech,jedox

 requests:
   - method: GET
     path:
       - "{{BaseURL}}"
     host-redirects: true
     max-redirects: 2
     matchers:
       - type: word
         words:
           - "Jedox AG. All rights reserved."
           - "Jedox Web - Login"
         condition: and
         part: body
```

![image](https://user-images.githubusercontent.com/7896159/236408699-fe053c5c-63fa-4784-b149-91ab74ae5682.png)
