### ISSUE TITLE
Headless DOM XSS

### ISSUE THREAD

**Issue by abdulx01** [projectdiscovery/nuclei-templates#7240]
### Please describe your feature request:

I want to make a DOM XSS template with headles, basically I want to fuzz on all Payload on every endpoint. 
I have created one but that is not valid because of matchers condition, I don't know for that, Here I want headless matchers for alert window pops up or not. To confirm dom XSS.

**Comment by olearycrew** [comment]
Can you share the example you have started thusfar?

**Comment by abdulx01** [comment]
```yaml
id: DOM_XSS
info:
  name: Headless DOM xss
  author: abdulrahman
  severity: high

headless:
  - steps:
    - args:
        url: '{{BaseURL}}'
      action: navigate
    - action: waitload

    payloads:
      xss:
        - "'-alert(11)-'"
        - '"-alert(11)-"'
        - "<img src=x onerror=alert(11)>"

    fuzzing:
      - part: query
        type: postfix
        mode: single
        fuzz:
          - "{{xss}}"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - part: alert
        type: word
        words:
          - "11"
```
Here is Example of my idea: but nuclei validate is refusing, because of this fuzzing function not found in headless requests.
```bash
[ERR] Error occurred loading template /root/FindBug/headless/DOM-XSS.yaml: Could not load template /root/FindBug/headless/DOM-XSS.yaml: yaml: unmarshal errors:
  line 21: field fuzzing not found in type headless.Request
[FTL] Could not validate templates: errors occured during template validation
```
I hope you got this my idea.
