### ISSUE TITLE
 web-server-detection.yaml

### ISSUE THREAD

**Issue by ctflearner** [projectdiscovery/nuclei-templates#7270]
### Template Information:

 This nuclei template sends a GET request to a website and detects various web servers based on the response headers. It Supports the given server that are mention in the Template

Reference 
-   https://cloudinfrastructureservices.co.uk/best-open-source-web-servers/

### Nuclei Template:

```yaml
id: detect-web-servers
info:
  name: Web Server Detection
  author: ctflearner
  severity: low
  tags:
  - web server
  - server detection
  - response headers
  reference: 
  - https://cloudinfrastructureservices.co.uk/best-open-source-web-servers/
  - google.com
  description: |
    This nuclei template sends a GET request to a website and detects various web servers based on the response headers. It supports the following servers:

    - Apache
    - nginx
    - Microsoft IIS
    - Apache Tomcat
    - LiteSpeed
    - Google Web Server (GWS)
    - Caddy
    - OpenLiteSpeed
    - lighttpd
    - Jetty
    - Cherokee
    - Abyss
    - IBM HTTP Server
    - Oracle HTTP Server
    - Hiawatha
    - Tengine
    - Resin
    - thttpd
    - Monkey
    - Boa
    - Mongoose
    - MochiWeb
    - IBM Domino
    - gunicorn
    - Twisted Web
    - Xitami
    - AOLserver
    - Jexus
    - Warp
    - G-WAN
    - CherryPy
    - Amazon S3
    - Wt (Web Toolkit)
    - Appweb
    - Embedthis Appweb
    - Puma
    - 3rdTech Examine3D Web Server
    - Roxen WebServer
    - Argo Server
    - Alibaba Cloud Web Server
    - Jigsaw (W3C Server)
    

requests:
  - method: GET
    path:
      - "{{Host}}"
    matchers:
      - type: word
        name: apache
        words:
          - "Server: Apache"
        part: header
      - type: word
        name: nginx
        words:
          - "Server: nginx"
        part: header
      - type: word
        name: iis
        words:
          - "Server: Microsoft-IIS/"
        part: header  
      - type: word
        name: tomcat
        words:
          - "Server: Apache-Coyote/"
        part: header 
      - type: word
        name: litespeed
        words:
          - "Server: LiteSpeed/"
        part: header 
      - type: word
        name: gws
        words:
          - "Server: GWS/"
        part: header  
      - type: word
        name: caddy
        words:
          - "Server: Caddy/"
        part: header 
      - type: word
        name: openlitespeed
        words:
          - "Server: OpenLiteSpeed/"
        part: header  
      - type: word
        name: lighttpd
        words:
          - "Server: lighttpd/"
        part: header 
      - type: word
        name: jetty
        words:
          - "Server: Jetty/"
        part: header 
      - type: word
        name: cherokee
        words:
          - "Server: Cherokee/"
        part: header  
      - type: word
        name: abyss
        words:
          - "Server: Abyss/"
        part: header 
      - type: word
        name: ibm-http
        words:
          - "Server: IBM-HTTP/"
        part: header     
      - type: word
        name: oracle-http
        words:
          - "Server: Oracle-HTTP/"
        part: header     
      - type: word
        name: hiawatha
        words:
          - "Server: Hiawatha/"
        part: header 
      - type: word
        name: tengine
        words:
          - "Server: Tengine/"
        part: heade  
      - type: word
        name: resin
        words:
          - "Server: Resin/"
        part: header     
      - type: word
        name: thttpd
        words:
          - "Server: thttpd/"
        part: header  
      - type: word
        name: monkey
        words:
          - "Server: Monkey/"
        part: header    
      - type: word
        name: boa
        words:
          - "Server: Boa/"
        part: header   
      - type: word
        name: mongoose
        words:
          - "Server: Mongoose/"
        part: header 
      - type: word
        name: mochiweb
        words:
          - "Server: MochiWeb/"
        part: header    
      - type: word
        name: domino
        words:
          - "Server: IBM Domino/"
        part: header  
      - type: word
        name: gunicorn
        words:
          - "Server: gunicorn/"
        part: header   
      - type: word
        name: twisted-web
        words:
          - "Server: Twisted Web/"
        part: header   
      - type: word
        name: xitami
        words:
          - "Server: Xitami/"
        part: header 
      - type: word
        name: aolserver
        words:
          - "Server: AOLserver/"
        part: header  
      - type: word
        name: jexus
        words:
          - "Server: Jexus/"
        part: header 
      - type: word
        name: warp
        words:
          - "Server: Warp/"
        part: header  
      - type: word
        name: gwan
        words:
          - "Server: G-WAN/"
        part: header 
      - type: word
        name: cherrypy
        words:
          - "Server: CherryPy/"
        part: header  
      - type: word
        name: amazons3
        words:
          - "Server: Amazon S3/"
        part: header 
      - type: word
        name: wt-toolkit
        words:
          - "Server: Wt (Web Toolkit)/"
        part: header  
      - type: word
        name: appweb
        words:
          - "Server: Appweb/"
        part: header   
      - type: word
        name: embedthis-appweb
        words:
          - "Server: Embedthis Appweb/"
        part: header  
      - type: word
        name: puma
        words:
          - "Server: Puma/"
        part: header  
      - type: word
        name: examine3d
        words:
          - "Server: 3rdTech Examine3D Web Server/"
        part: header    
      - type: word
        name: roxen
        words:
          - "Server: Roxen WebServer/"
        part: header    
      - type: word
        name: argo
        words:
          - "Server: Argo Server/"
        part: header  
      - type: word
        name: alibaba-cloud
        words:
          - "Server: Alibaba Cloud Web Server/"
        part: header    
      - type: word
        name: jigsaw
        words:
          - "Server: Jigsaw (W3C Server)/"
        part: header         
    extractors:
      - type: regex
        regex:
          - "Server: Apache/([\\d.]+)"
        part: header
      - type: regex
        regex:
          - "Server: nginx/([\\d.]+)"
        part: header
      - type: regex
        regex:
            - "Server: Microsoft-IIS/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Apache-Coyote/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: LiteSpeed/([\\d.]+)"
        part: header   
      - type: regex
        regex:
              - "Server: GWS/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Caddy/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: OpenLiteSpeed/([\\d.]+)"
        part: header 
      - type: regex
        regex:
              - "Server: lighttpd/([\\d.]+)"
        part: header 
      - type: regex
        regex:
              - "Server: Jetty/([\\d.]+)"
        part: header 
      - type: regex
        regex:
              - "Server: Cherokee/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Abyss/([\\d.]+)"
        part: header     
      - type: regex
        regex:
              - "Server: IBM-HTTP/([\\d.]+)"
        part: header    
      - type: regex
        regex:
              - "Server: Oracle-HTTP/([\\d.]+)"
        part: header   
      - type: regex
        regex:
              - "Server: Hiawatha/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Tengine/([\\d.]+)"
        part: header 
      - type: regex
        regex:
              - "Server: Resin/([\\d.]+)"
        part: header   
      - type: regex
        regex:
              - "Server: thttpd/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Monkey/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Boa/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: Mongoose/([\\d.]+)"
        part: header  
      - type: regex
        regex:
              - "Server: MochiWeb/([\\d.]+)"
        part: header  
      - type: regex
        regex:
             - "Server: IBM Domino/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server: gunicorn/([\\d.]+)"
        part: header
      - type: regex
        regex:
             - "Server: Twisted Web/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server: Xitami/([\\d.]+)"
        part: header 
      - type: regex
        regex:
             - "Server: AOLserver/([\\d.]+)"
        part: header 
      - type: regex
        regex:
             - "Server: Jexus/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server: Warp/([\\d.]+)"
        part: header  
      - type: regex
        regex:
             - "Server: G-WAN/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server: CherryPy/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server: Amazon S3/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Wt (Web Toolkit)/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Appweb/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Embedthis Appweb/([\\d.]+)"
        part: header  
      - type: regex
        regex:
             - "Server:Puma/([\\d.]+)"
        part: header    
      - type: regex
        regex:
             - "Server:3rdTech Examine3D Web Server/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Roxen WebServer/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Argo Server/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Alibaba Cloud Web Server/([\\d.]+)"
        part: header   
      - type: regex
        regex:
             - "Server:Jigsaw (W3C Server)/([\\d.]+)"
        part: header    



```

![nuclei-web-server-poc-2](https://github.com/projectdiscovery/nuclei-templates/assets/98345027/692e6e1c-d91a-4d7a-9ada-570db5dcabb8)
![nuclei-web-server-poc-1](https://github.com/projectdiscovery/nuclei-templates/assets/98345027/9c0c5659-123a-4788-babb-43c0ddfdbb1c)
