### ISSUE TITLE
CVE-2023-1362.yaml

### ISSUE THREAD

**Issue by ctflearner** [projectdiscovery/nuclei-templates#7290]
### Template Information:

This template checks for the presence of clickjacking prevention headers in the HTTP response, aiming to identify vulnerabilities related to the improper restriction of rendered UI layers or frames in the GitHub repository unilogies/bumsys prior to version 2.0.2.

Reference:
-  https://nvd.nist.gov/vuln/detail/CVE-2023-1362
- https://huntr.dev/bounties/e5959166-c8ef-4ada-9bb1-0ff5a9693bac/

### Nuclei Template:

```yaml
id: CVE-2023-1362
info:
  name: Improper Restriction of Rendered UI Layers or Frames in GitHub repository unilogies/bumsys prior to v2.0.2
  description: |
    This template checks for the presence of clickjacking prevention headers in the HTTP response, aiming to identify vulnerabilities related to the improper restriction of rendered UI layers or frames in the GitHub repository unilogies/bumsys prior to version 2.0.2.
  author: ctflearner
  severity: medium
  tags:
    - web
    - UI REDRESSING 
    - unilogies/bumsys 
  reference: 
       - https://nvd.nist.gov/vuln/detail/CVE-2023-1362
       - https://huntr.dev/bounties/e5959166-c8ef-4ada-9bb1-0ff5a9693bac/
  classification: 
     cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
     cvss-score: 6.1
     cve-id: CVE-2023-1362
     cwe-id: CWE-1021
     cpe: cpe:2.3:a:bumsys_project:bumsys:*:*:*:*:*:*:*:*    

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers-condition: or
    matchers:
      - type: dsl
        name: security-headers
        dsl:
          - "!regex('(?i)(x-frame-options|content-security-policy|x-content-type-options|x-xss-protection|frame-ancestors)', all_headers)"
        condition: or
```

![cve-2023-1362-poc-validate](https://github.com/projectdiscovery/nuclei-templates/assets/98345027/05406dd6-f05f-42e9-b993-d48c7d08b4d0)

# Since the latest version of bumsys doesn't have this vulnerability
![cve-2023-1362-poc-2-bumsys](https://github.com/projectdiscovery/nuclei-templates/assets/98345027/7f3505eb-2af7-4563-b8ea-0f463adb44c8)

![cve-2023-1362-poc-1-timetracker](https://github.com/projectdiscovery/nuclei-templates/assets/98345027/b757ef0b-a84b-4a97-8808-56a2abacc9e9)
