### ISSUE TITLE
False positive --again-open redirected -Twitter

### ISSUE THREAD

**Issue by kolor33** [projectdiscovery/nuclei-templates#7293]

**Comment by princechaddha** [comment]
Hi @kolor33, Thank you for taking the time to create this issue and for contributing to this project 🍻

```yaml
[INF] [open-redirect] Dumped HTTP request for https://twitter.com//evil.com

GET //evil.com HTTP/1.1
Host: twitter.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[DBG] [open-redirect] Dumped HTTP response https://twitter.com//evil.com

HTTP/1.1 302 Found
Content-Length: 32
Cache-Control: no-cache, no-store, max-age=0
Content-Type: text/plain; charset=utf-8
Date: Thu, 01 Jun 2023 07:21:31 GMT
Location: //evil.com
Perf: 7626143928
Server: tsa_f
Set-Cookie: guest_id_marketing=v1%3A168560409156276985; Max-Age=63072000; Expires=Sat, 31 May 2025 07:21:31 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
Set-Cookie: guest_id_ads=v1%3A168560409156276985; Max-Age=63072000; Expires=Sat, 31 May 2025 07:21:31 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
Set-Cookie: personalization_id="v1_Dz12LFGObgawHFHZ7oQfoQ=="; Max-Age=63072000; Expires=Sat, 31 May 2025 07:21:31 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
Set-Cookie: guest_id=v1%3A168560409156276985; Max-Age=63072000; Expires=Sat, 31 May 2025 07:21:31 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
Strict-Transport-Security: max-age=631138519
Vary: Accept
X-Connection-Hash: 76cb5e9744207e9253fdea92c4853abcde731c4fc1881c808ef34acd3407ab34
X-Powered-By: Express
X-Response-Time: 103
X-Transaction-Id: 129c8d5818d36cc7

Found. Redirecting to //evil.com
[open-redirect:status-2] [http] [medium] https://twitter.com//evil.com [redirect="/evil.com"]
[open-redirect:regex-1] [http] [medium] https://twitter.com//evil.com [redirect="/evil.com"]
```

The redirection appears to be valid looking at the debug data, but it's not reflecting the same behavior in the browser, causing the host to get matched. It seems we're dealing with an edge case here. The team is actively working to resolve this issue. Thank you
