### ISSUE TITLE
CVE-2023-25157.yaml

### ISSUE THREAD

**Issue by vsh00t** [projectdiscovery/nuclei-templates#7363]
### Template Information:

SQL Injection Vulnerabilities on GeoServer includes support for the OGC Filter expression language and the OGC Common Query Language (CQL) as part of the Web Feature Service (WFS) and Web Map Service (WMS) protocols. CQL is also supported through the Web Coverage Service (WCS) protocol for ImageMosaic coverages.
  remediation: Users are advised to upgrade to either version 2.21.4, or version 2.22.2 to resolve this issue. Users unable to upgrade should disable the PostGIS Datastore *encode functions* setting to mitigate ``strEndsWith``, ``strStartsWith`` and ``PropertyIsLike `` misuse and enable the PostGIS DataStore *preparedStatements* setting to mitigate the ``FeatureId`` misuse.

reference:
    - https://github.com/geoserver/geoserver/security/advisories/GHSA-7g5f-wrx8-5ccf

### Nuclei Template:

```yaml
id: CVE-2023-25157

info:
  name: OGC Filter SQL Injection Vulnerabilities
  author: vsh00t
  severity: critical
  description: |
    SQL Injection Vulnerabilities on GeoServer includes support for the OGC Filter expression language and the OGC Common Query Language (CQL) as part of the Web Feature Service (WFS) and Web Map Service (WMS) protocols. CQL is also supported through the Web Coverage Service (WCS) protocol for ImageMosaic coverages.
  remediation: Users are advised to upgrade to either version 2.21.4, or version 2.22.2 to resolve this issue. Users unable to upgrade should disable the PostGIS Datastore *encode functions* setting to mitigate ``strEndsWith``, ``strStartsWith`` and ``PropertyIsLike `` misuse and enable the PostGIS DataStore *preparedStatements* setting to mitigate the ``FeatureId`` misuse.
  reference:
    - https://github.com/geoserver/geoserver/security/advisories/GHSA-7g5f-wrx8-5ccf
  classification:
    cve-id: CVE-2023-25157
  metadata:
    max-request: 1
    verified: "true"
  tags: sqli,cve,cve2023

http:
  - raw:
      - |+
        GET /geoserver/ows?service=wfs HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    unsafe: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "GeoServer"
          - "opengis"
          - "WFS 1.0.0"
          - "FeatureType"
          - "ogc"
        part: body
        condition: or
```

[CVE-2023-25157] [http] [critical] https://HOSTNAME/geoserver/ows?service=wfs
