### ISSUE TITLE
Axxon Next client Login Detection

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7516]
### Template Information:
Axxon Next client Login
Info: Axxon Next is a video management software (VMS) developed by AxxonSoft, a leading provider of intelligent surveillance and security solutions. 
Reference: - https://www.axxonsoft.com/products/video-management-software

### Nuclei Template:

```yaml
id: axxon-next-client-login

info:
  name: Axxon Next client Login
  author: irshad ahamed 
  severity: low
  description: Axxon One is a limitlessly scalable video management software
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  remediation: Implement strong authentication measures and enforce password complexity requirements for the Axxon Next client login to enhance the security of access to the panel.
  reference:
    - https://www.axxonsoft.com/products/video-management-software
  metadata:
    verified: true
  tags: axxon,vms,login


requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Axxon Next client</title>'

      - type: status
        status:
          - 200
```

<img width="362" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/be2de6b4-a200-4d1f-9034-5173570fd490">
