### ISSUE TITLE
Untangle Administrator Login

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7583]
### Template Information:

Untangle Administrator Login

Info: Untangle Administrator is a centralized web-based management console that allows administrators to efficiently configure, monitor, and control various network security and filtering features provided by the Untangle NG Firewall, ensuring robust network protection and policy enforcement.

Reference: https://edge.arista.com/ng-firewall/

### Nuclei Template:
```yaml
id: untangle-administrator-login

info:
  name: Untangle Administrator Login
  author: irshad ahamed
  severity: info
  description: Untangle Administrator is a centralized web-based management console that allows administrators to efficiently configure, monitor, and control various network security and filtering features provided by the Untangle NG Firewall, ensuring robust network protection and policy enforcement.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  remediation: Implement strong authentication measures and enforce password complexity requirements for the Untangle Administrator login to enhance the security of access to the panel.
  reference:
    - https://edge.arista.com/ng-firewall/
  metadata:
    verified: true
  tags: untangle,adinistrator,login


requests:
  - method: GET
    path:
      - '{{BaseURL}}/auth/login'

    matchers-condition: and

    matchers:
      - type: word
        words:
          - "<title>Untangle Administrator Login</title>"

      - type: status
        status:
          - 200
```

<img width="479" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/cf627ff6-8f75-44f3-80e8-4fbcd5c7b237">
