### ISSUE TITLE
Pritunl Login

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7584]
### Template Information:

Pritunl Login

Info: Pritunl is an open-source VPN server that provides secure remote access and networking capabilities.

Reference: https://pritunl.com/

### Nuclei Template:
```yaml
id: pritunl-login

info:
  name: Pritunl Login
  author: irshad ahamed
  severity: info
  description: Pritunl is an open-source VPN server that provides secure remote access and networking capabilities.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  remediation: Implement strong authentication measures and enforce password complexity requirements for the Pitunl login to enhance the security of access to the panel.  
  reference:
    - https://pritunl.com/
  metadata:
    verified: true
  tags: pritunl,vpn,login

requests:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and

    matchers:
      - type: word
        words:
          - "<title>Pritunl</title>"
          - "sudo pritunl default-password"
        condition: and

      - type: status
        status:
          - 200
```

<img width="411" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/08497a04-b8b3-4542-bdf8-4438ec099ce8">
