### ISSUE TITLE
Uptime Kuma Login

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7585]
### Template Information:

Uptime Kuma Login

Info: Realtime website and application monitoring tool

Reference:
    - https://github.com/louislam/uptime-kuma
    - https://uptime.kuma.pet/docs/

### Nuclei Template:

```yaml
id: uptime-kuma-login

info:
  name: Uptime Kuma Login 
  author: irshad ahamed
  severity: low
  description: Realtime website and application monitoring tool
  remediation: Implement strong authentication measures and enforce password complexity requirements for the Uptime Kuma login to enhance the security of access to the panel.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  reference:
    - https://github.com/louislam/uptime-kuma
    - https://uptime.kuma.pet/docs/
  metadata:
    verified: true
  tags: kuma,monitoring,login


requests:
  - method: GET
    path:
      - '{{BaseURL}}/dashboard'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Uptime Kuma</title>' 

      - type: status
        status:
          - 200
```

<img width="404" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/d7610685-feab-404c-82e1-7c87a976b20a">
