### ISSUE TITLE
Eagle For Apache Kakfa Login 

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7586]
### Template Information:

Eagle For Apache Kakfa Login 

Info: EFAK is a visualization and management software that allows one to query, visualize, alert on, and explore their metrics wherever they were stored.

Reference: 
    - https://github.com/smartloli/efak
    - https://www.kafka-eagle.org/

### Nuclei Template:

```yaml
id: eagle-for-apache-kafka-login

info:
  name: Eagle For Apache Kakfa Login 
  author: irshad ahamed
  severity: medium
  description: EFAK is a visualization and management software that allows one to query, visualize, alert on, and explore their metrics wherever they were stored.
  remediation: Implement strong authentication measures and enforce password complexity requirements for the EFAK login to enhance the security of access to the panel.
  reference:
    - https://github.com/smartloli/efak
    - https://www.kafka-eagle.org/
  metadata:
    verified: true
  tags: eagle,apache,kafka,login


requests:
  - method: GET
    path:
      - '{{BaseURL}}/account/signin'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Login - EFAK</title>' 

      - type: status
        status:
          - 200
```

<img width="479" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/448b52a5-03ea-4d07-94ab-e1afdf397f86">
