### ISSUE TITLE
Shell In A Box

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7587]
### Template Information:

Shell In A Box

Info: Shell In A Box implements a web server that can export arbitrary command line tools to a web based terminal emulator

Reference: 
    - https://github.com/shellinabox/shellinabox
    - https://www.cvedetails.com/vulnerability-list/vendor_id-15771/product_id-33062/Shellinabox-Project-Shellinabox.html

### Nuclei Template:

```yaml
id: shell-in-a-box

info:
  name: Shell In A Box
  author: irshad ahamed
  severity: info
  description: Shell In A Box implements a web server that can export arbitrary command line tools to a web based terminal emulator
  reference:
    - https://github.com/shellinabox/shellinabox
    - https://www.cvedetails.com/vulnerability-list/vendor_id-15771/product_id-33062/Shellinabox-Project-Shellinabox.html
  metadata:
    verified: true
  tags: shell,emulator


requests:
  - method: GET
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Shell In A Box</title>' 

      - type: status
        status:
          - 200
```

<img width="405" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/40674c6a-6296-44c7-9693-56e7ba4c6f83">
