### ISSUE TITLE
CVE-2023-24488 Also can be leveraged for Open Redirects

### ISSUE THREAD

**Issue by YashVardhanTrip** [projectdiscovery/nuclei-templates#7623]
### Template Information:

The query parameter of Citrix-ADC which led to CVE-2023-24488 can also be leveraged for Open-Redirects issue.

### Nuclei Template:

```yaml
id: CVE-2023-24487

info:
  name: Open-Redirect
  author: YashVardhanTripathi 
  severity: Mdium 
  description: Open-Redirect
  
  tags: cve,cve2023,citrix

requests:
  - method: GET
    path:
      - '{{BaseURL}}/oauth/idp/logout?post_logout_redirect_uri={[evilurl]}

    payloads: 
      evilurl:
        - https://evil.com

    matchers:
      - type: word
        words:
          - "www.evil.com"
      - type: dsl
        dsl:
          - "len(body) > 20"
      - type: status
        status:
          - 200
          - 301
          - 302
```
![image](https://github.com/projectdiscovery/nuclei-templates/assets/96331700/4d2ecab9-cd41-4ddb-9766-644126d44b63)
