### ISSUE TITLE
Add GitHub workflow to automatically add template creation date as metadata info

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#7653]
### Please describe your feature request:

```yaml
id: CVE-2022-4321

info:
  name: Test HTTP Template
  author: pdteam
  severity: info
  metadata:
    added_at: "2023-07-10"
```
