### ISSUE TITLE
Citrix Sharefile Login

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7660]
### Template Information:

Citrix ShareFile Login

Description: 
Citrix ShareFile is a cloud-based file sharing and collaboration platform that provides secure access to files from anywhere.

Reference: 
 -  https://www.sharefile.com/
 - https://blog.assetnote.io/2023/07/04/citrix-sharefile-rce/
 

### Nuclei Template:

```yaml
id: citrix-sharefile-login

info:
  name: Citrix Sharefile Login
  author: irshad ahamed
  severity: info
  description: Citrix ShareFile is a cloud-based file sharing and collaboration platform that provides secure access to files from anywhere.
  reference:
    - https://www.sharefile.com/
    - https://blog.assetnote.io/2023/07/04/citrix-sharefile-rce/
  metadata:
    verified: true
  tags: citrix,sharefile,login


requests:
  - method: GET
    path:
      - "{{BaseURL}}/Authentication/Login"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>ShareFile Login</title>'
          - 'url=/authentication/error'
        condition: and

      - type: status
        status:
          - 200
```

<img width="462" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/d93b5c0f-7da6-4fe1-ac0d-b446b3fc20f2">
