### ISSUE TITLE
Prometheus Promtail

### ISSUE THREAD

**Issue by Zinkuth** [projectdiscovery/nuclei-templates#7662]
### Template Information:
Prometheus Promtail

Description: Prometheus Promtail is an agent that gathers log data from various sources, such as files or systemd journal.

Reference:
    - https://grafana.com/docs/loki/latest/clients/promtail/
    - https://github.com/grafana/loki/issues/8680
    

### Nuclei Template:

```yaml
id: prometheus-promtail

info:
  name: Prometheus Promtail
  author: irshad ahamed
  severity: medium
  description: Prometheus Promtail is an agent that gathers log data from various sources, such as files or systemd journal.
  reference:
    - https://grafana.com/docs/loki/latest/clients/promtail/
    - https://github.com/grafana/loki/issues/8680
  metadata:
    verified: true
  tags: prometheus,promtail,log


requests:
  - method: GET
    path:
      - "{{BaseURL}}/service-discovery"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '>Promtail</a>'
          - 'https://github.com/grafana/loki'
        condition: and

      - type: status
        status:
          - 200
```

<img width="468" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/36253549/e33ec9bf-d37a-4479-9a94-18c246946994">
