### ISSUE TITLE
question of extractors

### ISSUE THREAD

**Issue by k3rwin** [projectdiscovery/nuclei-templates#7748]
how to use or to match multiple regular expressions, if the first one is matched, the second one will not be matched.
For example, linux use \n and windows use \r\n,I only want to match once,Is there any parameter setting?  like `condition: or` in matchers
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*)\n</string>'
```

_Originally posted by @k3rwin in https://github.com/projectdiscovery/nuclei-templates/discussions/7744#discussioncomment-6520244_

**Comment by ehsandeep** [comment]
@k3rwin, if the purpose is to extract any (first) match, you can use the above format.

If you want to ensure other extractors to check regardless of the first extract, you can write in separate blocks, for example:

```yaml
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\n</string>'
```

**Comment by k3rwin** [comment]
What I mean is that it ends when the first regex is matched, because the second regex can also be matched, so the content will be printed twice, and I only want to print the content of the first match

**Comment by k3rwin** [comment]
> 

What I mean is that it ends when the first regex is matched, because the second regex can also be matched, so the content will be printed twice, and I only want to print the content of the first match

**Comment by k3rwin** [comment]
> @k3rwin, if the purpose is to extract any (first) match, you can use the above format.
> 
> If you want to ensure other extractors to check regardless of the first extract, you can write in separate blocks, for example:
> 
> ```yaml
>     extractors:
>       - type: regex
>         group: 1
>         part: body
>         regex:
>           - '<string>(.*)\r\n</string>'
>           
>       - type: regex
>         group: 1
>         part: body
>         regex:
>           - '<string>(.*)\n</string>'
> ```
When I use this, it will extract twice and return two results, one without \r and one with \r
```
    extractors:
      - type: regex
        group: 1
        part: body
        regex:
          - '<string>(.*)\r\n</string>'
          - '<string>(.*)\n</string>'
```
