### ISSUE TITLE
scanning false alarms

### ISSUE THREAD

**Issue by Shea-Des** [projectdiscovery/nuclei-templates#7923]
### Nuclei Version: 
v2.9.10

### Template file:

matchers partial information
```
    matchers:
      - type: status
        status:
          - 200
```

### Command to reproduce:

scanning
![image](https://github.com/projectdiscovery/nuclei-templates/assets/69289278/a98d1ef1-eff5-49f9-b986-aa5caff40214)
but, in burp, the page is not accessible, it prompts Done
![image](https://github.com/projectdiscovery/nuclei-templates/assets/69289278/79388cec-024f-4d65-a91b-1de12b80a672)
