### ISSUE TITLE
chatgpt-web-unauth

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7969]
### Template Information:

chatgpt-web-unauth
fofa: app="Chatgpt-web"

### Nuclei Template:

```yaml
id: chatgpt-web-unauth

info:
  name: ChatGPT Web 未授权访问漏洞
  author: SleepingBag945
  severity: high
  description: |
    ChatGPT Web 未授权访问漏洞
  metadata:
  tags: chatgpt

http:
  - raw:
      - |
        POST /api/session HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/plain, */*
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.127 Safari/537.36
        Content-Type: application/json
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

        {}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "\"status\":\"Success\""
          - "\"auth\":false"
          - "ChatGPTAPI"
        condition: and
```
