### ISSUE TITLE
clickhouse web unauth

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7971]
### Template Information:

clickhouse web unauth
fofa: header="X-ClickHouse-Summary"

### Nuclei Template:

```yaml
id: clickhouse-web-unauth
info:
  name: clickhouse web unauth
  author: SleepingBag945
  severity: high
  description: ClickHouse 存在着的接口由于没有鉴权，则任意访问者都可以执行SQL语句获取数据.
  reference:
    - https://mp.weixin.qq.com/s/xIc3Ic7N104iTogZul1LJA
  tags: clickhouse

http:
  - raw:
      - |
        GET /ping HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /?query=SHOW%20DATABASES HTTP/1.1
        Host: {{Hostname}}


    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(header_1, "X-Clickhouse-Summary")'
          - 'status_code_2 == 200 && contains(body_2,"default") && contains(body_2,"system")'
        condition: and
```
