### ISSUE TITLE
dahua-smart-park-fastjson-rce

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7973]
### Template Information:

dahua-smart-park-fastjson-rce
app="dahua-智慧园区综合管理平台"

### Nuclei Template:

```yaml
id: dahua-smart-park-fastjson-rce

info:
  name: 大华智慧园区综合管理平台Fastjson RCE
  author: SleepingBag945
  severity: critical
  description: |
    大华智慧园区综合管理平台Fastjson RCE
  tags: fastjson,rce

http:
  - raw:
      - |
        @timeout: 20s
        POST /WPMS/getPublicKey HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json; charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.127 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

        {"x":{"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 400

      - type: word
        part: body  # Confirms the DNS Interaction
        words:
          - "请求参数转化成JSON格式异常,请检查"


```
