### ISSUE TITLE
easyreport-default-login

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7975]
### Template Information:

easyreport-default-login
fofa: body="EasyReport-A Sample and Easy to Use Web Reporting System"

### Nuclei Template:

```yaml
id: easyreport-default-login

info:
  name: EasyReport Default Login
  author: SleepingBag945
  severity: medium
  description: EasyReport 默认密码admin/123456
  tags: easyreport,default-login

http:
  - raw:
      - |
        POST /member/authenticate HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/javascript, */*; q=0.01
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8
        X-Requested-With: XMLHttpRequest

        account=admin&password=123456&rememberMe=false

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '"code":0'
          - "detailMsg"
          - '"data":true'
        part: body
        condition: and
```
