### ISSUE TITLE
Hikvision Springboot Env Actuator - Detect

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7983]
### Template Information:

Hikvision Springboot Env Actuator - Detect
app="HIKVISION-iSecure-Center"

### Nuclei Template:

```yaml
id: hikvision-isecure-center-springboot-env

info:
  name: Hikvision Springboot Env Actuator - Detect
  author: SleepingBag945
  severity: high
  description: Sensitive environment variables may not be masked
  tags: misconfig,springboot,env,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/artemis/env"
      - "{{BaseURL}}/artemis-portal/artemis/env"
      - "{{BaseURL}}/artemis/actuator/env"
      - "{{BaseURL}}/artemis;/env;"
      - "{{BaseURL}}/artemis/1/..;/env"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "applicationConfig"
          - "activeProfiles"
        condition: or

      - type: word
        part: body
        words:
          - "server.port"
          - "local.server.port"
        condition: or

      - type: word
        part: header
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
          - "application/vnd.spring-boot.actuator.v3+json"
        condition: or

      - type: status
        status:
          - 200

```
