### ISSUE TITLE
huatian-oa8000-buffalo-rce

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7989]
### Template Information:

huatian-oa8000-buffalo-rce
app="华天动力-OA8000"

### Nuclei Template:

```yaml
id: huatian-oa8000-buffalo-rce

info:
  name: huatian-oa8000-buffalo-rce
  author: SleepingBag945
  severity: critical
  description: 华天OA 8000 buffalo 远程命令执行
  tags: huatian,oa

http:
  - raw:
      - |
        GET /OAapp/bfapp/buffalo/ HTTP/1.1
        Host: {{Hostname}}
        

      - |
        POST /OAapp/bfapp/buffalo/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded


    req-condition: true
    matchers-condition: and
    matchers:
      - type: dsl
        dsl: 
          - status_code_1 == 500 && contains(body_1,'Buffalo worker support POST only!') && contains(body_1,'net.buffalo.service.BuffaloWorker.validate')
          - status_code_2 == 500 && contains(body_2,'net.buffalo.service.NoSuchServiceException') && contains(body_2,'net.buffalo.service.BuffaloWorker.processRequest')
        condition: and



```
