### ISSUE TITLE
[Feature] golang-metrics.yaml miss a lot of results due to limited validation

### ISSUE THREAD

**Issue by DEMON1A** [projectdiscovery/nuclei-templates#807]
- I just noticed that there's a new template has been added `golang-metrics.yaml`. that scans the metrics endpoint then validate the response. the problem here that its not really limited to golang only. it's used too by nodejs and other stuff. if you made the template based on the golang metrics only you will miss a lot of valid results. i would recommend changing the compare string into `cpu_seconds_total`. I use this string for matching all of the possible results on metrics. and it does exists on all languages metrics.

- Here's the template after update.

```yaml
id: golang-metrics

info:
  name: Golang exposed metrics
  author: dhiyaneshDK
  severity: low
  reference: https://hackerone.com/reports/1026196

requests:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'cpu_seconds_total'

      - type: status
        status:
          - 200
```
