### ISSUE TITLE
如何写requests包里的cookie 

### ISSUE THREAD

**Issue by wtdata99** [projectdiscovery/nuclei-templates#8201]
我在写一个禅道命令执行漏洞时候，他先要访问misc-captcha-user.html获取一个有效的cookie，我如何在模板请求的时候将此cookie设为变量，供下一个包去使用？

**Comment by princechaddha** [comment]
@wtdata99, if I understand correctly, you want to extract the cookie values from a request and use them in the next request?"

You can simply use `cookie-reuse:` true for maintaining a browser-like session with cookie-based session handling between multiple requests.

```yaml
http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

      - |
        POST / HTTP/2
        Host: {{Hostname}}
        Origin: {{BaseURL}}
        Content-Type: application/x-www-form-urlencoded

    cookie-reuse: true
```

Example: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2022/CVE-2022-2546.yaml
