### ISSUE TITLE
Shiro-default-key-detect

### ISSUE THREAD

**Issue by union-cmd** [projectdiscovery/nuclei-templates#8243]
```yaml
id: shiro-default-key-detect

info:
  name: Detect Shiro Default Key
  author: hotpot
  severity: critical
  description: This template is designed to detect the Shiro framework's default key vulnerabilities. It leverages 51 built-in Shiro keys to probe for potential vulnerabilities.
  reference: https://github.com/sv3nbeast/ShiroScan
  tags: shiro

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Cookie: JSESSIONID={{randstr}};rememberMe=123;

      - |
        GET / HTTP/1.1
        Host: {{Hostname}}
        Cookie: JSESSIONID={{randstr}};rememberMe={{key}};
    
    payloads:
      key: helpers/wordlists/shiro_encrypted_datas.txt
    req-condition: true
    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(header_1, "Set-Cookie") && (contains(header_1, "rememberMe=") || contains(header_1, "=deleteMe"))'
          - '!contains(header_2, "rememberMe=") && !contains(header_2, "=deleteMe")'
        condition: and

```
