### ISSUE TITLE
[grafana-login-check.yaml] Indentation errors in tags 

### ISSUE THREAD

**Issue by k3mlol** [projectdiscovery/nuclei-templates#8393]
### Template Information:
grafana-login-check.yaml

### Nuclei Template:
https://github.com/projectdiscovery/nuclei-templates/blob/main/http/credential-stuffing/self-hosted/grafana-login-check.yaml#L14

``` yaml
id: grafana-login-check

info:
  name: Grafana Login Check
  author: parthmalhotra,pdresearch
  severity: critical
  description: Checks for a valid login on self hosted Grafana instance.
  reference:
    - https://owasp.org/www-community/attacks/Credential_stuffing
  metadata:
    max-request: 1
    shodan-query: title:"Grafana"
    fofa-query: title="Grafana"
    tags: login-check,grafana,creds-stuffing,self-hosted
```
tags and metadata indentation should be the same.
