### ISSUE TITLE
phpmyadmin-default-login error

### ISSUE THREAD

**Issue by notwhy** [projectdiscovery/nuclei-templates#8417]
### Nuclei Version:

lastet version

### Template file:
phpmyadmin-default-login.yaml

### Command to reproduce:
nuclei -t ~/nuclei-templates/http/default-logins/phpmyadmin/phpmyadmin-default-login.yaml -u https:// -debug

```yaml
      - type: regex
        name: session
        part: header
        internal: true
        group: 1
        regex:
          - "phpMyAdmin=([0-9a-z]+)"
```

this regex error when i test a https site. i check the website return headers is 

```
Set-Cookie: phpMyAdmin_https=8fpqu039s8iofr2v6rfsqd6g54; path=/phpMyAdmin/; secure; HttpOnly
```
phpMyAdmin_https= does not match phpMyAdmin=([0-9a-z]+) 

I don't know if the version is correct . i guess If the website uses HTTPS, current templates will report an error.

so correct regex should like "phpMyAdmin((_https)?)=([0-9a-z]+) ? 
like:

```yaml
      - type: regex
        name: session
        part: header
        internal: true
        group: 2
        regex:
          - "phpMyAdmin(_https)?=([0-9a-z]+)"
```
