### ISSUE TITLE
servicenow-widget-misconfig False Positive Improvement

### ISSUE THREAD

**Issue by Shumaan** [projectdiscovery/nuclei-templates#8440]
### Template Information:
Template: servicenow-widget-misconfig

The original checks for servicenow-widget-misconfig incorrectly flagged tables when column level ACLs were actually protecting the data correctly and preventing data from leaking. 

For example, `POST /api/now/sp/widget/5b255672cb03020000f8d856634c9c28?t=sys_user&f=name` may not actually return data. 

```json
"data":{"viewAllMsg":"View all","isValid":true,"count":500,"list":[{"sys_id":"5136503cc611227c0183e96598c4f706","className":"sys_user","display_field":{"display_value":null,"value":null},"secondary_fields":[{"display_value":null,"value":null}]}],"maxCount":500,"actions":[],"filterMsg":"Filter..."}
```

It is necessary to check that there is a non-null value for `display_value` present in the response body.

### Nuclei Template:

The below template includes a change to reduce false positives, aka, checking that display_value does not return null data.

New additional check:
```yaml
      - type: regex
        part: body
        regex:
          - '"display_value":"(.*)",'
```

I've also added a new table check for the sys_user table to help validate.

Full new template
```yaml
id: servicenow-widget-misconfig

info:
  name: ServiceNow Widget-Simple-List - Misconfiguration
  author: DhiyaneshDk
  severity: unknown
  reference:
    - https://github.com/bsysop/servicenow
    - https://twitter.com/ConspiracyProof/status/1713270026046685272
    - https://www.enumerated.ie/servicenow-data-exposure
  metadata:
    verified: true
    max-request: 54
    shodan-query: title:"servicenow"
  tags: servicenow,widget,misconfig

http:
  - raw:
      - |
        @once
        GET / HTTP/1.1
        Host: {{Hostname}}
      - |
        @once
        GET /login.do HTTP/1.1
        Host: {{Hostname}}
      - |
        POST /api/now/sp/widget/widget-simple-list?{{table_list}} HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

    cookie-reuse: true
    payloads:
      table_list:
        - t=sys_user&f=name
        - t=kb_knowledge&f=text
        - t=cmdb_model&f=name
        - t=cmn_department&f=app_name
        - t=licensable_app&f=app_name
        - t=alm_asset&f=display_name
        - t=sys_attachment&f=file_name
        - t=sys_attachment_doc&f=data
        - t=oauth_entity&f=name
        - t=cmn_cost_center&f=name
        - t=cmdb_model&f=name
        - t=sc_cat_item&f=name
        - t=sn_admin_center_application&f-name
        - t=cmn_company&f=name
        - t=sys_email_attachment&f=email
        - t=sys_email_attachment&f=attachment
        - t=cmn_notif_device&f=email_address
        - t=sys_portal_age&f=display_name
        - t=incident&f=short_description

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"isValid":true'
          - '"count":'
        condition: and
      - type: regex
        part: body
        regex:
          - '"display_value":"(.*)",'

    extractors:
      - type: regex
        name: user-token
        group: 1
        regex:
          - var g_ck = '([0-9a-z]+)'
        internal: true

      - type: regex
        part: body
        group: 1
        regex:
          - '"count":([0-9]+),'
```

Before:
![before](https://github.com/projectdiscovery/nuclei-templates/assets/2516230/7e4dc338-529d-4cc9-8c17-28bc6123ce33)

After:
![after](https://github.com/projectdiscovery/nuclei-templates/assets/2516230/a9b2424b-8ac8-4a03-9fd8-0081232ccf0a)
