### ISSUE TITLE
Using flow to get rid of multi-template match: worksites-takeover

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei-templates#8600]
### Template Information:

hey there, one more multi-template match situation that can be solved through flow.
This time, worksites-takeover and canny-takeover have the very same condition in place.
However, worksites can be refactored to match words instead of regex and also using flow to match the A record it depends on.
So flow will first match the IP address using DNS, then use http request to match the words.

More details here: https://melbadry9.gitbook.io/blog/dangling-dns/xyz-services/ddns-worksites

### Nuclei Template:

```yaml
id: worksites-takeover

info:
  name: worksites takeover detection
  author: melbadry9, dogasantos
  severity: high
  reference:
    - https://blog.melbadry9.xyz/dangling-dns/xyz-services/ddns-worksites
  metadata:
    max-request: 1
  tags: takeover

flow: dns(1) && http(1)

dns:
  - name: "{{FQDN}}"
    type: A
    class: inet
    recursion: true
    retries: 3
    matchers:
      - type: word
        words:
          - "69.164.223.206"

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - Host != ip

      - type: word
        words:
          - "Company Not Found"
          - "worksites.net"

```

I've created a worksites account to test this. it works.
