### ISSUE TITLE
PHP Composer Binary Detection

### ISSUE THREAD

**Issue by MayankPandey01** [projectdiscovery/nuclei-templates#8651]
### Template Information:

This Template checks if a Website exposes the PHP Composer Binary on the `/composer` endpoint

### Nuclei Template:

```yaml
id: php-composer-binary
info:
  name: Publically Accessible PHP Composer Binary
  author: mayank_pandey01
  severity: low
  description: |
    This Nuclei template checks if the specified endpoints have Publically Accessible PHP Composer Binary.
http:
  - method: GET
    path:
      - "{{BaseURL}}/composer"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "/usr/bin/env php"
        part: body
      - type: status
        status:
          - 200
```
![image](https://github.com/projectdiscovery/nuclei-templates/assets/29165227/560a30e0-67ba-498b-b7eb-0638b56bb057)

```[tasklist]
### Tasks
```
