### ISSUE TITLE
Appsetting Config Endpoints Detection

### ISSUE THREAD

**Issue by MayankPandey01** [projectdiscovery/nuclei-templates#8652]
### Template Information:

This Nuclei template checks if the specified endpoints have a Publically Accessible Appsetting Config Endpoint.
    Endpoints:
    -  "/appsettings.Development.json"
    -  "/appsettings.json"
    -  "/appsettings.Release.json"

### Nuclei Template:

```yaml
id: appsetting-config
info:
  name: Publically Accessible Appsetting Config Endpoints
  author: mayank_pandey01
  severity: low
  description: |
    This Nuclei template checks if the specified endpoints have a Publically Accessible Appsetting Config Endpoint.
    Endpoints:
    - "/appsettings.Development.json"
    - "/appsettings.json"
    - "/appsettings.Release.json"

http:
  - method: GET
    path:
      - "{{BaseURL}}/appsettings.Development.json"
      - "{{BaseURL}}/appsettings.json"
      - "{{BaseURL}}/appsettings.Release.json"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "application/json"
        part: header
      - type: status
        status:
          - 200
```
### Reference

Possible Output on `appsettings.Development.json`
```json
{
"APIBasePath": "https://localhost:5001/api/",
"ImageBasePath": "https://localhost:5001/images/"
}
```

![image](https://github.com/projectdiscovery/nuclei-templates/assets/29165227/0b8e83d5-6258-40c3-8a6f-8898eadea2fa)
