### ISSUE TITLE
Add `recommended.yaml` to run curated templates

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei-templates#8674]
We are planning to introduce a `recommended.yaml` file, which will contain a curated list of templates specifically chosen for their efficiency and relevance. The primary goal is to offer a streamlined and more focused scanning process by default, thereby avoiding the often exhaustive and less relevant results of a full template scan. 

We are also contemplating making the `recommended.yaml` the standard default for all Nuclei scans. This would mark a shift from running all available templates to a more selective approach by default. As we have been adding many useful information templates, we recognize that they might not be useful for everyone and could result in an overload of scan results.

This can be a major change and would greatly value the community's input on this. Do you feel that making `recommended.yaml` the default behavior aligns with your scanning needs? We are eager to hear your thoughts, concerns, and any suggestions you might have regarding this proposed change.

Example `recommended.yaml`:

```yaml
exclude-severity:
  - info

exclude-tags:
  - tech
  - dos
  - fuzz
  - creds-stuffing
  - token-spray

exclude-protocols:
  - ssl
  - dns
  - file
  - code
  - whois
  - headless
  - workflow

exclude-id:
  - generic-tokens
  - credentials-disclosure
  - CVE-2021-28164
  - ....
 ```
