### ISSUE TITLE
How to specify the header without adding other field information

### ISSUE THREAD

**Issue by Shea-Des** [projectdiscovery/nuclei-templates#8681]
In the POST request header, I only need the `User-Agent` and `cmd` fields in the header, how do I write the template. I tried
```
requests:
  - method: POST
    path:
      - "{{BaseURL}}/index.jsp"
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
      cmd: "whoami"
```

and
 
```
http:
  - raw: 
.....
```
A look at the traffic reveals that the requests are supplemented with other header fields that I don't need

**Comment by ritikchaddha** [comment]
Hello @Shea-Des, To send a POST request with only the `User-Agent` and `cmd` headers,  the request should be in raw HTTP and include `unsafe: true` in the request block.

Your template should be like this:

```
http:
  - raw:
      - |+
        POST / HTTP/1.1
        Host: {{Hostname}}
        cmd: "whoami"
        User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36

    unsafe: true
```
