### ISSUE TITLE
drupal-7-elfinder

### ISSUE THREAD

**Issue by 0xr2r** [projectdiscovery/nuclei-templates#8865]
### Template Information:

https://github.com/Kro0oz/drupal-7-elfinder

![1](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/70c31ef0-c190-4a01-941a-4443f0481000)

### Nuclei Template:

```yaml
id: drupal-7-elfinder
info:
  name: Drupal 7 elfinder
  author: 1337kro
  severity: high
  reference:
    - https://github.com/Kro0oz/drupal-7-elfinder

http:
  - method: GET
    path:
      - "{{BaseURL}}/sites/all/libraries/elfinder/connectors/php/connector.php"
    matchers:
      - type: word
        words:
          - '{"cwd":'
        part: body
```
