### ISSUE TITLE
Cisco ASA Software Version Enumerator

### ISSUE THREAD

**Issue by sdcampbell** [projectdiscovery/nuclei-templates#8874]
### Template Information:

Cisco ASA's have been affected by multiple CVE. See https://www.cvedetails.com/vulnerability-list/vendor_id-16/product_id-20366/Cisco-Adaptive-Security-Appliance-Software.html

While there are numerous Nuclei templates targeting specific Cisco ASA CVE, none of them enumerate the software version. 

Additionally, Nessus scan plugins which report on the ASA version don't show how they found the version which is problematic for pentest and vulnerability scan report validation. It recently took me far to long to figure out how to enumerate the Cisco ASA software version to validate a vulnerability scan report which lacked any proof of how it identified the version.

I would appreciate your help to produce cleaner output, such as "9.1(6)" instead of `<version who="sg">9.1(6)</version>`. I tried valid regex patterns but they didn't work with Nuclei.

### Nuclei Template:

```yaml
id: cisco-asa-software-version
info:
  name: Cisco ASA Software Version Extractor
  author: sdcampbell (@lpha3ch0)
  severity: info

http:
  - method: POST
    path:
      - "{{BaseURL}}"
    headers:
      X-Aggregate-Auth: "1"
    body: "Give me your version number"

    extractors:
      - type: regex
        part: body
        regex:
          - "<version who=\"sg\">(.*?)</version>"
```
An example run:

```
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.1.0 (outdated)
[INF] Current nuclei-templates version: v9.7.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 61
[INF] Templates loaded for current scan: 1
[WRN] Executing 1 unsigned templates. Use with caution.
[INF] Targets loaded for current scan: 1
[VER] [cisco-asa-software-version] Sent HTTP request to https://[redacted]/
[cisco-asa-software-version] [http] [info] https://[redacted]:443/ [<version who="sg">9.1(6)</version>]

The process exited with code 0
```

The raw HTTP response contains:

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Wed, 27 Dec 2023 18:23:03 GMT
X-Frame-Options: SAMEORIGIN
X-Aggregate-Auth: 1
Content-Length: 211

<?xml version="1.0" encoding="UTF-8"?>
<config-auth client="vpn" type="complete">
<version who="sg">9.1(6)</version>
<error id="98" param1="" param2="">VPN Server could not parse request.</error>
</config-auth>
```

An associated curl request which gets the same info:

```
curl -i -s -k -X $'POST' \
    -H $'Host: [target IP]' -H $'X-Aggregate-Auth: 1' -H $'Content-Length: 10' \
    --data-binary $'\x0d\x0a\"TESTME\"' \
    $'https://[target IP]/'
```
