### ISSUE TITLE
version.bind DNS TXT Chaos Queries

### ISSUE THREAD

**Issue by denizcevik** [projectdiscovery/nuclei-templates#8877]
Hello,

Is there a way to create a template which makes query for chaos version.bind txt record using dns features of nuclei.  So we can detect vulnerabilities according to version number. For example sigred dns vulnerability can be detected in such a way.

Regards

**Comment by dwisiswant0** [comment]
Yes, you can create a template to query for CHAOS class version.bind TXT record.

Since `version.bind` is queried against a specific DNS server (not resolved normally), you need to:

* Set name: "version.bind" as a literal string.
* Use the resolvers field to specify the target DNS server (from input).
* Still provide a dummy domain as input (required by nuclei), or use the input as the resolver.

Example working approach:

```yaml
id: dns-version-bind

info:
  name: DNS Version Bind Query
  author: example
  severity: info

dns:
  - name: "version.bind"   # Literal name, not {{FQDN}}
    type: TXT
    class: chaos
    recursion: false
    resolvers:
      - "{{Hostname}}:53"  # Target the input as resolver, or use {{Host}}

    extractors:
      - type: regex
        part: answer
        regex:
          - ".*"
```

Hope that helps!

Ref: https://github.com/projectdiscovery/nuclei/blob/v3.6.0/SYNTAX-REFERENCE.md#dnsrequest
