### ISSUE TITLE
Nuclei removed url fragment (#) In their HTTP request

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#8909]
## Issue
https://github.com/projectdiscovery/nuclei/discussions/4571

## Description
I found some templates that use URL fragments (#) in the `path` section. Here is a list of these templates:
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/saia-web-server-info.yaml#L21
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/ibm-friendly-path-exposure.yaml#L20
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/forti/fortiadc-panel.yaml#L23
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2021/CVE-2021-24891.yaml#L36
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2018/CVE-2018-20470.yaml#L34
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/rethinkdb-admin-console.yaml#L23
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/cisco/cisco-meraki-exposure.yaml#L21
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/keenetic-web-login.yaml#L21
* https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/mystrom-panel.yaml#L21
* etc.

## How to solve?
@tarunKoyalwar has already shared his solver, which uses the Javascript protocol to send the HTTP request (you can check the solver in the discussions I shared above). However, I have also tested it and have an alternative method using 'unsafe: true.' Here is the example template:

```yaml
id: testing-url-fragments

info:
  name: Testing URL Fragment (#)
  author: daffainfo
  severity: info
  metadata:
    max-request: 1
  tags: test

http:
  - raw:
      - |+
        GET /testing#daffainfo HTTP/1.1
        Host: {{Hostname}}
        Origin: {{BaseURL}}

    unsafe: true
    matchers:
      - type: status
        status:
          - 200
```

Output:

```
[INF] Targets loaded for current scan: 1
[INF] [testing-url-fragments] Dumped HTTP request for https://daffa.info/testing#daffainfo

GET /testing#daffainfo HTTP/1.1
Host: daffa.info
Origin: https://daffa.info

[DBG] [testing-url-fragments] Dumped HTTP response https://daffa.info/testing#daffainfo

HTTP/1.1 404 Not Found
Content-Length: 162
Connection: keep-alive
Content-Type: text/html
Date: Fri, 05 Jan 2024 06:16:40 GMT
Server: nginx/1.18.0 (Ubuntu)

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
[INF] No results found. Better luck next time!
```

We need to recode some templates that use an url fragment
