### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by Banannna69** [projectdiscovery/nuclei-templates#8949]
### CVE-2023-50290- Apache Solr - Unauthorized access

```yaml
id: CVE-2023-50290

info:
  name: Apache Solr - Unauthorized access
  author: Banana69
  severity: High
  description: |
    Exposure of Sensitive Information to an Unauthorized Actor vulnerability in Apache Solr. The Solr Metrics API publishes all unprotected environment variables available to each Apache Solr instance. Users are able to specify which environment variables to hide, however, the default list is designed to work for known secret Java system properties. Environment variables cannot be strictly defined in Solr, like Java system properties can be, and may be set for the entire host, unlike Java system properties which are set per-Java-proccess. The Solr Metrics API is protected by the "metrics-read" permission. Therefore, Solr Clouds with Authorization setup will only be vulnerable via users with the "metrics-read" permission. This issue affects Apache Solr: from 9.0.0 before 9.3.0. Users are recommended to upgrade to version 9.3.0 or later, in which environment variables are not published via the Metrics API.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-50290
  classification:
    cve-id: CVE-2023-50290
  metadata:
    fofa-query: app="APACHE-Solr"
  tags: cve,cve2023,unauth,

http:
  - method: GET
    path:
      - "{{BaseURL}}/solr/admin/metrics"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "system.env")'
        condition: and
```

![image](https://github.com/projectdiscovery/nuclei-templates/assets/88693653/019768d9-a80d-4644-a884-e59e5d9b7355)
