### ISSUE TITLE
[nuclei-template] server-config-files

### ISSUE THREAD

**Issue by hackerrishad** [projectdiscovery/nuclei-templates#899]
**Template Details**

```
id: server-config-files

info:
  name: server config file disclosure
  author: sheikhrishad
  severity: low
  tags: config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/proftpd.conf"
      - "{{BaseURL}}/apache.conf"
      - "{{BaseURL}}/nginx.conf"
      - "{{BaseURL}}/php-fpm.conf"
      - "{{BaseURL}}/httpd.conf"
      - "{{BaseURL}}/svnserve.conf"
      - "{{BaseURL}}/smb.conf"
      - "{{BaseURL}}/tidy.conf"
      
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ProFTPD"
          - "Apache2"
          - "PHP-FPM"
          - "/var/www/html"
          - "svnserve.conf"
          - "smb.conf"
          - "tidy"
          
        condition: and

      - type: status
        status:
          - 200
```

**Comment by geeknik** [comment]
Shouldn't `condition: and` be `conditon: or` instead? Otherwise it will only look for files containing all of the words. 👍🏻

**Comment by ehsandeep** [comment]
Hi @hackerrishad, 

Thank you for sharing this template, just wanted to double-check with the 1st matcher:- 

```yaml
        words:
          - "ProFTPD"
          - "Apache2"
          - "PHP-FPM"
          - "/var/www/html"
          - "svnserve.conf"
          - "smb.conf"
          - "tidy"
        condition: and
```

You indicated `condition: and` i.e all the keyword has to be in the response for every path you listed? or `condition: or` is the expected matcher?

in general, I will suggest having a different template for each unique path is a good idea as each path going to cost the same number of HTTP requests + more simple matchers.
