### ISSUE TITLE
Springboot Actuator integrationgraph

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#8998]
### Nuclei Template:

```yaml
id: springboot-integrationgraph

info:
  name: Springboot Actuator integrationgraph
  author: ELSFA7110
  severity: low
  description: the integrationgraph endpoint exposes a graph containing all Spring Integration components.
  reference:
    - https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#caches
  metadata:
    verified: true
    max-request: 2
  tags: misconfig,springboot,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/integrationgraph"
      - "{{BaseURL}}/actuator/integrationgraph"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "provider"

      - type: word
        part: header
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
          - "application/vnd.spring-boot.actuator.v3+json"
        condition: or

      - type: status
        status:
          - 200
```
