### ISSUE TITLE
Springboot Actuator startup

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#8999]
### Nuclei Template:

```yaml
id: springboot-startup

info:
  name: Springboot Actuator startup
  author: ELSFA7110
  severity: low
  description: The startup endpoint provides information about the application’s startup sequence.
  reference:
    - https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/
  metadata:
    verified: true
    max-request: 2
  tags: misconfig,springboot,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/startup"
      - "{{BaseURL}}/actuator/startup"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "springBootVersion"

      - type: word
        part: header
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
          - "application/vnd.spring-boot.actuator.v2+json"
          - "application/vnd.spring-boot.actuator.v3+json"
        condition: or

      - type: status
        status:
          - 200
```
