### ISSUE TITLE
Google Chromecast devices enumeration

### ISSUE THREAD

**Issue by NitescuLucian** [projectdiscovery/nuclei-templates#9096]
### Template Information:

I would like a template allowing me and maybe others to discover Google Chromecast devices, especially for internal network scanning. I was able to get the path from this python script:

- https://github.com/thewhiteh4t/killcast/blob/ee81cfa03c963d47d3335770fcea2ca48bddeabf/killcast.py#L100C25-L100C43

### Nuclei Template:

```yaml
id: chromecast-enum

info:
  name: Google Chromecast Enumeration
  author: LucianNitescu
  severity: info
  description: Searches for Google Chromecast via their eureka_info route.
  reference:
    - https://github.com/thewhiteh4t/killcast/blob/ee81cfa03c963d47d3335770fcea2ca48bddeabf/killcast.py#L100C25-L100C43
    - https://rithvikvibhu.github.io/GHLocalApi/#section/Google-Home-Local-API/Authentication
  tags: enum

http:
  - raw:
      - |+
        GET /setup/eureka_info HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"cast_build_revision":'
      - type: status
        status:
          - 200

```

Sample Nuclei Output:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/12897148/64b1a59e-70aa-4e8e-bae1-90972c03c617)

Sample Response:

```
HTTP/1.1 200 OK
Access-Control-Allow-Headers:Content-Type
Cache-Control:no-cache
Content-Length:1339
Content-Type:application/json

{"bssid":"ESCAPED","build_version":"275994","cast_build_revision":"1.56.275994","closed_caption":{},"connected":true,"ethernet_connected":false,"has_update":false,"hotspot_bssid":"ESCAPED","ip_address":"ESCAPED","locale":"en-US","location":{"country_code":"ESCAPED","latitude":ESCAPED.0,"longitude":ESCAPED.0},"mac_address":"ESCAPED","name":"ESCAPED","noise_level":-95,"opt_in":{"crash":true,"opencast":false,"stats":true},"public_key":"ESCAPED","release_track":"stable-channel","setup_state":60,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":0,"num_connect_wifi":0,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":0,"num_obtain_ip":0},"signal_level":-24,"ssdp_udn":"ESCAPED","ssid":"ESCAPED","time_format":2,"timezone":"Europe/Helsinki","tos_accepted":true,"uma_client_id":"ESCAPED","uptime":81629.312699,"version":12,"wpa_configured":true,"wpa_id":1,"wpa_state":10}
```
