### ISSUE TITLE
CVE-2024-1709

### ISSUE THREAD

**Issue by hhhharshil** [projectdiscovery/nuclei-templates#9185]
### Template Information:

This is a template to detect vulnerable instances of screenconnect per https://www.cvedetails.com/cve/CVE-2024-1709/

### Nuclei Template:

```yaml
id: CVE-2024-1709
info:
  name: ConnectWise ScreenConnect Auth Bypass via Alternate Path or Channel
  author: hhhharshil
  severity: high
  reference:
    - https://www.huntress.com/blog/detection-guidance-for-connectwise-cwe-288-2
    - https://github.com/watchtowrlabs/connectwise-screenconnect_auth-bypass-add-user-poc
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N
    cvss-score: 10
    cve-id: CVE-2024-1709
    cwe-id: CWE-288
    cpe: cpe:2.3:a:connectwise:screenconnect:*:*:*:*:*:*:*:*
  metadata:
    vendor: connectwise
    product: screenconnect
    max-request: 1
  tags: screenconnect,connectwise

http:
  - method: GET
    path:
      - "{{BaseURL}}/SetupWizard.aspx/zzzzzz"
    matchers:
      - type: status
        status:
          - 500
      - type: regex
        regex:
          - "ScreenConnect"
    extractors:
      - type: kval
        part: header
        kval:
          - Server
```

This template is a bit more accurate as vulnerable instances would return a 500 if SetupWizard.aspx is requested I tested this against both patched and unpatched instances by using results from the shodan queries.

Patched instances:
https://www.shodan.io/search?query=Server%3A+ScreenConnect%2F23.9.8.8811

Unpatched:
https://www.shodan.io/search?query=Server%3A+ScreenConnect+-%22ScreenConnect%2F23.9.8.8811%22
