### ISSUE TITLE
Faulty regex for IPv6 in dns-rebinding.yaml 

### ISSUE THREAD

**Issue by gabriellavengeo** [projectdiscovery/nuclei-templates#9212]
### Nuclei Version:

any

### Template file:

https://github.com/projectdiscovery/nuclei-templates/blob/main/dns/dns-rebinding.yaml

### Command to reproduce:

My understanding is that this tries to match [local IPv6 addresses](https://en.wikipedia.org/wiki/Unique_local_address) with an `fd` prefix. However, due to due to `IN.+A.+` at the start of the regex allowing any number of arbitrary characters between the record type and the `fd` prefix, addresses for which the second hextet starts with `fd` would also produce a match. 

For example, something `IN AAAA XXXX:fdXX:X:XXXX::XX` (redacted) would produce a false positive.

**Comment by princechaddha** [comment]
Hi @gabriellavengeo, Thank you for taking the time to create this issue and for contributing to this project 🍻

I have updated the regex in https://github.com/projectdiscovery/nuclei-templates/pull/9252/files let me know if it looks good. 

cc @ricardomaia

**Comment by ricardomaia** [comment]
> ### Nuclei Version:
> any
> 
> ### Template file:
> https://github.com/projectdiscovery/nuclei-templates/blob/main/dns/dns-rebinding.yaml
> 
> ### Command to reproduce:
> My understanding is that this tries to match [local IPv6 addresses](https://en.wikipedia.org/wiki/Unique_local_address) with an `fd` prefix. However, due to due to `IN.+A.+` at the start of the regex allowing any number of arbitrary characters between the record type and the `fd` prefix, addresses for which the second hextet starts with `fd` would also produce a match.
> 
> For example, something `IN AAAA XXXX:fdXX:X:XXXX::XX` (redacted) would produce a false positive.
> 
> ### Anything else:

You are right @gabriellavengeo! The regex error occurs in both the full and compressed versions.

![image](https://github.com/projectdiscovery/nuclei-templates/assets/1353811/d58353ec-ce33-409e-b41f-e55018a93b72)

@princechaddha, in my tests, testing the string 'IN' at the beginning with `^` will not work properly. I also noticed that an error was introduced in the regex for IPv4. I am submitting my suggestion for change.

**Comment by ricardomaia** [comment]
```yaml
name: DNS Rebinding Attack
  author: ricardomaia
  severity: unknown
  description: |
    Detects DNS Rebinding attacks by checking if the DNS response contains a private IPv4 or IPv6 address.
  reference:
    - https://capec.mitre.org/data/definitions/275.html
    - https://payatu.com/blog/dns-rebinding/
    - https://heimdalsecurity.com/blog/dns-rebinding/
  tags: redirect,dns,network

dns:
  - name: "{{FQDN}}"
    type: A
    matchers:
      # IPv4
      - type: regex
        part: answer
        regex:
          - 'IN\s+A\s+(127\.0\.0\.1|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3})$'

    extractors:
      - type: regex
        part: answer
        name: IPv4
        group: 1
        regex:
          - 'IN\s+A\s+(127\.0\.0\.1|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3})'

  - name: "{{FQDN}}"
    type: AAAA
    matchers:
      # IPv6 Compressed and Full
      - type: regex
        part: answer
        regex:
          - "IN\\s+AAAA\\s+(fd[0-9a-fA-F]{2}(:[0-9a-fA-F]{0,4}){0,7})"

    extractors:
      - type: regex
        part: answer
        name: IPv6_ULA
        group: 1
        regex:
          - "IN\\s+AAAA\\s+(fd[0-9a-fA-F]{2}(:[0-9a-fA-F]{0,4}){0,7})"
```
