### ISSUE TITLE
[nuclei-template] http2-detection

### ISSUE THREAD

**Issue by yaabdala** [projectdiscovery/nuclei-templates#9213]
### Template Information:

There is no way to get ALPN data with nuclei through a template so here is a code template that uses curl to detect http2

### Nuclei Template:

```yaml

id: http2-detection
info:
  name: Detect HTTP/2 Support
  author: aabdala
  severity: info

variables:
  TARGET: "{{BaseURL}}"

code:
  - engine:
      - sh 
      - bash
    source: |
      curl -sI https://$TARGET -o/dev/null -w '%{http_version}\n' --connect-timeout 5 --max-time 10
    matchers:
      - type: word
        words: 
          - "2"
```

the output of the curl command is "2" if http2 is supported
