### ISSUE TITLE
mss-76-Open-Redirect.yaml

### ISSUE THREAD

**Issue by 0xr2r** [projectdiscovery/nuclei-templates#9253]
### Template Information:

![VD9WfrVT](https://github.com/projectdiscovery/nuclei-templates/assets/72355033/c53cde5c-e414-4248-bab4-7b4e5bee7c74)

### Nuclei Template:

```yaml
id: open_redirect
info:
  name: Open Redirect
  author: 0xr2r
  severity: medium
requests:
  - method: GET
    path:
      - "{{BaseURL}}/https://evil.com/"
      - "{{BaseURL}}//https://evil.com//"
      - "{{BaseURL}}/?targetOrigin=https://evil.com/"
      - "{{BaseURL}}/?fallback=https://evil.com/"
      - "{{BaseURL}}/?query=https://evil.com/"
      - "{{BaseURL}}/?redirection_url=https://evil.com/"
      - "{{BaseURL}}/?next=https://evil.com/"
      - "{{BaseURL}}/?ref_url=https://evil.com/"
      - "{{BaseURL}}/?state=https://evil.com/"
      - "{{BaseURL}}/?1=https://evil.com/"
      - "{{BaseURL}}/?redirect_uri=https://evil.com/"
      - "{{BaseURL}}/?forum_reg=https://evil.com/"
      - "{{BaseURL}}/?return_to=https://evil.com/"
      - "{{BaseURL}}/?redirect_url=https://evil.com/"
      - "{{BaseURL}}/?return_url=https://evil.com/"
      - "{{BaseURL}}/?host=https://evil.com/"
      - "{{BaseURL}}/?url=https://evil.com/"
      - "{{BaseURL}}/?redirectto=https://evil.com/"
      - "{{BaseURL}}/?return=https://evil.com/"
      - "{{BaseURL}}/?prejoin_data=https://evil.com/"
      - "{{BaseURL}}/?callback_url=https://evil.com/"
      - "{{BaseURL}}/?path=https://evil.com/"
      - "{{BaseURL}}/?authorize_callback=https://evil.com/"
      - "{{BaseURL}}/?email=https://evil.com/"
      - "{{BaseURL}}/?origin=https://evil.com/"
      - "{{BaseURL}}/?continue=https://evil.com/"
      - "{{BaseURL}}/?domain_name=https://evil.com/"
      - "{{BaseURL}}/?redir=https://evil.com/"
      - "{{BaseURL}}/?wp_http_referer=https://evil.com/"
      - "{{BaseURL}}/?endpoint=https://evil.com/"
      - "{{BaseURL}}/?shop=https://evil.com/"
      - "{{BaseURL}}/?qpt_question_url=https://evil.com/"
      - "{{BaseURL}}/?checkout_url=https://evil.com/"
      - "{{BaseURL}}/?ref_url=https://evil.com/"
      - "{{BaseURL}}/?redirect_to=https://evil.com/"
      - "{{BaseURL}}/?succUrl=https://evil.com/"
      - "{{BaseURL}}/?file=https://evil.com/"
      - "{{BaseURL}}/?link=https://evil.com/"
      - "{{BaseURL}}/?referrer=https://evil.com/"
      - "{{BaseURL}}/?recipient=https://evil.com/"
      - "{{BaseURL}}/?redirect=https://evil.com/"
      - "{{BaseURL}}/?u=https://evil.com/"
      - "{{BaseURL}}/?hostname=https://evil.com/"
      - "{{BaseURL}}/?returnTo=https://evil.com/"
      - "{{BaseURL}}/?return_path=https://evil.com/"
      - "{{BaseURL}}/?image=https://evil.com/"
      - "{{BaseURL}}/?requestTokenAndRedirect=https://evil.com/"
      - "{{BaseURL}}/?retURL=https://evil.com/"
      - "{{BaseURL}}/?next_url=https://evil.com/"
      - "{{BaseURL}}/redirect.php?url=https://evil.com/"
      - "{{BaseURL}}/r/?url=https://evil.com/"
      - "{{BaseURL}}/login?next=https://evil.com/"
      - "{{BaseURL}}/checkcookie?redir=https://evil.com/"
      - "{{BaseURL}}/#/path///https://evil.com/"
      - "{{BaseURL}}/login?to=https://evil.com/"
      - "{{BaseURL}}/?view=https://evil.com/"
      - "{{BaseURL}}/out?https://evil.com/"
      - "{{BaseURL}}/cgi-bin/redirect.cgi?https://evil.com/"
      - "{{BaseURL}}/redirect/https://evil.com/"
      - "{{BaseURL}}/redirect?url=https://evil.com/"
      - "{{BaseURL}}/link?url=https://evil.com/"
      - "{{BaseURL}}/?target=https://evil.com/"
      - "{{BaseURL}}/?rurl=https://evil.com/"
      - "{{BaseURL}}/?dest=https://evil.com/"
      - "{{BaseURL}}/?destination=https://evil.com/"
      - "{{BaseURL}}/?image_url=https://evil.com/"
      - "{{BaseURL}}/?go=https://evil.com/"
      - "{{BaseURL}}/?returnTo=https://evil.com/"
      - "{{BaseURL}}/success=https://evil.com/"
      - "{{BaseURL}}/data=https://evil.com/"
      - "{{BaseURL}}/qurl=https://evil.com/"
      - "{{BaseURL}}/login=https://evil.com/"
      - "{{BaseURL}}/logout=https://evil.com/"
      - "{{BaseURL}}/ext=https://evil.com/"
      - "{{BaseURL}}/clickurl=https://evil.com/"
      - "{{BaseURL}}/goto=https://evil.com/"

      
      
    redirects: false
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "Location: https://evil.com"
      - type: status
        status:
          - 301
          - 302
          - 303
          - 304
          - 307
          - 308
```
