### ISSUE TITLE
[nuclei-template] gunicorn-detect.yml

### ISSUE THREAD

**Issue by joanbono** [projectdiscovery/nuclei-templates#945]
**Gunicorn Server Banner extractor**

```yaml
id: gunicorn-detect
info:
  name: Detect Gunicorn Server
  author: joanbono
  description: Gunicorn Python WSGI HTTP Server for UNIX - https://github.com/benoitc/gunicorn
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:

      - type: regex
        part: header
        regex:
          - gunicorn+

    extractors:
      - type: kval
        part: header
        kval:
          - Server
```
