### ISSUE TITLE
Gabia Web Server Detection

### ISSUE THREAD

**Issue by jadu101** [projectdiscovery/nuclei-templates#9821]
### Template Information:

Gabia is one of the biggest Cloud, server, security control, domain, hosting IT infrastructure company from South Korea. 
Following .yaml file helps to detect whether gabia server is running on the host and potentially grabs the version info as well. 
You can test the .yaml file on https://www.gabia.com for Proof of Concept

### Nuclei Template:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/76433661/450a875f-32ad-4f03-87b7-41605c35f33a)

```yaml
id: gabia-detect

info:
  name: Gabia Detection
  author: jadu101
  severity: info
  description: This template identifies Gabia web servers by detecting the unique "gabia" keyword in the Server header of HTTP responses. 
  metadata:
    max-request: 1
  tags: tech,gabia

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: regex
        part: header
        regex:
          - "gabia+"

      - type: status
        status:
          - 200

    extractors:
      - type: kval
        part: header
        kval:
          - Server
```
