### ISSUE TITLE
Gabia Server Detection 

### ISSUE THREAD

**Issue by jadu101** [projectdiscovery/nuclei-templates#9822]
### Template for?

Gabia is one of the biggest Cloud, groupware, server, security control, domain, hosting IT infrastructure company from South Korea. 
Below .yaml files detects Gabia server from the host. 
You can test this .yaml file through https://www.gabia.com
### Nuclei Template:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/76433661/c38c01cd-c9a6-4811-9a02-bb9c3c35ae46)

```yaml
id: gabia-detect

info:
  name: Gabia Detection
  author: jadu101
  severity: info
  description: This template identifies Gabia web servers by detecting the unique "gabia" keyword in the Server header of HTTP responses. 
  metadata:
    max-request: 1
  tags: tech,gabia

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: regex
        part: header
        regex:
          - "gabia+"

      - type: status
        status:
          - 200

    extractors:
      - type: kval
        part: header
        kval:
          - Server
```

/ Vulnerability / Exploit / Misconfiguration / Technology -->
