### ISSUE TITLE
MantisBT Template Not Working on Valid Vulnerable Instance

### ISSUE THREAD

**Issue by YashVardhanTrip** [projectdiscovery/nuclei-templates#9890]
Team, recently I discovered that the MantisBT default login template is not working and is yielding that no issues were found although the URL on which it was run is accessible via Default Credentials.

I tried to write my own custom template : 

```yaml
http:
  - raw:
      - |
        POST /mantis/login_password_page.php HTTP/1.1
        Host: {{Hostname}}
        Cookie: MANTIS_secure_session=1; PHPSESSID={{session}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate, br
        Content-Type: application/x-www-form-urlencoded
        Connection: close
        Upgrade-Insecure-Requests: 1

        return=index.php&username={{username}}

    redirects: true
    
    extractors:
      - type: regex
        name: session
        group: 1
        part: header
        regex:
          - "PHPSESSID=([a-zA-Z0-9]+);"

  - raw:
      - |
        POST /mantis/login_password_page.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Cookie: MANTIS_secure_session=1; PHPSESSID={{session}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: en-US,en;q=0.5
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Upgrade-Insecure-Requests: 1

        return=index.php&username={{username}}&password={{password}}&secure_session=on

    payloads:
      username:
        - administrator
      password:
        - root
    attack: pitchfork

    matchers:
      - type: status
        status:
          - 302
      - type: regex
        part: header
        regex:
          - "Location: .*?/login_cookie_test.php\\?return=account_page.php"`
```

My template is not yielding any results too, Requesting to please fix this , feel free to use my custom template as reference if needed.
