### ISSUE TITLE
[nuclei-template] Aerohive HiveManager Login

### ISSUE THREAD

**Issue by binaryfigments** [projectdiscovery/nuclei-templates#992]
**HiveManager Login**

The Aerohive HiveManager is a central place to manage all Aerohive equipment.
Aerohive is Aquired by Extreme Networks and the product is end-off-sale. But there are still some online.
https://www.aerohiveworks.com/HiveManager.asp

```yaml
id: hivemanager-login-panel
info:
  name: HiveManager Login panel
  author: binaryfigments
  severity: low

requests:
  - method: GET
    path:
      - '{{BaseURL}}/hm/login.action'
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "HiveManager Login"
      - type: status
        status:
          - 200
```
